### ISSUE TITLE
Version 3.0.0 fails to runs any Node commands -- syntax error

### ISSUE THREAD

**Issue by stevendesu** [davezuko/react-redux-starter-kit#1001]
I'm using Node v4.2.6 with npm v3.5.2

I just installed react-redux-starter-kit per the instructions (git clone, then ran "npm install") however the next step (running "npm start") failed. I tried all of the commands: npm run start, npm run deploy, npm run compile,... they all fail with a similar error message:

```
to be executed: node bin/server 
/mnt/dev-code/stephaniebarnett/clickerforge/bin/server.js:5
const { server_host: host, server_port: port } = config
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by davezuko** [comment]
Ah you are right, thank you for catching that. I just dropped babel on the server earlier today which means all this stuff will no longer be transpiled. For some reason I thought the README suggested Node v6 as the minimum version, but it appears as though I was mistaken.

There are two possible routes from here:

1) Upgrade to Node 6 and reap the benefits of better ES6 support! I _would_ like to make 6 the minimum version, but...

2) A lot users may still be on Node 4 LTS, so it'd make sense to keep the server code compatible. If we go this route I will update Travis to also run our tests on Node 4.

Sorry for the inconvenience.

**Comment by davezuko** [comment]
Just pushed https://github.com/davezuko/react-redux-starter-kit/commit/cc6ae303327647fdc9674385b596c58fe9745675 after testing it locally on Node `4.5.0` (the latest `4.x.x` release). That should work for you!

**Comment by davezuko** [comment]
Closing as resolved. Let me know if you still have any issues.
