### ISSUE TITLE
`ip` package missing

### ISSUE THREAD

**Issue by o1dnik** [davezuko/react-redux-starter-kit#1002]
On latest version the `ip` package should be added to `package.json`.

**Comment by davezuko** [comment]
https://github.com/davezuko/react-redux-starter-kit/blob/master/package.json#L94 looks like it's there. Are you sure you pulled the latest version?

**Comment by o1dnik** [comment]
Weird. Sorry for taking your time, I must have mistaken a branch.

**Comment by davezuko** [comment]
No worries!
