### ISSUE TITLE
Trying to add a navbar

### ISSUE THREAD

**Issue by jmarlow4** [davezuko/react-redux-starter-kit#101]
I realize this issue isn't strictly with the code and more a request for a total noob, but your were so prompt yesterday that you were the first person I thought to ask about this.

When I try adding a new component to the core layout I get errors. Here's what it all looks like:
![untitled](https://cloud.githubusercontent.com/assets/2195317/10028577/77ab3972-612a-11e5-827c-9a694e98e15f.png)

Any idea what could be going on? Again, It's not really an issue with the code you wrote, it's just something I'm not grasping about the architecture of Redux (or the Flux philosophy)

**Comment by davezuko** [comment]
Hey, no problem.

My first guess is that you're just defining Navbar as a named export, not the default one. It should probably be:

`export default class Navbar extends React.Component`

One other thing I'd suggest is to not put `Navbar` inside `~/src/containers`. Containers is generally reserved for components that wrap an application to achieve some effect (such as rendering the Redux provider). It's totally up to you, but that's just a small side suggestion.

Anyways, see if that fixes it.

**Comment by jmarlow4** [comment]
Awesome. That did it. Yeah, I created another folder explicitly for components for that reason. Dude you are so gloriously awesome. I realize that this isn't a proper use for the issues section of a github page. So thanks for being cool about it.

**Comment by davezuko** [comment]
Awesome. And lol don't worry about it, I'd rather somebody gets their question answered then pull their hair out over. Feel free to post any time, keeps me busy at work haha. I'll close this for now though :)
