### ISSUE TITLE
define environment variable

### ISSUE THREAD

**Issue by ErwinLee10** [davezuko/react-redux-starter-kit#1010]
Hi, currently I am not really sure where I should put my environment variable like "api_endpoint".
If I refer to #604, I should put the variable inside the config.globals.

is the config.global referring to the one inside the config/index.js?

so lets say my prod and dev have different environment, how do make them referring to the different api_endpoint? my guess would be to put it inside the environment.js but not really sure how the index.js can refer to that.

**Comment by jgallow** [comment]
I agree this is still a little confusing, especially with the presence of the build environment configs. I found two ways to do this. The solution I ended up rolling with was that suggested by @davezuko in #926. Namely: 

> If you want a config that you share inside of your application, I suggest just creating it yourself (perhaps src/config.js), and you can export different things there based on the Node environment.

In this file you can basically just export an object with all your "env" variables set based on the `__DEV__`,`__TEST__`, and `__PROD__` globals as needed. Then you can import it anywhere you need it in your code easily thanks to the resolve.root setup. e.g. 

```js
// src/any/nested/path/index.js
import APP_SETTINGS from 'config'

const endpoint = `${APP_SETTINGS.API_BASE}/endpoint`

...
``` 

The other important thing to remember here is to .gitignore this file to keep any keys or other protected information out of source control.

### Alternative solution
The second solution I see is using better-npm-run's .env file loading and adding your vars as globals in `config/index.js`. Here you'd add keys to `config.globals` whose values depend on whatever you're loading onto `process.env` in your .env file. When going this route make sure you also add the globals to `~/.eslintrc` like the main readme instructs.

So this is a three step process. First, create your .env file in the root of your project **and add it to .gitignore**. It can look something like:

```
API_BASE=http://localhost:4000
API_KEY=someKey
```

Second, add your variables to `config.globals` in `config/index.js`.

```js
 // config/index.js
 // ------------------------------------
// Environment
// ------------------------------------
// N.B.: globals added here must _also_ be added to .eslintrc
config.globals = {
  'process.env'  : {
    'NODE_ENV' : JSON.stringify(config.env)
  },
  'NODE_ENV'     : config.env,
  '__DEV__'      : config.env === 'development',
  '__PROD__'     : config.env === 'production',
  '__TEST__'     : config.env === 'test',
  '__COVERAGE__' : !argv.watch && config.env === 'test',
  '__BASENAME__' : JSON.stringify(process.env.BASENAME || ''),
  // process.env.API_BASE & API_KEY injected from .env file by better-npm-run
  '__API_BASE__' : JSON.stringify(process.env.API_BASE || ''),
  '__API_KEY__'  : JSON.stringify(process.env.API_KEY || '')
}
```

Finally, add the new globals to `~/.eslintrc`.

```json
"globals": {
    "__DEV__"      : false,
    "__TEST__"     : false,
    "__PROD__"     : false,
    "__COVERAGE__" : false,
    "__API_BASE__" : "",
    "__API_KEY__"  : "",
  },
```

Now you can use `__API_BASE__` and `__API_KEY__` anywhere in your app code. This all works but it definitely requires a little more bootstrapping and is probably harder to maintain than the first solution.

**Comment by ErwinLee10** [comment]
@jgallow awesome! look like im going with the first solution

**Comment by ErwinLee10** [comment]
Hi, Currently I am trying to follow this #926, but kept getting error in the object spread syntax :
```javascript 
...config.globals,
      ^^^

SyntaxError: Unexpected token ...
```

any idea what happened?

**Comment by davezuko** [comment]
@ErwinLee10 object spread is not supported in Node 6 w/o babel, so you need to use `Object.assign` now. Closing as this is solved, though I am working to simplify the amount of configuration indirection in the project to make it easier to discover how to make these sorts of changes.
