### ISSUE TITLE
Warning: Store does not have a valid reducer. 

### ISSUE THREAD

**Issue by dadtmt** [davezuko/react-redux-starter-kit#1011]
Hi
Without modifying any code I get this warning in the browser 
Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers

The counter example is working though.

**Comment by simonedavico** [comment]
Same for me, even if the async reducers are working as expected.

**Comment by tseho** [comment]
@davezuko said he was going to fix it: [comment](https://github.com/davezuko/react-redux-starter-kit/commit/4ecc655ae7c5db83e6c3edffd7456a667191bf2e#commitcomment-19091452).

**Comment by davezuko** [comment]
Yeap, totally my bad. I am currently in physical therapy for my hand/wrist so can't work for as long as normal, but will get to this ASAPly.

**Comment by tseho** [comment]
@davezuko no pressure, I just wanted to inform them you are already aware of this error.

**Comment by justingreenberg** [comment]
@davezuko i got you... will submit a PR in a few mins

**Comment by davezuko** [comment]
@justingreenberg I appreciate it, but seriously, if you have better things to do don't worry about it. Worst case I'll get to it tomorrow morning.
