### ISSUE TITLE
Using the starter-kit for a new project

### ISSUE THREAD

**Issue by therios9** [davezuko/react-redux-starter-kit#1015]
I would like to use this starter kit for a new project. I will need to change the contents of the project.json file (author, repo, etc.) The README file would probably be replaced too. Where should I keep these original files so I can still credit the starte-kit developers?

**Comment by marshallford** [comment]
Maybe a credits section in your new README?

**Comment by davezuko** [comment]
@marshallford's suggestion sounds good, sorry for not seeing this earlier!
