### ISSUE TITLE
Redux-cli is not installed by default

### ISSUE THREAD

**Issue by thedrow** [davezuko/react-redux-starter-kit#1017]
I understand from it's documentation that it should be installed globally but it's not really mentioned in the README file or the blog post so it was unclear what the blueprints are for.
We should document it's usage here as well.

**Comment by lactozily** [comment]
redux-cli and blueprint was deprecated in [this commit](https://github.com/davezuko/react-redux-starter-kit/commit/b2756be3fd0a96d3ff0f689689969cd4273246a3)

**Comment by thedrow** [comment]
That's a shame because it was comfortable to scaffold new components like this.

**Comment by davezuko** [comment]
@thedrow The team I work on is currently working on a tool that supersedes this project and will contain blueprints/generators. This project was original meant to just be a simple boilerplate and less of a full dev environment/ecosystem, so I'm going to hold off on adding the blueprints back into here directly in favor of the soon-to-be-open-sourced tool.

**Comment by mikedevita** [comment]
@davezuko any updates to this tool and when it might be released, or if I can help contribute?
