### ISSUE TITLE
Cannot inject two or more reducers

### ISSUE THREAD

**Issue by auswalk** [davezuko/react-redux-starter-kit#1026]
I want to inject two reducers inside a index.js and it complains. E.g.

`
import { injectReducer } from '../../store/reducers'

export default (store) => ({
  path: 'homepage',
  getComponent (nextState, cb) {

    require.ensure([], (require) => {

      const Homepage = require('./containers/Homepage').default require('../../components/Homepage').default
      const reducer = require('./modules/session').default

      /*  Add the reducer to the store on key 'counter'  */
      injectReducer(store, { key: 'session', reducer })

      const qReducer = require('./modules/questionCardList').default

      /*  Add the reducer to the store on key 'counter'  */
      injectReducer(store, { key: 'questionCardList', qReducer })

      /*  Return getComponent   */
      cb(null, Homepage)

    /* Webpack named bundle   */
    }, 'session')
  }
})
`

Browser error:
`warning.js:14No reducer provided for key "questionCardList"`

**Comment by m4recek** [comment]
You need to insert reducer with key 'reducer'. So it should be 'injectReducer(store, { key: 'questionCardList', reducer: qReducer })'

**Comment by auswalk** [comment]
Thanks!
