### ISSUE TITLE
there was an error

### ISSUE THREAD

**Issue by midcore-nam** [davezuko/react-redux-starter-kit#1029]
Win 10
here is an error when i run npm start

 npm start

> react-redux-starter-kit@3.0.0-alpha.2 start C:\xampp\htdocs\NewApp
> better-npm-run start

running better-npm-run in C:\xampp\htdocs\NewApp
Executing script: start

to be executed: "node bin/server"
Thu, 29 Sep 2016 18:28:52 GMT app:config Creating default configuration.
Thu, 29 Sep 2016 18:28:52 GMT app:config Looking for environment overrides for NODE_ENV "development".
Thu, 29 Sep 2016 18:28:52 GMT app:config Found overrides, applying to default configuration.
Thu, 29 Sep 2016 18:28:53 GMT app:webpack:config Creating configuration.
Thu, 29 Sep 2016 18:28:53 GMT app:webpack:config Enable plugins for live development (HMR, NoErrors).
Thu, 29 Sep 2016 18:28:53 GMT app:server Enable webpack dev and HMR middleware
Thu, 29 Sep 2016 18:28:53 GMT app:bin:server Server is now running at http://localhost:3000.
webpack built c124ef3f5a166d913733 in 1436ms
Hash: c124ef3f5a166d913733
Version: webpack 1.13.2
Time: 1436ms
                             Asset     Size  Chunks       Chunk Names
       app.c124ef3f5a166d913733.js  80.6 kB       0       app
    vendor.c124ef3f5a166d913733.js   386 kB       1       vendor
   app.c124ef3f5a166d913733.js.map    89 kB       0       app
vendor.c124ef3f5a166d913733.js.map   462 kB       1       vendor

ERROR in Cannot find module 'babel-core'
 @ multi app
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  571 kB       0
webpack: bundle is now VALID.

browser shows this when i go to http://localhost:3000
![image](https://cloud.githubusercontent.com/assets/16084009/18966942/4e4af2be-8651-11e6-8bbb-c10c124edd3d.png)

**Comment by qivhou** [comment]
seems the `babel-core` was removed in [this commit](https://github.com/davezuko/react-redux-starter-kit/commit/4ecc655ae7c5db83e6c3edffd7456a667191bf2e)
the fix is easy, just ```npm install babel-core --save```

**Comment by midcore-nam** [comment]
you are the man.....i did it too but it didn't work.....i forgot the --save flag LOL....awesome stuff. thanks bud.

**Comment by jkettmann** [comment]
I also got an error here on my linux machine: "Module build failed: TypeError: Path must be a string. Received undefined."

Installing babel-core fixed it

**Comment by davezuko** [comment]
The missing dependency has been added in the above PR. Thanks, and sorry for the issue!
