### ISSUE TITLE
Compression for server by default

### ISSUE THREAD

**Issue by matyunya** [davezuko/react-redux-starter-kit#1031]
I realize that this is a starter kit of front-end related stuff but I'm sure that many people are using this as Express boilerplate as well, so maybe there should be gzip compression enabled by default for the server? Or is there a case when compression should be avoided?

**Comment by davezuko** [comment]
You make a good point, this should be added. Willing to accept a PR, otherwise I will get to it when I get back to having Free Time^TM. Closing in favor of a PR.
