### ISSUE TITLE
Include third-party files

### ISSUE THREAD

**Issue by ghost** [davezuko/react-redux-starter-kit#1038]
Hi,

I need to include jQuery and more third-party scripts, but I'm having a hard time with it. I do not understand webpack and I cannot include it in the `index.html` file, for it never finds it. I've put those files in `src/static/scripts/`.

Thank you.

**Comment by mteichtahl** [comment]
Use yarn or npm to bring in your third party dependencies

**Comment by davezuko** [comment]
See @mteichtahl's answer (thanks!).
