### ISSUE TITLE
Readme incomplete?

### ISSUE THREAD

**Issue by jakehm** [davezuko/react-redux-starter-kit#1042]
> After confirming that your development environment meets the specified requirements, you can create a new project based on react-redux-starter-kit in one of two ways:

But I only see one way described.

**Comment by davezuko** [comment]
You are correct, this is outdated. I will fix this later today.

**Comment by davezuko** [comment]
This has been fixed with https://github.com/davezuko/react-redux-starter-kit/commit/c135b61617327b9386d83e053f7a61ac46ff13d7.
