### ISSUE TITLE
Cannot import environment config variable to front end code

### ISSUE THREAD

**Issue by vincaslt** [davezuko/react-redux-starter-kit#1044]
I have registerd an environment specific variable in environments.js, like so:

```
development : (config) => ({
    compiler_public_path : `http://${config.server_host}:${config.server_port}/`,
    AR_API_URL : 'http://localhost:8080'
  }),
```

And I'm trying to import it in my front end module `import config from '../../config'`

It throws lots of errors: https://puu.sh/rCMOI/00bd28dc17.png

**Comment by davezuko** [comment]
Please see https://github.com/davezuko/react-redux-starter-kit/issues/644 and https://github.com/davezuko/react-redux-starter-kit/issues/926.

This is because the config is meant to configure the build; it is not meant to be imported into the application. Hope that helps!
