### ISSUE TITLE
Chrome gives "426 (Upgrade Required)" error on fresh install of the kit

### ISSUE THREAD

**Issue by mikedevita** [davezuko/react-redux-starter-kit#1047]
System Info
------------------
**OS:** Windows 10 x64 Enterprisee
**Chrome Version:** 53.0.2785.143 m
**Node Version:** 4.6.0

Description
-------------------
I cant load the latest clone of the repo, running `npm start` or `npm run dev` gives me the same errors..

Steps to reproduce
-------------------
```
git clone https://github.com/davezuko/react-redux-starter-kit/ frontend
cd frontend
npm install
npm start
```

Screenshot
-------------------

![image](https://cloud.githubusercontent.com/assets/2991640/19315123/62a07824-9051-11e6-9087-67a468954aba.png)

**Comment by neverfox** [comment]
I'm sorry but I'm was not able to recreate this. I'm on Node 6.6.0 and OS X, but I tried 4.6.0 also. Is there anything strange in the output of your npm install or the server?

**Comment by mikedevita** [comment]
not sure whats up as it now works fine on my macbook lol.

**Comment by abelchee** [comment]
I am having the same issue on Windows 7

After run "cmd: netstat -abno",  I get 

> [CmRcService.exe]
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       2244

I think this is related. After changing express server port to 3333, the issue is gone.
