### ISSUE TITLE
I can build and start the project in macosx's termial, but it can't run correct in my chrome, it throw the error as can't get app-xxxx.js and vendor-xxxx.js

### ISSUE THREAD

**Issue by ShadowWalker627** [davezuko/react-redux-starter-kit#1048]

**Comment by thomasthiebaud** [comment]
What are you doing to run it ? Are you running

```js
npm install
npm start
```

and then go to `localhost:3000`. I'm using it on OSX and Chrome and it is working

**Comment by davezuko** [comment]
Unfortunately, I cannot reproduce this. If you can provide more details I'd be happy to help. Thanks!
