### ISSUE TITLE
Upgrade to webpack 2

### ISSUE THREAD

**Issue by jonricaurte** [davezuko/react-redux-starter-kit#1057]
Now that webpack 2 is pretty much done and the only thing being worked on is documentation, would be great to update this repo to use it.

**Comment by kolpav** [comment]
Yes I am really looking forward to tree-shaking feature.

**Comment by cypherq** [comment]
@davezuko any plans regarding this one? I can prepare PR, question is if you're interested on migrating right now?

**Comment by davezuko** [comment]
@cypherq I am interested, and would gladly accept a PR. I have not had much time to devote to this project, but it is definitely a worthwhile change.

**Comment by davezuko** [comment]
Since it's the only open PR for it at the moment, moving discussion to https://github.com/davezuko/react-redux-starter-kit/pull/1063. Thanks!
