### ISSUE TITLE
How to define a route without the CoreLayout props children?

### ISSUE THREAD

**Issue by onweer** [davezuko/react-redux-starter-kit#1061]
I need a landing page 。 
Visit the home page(path = '/') and check no session will redirection to /login
Do not want '/login' is in the CoreLayout under the props, but a complete page.

eg: 

``` js
<Router> 
    <Route path='/' component="CoreLayout">
    <Route path='/login' component="Login">
</Router>
```

**Comment by bulicmatko** [comment]
Hi @onweer,
You should be able to do something like this:

```js
import CoreLayout from '../layouts/CoreLayout/CoreLayout'
import Home from './Home'
import CounterRoute from './Counter'
import Login from './Login'

export const createRoutes = (store) => ([ // now we are passing an array of routes
  {
    path: '/',
    component: CoreLayout,
    indexRoute: Home,
    childRoutes: [
      CounterRoute(store)
    ]
  },
  {
    path: '/login',
    component: Login
  },
])

...
```

Don't forget to change PropType in [AppContainer.js](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/containers/AppContainer.js#L7) to `PropType.array.isRequired`

Hope this helps ;)
Best Regards

**Comment by onweer** [comment]
@bulicmatko Thanks ;) .

**Comment by onweer** [comment]
@bulicmatko

**Comment by onweer** [comment]
succress with 
```js
export const createRoutes = (store) => ([
  Login(store)
])
```

**Comment by bulicmatko** [comment]
@onweer 
Glad it helped ;)
Can maybe this issue be closed?
