### ISSUE TITLE
Environment config section should go to the end

### ISSUE THREAD

**Issue by janoist1** [davezuko/react-redux-starter-kit#1065]
I had an issue with config environments not overriding default [globals](https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L76) because some JSON stringifed values stuck. The solution was to move the [globals](https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L76) section to the bottom.

**Comment by davezuko** [comment]
The links you posted no longer work due to some refactors, but I _believe_ this is no longer an issue. If it is, please let me know and I will fix it!
