### ISSUE TITLE
Add nested route example

### ISSUE THREAD

**Issue by orielz** [davezuko/react-redux-starter-kit#1070]
Please add an example of how to implement nested route with parameters, it could be very helpful. Thanks.

**Comment by kolpav** [comment]
You can implement nested route exactly as [index](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/index.js) one. It all repeats itself as much as you want, child route can have more `childRoutes ` and so on. 

Very rough example

```javascript

const SettingsLayout = ({ children }) => (
  <div>
    <SettingsMenu /> // With links to UserProfileSettings and ThemeSettings route
    <div>{children}</div> // Content of respective route
  </div>
)

export default store => ({
  path: '/settings',
  component: SettingsLayout,
  childRoutes: [
    UserProfileSettingsRoute(store), // <site>/settings/profile
    ThemeSettingsRoute(store) // <site>/settings/theme
  ]
})
```

If you have any questions feel free to ask.

**Comment by mull** [comment]
A full working example with bundle split subroutes would actually be quite useful. I'm running into a problem where react-router is calling `getComponent` for both `/partners` and `/partners/search` in this setup:

```
{
  path: '/partners',
  getComponent: function(cb) { ... cb() },
  childRoutes: [
     SearchRoute(store)
  ]
}

function SearchRoute(store) {
  path: '/partners/search',
  getComponent: function(cb) { ...cb() },
}
```

I've tried different variations of the path settings. Strangely enough getComponent gets called for both the parent and the subroute, but the parent route is rendered. Is this familiar to anyone? The setting up of childRoutes is synchronous and only getComponent uses require.ensure. Wouldn't surprise me if I'm either doing something really stupid or ran into a react-router bug.

**Comment by huangzhuolin** [comment]
grateful and agree with @kolpav , I came with the same problem these days.
The index route is an excellent self-explain example for nested routes.
In each route, several things should be mentioned.
1. the path that the route match.
2. the component that the route use to serve.
3. childRoutes, each childRoute is structured like this route itself.

After some practice, I found the solution and post it here, and any suggestions will be appreciate. 

```javascript
// routes/index.js

export const createRoutes = (store) => ({
  path        : '/',
  component   : CoreLayout,
  indexRoute  : Home,
  childRoutes : [
    CounterRoute(store),
    YourOtherLevelOneRoute(store),
    // ...
  ],
  onEnter: () => {
    store.dispatch(fetchMenu())
  },
})
```

For example, in Counter folder, you can define your components to serve that level and, 
you can define `routes` folder in the same way as level one routes. In routes/Counter/index.js, 
add `childRoutes` just as before.
```javascript
export default (store) => ({
  path : 'counter',
  // add code here
  childRoutes: [
     LevelTwoRoute(store),
     OtherLevelTwoRotue(store),
  ],
  /*  Async getComponent is only invoked when route matches   */
  getComponent (nextState, cb) {
    /*  Webpack - use 'require.ensure' to create a split point
        and embed an async module loader (jsonp) when bundling   */
    require.ensure([], (require) => {
      /*  Webpack - use require callback to define
          dependencies for bundling   */
      const Counter = require('./containers/CounterContainer').default
      const reducer = require('./modules/counter').default

      /*  Add the reducer to the store on key 'counter'  */
      injectReducer(store, { key: 'counter', reducer })

      /*  Return getComponent   */
      cb(null, Counter)

    /* Webpack named bundle   */
    }, 'counter')
  }
})
```
The main idea is thinking just like using recursive way to define something. The example just for explain. Really hope this will help.

**Comment by davezuko** [comment]
See @kolpav 's and @huangzhuolin 's great explanations.
