### ISSUE TITLE
Question about auth0 authentication and page redraw on callback

### ISSUE THREAD

**Issue by therealgilles** [davezuko/react-redux-starter-kit#1071]
Hello,

I am using auth0 to authenticate with facebook. Auth0 does a callback redirect to the login page to send back the authentication token, then there is a redirect to the dashboard.

Is there a way to avoid the page redraw when the callback redirect happens?

**Comment by davezuko** [comment]
I don't believe so, since you are completely reloading the page, aside from whatever requests are restored from cache. If you find out otherwise I'd be interested to hear! Closing since this is not directly related to this project, but best of luck!
