### ISSUE TITLE
Error on npm start: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by bhuffman** [davezuko/react-redux-starter-kit#1072]
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Debug Log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-redux-starter-kit@3.0.0-alpha.2
6 info start react-redux-starter-kit@3.0.0-alpha.2
7 verbose unsafe-perm in lifecycle true
8 info react-redux-starter-kit@3.0.0-alpha.2 Failed to exec start script
9 verbose stack Error: react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-redux-starter-kit@3.0.0-alpha.2
11 verbose cwd /Users/sfc/sandbox/react1
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.6.1
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
17 error Exit status 1
18 error Failed at the react-redux-starter-kit@3.0.0-alpha.2 start script 'better-npm-run start'.
18 error This is most likely a problem with the react-redux-starter-kit package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     better-npm-run start
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-redux-starter-kit
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-redux-starter-kit
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by wrabbit23** [comment]
I'm seeing the same.  Fresh install of node 5.12.0

**Comment by nicolasgarnil** [comment]
Same here, solved it with @wrabbit23 fix

**Comment by davezuko** [comment]
Also removed this variable altogether in https://github.com/davezuko/react-redux-starter-kit/commit/85d16e05cd97ecf3119409d468d9dc88ba7401e5.
