### ISSUE TITLE
Quick heads up about the counter reducer

### ISSUE THREAD

**Issue by przeor** [davezuko/react-redux-starter-kit#1073]
Hi Guys,

A question about the starter configuration and the non-mutable state in Redux.

Where exactly it's taken care about the below:
<img width="783" alt="screen shot 2016-11-07 at 10 16 10" src="https://cloud.githubusercontent.com/assets/5995/20052220/4b497752-a4d3-11e6-9758-b41ebf004e10.png">

...is done the "non-mutating way"? I don't see the Object.assign or spread operator.

Link do the file: https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/containers/CounterContainer.js

**Comment by davezuko** [comment]
Mutation only applies when the value is something that is mutable (e.g. objects, arrays). The counter state in our example is simply a primitive (a number), and those are not mutable so there is nothing to spread. If the state was shaped like this, however:

```js
const initialState = {
  count: 0,
}
```

Then you would be correct, as we would not want to mutate the state object:

```js
[COUNTER_INCREMENT]: (state, action) => ({
  ...state,
  count: state.count + action.payload
})
```

Hope that helps!
