### ISSUE TITLE
Compiling issues running npm run deploy:prod

### ISSUE THREAD

**Issue by bytewiz** [davezuko/react-redux-starter-kit#1075]
Getting this log error when trying to run the command in the title.

And getting an insane amount of errors in the console.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'deploy:prod' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'predeploy:prod', 'deploy:prod', 'postdeploy:prod' ]
5 info lifecycle react-redux-starter-kit@3.0.0-alpha.0~predeploy:prod: react-redux-starter-kit@3.0.0-alpha.0
6 silly lifecycle react-redux-starter-kit@3.0.0-alpha.0~predeploy:prod: no script for predeploy:prod, continuing
7 info lifecycle react-redux-starter-kit@3.0.0-alpha.0~deploy:prod: react-redux-starter-kit@3.0.0-alpha.0
8 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.0~deploy:prod: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.0~deploy:prod: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/jenkins/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.0~deploy:prod: CWD: /home/jenkins/app
11 silly lifecycle react-redux-starter-kit@3.0.0-alpha.0~deploy:prod: Args: [ '-c', 'better-npm-run deploy:prod' ]
12 silly lifecycle react-redux-starter-kit@3.0.0-alpha.0~deploy:prod: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@3.0.0-alpha.0~deploy:prod: Failed to exec deploy:prod script
14 verbose stack Error: react-redux-starter-kit@3.0.0-alpha.0 deploy:prod: `better-npm-run deploy:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-redux-starter-kit@3.0.0-alpha.0
16 verbose cwd /home/jenkins/app
17 error Linux 4.4.0-45-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "deploy:prod"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error react-redux-starter-kit@3.0.0-alpha.0 deploy:prod: `better-npm-run deploy:prod`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@3.0.0-alpha.0 deploy:prod script 'better-npm-run deploy:prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run deploy:prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by davezuko** [comment]
Does anything succeed before this? Are there any other errors you can provide? I just tried it locally (and it's also run in CI) and could not reproduce it. Will try upgrading to your specific Node version, but unfortunately cannot glean much from the above npm script log.

The most I see with purged/rebuilt dependencies are some PostCSS warnings (which warrant investigation), but nothing that blows up the build.

**Comment by bytewiz** [comment]
@davezuko All the errors I can provide from the console, appreciate it!

[log.txt](https://github.com/davezuko/react-redux-starter-kit/files/579059/log.txt)

**Comment by bytewiz** [comment]
another note, I did try to pull this on my own pc and npm install and run compile with no errors, so just wondering what happens here 😕

**Comment by davezuko** [comment]
@bytewiz looks like a CI task on Jenkins. Can you please try to run `npm rebuild` on that environment before the deploy task? Looks like a bad `node-sass` binary`.

**Comment by bytewiz** [comment]
@davezuko It is supposed to be a Jenkins job. I have now tried to run `npm rebuild` after `npm install` and then tried the `npm run deploy:prod` again but getting same massive list of errors 😖

**Comment by davezuko** [comment]
@bytewiz hmm... And you're doing this on a Linux box? Do any of the deploy tasks work, or just this one? My guess is that _all_ of them should fail if this is an environment issue w/ `node-sass`.

**Comment by bytewiz** [comment]
@davezuko I am running this on a droplet on Digitalocean an Ubuntu 16.04 and with pre-installed Node 6.9.1, then installed Nginx. and changed my Node version to v6.2.0 to match the one I am running locally.

I am only running this one task manually through ssh into the server and executing it like I would locally

**Comment by bytewiz** [comment]
@davezuko managed to get the full error message, couldn't fit it here so had to go in a .txt file again.

Seems that something goes completely off and a lot of module references which is not found it seems.

[compile-log.txt](https://github.com/davezuko/react-redux-starter-kit/files/579775/compile-log.txt)

**Comment by bytewiz** [comment]
@davezuko I think I found the source of this bug, apparently my system is more friendly when it comes to Case sensitivity of file names. And that is why it fails. My bad. Appreciate your help! closing this again
