### ISSUE TITLE
How do I trigger build when I hit refresh on my browser?

### ISSUE THREAD

**Issue by JasonShin** [davezuko/react-redux-starter-kit#1078]
Hi, I have a project that uses react-redux-starter-kit and the project is quite huge. I am not a big fan of Webpack hot reloader. I feel productive when I actually hit F5 on my keyboard to see changes that I made. Webpack watch is annoying to me now because whenever I hit ctrl+s, it occasionally freezes my IDE or text editors. Since I am CTRL+S and F5 person (will always doing it in the future), is it possible to trigger webpack build whenever I hit F5 on my Chrome browser and see changes?

**Comment by JasonShin** [comment]
I am open for communication. I am happy to receive any recommendations as well. If you need more information about my issue, please let me know.

**Comment by JasonShin** [comment]
I was actually using `npm start` instead of `npm run dev`. It was causing the issue =(

**Comment by davezuko** [comment]
Sorry for not replying earlier, the best way to do this is probably by enabling the `lazy` option for webpack's dev server -- see http://webpack.github.io/docs/webpack-dev-server.html.

Hope that helps!
