### ISSUE TITLE
how to run app after run command "npm run deploy:prod" ?

### ISSUE THREAD

**Issue by dark4eg** [davezuko/react-redux-starter-kit#1081]
open index page in browser as static site on local file system or hosted on nginx - fact is working,
but current route render to 
Please show me fix this trouble

**Comment by mikedevita** [comment]
`http-server dist/`

**Comment by bulicmatko** [comment]
Hi @dark4eg,

You can run `node ./bin/server.js`.
This will boot up express server with `connect-history-api-fallback` (This is probably what you need for running a SPA).

If you check [./server/main.js#L42-L55](https://github.com/davezuko/react-redux-starter-kit/blob/master/server/main.js#L42-L55) which is required by `./bin/server.js` script, you'll see that the express server will boot up using `./dist` folder as a static folder.

This should work as what you need.

If you want to start it with special `NODE_ENV`, you can do it by running:
`NODE_ENV=production node ./bin/server.js`

...or even better you can add `npm run server` script to your `package.json`.
It could look something like this:

```
...
    "scripts:: {
        ...
        "server": "better-npm-run server"
        ...
    },
   ...
   "betterScripts": {
        ...  
        "server": {
            "command": "node ./bin/server.js",
            "env": {
                "NODE_ENV": "production",
                "DEBUG": "app:*"
            }
        },
        ...
   }
...
```

Hope this helps ;)

PS: Maybe it would be good to add similar script to the kit.
@davezuko What do you think?

Regards,

**Comment by dark4eg** [comment]
@bulicmatko yes, thanks)
