### ISSUE TITLE
Failed to load resource: net::ERR_NETWORK_ACCESS_DENIED

### ISSUE THREAD

**Issue by charleylla** [davezuko/react-redux-starter-kit#1092]
Hi.
When I start the program (npm run dev), the browser reported an error: 
_Failed to load resource: net::ERR_NETWORK_ACCESS_DENIED_

I don't know what happened,can you help me?Thanks! :)

**Comment by davezuko** [comment]
I believe this is a Chrome issue, though I don't have a bug to point you to. If you are still experiencing this please let me know and we can reopen.

**Comment by aozfen** [comment]
I got this mistake. The problem is that the nginx server is not marked the correct way. I share the Nginx configuration. If someone has the same problem, he can do it
`
server {

        listen 80;
        server_name www.ahmetozfen.com ahmetozfen.com;

        root /home/.../ahmetozfen.com/react/dist;
        index index.html;

        location / {

        }
}

`
