### ISSUE TITLE
 Failed at the react-redux-starter-kit@3.0.0-alpha.2 start script 'better-npm-run start'.

### ISSUE THREAD

**Issue by cnewell187** [davezuko/react-redux-starter-kit#1093]
to be executed: "node bin/server"
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "production". +8ms
  app:config Found overrides, applying to default configuration. +4ms
module.js:471
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Casey\Desktop\react\react-redux-starter-kit\server\main.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Casey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@3.0.0-alpha.2 start script 'better-npm-run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Casey\Desktop\react\react-redux-starter-kit\npm-debug.log

**Here is the debug LOG**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Casey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.0.2
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~prestart: react-redux-starter-kit@3.0.0-alpha.2
6 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~prestart: no script for prestart, continuing
7 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: react-redux-starter-kit@3.0.0-alpha.2
8 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: PATH: C:\Users\Casey\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Casey\Desktop\react\react-redux-starter-kit\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Lenovo\Bluetooth Software\;C:\Program Files\Lenovo\Bluetooth Software\syswow64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files\Git\cmd;C:\Users\Casey\Anaconda3;C:\Users\Casey\Anaconda3\Scripts;C:\Users\Casey\Anaconda3\Library\bin;C:\Users\Casey\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Casey\AppData\Local\Programs\Python\Python35\;C:\Users\Casey\AppData\Roaming\npm;C:\Users\Casey\AppData\Local\atom\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: CWD: C:\Users\Casey\Desktop\react\react-redux-starter-kit
11 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Args: [ '/d /s /c', 'better-npm-run start' ]
12 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Failed to exec start script
14 verbose stack Error: react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Casey\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Casey\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-redux-starter-kit@3.0.0-alpha.2
16 verbose cwd C:\Users\Casey\Desktop\react\react-redux-starter-kit
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Casey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.1
20 error npm  v4.0.2
21 error code ELIFECYCLE
22 error react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@3.0.0-alpha.2 start script 'better-npm-run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

I have the latest npm and node installed, I ran npm install, and then npm start. Not sure what the issue is.

**Comment by heronblade** [comment]
Did you run the npm install and npm start commands in a command prompt window with administrator privileges?

**Comment by cnewell187** [comment]
Apparently, npm install wasn't installing the dev dependencies for some
reason. So I had to run npm install --dev

**Comment by davezuko** [comment]
Cool, closing this then!
