### ISSUE TITLE
Remove connect-history-api-fallback

### ISSUE THREAD

**Issue by jonricaurte** [davezuko/react-redux-starter-kit#1097]
I think you should remove connect-history-api-fallback from the starter kit because it also kills the connection for webpack-hot-middleware. If you run

```
time curl http://localhost:3000/__webpack_hmr -v
```

It should keep a live connection and you should see emoji heartbeats but it dies right away. It does not because of the below code:

```
app.use(require('connect-history-api-fallback')({
  verbose: false,
  index: '/static/index.html'
}));
```

Commenting the above code out, restarting the server and then rerunning the curl command, you see the heartbeats.

**Comment by jonricaurte** [comment]
You should remove that and add this:

```
app.use('*', (req, res, next) => {
    const filename = path.join(compiler.outputPath, 'index.html');
    compiler.outputFileSystem.readFile(filename, (err, result) => {
      if (err) {
        return next(err);
      }
      res.set('content-type', 'text/html');
      res.send(result);
      return res.end();
    });
  });
```

Based on this answer: https://github.com/ampedandwired/html-webpack-plugin/issues/145#issuecomment-170554832

You will still get the heartbeats and now using nginx is instant.

**Comment by davezuko** [comment]
I didn't know that, thanks for pointing that out! I will make this change shortly.
