### ISSUE TITLE
How to insert a reducer into other reducer where not in root state

### ISSUE THREAD

**Issue by zhangda47** [davezuko/react-redux-starter-kit#1098]
I have two pages:
``` 
/expense_reimbursement/receipt
/expense_reimbursement/receipt/add
```

The pages both connect to redux, and I want to insert the second reducer into the first reducer.
I tried follows, but I can only find the first reducer in root state.

store/reducers.js
``` jsx
export const injectSubReducer = (store, {pathString, reducer}) => {
  const pathArr = pathString.split('/')
  store.asyncReducers[pathArr[0]][pathArr[1]] = reducer
  store.replaceReducer(makeRootReducer(store.asyncReducers))
}
```

Add/index.js
``` jsx
export default (store) => ({
  path: '/expense_reimbursement/receipt/add',
  getComponent(nextState,cb) {
    injectSubReducer(store, {pathString: 'receipt/add', reducer: reducer})
    cb(null, Container)
  }
})
```

**Comment by CWilliams014** [comment]
Did you find a solution to this problem? I'm having the same questions...

**Comment by piu130** [comment]
Try to hold your redux store as flat as possible. For more read [here](https://stackoverflow.com/questions/42472415/structuring-state-management-store-ngrx-redux-flat-as-representative-of-data).
