### ISSUE TITLE
reducers for global shared components in fractal structure

### ISSUE THREAD

**Issue by sosaucily** [davezuko/react-redux-starter-kit#1102]
I'm new to the fractal structure, but trying to give it a go.

If I want a top-level component to be in the redux lifecycle, I will need to give it a **container, action, reducer,** etc.

For example, to use the sample structure of this starter-kit, I added **components**, **containers**, and **modules** folders under a **Header** folder in **src/components**, as well as an _index.js_ file.  I tried to mimic the structure under Counter.  For instance, let's say the Header will appear across multiple routes and will display a _welcome Master Shake_ message when user is logged in.

However, I don't know where to tie in the reducer.  I've tried a few ways, but errors at every turn.  What would be best practice for adding global _containers_ such as this?  

Input much appreciated, Thanks!

**Comment by albertovilva** [comment]
Also curious about this.

I have done a similar thing, I have an "Auth" reducer in my app that controls user authorization and credentials. 

I have created a "reducers" folder in /src/store where I placed my "auth.js" which contains the reducer and actions for my authorization methods.

Then I include it into combineReducers on "/src/store/reducers.js", It its working, but I fear this might not be the best way to do it, so any insight would be greatly appreciated!

**Comment by albertovilva** [comment]
BTW, I have a different question regarding this (Im also pretty new to this fractal paradigm).

If I want to group several reducers/pieces of state under the same key how should I do it? For example I have 'settings/personalData' and 'settings/billingData' my idea would be to create them in state as

user: { personalData : {} , billingData: {}} but using the project "template" as @sosaucily says, I can't find the way, I can only specify a key on the index.js of each route, I don't see the way to nest both reducers under the same key.

Thank you, and sorry if I derailed to much, but I feel like its pretty related.

**Comment by przeor** [comment]
@sosaucily check the www.ReactJS.co tutorial and a Session reducer (which is global). That may help.

**Comment by sosaucily** [comment]
Thanks @przeor.  This example does get things working for me.  Basically the fix was to include the top-level reducer in the _makeRootReducer_ method, in the reducers.js file.

In the end I created a top-level _shared_ folder, and put components within that, each with a folder including components / containers / modules.  Seems like a sane approach.

Thanks!

**Comment by sosaucily** [comment]
for @albertovilva to put data under the same top-level key, it needs to be defined and managed from within the same reducer. I don't know of another way.

**Comment by albertovilva** [comment]
Thank you very much @sosaucily that's what I was suspecting after trying many different ways, without success.

**Comment by albertovilva** [comment]
@sosaucily just managed to do the reducers thing, and it was extremely simple, so guess would be nice to share. I used combineReducers() before getting them into the root reducer, that way I get the state tree nested under the same key, but each reducer can be independent and in separate files. Working great so far.

![Uploading Screen Shot 2016-12-22 at 15.20.10.png…]()
