### ISSUE TITLE
No /dist/server.js File

### ISSUE THREAD

**Issue by Tresky** [davezuko/react-redux-starter-kit#1105]
I have just noticed that there is a development server file in the dist folder: `dev-server.js`. However, there is no production version of the server. Is this intentional?

If so, I am unsure how to get it to deploy. I am attempting to deploy on Heroku.

**Comment by davezuko** [comment]
The server as it stands is production ready and will just serve the files in dist when you are outside of development mode; there is no need to compile it, so if there is a server file in dist something is wrong. Check out https://github.com/davezuko/react-redux-starter-kit/wiki/FAQ:-Frequently-Asked-Questions#heroku-deployment for details on deploying to heroku. Hope that helps.
