### ISSUE TITLE
resolve failed:  { [Error: Cannot find module 'rc-util'] code: 'MODULE_NOT_FOUND' } rc-util node_modules/nan

### ISSUE THREAD

**Issue by febobo** [davezuko/react-redux-starter-kit#1108]
I'm run npm start, but it throw error, see image
![image](https://cloud.githubusercontent.com/assets/9276376/21138006/22741b74-c167-11e6-9f3c-b0feb287fa6e.png)

I'm try install it tips modules, don't result, error exist

**Comment by sxcooler** [comment]
您好，请问您这个问题怎么解决的呢？

**Comment by sxcooler** [comment]
您好，请问您这个问题怎么解决的呢？

**Comment by FallingSnow** [comment]
I have the same question.

**Comment by FallingSnow** [comment]
@sxcooler https://github.com/FallingSnow/lightdm-webkit2-material2/commit/3fc1850066cbccc008e595976ec0754a6acaf47a#diff-e56633f72ecc521128b3db6586074d2c
