### ISSUE TITLE
Why not use yarn start?

### ISSUE THREAD

**Issue by jakehm** [davezuko/react-redux-starter-kit#1109]
The readme says use `yarn install` and `npm start`.

Why not use `yarn start` as well since you are using yarn already.  It does the same thing.

**Comment by davezuko** [comment]
Might as well, it doesn't _really_ matter since, as you say, they do the exact same thing; I just wanted to emphasize its use for dependencies where there is actually a difference. Will update for consistency.

**Comment by davezuko** [comment]
Done: https://github.com/davezuko/react-redux-starter-kit/commit/97f0fd1fb5d9c368a0ea1b24e36725d8327db183

Going to leave the table of run commands as `npm run` just for simplicity, but will consider updating it next time I work on the readme.

**Comment by mikedevita** [comment]
FYI yarn has known issues..

**Comment by davezuko** [comment]
I am aware; the nice part is it's not at all necessary to use it, just encouraged. Need to drive things forward somehow!

**Comment by jakehm** [comment]
Yarn issues I've encountered are with install. X yarn start is the same thing as npm start
