### ISSUE TITLE
Universal Server on Production

### ISSUE THREAD

**Issue by guidiego** [davezuko/react-redux-starter-kit#1111]
I saw that `npm run deploy:prod` create a dist with prod files, but how can I run Unviersal Server on Prod? I need use `webpack-dev-server`?

**Comment by davezuko** [comment]
Hey! There's a whole host of things you'd need to do, and unfortunately I don't have the bandwidth to provide all of the necessary details. [Here](https://github.com/davezuko/react-redux-starter-kit/issues/212#issuecomment-165101373) is an issue discussion the fact that this project does not concern itself with SSR.

Sorry that I could not be of more help, but I hope you find what you're looking for elsewhere. Best of luck!
