### ISSUE TITLE
Multiple Actions Keys with same Handlers

### ISSUE THREAD

**Issue by RadomirPerisic** [davezuko/react-redux-starter-kit#1113]
Hi,

I'm wondering what would be the correct syntax to have action assigned to more than one key:

Example of switch styled reducer:

```javascript
export default function user(state = {}, action = {}) {
  switch (action.type) {
    case LOAD_ACCOUNT:
    case LOG_IN_SUCCESS:
      return {
        ...state,
        accountStatus: 'loaded',
        account: action.payload.account
      };
  }
  return state;
}
```
But avoid doing it like this, because it won't be that transparent when there are more actions:

```javascript
const ACTION_HANDLERS = {

  [LOG_IN_SUCCESS] : (state, action) => ({
    ...state,
    loginStatus: 'loaded',
    token: action.payload.token
  })
}

ACTION_HANDLERS[LOAD_ACCOUNT] = ACTION_HANDLERS[LOG_IN_SUCCESS]
```

Or maybe it is a good way after all?

**Comment by davezuko** [comment]
This is just a personal preference, I wouldn't say one is measurably better than the other, but use whatever makes the most sense to you. There is (at least) one other option, which is to use named functions to make it slightly more clear:

```js
const handleLoginSuccess = (state, action) => ({ ... })

const ACTION_HANDLERS = {
  [LOG_IN_SUCCESS]: handleLoginSuccess,
  [LOAD_ACCOUNT]: handleLoginSuccess,
}
```

Just pick what makes the most sense to you :).
