### ISSUE TITLE
Use jsx rather than plain route objects for routing

### ISSUE THREAD

**Issue by jakehm** [davezuko/react-redux-starter-kit#1116]
In the official redux docs they are using jsx rather than plane route objects:
http://redux.js.org/docs/advanced/UsageWithReactRouter.html

JSX seems more supported and easier to use and understand.
I ran into a problem requiring auth on enter of a child route.  Easy with JSX but I see no examples with plain routes.

```
/*  Note: Instead of using JSX, we recommend using react-router
    PlainRoute objects to build route definitions.   */
```
Why?

**Comment by mikedevita** [comment]
one way is you'd just use a HOC.

```javascript
import Authenticated from 'containers/Auth'

// ... 
export const createRoutes = (store) => ({
  path        : '/',
  component   Authenticated(CoreLayout),
  indexRoute  : Home,
  childRoutes : [
   CounterRoute(store)
  ]
})
```


**containers/Auth/index.js**

```javascript
/**
 * Created by mhdevita on 12/14/16.
 */
import React, { PropTypes } from 'react'
import { connect } from 'react-redux'

const { object } = PropTypes
import { actions as Auth } from '../../reducers/auth'

export default function Authenticated (Component) {
  class AuthenticationComponent extends React.Component {
    static propTypes = {
      auth: object.isRequired
    }

    static contextTypes = {
      store: object.isRequired,
      router: object.isRequired
    }

    componentWillMount() {
      const { auth } = this.props
      const { dispatch } = this.context.store

      if ((!auth.user || !auth.token) && Auth.isAuthenticated()) {
        dispatch(Auth.setup())
      } else {
        this.checkAuth(auth.isAuthenticated)
      }
    }

    componentWillReceiveProps(nextProps) {
      this.checkAuth(nextProps.auth.isAuthenticated)
    }

    checkAuth(isAuthenticated) {
      const { router } = this.context
      if (!isAuthenticated) {
        router.replace('/auth/login')
      }
    }

    render() {
      return (<Component {...this.props} />)
    }
  }

  const mapStateToProps = (state) => ({
    auth: state.auth
  })

  return connect(mapStateToProps)(AuthenticationComponent)
}
```

**Comment by jakehm** [comment]
An easier way is something like 
`
childRoutes: [
  {
    onEnter: requireAuth,,
    childRoutes: [
      ProtectedRoute(store)
    ],
  },
  UnprotectedRoute(store)
]
`
It's just really ugly compared to the jsx alternative.  
And I don't see what the advantage is of plain route objects over jsx.

**Comment by mikedevita** [comment]
that's what you can do as well, what you mentioned is the other way. using the object notation allows you to conditionally require routes to help improve load times from what I've been told.

**Comment by jakehm** [comment]
This is diverging from the point of the issue kinda, but what's wrong with checking for auth in onEnter?

In your HoC example, can you do code splitting like in routes/Counter/index.js?
Since you have to pass CoreLayout as a Component class rather than a function.

**Comment by bhj** [comment]
I think the recommendation for POJO routes is related to #755? At one time there [was more in the README](https://github.com/davezuko/react-redux-starter-kit/commit/0d538c71e9278e952d979e591ac3592b9f8aefcd#diff-04c6e90faac2675aa89e2176d2eec7d8R231) but it was subsequently removed in ceb1198cdbe23ff0bcd429658bddd79acbf0def5

I do like the HOC auth way for flexibility and [redux-auth-wrapper](https://github.com/mjrussell/redux-auth-wrapper) mentions some of the `onEnter` issues.

**Comment by rhysburnie** [comment]
I thought it was to make code splitting easier and also because you can build route definitions conditionally with pogo and jsx is explicit and as far as jsx routes being "easier to use and understand" thats really a matter of opinion, personally I find pogo routes much easier to use.

Two of the functions in the https://github.com/ReactTraining/react-router/blob/master/docs/guides/DynamicRouting.md example don't seem to be available as props of `<Route />` either: https://github.com/ReactTraining/react-router/blob/master/modules/Route.js

**Comment by NorianNyx** [comment]
@mikedevita What would be the best way of using HOC to restrict access to child routes? Should I create multiple layouts based on userAccess? I suppose I could add the Authenticated method to getComponent of the child route, but that seems a bit messy.

**Comment by mikedevita** [comment]
@NorianNyx well, an HOC wrapper around your components would suffice....

`RequiresAuth(SomeComponent)`

**Comment by NorianNyx** [comment]
@mikedevita This doesn't work in the createRoutes method because the child routes are actually functions in this case, and not the actual component.

From the current version of the starter kit:

```javascript
export const createRoutes = (store) => ({
  path        : '/',
  component   : CoreLayout,
  indexRoute  : Home,
  childRoutes : [
    CounterRoute(store) //returns a route
  ]
})
```

**Comment by mikedevita** [comment]
```
export const createRoutes = (store) => ({
  path        : '/',
  component   : RequiresAuth(CoreLayout),
  indexRoute  : RequiresAuth(Home),
  childRoutes : [
    CounterRoute(store) //returns a route
  ]
})
```
one of these two approaches should work AFAIK.

**Comment by NorianNyx** [comment]
@mikedevita This works for `CoreLayout` to restrict access to all children of `CoreLayout` (including '/'). So it would make sense to have different layouts that restrict based on userAccess, no? i.e. An "AuthLayout" that has children that only someone that is properly authenticated can access.

This seems like a reasonable manner to move forward, but I'm very new to React/Redux/Router and not so sure about conventional practices.

**Comment by chillenious** [comment]
+1 for moving away from plain routes. That stuff is barely documented, and if you're looking to get productive fast while still learning all the bits and pieces of React/ Redux, it's not particularly helpful to deviate without a clear benefit (other than that the author says so) :-)

**Comment by artekr** [comment]
@chillenious Agreed! This kit should adapt the new version of react-router. I think react-router is splitting into different modules, for the plain routes. I find it in this sub-module called [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config). it all requires react-router v4.0.0 and newer.

**Comment by davezuko** [comment]
Moving react-router 4.0 discussion to https://github.com/davezuko/react-redux-starter-kit/issues/1130. I finally have a minute to look at this project, so will be trying to bring it back up to date.
