### ISSUE TITLE
can't run in ie9

### ISSUE THREAD

**Issue by j306796405** [davezuko/react-redux-starter-kit#1119]
after run 'npm start' project can't run in ie9. But run 'run start deploy:prod' is ok.

Thanks and Merry Christmas!

**Comment by davezuko** [comment]
Hey there! IE9 does not natively support all of the features that this project uses, and it isn't one of our supported targets. That said, you should be able to just include [babel-polyfill](https://github.com/webpack/webpack/issues/2506) to shim missing features -- you can use [this commit](https://github.com/jokeyrhyme/react-redux-starter-kit/commit/f3f095b547ee63474b9361128bb95d370da04b35) as a vague reference (the `compiler_globals` option is in `~/configs/project.config.js` now) for how to do this. [Here's an explanation about why it's not included by default](https://github.com/davezuko/react-redux-starter-kit/wiki/FAQ:-Frequently-Asked-Questions#babel-polyfill).

If that does not solve it, it would be helpful to understand what error message you are seeing in the console. Hope that helps; if not, just ping me and we can reopen, though it could also be related to https://github.com/webpack/webpack/issues/2506. Merry Christmas!

**Comment by j306796405** [comment]
Hi @davezuko  i find if using react and react-dom v15.1.0 and there is no crash

reference to this : https://github.com/ccoffey/react-ie9-crash

but thanks anyway and Merry Christmas.
