### ISSUE TITLE
Did css-modules be removed?

### ISSUE THREAD

**Issue by yqz0203** [davezuko/react-redux-starter-kit#1121]
I can't find it in  lastest version.

**Comment by tiagoalvesdulce** [comment]
Yes. See https://github.com/davezuko/react-redux-starter-kit/issues/787 and https://github.com/davezuko/react-redux-starter-kit/pull/1000

**Comment by yqz0203** [comment]
@tiagoalvesdulce got that, thanks😀

**Comment by MrStronger** [comment]
But why? Does css modules isn't a better choice?
