### ISSUE TITLE
Regarding Dependencies & Dev Dependencies

### ISSUE THREAD

**Issue by akmishra2712** [davezuko/react-redux-starter-kit#1122]
Dear David, 

Just one question, in the package.json. I can see many of the dependencies which should be in dev-dependencies. Could you please see is there any specific reason many of them are in dependencies?

**Comment by davezuko** [comment]
These may help :)

* https://github.com/davezuko/react-redux-starter-kit/issues/662
* https://github.com/davezuko/react-redux-starter-kit/issues/1085

🎄
