### ISSUE TITLE
require(...).default make error!

### ISSUE THREAD

**Issue by skatpgusskat** [davezuko/react-redux-starter-kit#1126]
I suffered error, ```Uncaught TypeError: __webpack_require__(...).ensure is not a function``` on sass files.
According to this [issue link](https://github.com/webpack/webpack/issues/1685), the reason they told is ```require(...).default```.

Why do we use ```require(...).default```? I think we can use general ```import``` expression on whole situation.

If you guys agree with that, I'm gonna try to edit every statement and make Pull Request.

**Comment by davezuko** [comment]
`.default` is used when importing ES6-style modules with `require`, since `require` imports the transformed `module.exports` object, on which the default export is named `default`. If you are just  importing a file, and it doesn't have any explicit exports, you can forego the `.default`.
