### ISSUE TITLE
RFC: Add flowtype support

### ISSUE THREAD

**Issue by amilajack** [davezuko/react-redux-starter-kit#1129]
Would a PR for this be welcome?

**Comment by mikedevita** [comment]
pretty sure this was in the kit once and removed for some reason...

**Comment by Piu130** [comment]
For me definitely yes! But I think for the project not [#1153](https://github.com/davezuko/react-redux-starter-kit/issues/1153). Removed in [this](https://github.com/davezuko/react-redux-starter-kit/commit/dfde2c359bb8d4ae47f34c2a62d0a59bd10fb855) commit.

**Comment by davezuko** [comment]
This was added before and removed after _a lot_ of misunderstanding from less experienced users. I personally would welcome some sort of type checking, but please don't worry about a PR. This project is not as active as it once was, so there are better uses for your time.
