### ISSUE TITLE
Cannot get webstorm debug working

### ISSUE THREAD

**Issue by melchoir55** [davezuko/react-redux-starter-kit#1139]
I have been trying to set breakpoints in webstorm for this app, but I can't seem to get it to work. I'm using an npm run configuration pointing at package.json. The standard run command works fine, but if I execute in debug mode, the application goes through the build process then just exits itself.
![run configuration](https://cloud.githubusercontent.com/assets/2881468/22011823/d0c1bd50-dc45-11e6-8fc3-41034cee785b.png)
![immediately after running](https://cloud.githubusercontent.com/assets/2881468/22011827/d7232846-dc45-11e6-9111-06a27b34702f.png)
![10 seconds after running](https://cloud.githubusercontent.com/assets/2881468/22011828/d9546eb8-dc45-11e6-82d4-08af0cfcf538.png)

Has anyone gotten the webstorm debugger working with this project?

**Comment by melchoir55** [comment]
Posting an answer to my own question in case anyone else has this problem. My problem came from a misunderstanding of the way JS and the debugger work. In order to run the debugger, it needs something to attach to, and webstorm will not spin that up.

First, run the app using `npm start`.  Then, point a javascript debugging run configuration from webstorm to the url provided by npm start (usually localhost:3000). You may also need to manually open chrome and install the webstorm plugin.

**Comment by davezuko** [comment]
Thank you for taking the time to explain the fix, @melchoir55 .
