### ISSUE TITLE
Jest-snapshot testing

### ISSUE THREAD

**Issue by albertovilva** [davezuko/react-redux-starter-kit#1148]
I find [jest snapshot](https://facebook.github.io/jest/blog/2016/07/27/jest-14.html) testing could be a very benefical thing to add to the project. I've read mixed opinions about Jest itself, but where everyone seems to agree is that snapshot testing is amazing. And it truly speeds up the process of testing component rendering.

The cool guys from jest have extracted this only functionality to its independent package [jest-snapshot](https://github.com/facebook/jest/tree/master/packages/jest-snapshot) and there is even a [chai integration](https://www.npmjs.com/package/chai-jest-snapshot)

Are there any plans to integrate it with the testing enviroment in the project? Or has anyone done it who could share some insights, I have tried with no success.

**Comment by davezuko** [comment]
I think it's a solid idea, but I haven't used it personally to be convinced either way just yet. Going to combine this with https://github.com/davezuko/react-redux-starter-kit/issues/1224, which has Jest under open consideration.
