### ISSUE TITLE
Upgrade utility / upgrade guide

### ISSUE THREAD

**Issue by macnibblet** [davezuko/react-redux-starter-kit#1151]
Heya

In my opinion keeping the build system up to date is extremely important. So a utility to upgrade the build system or a upgrade guide to quickly upgrade a existing code base to the latest version ?

**Comment by davezuko** [comment]
Hey, thanks for the suggestion. I'm currently in the process of replacing all the local build management code with a cohesive tool, so this will become moot once that is done. Sorry for being so distant from this project lately!
