### ISSUE TITLE
Any way to avoid duplicating name/value of constants?

### ISSUE THREAD

**Issue by jonaswindey** [davezuko/react-redux-starter-kit#1152]
In the modules we are using 

```
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DOUBLE_ASYNC = 'COUNTER_DOUBLE_ASYNC'
```

I know that there was a createConstants helper in the past, but it is gone. Are there any ways to replace this with a more concise way? It seems redundant to me to repeat values that are the same as the variable name.

Although I don't really see an easy solution, since we export each const separately, otherwise we could just export const constants = {....} and use a helper like `create-constants`

**Comment by pleunv** [comment]
Not much you can do if you want a named export for each actionType.

You can either define them manually (I don't see why the redundancy is an issue as you will rarely have to touch your actionTypes once they have been defined), you can use a utility like [redux-action-help](https://github.com/keuller/redux-action-help) which gives you the `createConstants` helper, or you can get rid of actionTypes altogether and use an actionCreator factory utility like the one in [redux-actions](https://github.com/acdlite/redux-actions).

Personally I don't mind it as I'm namespacing most of my actionTypes anyway, something like this:

`export const ADD_USER = '@@accounts/user/ADD';`

**Comment by Piu130** [comment]
So you recommend something like this?

```js
// ------------------------------------
// Constants
// ------------------------------------
export const PREFIX = '@@accounts/'
export const ADD_USER = `${PREFIX}user/ADD`
export const DELETE_USER = `${PREFIX}user/DELETE`
...
```

**Comment by davezuko** [comment]
Closing as a usage question, and not a project issue. A `createConstants` helper is probably the way to go, but I removed it in favor of keeping the demo code as straightforward as possible.
