### ISSUE TITLE
Multiple named exports from component

### ISSUE THREAD

**Issue by frantallukas10** [davezuko/react-redux-starter-kit#1155]
Hi, 
I am trying to export another named export along with component.

file A
```
export const ConfirmationButton = (props) => {
	// something
}

export const STYLE = {
	BIG: 'big',
	MEDIUM: 'medium',
	SMALL: 'small',
	SMALLER: 'smaller',
}

ConfirmationButton.propTypes = {
	style: React.PropTypes.oneOf(Object.keys(STYLE)),
}

export default ConfirmationButton
```

And then import and use it in different file as bellow. But it looks like STYLE is never exported/imported, only default import is visible for file B

file B
```
import ConfirmationButton, { STYLE as ConfirmationStyle } from 'components/_scaffolding/ConfirmationButton'

<ConfirmationButton key='confirmation-log' style={ConfirmationStyle.BIG} />
```

Is it a bug or a feature? Is there a way how to do something like this?

**Comment by 6zz** [comment]
remove the keyword `export` in `export const ConfirmationButton...`
