### ISSUE TITLE
404 catch-all using PlainRoute

### ISSUE THREAD

**Issue by gavinkilbride** [davezuko/react-redux-starter-kit#1157]
I'm struggling to get my 404 route working.

I have set up the /error/fourohfour route and can navigate to is directly but I cannot get this same page to render when no match is found in the route configuration.

I would assume I need to do something like this: 

`export const createRoutes = (store) => ({
    path: '/',
    indexRoute: { onEnter: (nextState, replace) => replace('/manage/people') },
    getChildRoutes(location, cb) {
        require.ensure([], (require) => {
            cb(null, [
                require('./Error').default(store),
                require('./Auth').default(store),
                require('./Manage').default(store),
            ]);
        });
    },
}, {
    path: '*',
    component: require('./Error/FourOhFour'),
});

export default createRoutes;`

however when I do this I get the error 

> Invariant Violation: The root route must render a single element

**Comment by Piu130** [comment]
[This](https://github.com/davezuko/react-redux-starter-kit/commit/babf72a32e1ad3da570c2298dad30094d69bbdec) worked for me.

**Comment by albertovilva** [comment]
@gavinkilbride This is working for me following your same approach. Maybe you are missing the route?

```javascript
{
  path: '/',
  component: PublicLayout,
  indexRoute: PublicRoute,
  childRoutes: [
    PlayRoute(store),
    LoginRoute(store),
  ],
}, {
  path: '*',
  component: ErrorComponent,
  indexRoute: ErrorRoute,

}
```

**Comment by davezuko** [comment]
Closing per the above suggestions. Thanks guys,

**Comment by tomaszantas** [comment]
I can confirm that above suggestion of @albertovilva works. But don't forget to set paths as an Array:

`[
  {
    path: '/',
    component: PublicLayout,
    indexRoute: PublicRoute,
    childRoutes: [
      PlayRoute(store),
      LoginRoute(store),
    ],
  }, {
    path: '*',
    component: ErrorComponent,
    indexRoute: ErrorRoute,  
  }
]`

Otherwise, _path: '*'_ overwrites __path: '/'_ and you will get Error Page everytime.

**Comment by avennn** [comment]
@tomaszantas It reports a warning tip that routes should be an "object" instead of an "array"
