### ISSUE TITLE
Can you use the `airbnb` specification to constrain the project?

### ISSUE THREAD

**Issue by MinJieLiu** [davezuko/react-redux-starter-kit#1162]
Can you use the `airbnb` specification to constrain the project?

**Comment by davezuko** [comment]
If you mean their eslint configuration, yes, you just have to modify `.eslintrc` to point to their configuration; their repo has instructions for setting this up (it's trivial). Once you switch to their config, just run `npm run lint -- --fix` to automatically apply code style changes. If you mean something else entirely, let me know.
