### ISSUE TITLE
Importing css into core.scss

### ISSUE THREAD

**Issue by jansselt** [davezuko/react-redux-starter-kit#1167]
I am working on a project and they would like to use [react-grid-layout](https://github.com/STRML/react-grid-layout)

According to their instructions I need to import the css files
```
/node_modules/react-grid-layout/css/styles.css
/node_modules/react-resizable/css/styles.css
```

I am having a heck of time getting this to work.  I have installed react-grid-layout and react-resizable via npm so they are in node_modules.  Looking at core.scss, I figured I'd be able to import these the same way normalize is imported from node_modules

```
@import 'base';
@import '~normalize.css/normalize';
@import '~react-grid-layout/css/style';
@import '~react-resizable/css/style';
```

However this is not working and resulting int the following error

```
ERROR in ./~/css-loader?sourceMap&-minimize!./~/postcss-loader!./~/sass-loader?sourceMap!./src/styles/core.scss
Module build failed:
@import '~react-grid-layout/css/style';
^
      File to import not found or unreadable: ~react-grid-layout/css/style.
Parent style sheet: stdin
      in /Users/luke/development/code/byteboard-cloud/web/src/styles/core.scss (line 3, column 1)
```

Any help would be greatly appreciated.  I must be doing something wrong here.  Probably something simple.  I apologize in advance if Im missing something stupid.  Im in the process of learning react-redux on the fly and am a complete webpack novice.

**Comment by carlwelchdesign** [comment]
This error just showed up out of the blue for me too. 

      File to import not found or unreadable: base
Parent style sheet: stdin
      in /Users/mycomputer/Documents/grindr.com/_git.grindr.com/grindr.com/frontend/src/components/SlideShow/components/SlideShow.scss (line 1, column 1)
 @ ./src/components/SlideShow/components/SlideShow.scss 4:14-224 13:2-17:4 14:20-230

**Comment by 6zz** [comment]
@jansselt you have a typo, you are missing the ending 's' in 'styles':
`@import` '~react-grid-layout/css/style**s**';

**Comment by jansselt** [comment]
Boy do I feel like a horses backside.  Not sure how on earth I missed that.  Made the change and all works well.

Thanks @6zz.  Closing.
