### ISSUE TITLE
Enhancment: add note on containers vs layouts vs views

### ISSUE THREAD

**Issue by sudodoki** [davezuko/react-redux-starter-kit#117]
It might be beneficial to add a brief note to Readme on differences & what goes into what folder regarding containers, layouts & views.

**Comment by davezuko** [comment]
Good idea, I'll try to get to it this week. спасибо!

**Comment by nhagen** [comment]
Bump--I'm finding myself just removing the containers and layouts folder and putting everything in the component folder. I might use the other folders, but I can't find an explanation of their purpose anywhere.

**Comment by davezuko** [comment]
There isn't really an "official" explanation for them, they're just something that I use in personal projects and kept in the starter kit. I will add some documentation in the README when I get a chance, but I don't at all expect people to conform to the structure if it doesn't make sense for their projects.

I'll update this issue once the documentation is added, and maybe you both will have some thoughts on it.

**Comment by davezuko** [comment]
Hopefully this provides some explanation: https://github.com/davezuko/react-redux-starter-kit#structure

Closing for now, let me know if you think this requires further documentation.

**Comment by sudodoki** [comment]
Great, thanks!

**Comment by christiansakai** [comment]
@davezuko 

When I go through other boilerplates and react redux tutorials, the `containers` folder are storing smart components in general, while in this boilerplate, it seems there are 2 folders that play the role as smart components, the `containers` and the `views` folder.  Therefore in building an app based off this boilerplate, user should just leave the `containers` folder alone and instead make the smart component inside `views` folder.

 Am I correct assuming this?

**Comment by SpencerCDixon** [comment]
I don't think you would want a smart and dumb component for each of those instances.  I would probably make SubmitEmail a dumb component that lives in `components/SubmitEmail` and Navigation a smart component in `containers/Navigation` and have navigation pass down the callback to submit emails to the dumb SubmitEmail component. 

I generally have my Navigation as a layout of its own though and do something like this in my routes:

```
  <Route path='/' component={CoreLayout}>
    <Route component={NavLayout}>
      <IndexRoute component={HomeView} />
      <Route path='/about' component={AboutView} />
... close routes
```

hope that helps!

**Comment by christiansakai** [comment]
@SpencerCDixon thanks for the comment! What if SubmitEmail is a component that needs to be able to live anywhere on the app? That means I should make a container for SubmitEmail and just let it communicate directly to redux, am I correct?  

Also, if I want to make my app with this approach, that means `views` folder is just for positioning the smart components only.  What do you think the downside of this approach?

**Comment by SpencerCDixon** [comment]
My `views` folder ends up containing most of my actual 'containers' in the traditional redux sense.  And yeah if you have a component that needs to be able to be in many places and you don't want to always have to pass down a CB down potentially many levels then putting SubmitEmail in a containers as well is a great approach

**Comment by christiansakai** [comment]
I see, thanks for the answer! I think it is best to do the traditional redux sense like you described! Thanks!

**Comment by chenfanggm** [comment]
@christiansakai I thought the "View" folder is a one to one mapping with your routing setting. It's like a entry point for any of your "page". Then, container as a smart component, where components is a pure dumb component :)

**Comment by christiansakai** [comment]
@chenfanggm thats what I thought too. After seeing this repo, the HomeView is being `connect`ed to redux, thats why I'm a little bit confused

**Comment by davezuko** [comment]
@christiansakai it's just a matter of semantics, really. Yes, a `view` is really technically a `container`, but to me it doesn't make sense to put all my components that are designed to live at a route in containers. I tend to, as @SpencerCDixon pointed out, use `containers` for any other smart components that aren't responsible for a route. Smaller apps may not have many of these as the views can handle most of the logic, but as your app grows so will `containers`.

**Comment by christiansakai** [comment]
@davezuko ah, I see. totally makes sense now! thank you

**Comment by christiansakai** [comment]
@SpencerCDixon would you mind sharing your code on CoreLayout and NavLayout?

**Comment by SpencerCDixon** [comment]
```
import 'styles/global.stuff';

// Note: Stateless/function components *will not* hot reload!
// react-transform *only* works on component classes.
//
// Since layouts rarely change, they are a good place to
// leverage React's new Statelesss Functions:
// https://facebook.github.io/react/docs/reusable-components.html#stateless-functions
//
// CoreLayout is a pure function of it's props, so we can
// define it with a plain javascript function...
const propTypes = {
  children: React.PropTypes.element
};

function CoreLayout ({ children }) {
  return (
    <div className='page-container'>
      <div className='view-container'>
        {children}
      </div>
    </div>
  );
}

CoreLayout.propTypes = propTypes;
export default CoreLayout;
```

```
import React, { Component, PropTypes } from 'react';
import { Navbar, NavItem, Nav } from 'react-bootstrap';
import { connect } from 'react-redux';
import { LinkContainer } from 'react-router-bootstrap';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';

import { navRoutes } from 'routes/index';
import { actions as authActions } from 'redux/modules/auth';
import { fetchLeadSourceTypes } from 'redux/modules/leadSourceTypes';
import NotificationContainer from 'containers/NotificationContainer';
import LogoSpinner from 'components/LogoSpinner';
import Icon from 'components/Icon';

const propTypes = {
  children: PropTypes.element,
  dispatch: PropTypes.func.isRequired,
  isAuthenticated: PropTypes.bool.isRequired,
  globalFetch: PropTypes.bool.isRequired
};

class NavLayout extends Component {
  componentWillMount() {
    // this will need to be moved if I ever have routes without nav
    this.props.dispatch(authActions.initAuth());
    this.props.dispatch(fetchLeadSourceTypes());
  }

  renderLinks(type) {
    let links = [];

    navRoutes[type].map((route, i) => {
      let icon;
      if (route.fa) {
        icon = <Icon is={route.fa} />;
      }

      links.push(
        <LinkContainer key={i} to={route.to}>
          <NavItem eventKey={route.to}>
            {icon}
            {route.msg}
          </NavItem>
        </LinkContainer>
      );
    });
    return links;
  }

  renderSignOut() {
    const { dispatch } = this.props;
    return (
      <NavItem
        key='signout'
        eventKey='signout'
        onClick={() => dispatch(authActions.signOut())}
      >
        <Icon is='sign-out' />
        Sign Out
      </NavItem>
    );
  }

  render() {
    const { children, isAuthenticated, globalFetch } = this.props;
    const rightLinks = isAuthenticated
      ? this.renderLinks('authenticated') : this.renderLinks('notAuthenticated');

    return (
      <div>
        <ReactCSSTransitionGroup transitionName='example' transitionEnterTimeout={500} transitionLeaveTimeout={300}>
          {globalFetch && <LogoSpinner color='white' />}
        </ReactCSSTransitionGroup>
        <Navbar inverse fluid className='site-nav'>
          <Navbar.Header>
            <Navbar.Brand>
              <LinkContainer to='/'>
                <a>Kira</a>
              </LinkContainer>
            </Navbar.Brand>
            <Navbar.Toggle />
          </Navbar.Header>
          <Navbar.Collapse>
            <Nav>
              {this.renderLinks('shared')}
            </Nav>

            <Nav pullRight>
              {rightLinks}
              {isAuthenticated && this.renderSignOut()}
            </Nav>
          </Navbar.Collapse>
        </Navbar>
        <NotificationContainer />

        {children}
      </div>
    );
  }
}

function mapStateToProps(state) {
  return {
    isAuthenticated: state.auth.isAuthenticated,
    globalFetch:
      state.auth.isFetching ||
      state.user.isFetching ||
      state.leadSource.isFetching ||
      state.touches.isFetching ||
      state.leads.isFetching
  };
}

NavLayout.propTypes = propTypes;
export default connect(mapStateToProps)(NavLayout);
```

**Comment by christiansakai** [comment]
@SpencerCDixon thanks! really appreciate it! I like the way you put initAuth in Navigation!

**Comment by SpencerCDixon** [comment]
Yeah, havn't looked at this in a while but looking at it now I think I'm actually going to refactor it to dispatch an action that just does all site-wide initialization and I'll make that action a thunk that dispatches all pieces of the app that need to dispatch something on page load if that makes sense

**Comment by christiansakai** [comment]
yeah that totally makes sense! I'll try this first and refactor later
