### ISSUE TITLE
how to modify other reducer state 

### ISSUE THREAD

**Issue by ssamj** [davezuko/react-redux-starter-kit#1171]
Hi I'm new to react-redux ,  have a base reducer to control something public ,like show alter/confirm.
Now in an other reducer ,how can i to use base reducer's action ?Sorry, my English is not good...

**Comment by mikedevita** [comment]
have your other  reducer call an action which exists in reducer 1.

ex:

##reducer1.js
```

const someactionthunk = (params = {}) =>  (dispatch) => {
  // do some crap and eventually update my state
}

##reducer2.js
```
const someotheractionthunk = (params = {}) =>  (dispatch) => {
  dispatch(someactionthunk());
}
