### ISSUE TITLE
I can't manage to import a global scss file for the whole project

### ISSUE THREAD

**Issue by ghost** [davezuko/react-redux-starter-kit#1173]
I want to import a `_default.scss` file from `_base` to have default rules that should be applied to the whole project I'm building, but I can't make it work. No errors nor anything is shown.

I have the following `styles` folder structure:

```javascript
styles/
----/components/
--------/Home/
--------/Dashboard/
--------_default.scss
----/fonts/
--------/...
----_base.scss
----core.scss
```

And I tried the following in `_base.scss`:
`@import './components/_default.scss'`,
`@import './components/_default'` and
`@import './components/default`.

I have cloned it without picking up any version and I haven't made any alteration but these.

**Comment by piu130** [comment]
This works for me

```
styles/
----components/
------_default.scss
----_base.scss
```

With `_default.scss`

```css
* { background-color: black; }
```

And `_base.scss`

```css
@import './components/default';
```

Makes every background black.
Don't forget `'` and `;`

**Comment by mfgabriel92** [comment]
@piu130 I tried it already, it doesn't work for me... why? What could I have possibly done wrong?! Agh.

**Comment by piu130** [comment]
Are you trying to override some [bootstrap-style](https://getbootstrap.com/) imported on line [#7](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/index.html#L7) in `index.html`. Or some normalize-style imported on line [#2](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/styles/core.scss#L2) in core.scss?

If not could you post your `_default.scss` content?

**Comment by mfgabriel92** [comment]
I wanted to create global rules for input fields, some borders etc, nothing
big. I do not have the file anymore.

**Comment by davezuko** [comment]
Just released a bunch of changes: https://github.com/davezuko/react-redux-starter-kit/releases/tag/v3.0.0.

I recommend putting your global styles in `./src/styles/main.scss` and seeing if they get loaded. If they don't, let me know and we can revisit.
