### ISSUE TITLE
compiled and when run in apache loads but nothing rendes

### ISSUE THREAD

**Issue by psound** [davezuko/react-redux-starter-kit#1178]
I am trying to render the static files of the dist folder, I see all rendering correctly on my log. No errors but nothing displays on the page. I am running a simple apache server. Please help

Thanks
-Pedro

**Comment by razazaidisd** [comment]
When you open in browser is it taking the right URL? I think you need to change to 'localhost' in config/project.config.js line 26 .

**Comment by alex-bu-89** [comment]
Maybe the problem is routing and history http://stackoverflow.com/a/37557805.
Look at `history` in `AppContainer`.  `hashHistory` works for me.

**Comment by davezuko** [comment]
Is this from a fresh clone of this project? If not, please link to your source (or website, even, if you can). Closing in the meantime.
