### ISSUE TITLE
Can I Watch the COMPILE task? 

### ISSUE THREAD

**Issue by razazaidisd** [davezuko/react-redux-starter-kit#1179]
I want to *Watch* the change after the compile task and once its compile and I change some source code, it should compile it again.

Is this possible?

**Comment by davezuko** [comment]
https://github.com/davezuko/react-redux-starter-kit/blob/master/bin/compile.js#L36

The code is written to allow this, as `compile` returns a promise, but you would have to rework the export so that compile is exported from that file and not called automatically. Hope that helps.
