### ISSUE TITLE
Render in iframe

### ISSUE THREAD

**Issue by matejstrasek** [davezuko/react-redux-starter-kit#1182]
Trying to render website built with this starter kit in an <iframe> in another website and getting:

`Refused to display 'https://example.web.site' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

Is this header automatically set in the code somewhere?

**Comment by dbrrt** [comment]
Are you trying to display your iframe locally (via an page HTML) or hosted (via a webserver) ?
The fastest way to host a basic index.html (IMO), is to use : https://docs.python.org/2/library/simplehttpserver.html

`python -m SimpleHTTPServer 8000` , under same folder

Topic about `CORS` will help you to better understand why it's not working.

**Comment by matejstrasek** [comment]
Via webserver. 

I have 'www.iframe.site' running in webserver and would like to insert an <iframe src='www.example.web.site'> but get that specific error. 

So I was wondering if this is already set somewhere in the repo or is there a place I could set it to allow 'www.iframe.site' to load 'www.example.web.site' in iframe.

**Comment by matejstrasek** [comment]
Found that the header was set in nginx.conf and not in the repo.

Anyway, If anyone is interested, additional headers can be set in middleware (can check examples here: https://github.com/webpack/webpack-dev-middleware).
