### ISSUE TITLE
[help wanted] Test script - unexpected token

### ISSUE THREAD

**Issue by Catx7** [davezuko/react-redux-starter-kit#1186]
Hi I am trying to use this test module but in my application I use import /export commands .
Ex:

`import webpack from 'webpack';`
`export default webpackConfig;`

and when  I try to run 'test' script it says for import and export same  error:

> SyntaxError: Unexpected token export

What should  I add or set for this ? 

Thank you

**Comment by 6zz** [comment]
hi, with this starter kit, I shouldn't need to import webpack.  The bootstrap `tests/test-bundler.js` took care of those

**Comment by Catx7** [comment]
No. 
The problem is  that  in **config/karina.config.js** you are using `const webpackConfig = require('./webpack.config')` and I am using `import webpack from 'webpack';`

**Comment by Catx7** [comment]
Problem is regarding ES6  I think.
I used your configuration but replaced `module.exports` with `exports default` and `require('module')` with `import 'module`

**Comment by piu130** [comment]
Karma does not support ES6 currently. Maybe you can work around this if you execute karma with babel-node.

**Comment by Catx7** [comment]
Thank you.
I managed to start 'npm run test'.
I have the same project structure as you have and all configurations too.
But the problem I have now is that a lot of warnings and error found in `src/static/docs`  documentation folder , 
> Module build failed: SyntaxError:  /src/static/  **Unexpected token **
also this error
`PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  Invariant Violation: _registerComponent(...): Target container is not a DOM element.
  at webpack:///~/fbjs/lib/invariant.js:51:0 <- tests/test-bundler.js:18338
`
I tried to exclude in karma.config `exclude : [/node_modules/,/src\/static/],` but I still have the problem.

**Comment by Catx7** [comment]
After I added a test I got the following error:
`Error: Module build failed: ReferenceError: [BABEL]  ..\src\modules\module1\containers\Contianer.js: Unknown option: base.cssModules. 
Check out http://babeljs.io/docs/usage/options/ for more information about options.
A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`
`
What should I configure next?

**Comment by Catx7** [comment]
script from package json to start karma
"babel-node ./node_modules/karma/bin/karma start config/karma.config"
karma config file.

import {argv} from 'yargs';
import project from './base.js';
import webpackConfig from '../build/webpack.config.js';
import _debug from 'debug';

const debug = _debug('app:config:karma');
debug('Creating configuration karma.');
const karmaConfig = {
  basePath : '../', // project root in relation to bin/karma.js
  files    : [
    {
      pattern  : `./${project.testDir}/test-bundler.js`,
      watched  : false,
      served   : true,
      included : true
    }
  ],
  singleRun     : !argv.watch,
  frameworks    : ['mocha'],
  reporters     : ['mocha'],
  preprocessors : {
    [`${project.testDir}/test-bundler.js`] : ['webpack']
  },
  browsers : ['PhantomJS'],
  webpack  : {
    devTool : 'cheap-module-source-map',
    resolve : Object.assign({}, webpackConfig.resolve, {
      alias : Object.assign({}, webpackConfig.resolve.alias,{
        sinon : 'sinon/pkg/sinon.js'
      })
    }),
    plugins : webpackConfig.plugins,
    module  : {
      noParse : [
        /\/sinon\.js/
      ],
      loaders : webpackConfig.module.loaders.concat([
        {
          test   : /sinon(\\|\/)pkg(\\|\/)sinon\.js/,
          loader : 'imports?define=>false,require=>false'
        }
      ])
    },
    // Enzyme fix, see:
    // https://github.com/airbnb/enzyme/issues/47
    externals : Object.assign({}, webpackConfig.externals, {
      'react/addons'                   : true,
      'react/lib/ExecutionEnvironment' : true,
      'react/lib/ReactContext'         : 'window'
    }),
    sassLoader : webpackConfig.sassLoader
  },
  webpackMiddleware : {
    noInfo : true
  },
  coverageReporter : {
    reporters : project.coverageReporters
  }
};

if (project.globals.__COVERAGE__) {
  karmaConfig.reporters.push('coverage');
  karmaConfig.webpack.module.preLoaders = [{
    test    : /\.(js|jsx)$/,
    include : new RegExp(project.clientDir),
    exclude : /node_modules/,
    loader  : 'babel',
    query   : Object.assign({}, project.compiler, {
      plugins : (project.compiler.plugins || []).concat('istanbul')
    })
  }]
}
debug('Success karma config.');

// export default karmaConfig;
module.exports = (cfg) => cfg.set(karmaConfig)

Is there a way to make karama config to be exported default ?
Because I do the same thing with webpack.config `export default webpackConfig;`

But for karma.config I recive an error when I try to do default export.
**  module.exports = function(config) {
    config.set({
      // your config
    });
  };

**

**Comment by 6zz** [comment]
very odd, this starter kit uses Karma to run tests.  have you tried running the starter kit fresh and just run `npm install && npm run test`?

**Comment by piu130** [comment]
He wants to write ES6/ES7 tests. With the standard project you can only write NodeJS standard tests.

**Comment by Catx7** [comment]
Yes tests are in ES6 syntax but something went wrong when I do ES6 for karma.config 
```
export default karmaConfig; **DON`T WORK**
module.exports = (cfg) => cfg.set(karmaConfig) **WORK**
```
But all others files like _project.config ,env.config, webpack.your config_  I changed to ES6 and export default for each file. So the problem is when I run tests I says **project.config.js**  does not have devTools and others properties.

**Comment by 6zz** [comment]
okay, now I understand what you were trying to do.  Those files are what I consider build scripts.  They are perfectly fine to remain in the CommonJS format.  They are ran in the nodejs environment to generate your app.  It's more like the nodejs runtime environment might not support es6 features fully.

```
node --v8-options | grep "in progress"
  --harmony_object_observe (enable "harmony Object.observe" (in progress))
  --harmony_modules (enable "harmony modules" (in progress))
  --harmony_function_sent (enable "harmony function.sent" (in progress))
  --harmony_sharedarraybuffer (enable "harmony sharedarraybuffer" (in progress))
  --harmony_simd (enable "harmony simd" (in progress))
  --harmony_do_expressions (enable "harmony do-expressions" (in progress))
  --harmony_iterator_close (enable "harmony iterator finalization" (in progress))
  --harmony_tailcalls (enable "harmony tail calls" (in progress))
  --harmony_object_values_entries (enable "harmony Object.values / Object.entries" (in progress))
  --harmony_object_own_property_descriptors (enable "harmony Object.getOwnPropertyDescriptors()" (in progress))
  --harmony_regexp_property (enable "harmony unicode regexp property classes" (in progress))
```

**Comment by Catx7** [comment]
changed to 
export default (cfg) => cfg.set(karmaConfig);
 and it works now,
