### ISSUE TITLE
Production builds should not contain source maps

### ISSUE THREAD

**Issue by kiejo** [davezuko/react-redux-starter-kit#119]
Currently source maps are generated for development builds as well as for production builds. I think it would be better not to generate source maps in a production build by default.

Setting the devtool option in build/webpack/development.js instead of build/webpack/_base.js should fix this.

What do you think?

**Comment by davezuko** [comment]
Very much agree, was actually just thinking about that the other day. I'll make the changer later tonight/tomorrow unless you'd like to submit a PR for it before then.

Thanks!
