### ISSUE TITLE
error at first start (npm start)

### ISSUE THREAD

**Issue by mikeshaker** [davezuko/react-redux-starter-kit#1197]
Hi, after got the repo and installed the packages i tried to npm start or yarn start but getting error

```
> $ better-npm-run start
> running better-npm-run in C:\Users\mshaker\Source\Repos\UI\SMA-UI
> Executing script: start
> 
> to be executed: "node bin/dev-server"
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn cmd ENOENT
>     at exports._errnoException (util.js:1033:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:367:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
>     at Module.runMain (module.js:607:11)
>     at run (bootstrap_node.js:425:7)
>     at startup (bootstrap_node.js:146:9)
>     at bootstrap_node.js:540:3
> error Command failed with exit code 1.
```

**Comment by sabatsu** [comment]
+1

**Comment by sshadmand** [comment]
I get this:


`Version: webpack 1.13.3
Time: 2883ms
                                Asset     Size  Chunks       Chunk Names
          app.83e86a5905382fcc1ed5.js   822 kB       0       app
    1.counter.83e86a5905382fcc1ed5.js    25 kB       1       counter
       vendor.83e86a5905382fcc1ed5.js   386 kB       2       vendor
      app.83e86a5905382fcc1ed5.js.map   976 kB       0       app
1.counter.83e86a5905382fcc1ed5.js.map  30.3 kB       1       counter
   vendor.83e86a5905382fcc1ed5.js.map   456 kB       2       vendor

ERROR in ENOENT: no such file or directory, scandir '/Users/seanshadmand/repos/fakeresponse-client/node_modules/node-sass/vendor'
 @ ./src/routes/Home/components/HomeView.scss 4:14-218 13:2-17:4 14:20-224

ERROR in ENOENT: no such file or directory, scandir '/Users/seanshadmand/repos/fakeresponse-client/node_modules/node-sass/vendor'
 @ ./src/layouts/CoreLayout/CoreLayout.scss 4:14-211 13:2-17:4 14:20-217

ERROR in ENOENT: no such file or directory, scandir '/Users/seanshadmand/repos/fakeresponse-client/node_modules/node-sass/vendor'
 @ ./src/styles/core.scss 4:14-196 13:2-17:4 14:20-202

ERROR in ENOENT: no such file or directory, scandir '/Users/seanshadmand/repos/fakeresponse-client/node_modules/node-sass/vendor'
 @ ./src/components/Header/Header.scss 4:14-207 13:2-17:4 14:20-213
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  576 kB       0       
webpack: bundle is now VALID.
`

**Comment by sshadmand** [comment]
Upgrading to webpack 1.15.0 fixed it for me.

**Comment by davezuko** [comment]
This should automatically be resolved for all npm users. For yarn users, see the PR @sshadmand referenced above.
