### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by dsteinbach** [davezuko/react-redux-starter-kit#1199]
Just wanted to say that I used to use this boilerplate but I may have to fork so I can use a more sane routing approach. I died a little looking at all those files and boilerplate just to define a couple routes. I thought boilerplates were supposed to reduce javascript fatigue?

**Comment by davezuko** [comment]
https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure

> Small applications can be built using a flat directory structure, with folders for components, containers, etc. However, this structure does not scale and can seriously affect development velocity as your project grows. Starting with a fractal structure allows your application to organically drive its own architecture from day one.

> Large, mature apps tend to naturally organize themselves in this way—analogous to large, mature trees (as in actual trees :evergreen_tree:). The trunk is the router, branches are route bundles, and leaves are views composed of common/shared components/containers. Global application and UI state should be placed on or close to the trunk (or perhaps at the base of a huge branch, eg. /app route).

If it doesn't work for you, no worries.
