### ISSUE TITLE
access store for axios

### ISSUE THREAD

**Issue by ErwinLee10** [davezuko/react-redux-starter-kit#1200]
Hi, basically I have the same problem with this guy: 
http://en.stack.aiseen.org/questions/38460949/what-is-the-best-way-to-access-redux-store-outside-a-react-component

Would like to access the authorization code from redux but not sure how I can do that. 
Also need to find a way to dispatch an action from the axios interceptor. Could anyone guide me?

**Comment by davezuko** [comment]
Hey, give http://redux.js.org/docs/advanced/AsyncActions.html a shot. Unfortunately I'm not able to answer usage questions like this in this repo.
