### ISSUE TITLE
Issues after npm install

### ISSUE THREAD

**Issue by mesin** [davezuko/react-redux-starter-kit#1206]
~/tmp/work-co/universal-react-redux-starter-kit [master] $ npm run start:prod

> react-redux-starter-kit@3.0.0-alpha.2 start:prod /Users/apple/tmp/work-co/universal-react-redux-starter-kit
> better-npm-run start:prod

running better-npm-run in /Users/apple/tmp/work-co/universal-react-redux-starter-kit
Executing script: start:prod

to be executed: babel-node bin/server 
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "production". +82ms
  app:config Found overrides, applying to default configuration. +27ms
/Users/apple/tmp/work-co/universal-react-redux-starter-kit/node_modules/koa/lib/response.js:47
    const { res } = this;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/apple/tmp/work-co/universal-react-redux-starter-kit/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/apple/tmp/work-co/universal-react-redux-starter-kit/node_modules/koa/lib/application.js:11:18)
    at Module._compile (module.js:413:34)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "run" "start:prod"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.0-alpha.2 start:prod: `better-npm-run start:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@3.0.0-alpha.2 start:prod script 'better-npm-run start:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/tmp/work-co/universal-react-redux-starter-kit/npm-debug.log

**Comment by fernandolobao** [comment]
I have the same issue, does anyone fixed or have a workaround for it?

**Comment by davezuko** [comment]
This old issue is outdated since the webpack 2 overhaul was completed, but it's fixable by upgrading your Node version (try `^6.0.0`). If you are experiencing issues on `^5.0.0` let me now where the error is and then we can patch it to support older JS versions.

Closing for now, since this base issue is outdated, but I'd be interested in solving your latest issue if you can provide an updated log @fernandolobao .

**Comment by key60529** [comment]
I just clone the project today and try to run it by using
`yarn start`
and I still got this issue in environment like this 
npm 3.10.8
node v7.0.0
yarn v0.24.4
