### ISSUE TITLE
RedBox error not mapped to original source code

### ISSUE THREAD

**Issue by vikas0380** [davezuko/react-redux-starter-kit#1207]
Error in RedBox/Console showing links to compiled code instead of original code from Webpack  
![screen shot 2017-04-03 at 1 23 46 am](https://cloud.githubusercontent.com/assets/4193675/24590545/7a7ec296-180c-11e7-958a-311a78986c15.png)

**Comment by davezuko** [comment]
Closing in favor of PR discussion.
