### ISSUE TITLE
Link to React Router on main documentation page 404s

### ISSUE THREAD

**Issue by damiangreen** [davezuko/react-redux-starter-kit#1213]
The offfending link:

https://github.com/reactjs/react-router/blob/master/docs/API.md#plainroute

**Comment by davezuko** [comment]
Thank you. Looks like they moved it without offering redirects.

Fixed with https://github.com/davezuko/react-redux-starter-kit/commit/01b3508e974d675084284c78c9a7e3cb5223c6cf.
