### ISSUE TITLE
ERROR in Cannot assign to read only property 'canCollapseWhitespace' of true

### ISSUE THREAD

**Issue by whatifif** [davezuko/react-redux-starter-kit#122]
I installed davezuko/react-redux-starter-kit with Node v4.1.2 on Ubuntu 14.04.

Affter "npm install" and "npm start" , I got this error message at the end of long message shown on terminal.
When I go to http://localhost:3000, I only see this error message on blank screen.

**Comment by davezuko** [comment]
Hey, is there any chance you could provide a full stack trace for this? I can't think of a cause off the top of my head, so that would help a lot.

**Comment by davezuko** [comment]
I just reinstalled all node_modules and am getting the same error. Looking into it now, weird.

**Comment by davezuko** [comment]
Ok, looks like it was from a bad configuration option passed to HtmlWebpackPlugin. I've updated it and it's now building correctly for me. If you could pull latest and verify that would be awesome. Thank you for catching this!

**Comment by whatifif** [comment]
Thanks for your quick reaction ! 
Now it works without error.

Much more thanks for your sharing this nice work !

**Comment by davezuko** [comment]
Awesome, closing this then.
