### ISSUE TITLE
Deploying the static dist file using express

### ISSUE THREAD

**Issue by pradyuz3rocool** [davezuko/react-redux-starter-kit#1220]
How do i deploy the static dist file in AWS EC2  using nginx or express

**Comment by ajnudnyy** [comment]
I'm facing this problem too, I've fixed all of other error,  finally didn't fix this.
![Uploading error.jpg…]()

**Comment by davezuko** [comment]
See https://github.com/davezuko/react-redux-starter-kit#static-deployments.

**Comment by ishan123456789** [comment]
The link is broken where it refers to the configuring your server url . Can you please fix it.
And can you please help with deploying on Apache server ? @davezuko
