### ISSUE TITLE
Problem with resolving alias...

### ISSUE THREAD

**Issue by DeanHristov** [davezuko/react-redux-starter-kit#1226]
Hi guys... 

Currently I've a problem with creating an alias in **webpack.config.js**, that's would be acceptable in **/** directory  i mean in root directory on the project. When I try to create some alias in **webpack.config.js** via `  resolve : {
    root  : project.paths.client(),
    alias: {
      '~config': project.paths.config() // Here is my alias 
    },
    extensions : ['', '.js', '.jsx', '.json']
  }`, 
webpack throw error:
`ERROR in ./src/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./config/project.config in /home/***/***/project/src
 @ ./src/main.js 23:15-48`

So when when I have this configuration I just try to refer **project.config.js** from **/src/main.js** 
and my code is nothing more than `import $config from '~config/project.config'`

Where exactly is the problem in the code above? What is wrong? 
I just want to define alias which can be acceptable from everywhere in the project.

**Comment by DeanHristov** [comment]
I tried with relative path and absolute path, but the result is same.

**Comment by davezuko** [comment]
One problem with this is that you can't import any modules that rely on Node bindings (e.g. `fs`) into webpack, because they won't be running on the same platform in the browser.

If you were to create a config that webpack could package, and you wanted to import that across your project, it would look like this:

```js
// ./src/app.config.js
export default {
  foo: 'bar'
}

// ./build/webpack.config.
alias: {
  // points to `./src/app.config.js`
  config: inProject(project.srcDir, 'app.config'),
}

// src/path/to/some/nested/file.js
import $config from 'config'

$config.foo // => 'bar'
```

Hope that helps.
