### ISSUE TITLE
__webpack_hmr 404 (Not Found)

### ISSUE THREAD

**Issue by kanzuki** [davezuko/react-redux-starter-kit#1239]
Sorry, extremely new here to everything. Everything's working fine in localhost:3000, but once I run 'npm run compile' and uploaded the files under /dist folder into a directory in a ftp server, the message "__webpack_hmr 404 (Not Found)" keeps appearing several times inside the console. Not only that, it seems the routes are no longer working - which is probably associated with this error. Any idea what I might be doing wrong?

**Comment by davezuko** [comment]
Try running `npm run deploy:prod` and serving those files. If you compile the application to disk in development mode, it will be configured to look for HMR code. This should probably be better than it is, but it's a simple fix regardless.

**Comment by kanzuki** [comment]
Run into a few es lint problems but got that fixed. Works like a charm, thank you so much!! Especially for this starter kit - awesome work!!!
