### ISSUE TITLE
redux-router instead of react-router

### ISSUE THREAD

**Issue by nodkz** [davezuko/react-redux-starter-kit#124]
How do you think keep your router state inside your Redux store it is good solution or not?
https://github.com/rackt/redux-router ready for production or not?
Thoughts?

**Comment by davezuko** [comment]
Somebody made a PR for this a while ago and it nearly made it in. I've yet to use redux-router, but agree that it would make sense. Have you used it? Are there any possible negatives to switching to it? I'm eager for RR to release a stable 1.0.0, and will probably make a decision around that time.

**Comment by nodkz** [comment]
No, I don't use it. I think that negatives are 
- some good npm packages, which can extend functionality of react-router on client/server/native will not be ported to redux-router. But at this point of time I don't know such packages.
- lack in docs and examples

Pros:
- this library is from the redux maintainers
- router state in store without hacks and monkey-patching
- too much stars and forks. I think that it can not be dead trend.

**Comment by davezuko** [comment]
Redux-router has been added.
