### ISSUE TITLE
Hot reloading for styles not working

### ISSUE THREAD

**Issue by padsbanger** [davezuko/react-redux-starter-kit#1252]
Hello,

I am not sure if thats a feature request or a bug, but I have just cloned this repo, started the project, changes some styles in `src/styles/main.scss` and I get this error in dev tools:

![screenshot 2017-05-25 14 10 33](https://cloud.githubusercontent.com/assets/471029/26449733/30f54930-4154-11e7-9cb3-6a4bd2595007.png)

The styles get compiled in console, but I have to refresh the browser manually.

**Comment by davezuko** [comment]
This is caused by the same thing as https://github.com/davezuko/react-redux-starter-kit/issues/1248#issuecomment-302939754. Try that fix out and see if it works for you. Your IP of course being http://10.168.20.77:3000.

**Comment by padsbanger** [comment]
Yes, it works thank you 😄  Not sure why IP is hard coded like that.

**Comment by davezuko** [comment]
@padsbanger it's so you can access the dev server from other devices. I think I'll just remove it as the default so others don't experience this :/.
