### ISSUE TITLE
when I execute 'npm run deploy:prod', many error happened! Some space...

### ISSUE THREAD

**Issue by LaurenSUIYUE** [davezuko/react-redux-starter-kit#1257]
![default](https://cloud.githubusercontent.com/assets/25794273/26537629/afabab08-4473-11e7-9b05-560f711258a5.png)

**Comment by davezuko** [comment]
These are all linter errors from eslint enforcing a certain code style in your project. We use https://github.com/feross/eslint-config-standard, but you can change this here: https://github.com/davezuko/react-redux-starter-kit/blob/master/.eslintrc#L3-L6.
