### ISSUE TITLE
Local bootstrap?

### ISSUE THREAD

**Issue by OKNoah** [davezuko/react-redux-starter-kit#126]
I see that the Bootstrap CDN is used. How can I install it right in the project?

I've installed Bootstrap and Bootstrap-sass, but I get errors like these,

    ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
    Module parse failed: /Users/Username/Documents/dev/functin-frontend/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./~/css-loader!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?includePaths[]=/Users/Username/Documents/dev/functin-frontend/src/styles!./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss 6:4446-4509

**Comment by nodkz** [comment]
You should add loaders for fonts files.

For example, this is mine part of config with extended params: 
`
config['module']['loaders'] = [
    ....
    { test: /\.(jpg|png)$/,       loader: 'url-loader?name=[path][name].[ext]&limit=100000' },
    { test: /\.woff(\?.*)?$/,     loader: "url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff" },
    { test: /\.woff2(\?.*)?$/,    loader: "url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff2" },
    { test: /\.ttf(\?.*)?$/,      loader: "url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/octet-stream" },
    { test: /\.eot(\?.*)?$/,      loader: "file-loader?prefix=fonts/&name=[path][name].[ext]" },
    { test: /\.svg(\?.*)?$/,      loader: "url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=image/svg+xml" }
];
`

**Comment by davezuko** [comment]
@OKNoah I just merged in @nodkz 's PR (thank you!) so give it a try again and see if you're still having problems.

**Comment by mikedevita** [comment]
I am having "funkiness" with this, probably due to user error.. but either way.

```
styles/vendor/_bootstrap.css
```

and then in my `styles/core.scss` i have
```
@import 'base';
@import 'vendor/bootstrap';
```

some of the styling appears, but things like `.container` don't work :\

**Comment by davezuko** [comment]
@mikedevita can you try disabling this?

https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_base.js#L28

**Comment by mikedevita** [comment]
```
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./src/views/HomeView.scss
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".counter--green", ".counter--green" is weird
```

**Comment by davezuko** [comment]
Just delete `HomeView.scss` and remove the import in `HomeView.js`, since that file is making use of [CSS modules](https://github.com/css-modules/css-modules).

**Comment by mikedevita** [comment]
yup, that worked great thanks for the quick responses! Happy Holidays to you.

**Comment by davezuko** [comment]
Cool, glad it worked. I should probably emphasize the documentation around CSS modules so people don't run into similar issues. Merry Christmas!
