### ISSUE TITLE
Global Redux Variables?

### ISSUE THREAD

**Issue by sentry0** [davezuko/react-redux-starter-kit#1283]
I'm looking for a way to set a global variable in the redux datastore. My use case is that I want to track some session information about the current logged in user and I do not want to use localStorage as some of this information will be sensitive.

**Comment by synchu** [comment]
You just have to inject a "global" reducer within src/store/reducers.js.
**reducers.js**
```
......
import globals from './globals'
....
export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    location: locationReducer,
    globals: globals,
    ...asyncReducers
  })
}
```
**globals.js**
```
export const globals = (state = {}, action) => {
  switch (action.type) {
    case SET_SENSITIVE: return ({ ...state, sensitive: action.payload})
    case APP_INIT: return ({ ...state, init: action.payload})
............
    default:
      return ({ ...state })
  }
}

```
Then you just need to dispatch SET_SENSITIVE, APP_INIT or whatever action you need to set "globals".
 
And simply access them in your containers:
**SomeContainer.js**
```
.....................
const mapStateToProps = (state) => {
sensitive: state.globals.sensitive,
init: state.globals.init
}
...................
```
Hope this helps.
Niki

**Comment by sentry0** [comment]
This is a good solution, thank you.

**Comment by aphexyuri** [comment]
Thanks for this answers!

However this only puts me half way there. I'm attempting to do something similar, but I want to retrieve data from an remote endpoint at startup. Based on the answer here I've not set up a global reducer to handle the rsponse, but how am I able to trigger a resulting action to set this in motion? In short, I want to call `getGames` (below) but from a global place.

Below is my reducer:
```
import axios from 'axios'

export const GET_GAMES = 'GET_GAMES'

// ------------------------------------
// actions
// ------------------------------------
export function getGames (action) {
  var appSettings = require('AppSettings')

  var data = { action: 'getAllGames' }

  var requestConfig = {
    headers: {
      'x-api-key': appSettings.aws_api_key
    },
    method: 'post',
    url: appSettings.api_endpoint_stratus_services + '/gamesettings',
    data: data
  }

  const request = axios(requestConfig)

  return {
    type: GET_GAMES,
    payload: request
  }
}

// ------------------------------------
// Reducer
// ------------------------------------
export default function globalsReducer (state = {}, action) {
  // console.log('GLOBALS.JS REDUCER, action:', action);

  if(action.type === GET_GAMES) {
    console.log('globals.js', action.type)
    return ({ ...state, gamesList: action.payload})
  }
  else {
    return ({ ...state })
  }
}
```

**Comment by synchu** [comment]
You can possibly call getGames in src/main.js render function. 
It doesn't get much more global than this.
Using axios (i.e. async/promises) you will need to wait, before dispatching the actual action, i.e. something like:
```
.....
axios(requestConfig)
.then(response => 
  store.dispatch({type: GET_GAMES, payload: response})
.catch(error => {
      console.error('Axios catch error', error)
      if (error.response) {
        console.log(error.response.data)
        console.log(error.response.status)
        console.log(error.response.headers)
      }
      return error
    })
....
```

Hope this helps.

**Comment by aphexyuri** [comment]
Iy did in a way, thanks!
