### ISSUE TITLE
React code not loading in production

### ISSUE THREAD

**Issue by prestonbernstein** [davezuko/react-redux-starter-kit#1287]
Hi all,

I am trying to run my application in production, but am not getting any output on the screen. I am using the latest webpack config for the project. I added a script for deploy that is as follows:
```js
"deploy": "cross-env NODE_ENV=production npm run lint && npm run test && npm run clean && npm run compile && node build/scripts/start" 
```

The server runs on production, and then when I go to `localhost:3000` in my browser, nothing appears. There are two script tags containing the js files that are not visible when the app is run in development.

```
<!DOCTYPE html>
<html class="company" dir="ltr" lang="en">
<head>
	<meta charset="utf-8">
	<meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible">
	<title> Dashboard</title>
	<meta content="width=device-width,minimum-scale=1,maximum-scale=1,user-scalable=no" name="viewport">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js">
	</script>
	<link href="/CompanyLogo64.png" rel="shortcut icon">
</head>
<body class="pace-big" data-version="4.0.0">
	<div id="root">
          <script type="text/javascript" src="/main.70dbe42a3beaf52a4500.js"></script>
          <script type="text/javascript" src="/normalize.628df6127747801c6313.js"></script>
	</div>
</body>
</html>
```

Any help would be fantastic.

**Comment by needcaffeine** [comment]
On production, npm generates all the asset files into /dist, which you should serve using a web server. Not sure why you are running the express server on production. Take a look at server/main.js, which has sections for development vs production.

**Comment by prestonbernstein** [comment]
I understand that as-is, it is not ideal for production. However, in the last iteration of the starter-kit, users were able to take a look at the application running in production this way.

From the current README:
> The Express server that comes with the starter kit is able to be extended to serve as an API and more, but is not required for a static deployment.

Is this no longer the case?

**Comment by needcaffeine** [comment]
Ah, I see.

What you're missing is the NODE_ENV being set for each of those different commands. Try this: `npm run clean && cross-env NODE_ENV=production npm run compile && cross-env NODE_ENV=production node build/scripts/start`.

**Comment by prestonbernstein** [comment]
Thanks for the help, @needcaffeine 

Unfortunately, modifying the build script to what you suggested does not solve the problem.
