### ISSUE TITLE
Testing modules that depend on fetch

### ISSUE THREAD

**Issue by nhagen** [davezuko/react-redux-starter-kit#129]
I'm not sure how to test modules that depend on `fetch` with the default configuration. What can I do to get access to `fetch` in tests since webpack isn't compiling on individual modules?

**Comment by davezuko** [comment]
Hey sorry, been super swamped lately. Could you modify the exclude regex possibly?

**Comment by gaearon** [comment]
Can you mock it as described here?
https://github.com/rackt/redux/blob/master/docs/advanced/AsyncActions.md#async-action-creators

**Comment by davezuko** [comment]
@nhagen did you ever figure this out?

**Comment by sudodoki** [comment]
I made tests work with whatwg-fetch & babel provide plugin for fetch by using https://www.npmjs.com/package/babel-plugin-rewire + https://www.npmjs.com/package/fetch-mock

My code looks something like:
```
// in fetchWrapper.js
// used to work together with rewire;
module.exports = fetch;
```
&&
```
// in api.js
const fetch = require('./fetchWrapper');
// … code using fetch in here
```

And all further setup in specs boils down to

```
import fetchMock from 'fetch-mock';
import { apiFn1, apiFn2, __RewireAPI__ as apiRewire } from 'utils/api';

var fetchInstance;
  before(() => {
    fetchInstance = fetchMock.mock({ greed: 'good' });
    apiRewire.__set__('fetch', fetchInstance);
  });

  after(() => {
    fetchMock.restore();
    apiRewire.__ResetDependency__('fetch');
  });

  beforeEach(() => fetchMock.reMock());
```

**Comment by davezuko** [comment]
I'll be adding a link here from https://github.com/davezuko/react-redux-starter-kit/issues/221, closing for now.
