### ISSUE TITLE
Unable to use hashHistory with fractal structure

### ISSUE THREAD

**Issue by Mnw2212** [davezuko/react-redux-starter-kit#1297]
Hi,
I did a build for my project and now I am trying to get it to run as a standalone file( not served ).

By standalone I mean expecting it to work with fileURL like `file:///Users/username/project/dist/index.html`.

This is not working, I get a blank page.
The solution to this problem seems like using hashHistory instead of browserHistory.

I have tried replacing all `borswerHistory` to `hashHistory` but that doesnt seem to work. Please help me use hashHistory with this kit

**Comment by mikedevita** [comment]
I could be wrong (without testing it first) but this could have to do with the way most browsers handle `file:///` URLs. Have you tried using something like [http-server](https://www.npmjs.com/package/http-server) by running `http-server dist/` and see if hashHistory works then? 

Or is your use case required to serve up via `file:///`?

**Comment by Mnw2212** [comment]
My setup requires the files to be served via `file:///`

replacing browserHistory with hashHistory actually worked, but the problem was the since my public path was `/` , the js and css files were loaded as `file://scqeefs4532334.js` as opposed to `file:///<path>/<hash>.js`

This is solved.
Solution: 
- Replace all browserHistory to hashHistory
- change publicPath in config file from `/` to `./`
