### ISSUE TITLE
Difficulty setting up code coverage

### ISSUE THREAD

**Issue by sproogen** [davezuko/react-redux-starter-kit#1299]
I am trying to implement code coverage into my project that is using this starter kit (v3.0.1).

What was the reason it was removed in v3.0.0 and is there a plan to put it back in?
Or does anyone have code coverage working using this kit?

Thanks

**Comment by gontard** [comment]
I have added a coverage reporter in `karma.conf.js`:

    const karmaConfig = {
      ...
      coverageReporter: {
        reporters: [
          { type: 'text-summary' },
          { type: 'lcov', dir: 'coverage' }
        ]
      }
      ...
    }


and at the end:


    const withCoverage = !argv.watch;
    if (withCoverage) {
      karmaConfig.reporters.push('coverage');
      const babelLoader = webpackConfig.module.rules[0].use[0];
      babelLoader.query.plugins.push(['istanbul', {
        exclude: [
          `tests/**/*.js`
        ]
      }]);
    }

**Comment by sproogen** [comment]
I have managed to figure this out earlier and get code coverage mostly working.

@gontard I have also just tried your solution and it didn't seem to work. I have copied in your config exactly as you said and it just prints out 100% coverage but without finding any of the files.
So it prints out like `100% ( 0/0 )`

**Comment by stelioschar** [comment]
@sproogen I confirm the same problem with the above solution. 
What was your working configuration?

**Comment by sproogen** [comment]
@stelioschar I created this pull request here https://github.com/davezuko/react-redux-starter-kit/pull/1307
