### ISSUE TITLE
just pulled and installed, got this error

### ISSUE THREAD

**Issue by dougvk** [davezuko/react-redux-starter-kit#131]
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner). 
>invariant	@	invariant.js:39 
>ReactOwner.addComponentAsRefTo	@	ReactOwner.js:67`

**Comment by davezuko** [comment]
Hm, very interesting. I just did a full reinstall and couldn't reproduce this. I've never actually seen this error before so I don't really know where to begin debugging it, so... what node/npm version are you using? I'll dig around and see what I can find, sorry about that.

**Comment by dougvk** [comment]
old version of node! please disregard
