### ISSUE TITLE
Deprecated ??

### ISSUE THREAD

**Issue by nodeEnthu** [davezuko/react-redux-starter-kit#1313]
oh no! .. thought we were doing so well here ..anyways .. great  product ... i used this to make a production app... 

thanks for all the help in maintaining it over past year(s)

**Comment by MinJieLiu** [comment]
why? `create-react-app` is a semi-finished product

**Comment by seeruk** [comment]
`create-react-app` doesn't even aim to do anywhere near as much stuff. This seems like an odd decision.

**Comment by YutHelloWorld** [comment]
Inspired by this project.  I upgrade  react-router v4, webpack 3  and use ES7  syntax  writing react component in [vortex-react](https://github.com/YutHelloWorld/vortex-react).

**Comment by chungchiehlun** [comment]
My production was based on the project. The fractal structure is creative concept and make my folder structure clear. I thought it's an awesome project and needed to be maintainable again.

**Comment by mouhsinelonly** [comment]
if the owner cant keep updating maintaining this repo, it would be better to transfer it to someone else who can.

**Comment by dvdzkwsk** [comment]
@mouhsinelonly I considered that, but honestly I don't think it makes much sense to fragment the community further. If, however, you (or anybody else) would like to take over I'd be more than happy to provide commit rights.

Closing for https://github.com/davezuko/react-redux-starter-kit/issues/1331.
