### ISSUE TITLE
Error while running from initial state

### ISSUE THREAD

**Issue by roychoo** [davezuko/react-redux-starter-kit#132]
Hi,

gotten this error while checking out and running it.

npm version 3.3.8
node version v4.2.1
![image](https://cloud.githubusercontent.com/assets/1853311/10641423/c326e4f4-784b-11e5-8884-512d57c13134.png)

any idea?

**Comment by davezuko** [comment]
Closing this since you found the problem:

> @davezuko found the problem. there was another .babelrc in the parent directory...

Would still be nice to figure out _why_ this affected it, so I'll stay on gitter to try to figure that out.
