### ISSUE TITLE
Error when running `npm test` in CircleCI

### ISSUE THREAD

**Issue by EwanValentine** [davezuko/react-redux-starter-kit#1324]
I have an application built using this starter kit, which all works locally fine. However, when I run `npm test` as part of my build, I'm getting a strange error which seems to originate from PhantomJS 

```

START:
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: Symbol
  at webpack:///~/zen-observable-ts/lib/zenObservable.js:394:0 <- tests/test-bundler.js:76335
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: Symbol
  at webpack:///~/zen-observable-ts/lib/zenObservable.js:394:0 <- tests/test-bundler.js:76335
```

**Comment by amangeot** [comment]
Same here, it's coming from an ES6 for of iterator. 

It looks like PhantomJS needs to be polyfilled, I didn't manage to make it work yet.

**Comment by EwanValentine** [comment]
Glad it's not just me! I've tried a few different versions of node without any luck. I've had to skip tests on build for now which is obviously not ideal...

**Comment by amangeot** [comment]
Try installing `es6-symbol` and `es5-ext` then adding this to the file `normalize.js`, it worked for me
```
// 4) Symbol
// ------------------------------------
// PhantomJS doesn't implement ES6 for.. of loops
if (typeof Symbol === 'undefined') {
  require('es6-symbol/implement')
}

if (typeof [][Symbol.iterator] === 'undefined') {
  require('es5-ext/array/#/@@iterator/implement')
}
```
The idea is to polyfill Symbol and array[Symbol.iterator] that for..of loops require

**Comment by dvdzkwsk** [comment]
Thanks @amangeot!

I realize I'm super late to the party, but for fixes like this I've opened up https://github.com/davezuko/react-redux-starter-kit/issues/1331 to accept new contributors, if any of you are interested.
