### ISSUE TITLE
Migration to another project

### ISSUE THREAD

**Issue by chungchiehlun** [davezuko/react-redux-starter-kit#1330]
After the kit deprecated, create-react-app seems to be a better substitution. (#1313 #1321) 
Accordingly, I tried to integrate the starter kit with it. I launched a project [chalet starter app]( https://github.com/chungchiehlun/chalet-starter-app) to accomplish this and just publish the first release. If you like the folder structure of starter kit and convenient command line of create-react-app. Give it a try. I wonder whether the project could benefit bootstrapping of your project. 

Thanks.

**Comment by dvdzkwsk** [comment]
Cool project! Also, please see https://github.com/davezuko/react-redux-starter-kit/issues/1331.
