### ISSUE TITLE
Error with react-bootstrap

### ISSUE THREAD

**Issue by hunterbmt** [davezuko/react-redux-starter-kit#136]
Hot load feature will be broken if we add 'react-bootstrap' into vendor_dependencies (config.js)

**Comment by davezuko** [comment]
Looking into it, but in the meantime if you just remove all React-related vendor dependencies HMR works.

**Comment by hunterbmt** [comment]
Thank for your quick response @davezuko . I can include react-router but not react-bootstrap :)

**Comment by nhagen** [comment]
I'm having some trouble with hot loading right now. Removing everything but `react` and `redux` solves this for me. Where can I learn more about the relationship between the vendor config and hot loading so I can better debug this?

**Comment by davezuko** [comment]
@nhagen unfortunately I don't really have any resources regarding this, but since this seems like a bigger problem I'm going to keep the generic hot-reloading issue in https://github.com/davezuko/react-redux-starter-kit/issues/154. Still not sure how to solve this w/ react-bootstrap w/o eliminating much of the vendor bundle.

**Comment by davezuko** [comment]
@hunterbmt did you ever figure this out? I'll try picking it up again, but last I left it I still hadn't come up with anything beyond disabling most of the vendor dependencies. My guess is it has to do with webpack matching `react` in react-bootstrap with its naive path-matching pattern, as that's an issue I've seen before with `redux-devtools/lib/react`.

**Comment by davezuko** [comment]
Closing this for now, if this is still an issue or you have more details I'd be happy to re-open, but it's not necessarily an issue with the starter kit, moreso with common modules.
