### ISSUE TITLE
Upgrade strategy

### ISSUE THREAD

**Issue by brancusi** [davezuko/react-redux-starter-kit#138]
Hi,

What is the best upgrade strategy? I see a lot of nice changes I would like to move to. Is it just a copy paste deal right now?

Thanks

**Comment by kyleect** [comment]
There was a ticket about this a while back, can't seem to find it. I don't think there is a good way of doing this since this is just a template/starter kit. I would love to see this feature though as this code base just gets better and better and manually copying new changes is a bit tedious.

**Comment by brancusi** [comment]
Thanks @kyleect

**Comment by davezuko** [comment]
@brancusi as long as you're not still using the server you should be able to just copy over the build folder. You may have to to tweak your webpack.config.js and npm dependencies, but the build folder is the biggest piece and can mostly just be dropped in.
