### ISSUE TITLE
Socket.io integration

### ISSUE THREAD

**Issue by ajchambeaud** [davezuko/react-redux-starter-kit#14]
Nice work! I've not a full experience with Redux, so i want to ask you, in your opinion what is the best way to integrate in this stack, Socket.io/websocket events to build components that manage real-time data?

**Comment by davezuko** [comment]
Heya, thanks! Honestly I haven't had a chance to play with websockets yet so I can't be of much help. Maybe trying posting this on Redux repo? They seem to be pretty good about answering questions like this or at least pointing you in the right direction.
