### ISSUE TITLE
Upgrade Babel to ^6.0.0

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#150]
Would be great to get this done as soon as possible; keeping an eye on https://github.com/babel/babel-loader/issues/123.

**Comment by justingreenberg** [comment]
`babel-loader@6.0.1` has been released with babel 6 api support just have to wait for some other deps to catch up—specifically the react-transform plugin and related repositories

see the [discussion on babel-plugin-react-transform issue](https://github.com/gaearon/babel-plugin-react-transform/issues/46) (dan indicates support is coming with next release, sometime in the next couple weeks)

i'm tracking this closely and will submit pr when deps are ready

**Comment by davezuko** [comment]
Awesome thanks. I was naive in thinking that once babel-loader was caught up that would be most of it.

**Comment by starandtina** [comment]
Is there any update for it?

**Comment by davezuko** [comment]
@starandtina I've had a difficult time figuring out where react-transform/hot-reload and redbox-react are, so hopefully within the next week or so this will finally be @ babel 6. The process has just gotten harder since babel disabled github issues.

**Comment by justingreenberg** [comment]
@starandtina @davezuko i'm still on top of this guys. [there is a PR](https://github.com/chicoxyzzy/babel-plugin-react-transform/tree/babel-6)—used on the `babel-6` branch of my fork of [react-transform](justingreenberg/react-transform-boilerplate/tree/babel-6)... HMR, catch-errors, etc are all working. waiting for author to merge. 

also, to support eslint we'll need to wait for babel ast conversion to esprima, which is also in the works

**Comment by davezuko** [comment]
Thanks @justingreenberg, I just stumbled upon https://github.com/gaearon/babel-plugin-react-transform/pull/50 before seeing your edit so it looks like you're far ahead of me.

**Comment by davezuko** [comment]
@justingreenberg looks like https://github.com/gaearon/babel-plugin-react-transform/pull/50 just got merged and a pre-release is on the way later today.

**Comment by justingreenberg** [comment]
Awesome—I already have a working branch of this repo with my local fork of react-transform. Just have to review, merge and rebase. I'm meetings until around 4pm EST, will submit PR today whether pre-release get pushed or not :)

**Comment by davezuko** [comment]
Thanks! You're the best haha; I feel like every issue thread I'm in I see you with a PR or something. Anyways, looking forward to it; the test setup will probably have to change a bit now that `isparta` is on babel 6 (iirc), but either way super excited to finally get this moving!

**Comment by justingreenberg** [comment]
Haha I totally got sucked in. Babel and Webpack were always kinda just magic to me. Dan's move to london and resulting delay in react-transform ended up being a blessing in disguise—it forced me to sit down read the babel source like a book and totally demystified the ecosystem. Now I'm hooked :)

**Comment by davezuko** [comment]
Not to sidetrack this too much, but is that what helped you the most (reading the source)? Babel is still mostly a black box to me despite some of the talks I've watched... so I'm going to be going through https://github.com/thejameskyle/babel-plugin-handbook today and then maybe dig into the source later.

**Comment by justingreenberg** [comment]
[babel-plugin-handbook](https://github.com/thejameskyle/babel-plugin-handbook) is by far the most comprehensive resource—I *strongly* recommend starting there.

@thejameskyle really does an awesome job introducing and breaking down the internals: 

**parsing** (code &rarr; lexical [tokens] &rarr; syntax tree [AST])
**traversing** (visitors, paths, scope, binding)
**tranforming** nodes in the AST. Babel's API surface is surprisingly small.

Since bascially everything is a plugin in v6, there are a ton of examples in [babel-packages](https://github.com/babel/babel/tree/master/packages) for everything from sugaring syntax with `babel-plugin-syntax-jsx` to transforms like `babel-register` that traverses an entry module and transpiles all downstream imports/requires. it's super moduler and most of the packages are easily digestible in a few minutes (they are tiny, most are like < 50 LOC) :smile:

**Comment by justingreenberg** [comment]
Also FYI, hidden away in the `documentation` branch of his [personal babel fork](https://github.com/thejameskyle/babel/tree/documentation/doc/packages), james has started work on documenting the module APIs—currently there's `babel-traverse` and `babel-types`

**Comment by davezuko** [comment]
Thanks a bunch, I'll devote some time to reading through all these when I can.

**Comment by davezuko** [comment]
Closing this for now since it's been merged; additional issues are welcome for any bugs that may arise. Thanks for all your work @justingreenberg!
