### ISSUE TITLE
Uncommited redux react router actions can cause issues debugging in dev tool

### ISSUE THREAD

**Issue by kyleect** [davezuko/react-redux-starter-kit#151]
I'm noticing what could potentially be called a bug.

1. Fresh clone of the repo
2. `npm start`
3. Observe redux react router actions in the debug tool: routerDidChange, replaceRoutes, routerDidChange

If I click the counter to increment and then revert the page content disappears. I believe these router actions should be commited to the redux store on initial page load to prevent this from happening.

**Comment by davezuko** [comment]
Good catch, thanksl not sure what to label it as. If you'd like to submit a PR that would be awesome, if not I'll try to get to it when I have a minute. Thanks!

**Comment by davezuko** [comment]
Going to close this for now as after a lot of deliberation I don't think this is something the starter kit should handle. I see where you're coming from, but this is how it works out of the box w/ redux-router and I don't necessarily want to tailor the starter kit to the devtools. I might be switching this starter kit to https://github.com/Agamennon/redux-tiny-router anyways, so we'll see.
