### ISSUE TITLE
Hot reload stopped working

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#154]
I hesitate to bring this up as an issue here, in case it's just my environment, but hot reloading on all of the apps I've built with the kit has stopped working. It doesn't matter if it's an app I haven't touched in a few days where it was known to work before (and no dependency changes or updates) or a fresh clone of the kit with a fresh npm install. I get the message in the console that hot loading is enabled, but no changes to components have any effect. I've restarted Chrome (46.0.2490.80 (64-bit)), my computer etc. and still no luck. Can anyone else confirm?

**Comment by neverfox** [comment]
Just to confirm it wasn't the kit, I cloned the react-transform-boilerplate example, and it doesn't work either. I'm at a loss.

**Comment by davezuko** [comment]
Ugh, really not sure why this issue keeps cropping up. Just out of curiosity, what did you have to do to fix it with react-transform-boilerplate?

**Comment by neverfox** [comment]
I'm...not really sure. It just started working after a few tries. I was also able to confirm that this kit works fine on another machine, so this appears to be something that's wrong with that one machine's file watching. So if you want to close this, I understand.

**Comment by davezuko** [comment]
That's so strange. I'd really like to take a look on my machine but won't be able to until later tonight, so I'll leave it open for the time being.

**Comment by neverfox** [comment]
FWIW, athe update to El Capitan got things working again.

**Comment by davezuko** [comment]
That's really weird. I'm still on Yosemite with no issues... hopefully I don't get the opposite lol
