### ISSUE TITLE
Full reloads on file change

### ISSUE THREAD

**Issue by jonaswindey** [davezuko/react-redux-starter-kit#16]
When I change a file, the whole page reloads. Should the hot loader re-render without a full page refresh (and thus keeping the state)?

**Comment by ioRekz** [comment]
I think you can check the last issue
https://github.com/davezuko/react-redux-starter-kit/issues/15

**Comment by davezuko** [comment]
Not sure why this is happening, but please see the issue @ioRekz referenced. I'm looking into it but am having trouble reproducing it.

**Comment by davezuko** [comment]
I just pushed a fix for this; if you're still experiencing issues please let me know!
