### ISSUE TITLE
Scripts that set NODE_ENV to developement fail on Windows

### ISSUE THREAD

**Issue by fuczak** [davezuko/react-redux-starter-kit#162]
Command `NODE_ENV=development node --harmony bin/webpack-dev-server` fails on Windows.
Instead it should be as follows: `set NODE_ENV=development && node --harmony bin/webpack-dev-server` OR [`better-npm-run`](https://github.com/benoror/better-npm-run) can be implemented to ensure cross-platform compatibility out of the box.

The issue was introduced by #137

**Comment by davezuko** [comment]
Wow, thanks for catching that, I had no idea. I appreciate the PR, but just one question: in your opinion, what would be the better solution, removing those environment prefixes or using better-npm-run? Better-npm-run does seem like the best option initially, and I've seen it used in a few projects, but having never used it myself I'm a tad bit wary to rely on something outside of vanilla npm scripts.

I'll most likely merge your PR in, but I just wanted to hear your thoughts on this first.

**Comment by fuczak** [comment]
Here's the core functionality of better-npm-run, straight from the source code:

    var command_line = script.command;

	script.env = script.env || {};

	Object.keys(script.env).forEach(function (key) {
		var value = script.env[key];

		if(process.platform === 'win32') {
		  command_line = 'set ' + key + '=' + script.env[key] + '&& ' + command_line;
		} else {
		  command_line = key + '=' + script.env[key] + ' ' + command_line;
		}
	});

While I do understand relying on something else outside vanilla npm might feel sketchy, this in my opinion is not the case with better-npm-run because it's functionality is so simple.

Personally I would go with implementing better-npm-run instead of removing enviroment prefixes since they allow for the commands to be more flexible.

**Comment by davezuko** [comment]
Don't think you could have made your point any better, the source code says it all. I'll merge your PR in one second, thanks!

**Comment by fuczak** [comment]
Glad to help! :thumbsup:
