### ISSUE TITLE
npm start fails 

### ISSUE THREAD

**Issue by jma7889** [davezuko/react-redux-starter-kit#164]
osx with latest version of node, etc. log file is:

`
> react-redux-starter-kit@0.17.0 start XXX/react-redux-starter-kit
> npm run dev

> react-redux-starter-kit@0.17.0 dev /react-redux-starter-kit
> better-npm-run dev

env: node\r: No such file or directory

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-redux-starter-kit@0.17.0 dev: `better-npm-run dev`
npm ERR! spawn ENOENT
`
`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-redux-starter-kit@0.17.0
6 info start react-redux-starter-kit@0.17.0
7 verbose unsafe-perm in lifecycle true
8 info react-redux-starter-kit@0.17.0 Failed to exec start script
9 verbose stack Error: react-redux-starter-kit@0.17.0 start: `npm run dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-redux-starter-kit@0.17.0
11 verbose cwd XXXX/react-redux-starter-kit
12 error Darwin 15.0.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.1.1
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error react-redux-starter-kit@0.17.0 start: npm run dev
17 error Exit status 1
18 error Failed at the react-redux-starter-kit@0.17.0 start script 'npm run dev'.
18 error This is most likely a problem with the react-redux-starter-kit package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run dev
18 error You can get their info via:
18 error     npm owner ls react-redux-starter-kit
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by davezuko** [comment]
Hey, this was introduced with the latest PR. For now if you could just change your `dev` command to:

`node --harmony bin/webpack-dev-server`

instead of using better-npm-run. I'll get a fix for this ASAP.

**Comment by davezuko** [comment]
@jma7889 just released a hotfix for this, could you please pull latest and try again? This should be fixed once https://github.com/benoror/better-npm-run/pull/15 is released.

**Comment by jma7889** [comment]
The workaround is working, thanks!

On Thu, Nov 5, 2015 at 11:54 AM, David Zukowski <notifications@github.com>
wrote:

> Hey, this was introduced with the latest PR. For now if you could just
> change your dev command to:
>
> node --harmony bin/webpack-dev-server
>
> instead of using better-npm-run. I'll get a fix for this ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davezuko/react-redux-starter-kit/issues/164#issuecomment-154120899>
> .
>



-- 
Jay Ma
jma7889@gmail.com

**Comment by davezuko** [comment]
Awesome :D

**Comment by jma7889** [comment]
The new update is working too! Thank you!

Jay

On Thu, Nov 5, 2015 at 12:28 PM, Jay Ma <jma7889@gmail.com> wrote:

> The workaround is working, thanks!
>
> On Thu, Nov 5, 2015 at 11:54 AM, David Zukowski <notifications@github.com>
> wrote:
>
>> Hey, this was introduced with the latest PR. For now if you could just
>> change your dev command to:
>>
>> node --harmony bin/webpack-dev-server
>>
>> instead of using better-npm-run. I'll get a fix for this ASAP.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/davezuko/react-redux-starter-kit/issues/164#issuecomment-154120899>
>> .
>>
>
>
>
> --
> Jay Ma
> jma7889@gmail.com
>



-- 
Jay Ma
jma7889@gmail.com
