### ISSUE TITLE
Implement better-npm-run

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#165]
**Issue #1:** Figure out how to forward on CLI arguments so commands such as `dev:nw` and `dev:no-debug` don't need to entirely duplicate the dev command. Tracking https://github.com/benoror/better-npm-run/issues/20.

**Issue #2:** Wait for an npm release that includes this fix: https://github.com/benoror/better-npm-run/pull/15 so that `better-npm-run` does not have to be explicitly referenced inside of node_modules. This isn't necessary to re-integrate better-npm-run, but it would be nice.

**Comment by davezuko** [comment]
@fuczak adding you here just in case you happen to know of a quick fix for issue #1. I temporarily pulled out better-npm-run because the solution through duplication was fairly inelegant. In the meantime, I removed the explicit `NODE_ENV=development` prefixes, which were no longer necessary anyways.

**Comment by fuczak** [comment]
I've had a busy weekend, too. Sorry I couldn't help but it seems that new version of `better-npm-run` will solve both issues so that's nice.

**Comment by davezuko** [comment]
Closing this issue for now since better-npm-run is not actually needed with the removal of explicit `NODE_ENV` overrides in npm scripts. Willing to re-open if a need arises.
