### ISSUE TITLE
How to use Link and Navigation mixin?

### ISSUE THREAD

**Issue by hekike** [davezuko/react-redux-starter-kit#17]
Hi, could you help with this?

**Comment by davezuko** [comment]
Hey, you should be able to use it just like you normally would since react-router is entirely separate from Redux. Are you having any particular issues?

**Comment by ioRekz** [comment]
Link should work out of the box but the Navigation mixin won't work with es6 classes.
You just need to create the component that need the Navigation mixin with React.createClass

**Comment by hekike** [comment]
@davezuko @ioRekz thanks! Sry I missed it. It's working ;)
