### ISSUE TITLE
dev:nw is missing double hyphens in scripts

### ISSUE THREAD

**Issue by preflight** [davezuko/react-redux-starter-kit#177]
The `dev:nw` script is missing the second set of double hyphens; without it, devtools doesn't open in a new window (for me, at least, in Chrome 48).

Current:
`npm run dev --nw`

Change to:
`npm run dev -- --nw`

**Comment by davezuko** [comment]
Thanks, you're absolutely right. It used to have them but I must have forgotten them when we removed `better-npm-run`. I'll submit a patch shortly.

**Comment by davezuko** [comment]
Thanks for catching this, it's been fixed with https://github.com/davezuko/react-redux-starter-kit/commit/a27ce5dfdf41462ddd793654960adff997870ae6.

**Comment by preflight** [comment]
Sure, thanks for your work on the starter kit and for keeping it up to date -- I find it immensely valuable and it's a great resource for React/Redux developers.
