### ISSUE TITLE
Add support for babel-browser polyfill

### ISSUE THREAD

**Issue by vire** [davezuko/react-redux-starter-kit#179]
To support [Array.prototype.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) in unit-tests I was previously using karma.conf like this:

```
files: [
      'node_modules/phantomjs-polyfill/bind-polyfill.js',
      'node_modules/babel-core/browser-polyfill.js',
      'src/spec/**/*.spec.*'
    ],
```

but in redux starter kit this leads to: 

```
  TypeError: undefined is not a function!
  at ../react-redux-starter-kit/node_modules/babel-core/browser-polyfill.js:16
``` 

Does anybody have experience how to resolve such issue?

**Comment by bradbirnbaum** [comment]
I think you need to downgrade babel-core to 5.8.33

I bumped into this last night

**Comment by davezuko** [comment]
Is this a babel issue then? I would have figured that it would automatically polyfill `Array.prototype.find` if it wasn't found, but I could be totally off base.

**Comment by vire** [comment]
I think this issue is related to babel, but it depends which babel + babel-core comes bundled in `react-redux-starter-kit`

@bradbirnbaum :+1: your hint works.

**Comment by davezuko** [comment]
@vire I'm still waiting to upgrade to babel 6, so would you be cool with closing this for now and then re-opening it if it's still an issue after that upgrade?

**Comment by vire** [comment]
Makes sense, since there is no other solution than just using another version...

**Comment by vyorkin** [comment]
btw be carefull with this https://github.com/davezuko/react-redux-starter-kit/blob/master/package.json#L70, I suggest to use karma-chai-sinon instead, because it uses peerDependencies

**Comment by davezuko** [comment]
@vyorkin thanks for pointing that out, it's been replaced: https://github.com/davezuko/react-redux-starter-kit/pull/263

**Comment by vyorkin** [comment]
@davezuko, np, I've wasted several hours on because of this
