### ISSUE TITLE
Cannot import store in test

### ISSUE THREAD

**Issue by nojaf** [davezuko/react-redux-starter-kit#180]
I'm new to a lot of things in this starterkit and I'm trying to write a test where I dispatch an action from my store and verify that the state has changed.

I've created a spec file in ```/test/actions/people.spec.js```
My test:
```javascript
import configureStore from "store/configureStore";
import actions from "actions/people";

describe("invoking actions", () => {
	const store  = configureStore(window.__INITIAL_STATE__, __DEBUG__);

	it("should set the new person value", () => {
		store.dispatch(actions.newPersonChanged("John"));
		const state = store.getState();
		expect(state.people.newPerson).to.equal("John");
	});
});
```

I get an error on the import store line. I'm no expert on karma or webpack so I think I'm missing some configuration here.
Could anyone point me in the right direction here.
Thanks

**Comment by davezuko** [comment]
Hey, this is actually because the store alias got lost somewhere/sometime. If you try using a relative path does it work? I'll submit a fix for this when I get home, but that should hopefully solve your issue for now.

**Comment by nojaf** [comment]
I've tried relative ```import configureStore from "../../src/store/configureStore";``` with no luck.

**Comment by davezuko** [comment]
Woah, weird. Ok, what's the exact error you're getting? I checked the aliases and figured that was the problem, but I'll revert the title until we know exactly what it is.

**Comment by nojaf** [comment]
```
WARNING in ./src ^((?!app).)*\.(js|jsx)
Module not found: Error: a dependency to an entry point is not allowed
 @ ./src ^((?!app).)*\.(js|jsx)

ERROR in ./tests/actions/people.spec.js
Module not found: Error: a dependency to an entry point is not allowed
 @ ./tests/actions/people.spec.js 5:30-71
14 11 2015 14:30:14.383:INFO [watcher]: Changed file "C:/Projects/christmas-redux/tests/actions/people.spec.js".
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  Error: Cannot find module "../../src/store/configureStore"
  at C:/Projects/christmas-redux/tests/actions/people.spec.js:74

PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.302 secs / 0 secs)
```

**Comment by nojaf** [comment]
Looks related to https://github.com/webpack/webpack/issues/300

**Comment by nojaf** [comment]
Not sure why but using the relative path works now ```import configureStore from "../../src/store/configureStore";```
I'm guessing it was something on my end and not the starterkit

**Comment by davezuko** [comment]
Glad to hear that, though still really confused why it was broken in the first place.
