### ISSUE TITLE
How are aliases defined?

### ISSUE THREAD

**Issue by christian-fei** [davezuko/react-redux-starter-kit#183]
Hello, first of all thanks for this repo, excellent work and a lot to learn.

I wanted to ask if you could tell me how you configured the project with the alias for custom modules

Like

```
import counterActions         from 'actions/counter';
```

in https://github.com/davezuko/react-redux-starter-kit/blob/master/src/views/HomeView.js#L4

Thanks

**Comment by davezuko** [comment]
Hey, take a look at these code snippets:

https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L100 (defines the aliases)

https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack/_base.js#L34 (defines the aliases within webpack)

The docs for this configuration option in webpack can be found here: https://webpack.github.io/docs/resolving.html#aliasing -- so the `config/index.js` file simply generates these based off of what folder names you want to alias. Hope that helps.

**Comment by christian-fei** [comment]
Thank you sir!

**Comment by damiangreen** [comment]
would be great if this was updated as all these links now 404
