### ISSUE TITLE
Remove extra div around dev tools

### ISSUE THREAD

**Issue by nhagen** [davezuko/react-redux-starter-kit#189]
I was about to submit a PR to remove the 2 divs in `Root`, and saw you took the first one out. Figured I'd have the discussion before removing the second one: When you compile for production, the div inside of `Provider` is still there, but serves no semantic purpose.

Would you be willing to change `Root` to do [this] (https://github.com/rackt/redux/blob/master/examples/real-world/containers/Root.js) instead?

**Comment by davezuko** [comment]
Hey, good catch. It makes sense, but I'm a bit torn as far as the implementation of it; I find the 3 files very excessive and inelegant. I believe if you just use the `__DEV__` or `__PROD__` flags to generate the inner content of the `<Provider`>, then through minification/dead code removal in production that check will go away entirely. Thinking something like this:

```
render () {
  // this doesn't have to be a variable, it could just be inline, and it would become static
  // after it's processed with uglify.
  const content = __DEV__ ?
    ( ... ) :
    ( ... );

    return (
      <Provider>
        {content}
      </Provider>
    );
}
```

Thoughts? I think this way really helps eliminate duplicating `Root` in two separate files, but it's open for discussion.

**Comment by nhagen** [comment]
I agree, and attempted that but was still seeing the dead code when I
compiled with production. I'll try it again that way and see. I agree real
world's implementation is a bit drastic.

**Comment by davezuko** [comment]
Oh strange, I figured it would have been removed... I'll take a look as well when I get a chance. Let me know what you find out, since this would be a nice change to have.

**Comment by davezuko** [comment]
@nhagen this seems to be working for me, what are your thoughts?

<img width="605" alt="screen shot 2015-11-23 at 10 59 30 am" src="https://cloud.githubusercontent.com/assets/6439050/11341653/574c62dc-91d1-11e5-8ef8-dcd70e05158f.png">

And this is the resulting code (beautified) from a production build:

```
{
             key: "render",
             value: function() {
                 var e = l["default"].createElement(p.ReduxRouter, null, d["default"]),
                     t = e;
                 return l["default"].createElement(c.Provider, {
                     store: this.props.store
                 }, t)
             }
         }
```

**Comment by nhagen** [comment]
I've been having an unrelated issue with compiling so I haven't had a chance to play with this, but could you do something like `const content = __PROD__ || this.props.debug ? router : .... ;`

**Comment by davezuko** [comment]
Yeah but it means that the component still ends up relying on a global variable... but honestly I think that's a better solution than creating 2 additional files. I'll make a PR to remove the debug props and just commit to fully relying on the global variables.

**Comment by davezuko** [comment]
So looking at what the builds produce @nhagen, it looks like the only surefire way of getting unused DevTools code outside of production builds (even when it's dropped from the render method) is to follow that `Root.dev` and `Root.prod` style. Hmmmm.

**Comment by davezuko** [comment]
@nhagen would you mind taking a look at https://github.com/davezuko/react-redux-starter-kit/pull/211 when you get a chance? I'm using this setup in another project and it's working fairly well... not very elegant of course, but it accomplishes our goal.

**Comment by davezuko** [comment]
@nhagen please see my explanation in https://github.com/davezuko/react-redux-starter-kit/pull/211.

**Comment by davezuko** [comment]
@nhagen I got this working here: https://github.com/davezuko/react-redux-starter-kit/commit/23484a4ed4d792926832ed2f0800bdb7069d1fdd
