### ISSUE TITLE
Invariant violation in production mode

### ISSUE THREAD

**Issue by jonaswindey** [davezuko/react-redux-starter-kit#19]
```
NODE_ENV=production npm run compile
npm run server:start
```
Gives the following error(s)
```
Error: Invariant Violation: Server-side <Router>s need location, branch, params, and components props. Try using Router.run to get all the props you need
```
I suppose it is related to https://github.com/rackt/react-router/issues/1455

**Comment by davezuko** [comment]
Hey, thanks for catching this... my browser had been caching my favicon so never encountered it. I just added a fix https://github.com/davezuko/react-redux-starter-kit/commits/master so the server should no longer choke if react-router throws.

Adding a favicon also would have fixed this (and I will do that soon as well) but this should be a more robust solution in case any other invalid routes end up going through the router.
