### ISSUE TITLE
Clean starter kit

### ISSUE THREAD

**Issue by lifehackett** [davezuko/react-redux-starter-kit#20]
Thanks for creating this repo.  Could you move the todo example outside the starter kit?  Having an example is very useful, but if you want to use this as a starter kit, you have to remove the todo example source code. If the example were in its own folder (or own repo) it would be a lot simpler to get up and running.

Thanks!

**Comment by davezuko** [comment]
Hey, definitely agree with you; I'll clean it up in a little bit.

**Comment by lifehackett** [comment]
Awesome! And thanks for the quick response and resolution

**Comment by davezuko** [comment]
Hey let me know what you think of this PR: https://github.com/davezuko/react-redux-starter-kit/pull/22

It removes all Todo components, constants, actions, and the unnecessary about view. It keeps a sample reducer/store so that devTools work and show something meaningful, but it's all pretty barebones.

**Comment by lifehackett** [comment]
:+1: 

This looks much better from a starter kit perspective.  The only suggestion I'd make is having the Todo example as a separate repo (if you want) because I found your examples useful, not to mention high code quality.

Thanks again!

**Comment by davezuko** [comment]
Awesome, I'll keep the old one as a branch for now and reference it in the README in case people want to take a look. When I get some time I'll consider pulling it into separate repo like you suggested. Thanks for taking a look!

**Comment by davezuko** [comment]
This has been implemented with https://github.com/davezuko/react-redux-starter-kit/commit/82a4ee6c1e32b8f43199e3034493bc696e899489

**Comment by ioRekz** [comment]
The todo example was really important for me as I could learn how everything works. For example, I was wondering where to put my todo.jsx or todo-list.jsx as it's not a container nor a view. 
An other branch is still very fine as long as you/we can keep the todo example synced and up to date. I hope it won't fall behind.

**Comment by davezuko** [comment]
@ioRekz I'll definitely do my best to keep it updated to reflect any changes to the starter kit. I originally planned on migrating it to another repo, but thinking about it now it almost makes sense to keep it as a branch that way people are free to switch in and out of it while learning playing around with the starter kit.

Do you think that will work OK, or were you more in favor of keeping that in the base starter kit? The example could go either way, either it being in the master and a clean slate being in a branch, or vice versa (as it is currently).

**Comment by ioRekz** [comment]
The branch is actually nice, I didn't see that a lot before but that make sense and it's already more useful for me than separate repo. Concerning which branch should be master, I'm not sure. For me the todo example was really useful so I can show my team mates how everything works but I understand the benefit of a minimal starter kit. Time will probably tell what people are looking for.

**Comment by davezuko** [comment]
Yeah we'll just have to wait and see. I'll update the README to make the example branch more prominent and see where that takes us.
