### ISSUE TITLE
Bug in latest update (Nov 26, 2015)

### ISSUE THREAD

**Issue by patrickheeney** [davezuko/react-redux-starter-kit#201]
The [latest update](https://github.com/davezuko/react-redux-starter-kit/commit/cdb43acf8a11f1a918aa55e35faefd170a10d819#diff-76da7f987345718dbd9495015c2d719aL24) breaks the starter kit when debug = false, due to [this conditional](https://github.com/davezuko/react-redux-starter-kit/blob/db66626ca8a02ecf030a3f7f5a669ac338fd5897/src/store/configureStore.js#L11+L22) having the else condition removed. `createStoreWithMiddleware` becomes null and the function below errors out.

**Comment by davezuko** [comment]
Thanks for catching this, somebody else submitted a PR earlier to fix this and it just got merged.
