### ISSUE TITLE
vendor's hash will change when we change the code in the src path

### ISSUE THREAD

**Issue by qinyang912** [davezuko/react-redux-starter-kit#205]
how about use this plugin https://github.com/diurnalist/chunk-manifest-webpack-plugin

**Comment by davezuko** [comment]
Interesting! I'm taking a look at https://github.com/diurnalist/chunk-manifest-webpack-plugin/issues/1 to see how to implement it.

**Comment by davezuko** [comment]
Also adding https://github.com/webpack/webpack/issues/1315 just for reference.

**Comment by qinyang912** [comment]
the plugin works great!!

**Comment by davezuko** [comment]
Hey @qinyang912  got this working without the need for those plugins by following https://github.com/webpack/webpack/tree/master/examples/chunkhash. However, I don't know how to get webpack to inline the manifest script... :/

**Comment by davezuko** [comment]
Tracking https://github.com/ampedandwired/html-webpack-plugin/issues/104

**Comment by davezuko** [comment]
I need to improve the way it's inlined, but it's working w/o plugins here: https://github.com/davezuko/react-redux-starter-kit/commit/51f2230dab0ad53aa4710c2e5e941ebc9cf2a0f1. Let me know how that works.

**Comment by davezuko** [comment]
Reopening, previous solution broke production builds.

**Comment by davezuko** [comment]
To my eyes it seems like there's a conflict with `react` imports in modules that somehow gets broken when the manifest is bundled separately.

**Comment by valscion** [comment]
We fixed the changing hash problem by using OccurrenceOrder plugin from Webpack. It stops modules in the generated code from changing module IDs when source code wasn't changed as the module ID is based on the occurrence order of `require`/`import` calls. https://github.com/webpack/docs/wiki/internal-webpack-plugins#optimizeoccurenceorderpluginpreferentry

**Comment by davezuko** [comment]
@valscion even with that doesn't the vendor hash change because that bundle contains with entire webpack manifest, which will change if any new modules are imported in the app code?

**Comment by valscion** [comment]
Ohh yeah, it sure does change when source is changed. What the OccurrenceOrderPlugin solves is a problem where (at least we encountered) consequent builds differ. That is, when the same source is rebuilt, it might have a different hash as the order of modules in the build might have changed.

So, yeah, OccurrenceOrderPlugin doesn't really solve this issue :disappointed:

**Comment by outdooricon** [comment]
You can use https://github.com/diurnalist/chunk-manifest-webpack-plugin to get away from the manifest inside of the entry.js problem

**Comment by amay** [comment]
@outdooricon I'm looking to use the chunk-manifest-webpack-plugin to fix this issue for my project (which is based off this starter kit), but I cannot find a good example of how to inline the "webpackManifest" variable in my index.html template using the [HtmlWebpackPlugin](https://github.com/ampedandwired/html-webpack-plugin). Do you have an example you could point me to for this?

**Comment by outdooricon** [comment]
Hmm, no if you need to use HtmlWebpackPlugin, then you're probably better off with doing something like https://github.com/kevinrenskers/chunkhash-problem/commit/3969b5ac2233a933fe35b1338106cc13fd7caddb.

For this thread, I'd recommend abandoning OccurenceOrderPlugin since it will still cause unneeded change, and instead using the NamedModulesPlugin that is included inside of the latest webpack. Combining that with `chunk-manifest-webpack-plugin` and `WebpackMd5Hash` and a properly setup chunkFilename (something like `chunkFilename: '[name]-[chunkhash].js'`) will result minimal file churn.

**Comment by davezuko** [comment]
Thanks @outdooricon , do you have an example implementation? The commit you posted is definitely helpful, but in the past I've struggled to find a full demo for the functionality you describe below w/ the manifest plugin.

**Comment by outdooricon** [comment]
I don't have a repo to show, but here's what i have defined in my config:

```
config.output = Object.assign(config.output, {
  chunkFilename: '[name]-[chunkhash].js',
  filename: '[name]-[chunkhash].js',
  path: output_dir,
  pathinfo: false
});

config.plugins.push(
  new WebpackMd5Hash(),
  new StatsWriterPlugin(),
  new ChunkManifestPlugin({
    filename: 'common-manifest.json'
  }),
  new webpack.optimize.UglifyJsPlugin({
    comments: false,
    compress: {
      warnings: false
    }
  }),
  new webpack.NamedModulesPlugin()
```

This will produce a common-manifest.json file containing bundle name to bundle-with-hash name which you can read and assign to a global var in your html layout. Does that help?

**Comment by davezuko** [comment]
I'm also guessing we could just use the `DLLPlugin` for this, though I'm a bit unsure as to how to incorporate it properly for both development and production.

**Comment by davezuko** [comment]
Moving this to `2.0.0` milestone wiki.

**Comment by oowangoo** [comment]
why not use CommonsChunkPlugin ?  like:
```
    new webpack.optimize.CommonsChunkPlugin({
      names : ['vendor', 'manifest']
    })
```
