### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by DenJohX** [davezuko/react-redux-starter-kit#216]
as in the README `npm run dev:nw` should run the development server with the developer tools in a popup, but instead it gives me this error:

    $ nmp run dev:nw
    npm ERR! Error: ENOENT: no such file or directory, open '/home/dennis/workspace/wezend-react/node_modules/dev/package.json'
    npm ERR!     at Error (native)
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/npm/npm/issues>

my node and npm versions:

    $ npm -v
    1.4.21

    $ node -v
    v4.2.2

**Comment by JuoCode** [comment]
Which version do you use?

**Comment by davezuko** [comment]
That's strange, `dev:nw` is the exact same command as `npm start`/`npm run dev`, it just adds a CLI argument. Do the other commands work?

**Comment by davezuko** [comment]
Hoping this is resolved with this commit: https://github.com/davezuko/react-redux-starter-kit/commit/4ce3975260a9c6bb5e2bc49e58d46918a816c28d. If not, please let me know and I'd be happy to re-open and investigate further.
