### ISSUE TITLE
API Define in starter-kit?

### ISSUE THREAD

**Issue by giangstrider** [davezuko/react-redux-starter-kit#224]
Hi. 
My application use some Restful webservice from other service to get data back to app. I planning to make some API define in our kit, but don't find any place appropriate to write.
So is there existed file for API ?
If not, where is the most appropriate in your opinion?
Thanks.

**Comment by davezuko** [comment]
Hey @giangstrider, now that the starter kit uses an Express server for webpack middleware, you could just define your API in that app (`~/server/app`). If you want to use something other than Express you'll have to swap out the middleware, but hopefully that clears it up.

I'll be working on improving documentation about the server (API and deployment) next week.

**Comment by giangstrider** [comment]
:+1: thanks, waiting for a documentation.

**Comment by davezuko** [comment]
Cool, closing this for now, I'll get to the documentation [here](https://github.com/davezuko/react-redux-starter-kit/issues/221) as soon as I can.

**Comment by TheTFo** [comment]
Hello, In regards to this, is there a way to setup webpack/eslint to validate files under ~/server ?

I've done some frontend work previously, but never a node.js backend.  Is what I'm asking even part of a standard api deployment, or are files just normally unbundled?  Does it work with ES6?

Thanks!
