### ISSUE TITLE
upgrade babel 5 to babel 6

### ISSUE THREAD

**Issue by sandyjoshi** [davezuko/react-redux-starter-kit#236]
I have updated the babel to the latest version. Here is my branch 
https://github.com/sandyjoshi/react-redux-starter-kit/tree/babel5_to_6 

but i am getting some error in webpack-dev-middleware package.

Can anyone suggest anything ?

<img width="1258" alt="screen shot 2015-12-08 at 2 04 45 pm" src="https://cloud.githubusercontent.com/assets/10337440/11651389/5e3a505e-9db6-11e5-9e4e-41a7546135f4.png">

**Comment by davezuko** [comment]
Hey, thanks for taking a look at this, but let's keep all Babel 6 stuff together here: https://github.com/davezuko/react-redux-starter-kit/issues/150. If you want to pull it over there we can discuss it further, maybe @justingreenberg has some ideas, he's practically everywhere (esp. with Babel 6).
