### ISSUE TITLE
npm failed to start 

### ISSUE THREAD

**Issue by Abrarmm** [davezuko/react-redux-starter-kit#239]
Getting this error when run npm start on mac 

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.1.1
npm ERR! npm  v3.5.1
npm ERR! path /Users/username/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/username/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/username/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.

and here is the log from npm-debug.log :

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.5.1
3 info using node@v5.1.1
4 verbose config Skipping project config: /Users/Username/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/Users/Username/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /Users/abraralmoullad
7 error Darwin 13.4.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
9 error node v5.1.1
10 error npm  v3.5.1
11 error path /Users/username/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/Users/username/package.json'
16 error enoent ENOENT: no such file or directory, open '/Users/username/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by davezuko** [comment]
Hm, sorry to hear that. Are you up to date with the master branch? Also, could you please try running the Node REPL (with babel enabled) and requiring `~/config/index.js` -- I can't tell 100% from the error message, but that file may be the culprit.

**Comment by sotojuan** [comment]
Looks like he was running `npm start` or `npm install` from his home directory, not the repo directory.

See:

```
15 error enoent ENOENT: no such file or directory, open '/Users/abraralmoullad/package.json'
```

@Abrarmm Are you sure you `cd`'d into the repo directory?

**Comment by Abrarmm** [comment]
@sotojuan no I didn't , I have to cd to which directory ?

**Comment by sotojuan** [comment]
See [here](https://github.com/davezuko/react-redux-starter-kit#getting-started).

**Comment by davezuko** [comment]
Oh, thanks for catching that @sotojuan. Is it working for you @Abrarmm?

**Comment by Abrarmm** [comment]
@davezuko it did work thank you so much @sotojuan

**Comment by davezuko** [comment]
Great!
