### ISSUE TITLE
Need help integrating less-loader with this starter kit.

### ISSUE THREAD

**Issue by ranjithnori** [davezuko/react-redux-starter-kit#240]
I have installed the 'less-loader' npm package and added the loader in _base.js file.

  module : {
    loaders : [
      ...
      {
        test    : /\.less$/,
        loader: 'style!css!less'
      }
      ...
  }

How do I direct it to compile less files in the 'styles' folder ?

**Comment by davezuko** [comment]
Hey, in `~/webpack/production` there is a script that does this:

```
debug('Apply ExtractTextPlugin to CSS loaders.');
webpackConfig.module.loaders = webpackConfig.module.loaders.map(loader => {
  if (/css/.test(loader.test)) {
    const [first, ...rest] = loader.loaders;

    loader.loader = ExtractTextPlugin.extract(first, rest.join('!'));
    delete loader.loaders;
  }

  return loader;
});
```

So you'll want to change `/css/.test` to `/(css|less)` (that's a pipe between "css" and "less"), and then also update your less loader to declare the loaders as an array:

```
{
  test : /\.less$/,
  loaders : [
    'style',
    'css',
    'less'
  ]
}
```

Let me know how that works.

**Comment by ranjithnori** [comment]
I did everything that was mentioned. The less styles do not apply yet..

**Comment by davezuko** [comment]
No, that's just to alias import paths. Are you actually importing the styles anywhere? For example, the `core.scss` file is imported in `~/src/layouts/CoreLayout`, it's not automatically imported.

**Comment by ranjithnori** [comment]
@davezuko Thanks a lot! Yeah,  that's what I missed. Everything works fine now.
