### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by christiansakai** [davezuko/react-redux-starter-kit#243]
Is there a specific example on how to do authentication in this app? Just using timeout and no need to do the actual call to the backend

**Comment by GerritWanderer** [comment]
Have a look on this example: https://github.com/emmenko/redux-react-router-async-example, there is a simple static login included. 
http://emmenko.github.io/redux-react-router-async-example/#/login

**Comment by christiansakai** [comment]
Thank you

**Comment by davezuko** [comment]
Thanks @GerritWanderer , going to close this for now. If you have more questions please feel free to join the gitter chat!
