### ISSUE TITLE
Compiling react-native failed in xcode 

### ISSUE THREAD

**Issue by Abrarmm** [davezuko/react-redux-starter-kit#245]
Getting these errors while compiling react-native project on xcode :( 
![screen shot 2015-12-10 at 1 28 31 am](https://cloud.githubusercontent.com/assets/16222659/11700978/f73ed680-9edd-11e5-8f36-6c548711b1ad.png)

Thanks in advance

**Comment by davezuko** [comment]
I think you meant https://github.com/facebook/react-native.
