### ISSUE TITLE
Stylesheets not applied anymore when using class or id selector with latest master

### ISSUE THREAD

**Issue by GerritWanderer** [davezuko/react-redux-starter-kit#249]
Hey folks,

all the stylessheets (with id and class selector) are not beeing applied anymore after I've updated my react app with your master.
I can easily reproduce this error with a fresh react-redux-starter-kit instance from master:
```
git clone https://github.com/davezuko/react-redux-starter-kit.git
cd react-redux-starter-kit
npm install
npm start
```
Now add a random styling to the core.scss or _base.css with a selector that points to a class or element
```
.view-container {
  background-color: #c1c1c1;
}
```
You'll see that the style is not applied and also not listed when you inspect the .view-container element inside the Chrome DevTools. However, the generated core.css file in the sources tab contains the style.

**Comment by JuoCode** [comment]
@GerritWanderer CSS Modules is open in default, see #241

**Comment by GerritWanderer** [comment]
thanks @JuoCode, now I understand why all the styles are broken

**Comment by davezuko** [comment]
@GerritWanderer did you get it working by disabling CSS modules?

**Comment by JuoCode** [comment]
:joy: I also met this problem, The good news is that now it becomes configurable

**Comment by GerritWanderer** [comment]
@davezuko yes, it was working by disabled the CSS Modules
