### ISSUE TITLE
No CSS sourcemaps if css modules are disabled

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#250]
Easy to fix, but should be done ASAP.

**Comment by JuoCode** [comment]
I met another problem, multiple animation defined in per .scss file, but the animation seem to be renamed when i saw in Chrome style tab, the display result is very funny, Does this problem related to disable CSS modules?

**Comment by davezuko** [comment]
If you have CSS modules disabled the sass compilation should be exactly the same as prior to when they were added. That's strange, I'll have to look into it.

**Comment by JuoCode** [comment]
@davezuko Found it, because my animation defined in multiple .scss file, `postcss-reduce-idents` 's context may be a single file, when i disabled `reduceIdents` in `_base.js` it worked.

**Comment by davezuko** [comment]
This has been fixed. Also, thanks for noting that @JuoCode.
