### ISSUE TITLE
Implement thunk middleware and simple async increment

### ISSUE THREAD

**Issue by justingreenberg** [davezuko/react-redux-starter-kit#255]
since synchronous is the exception rather than the rule, are you opposed to adding an async action?

i don't really think it would take away from the unopinionated mantra of this project, since `redux-thunk` has really become the idiomatic approach to handling async actions (it is used throughout the documentation). it would also provide some basic structure for adding additional middleware (maybe in `redux/middleware`, as discussed in #248) 

eg. `incrementAsync` action creator from docs...

```js
export function incrementAsync(delay = 1000) {
  return dispatch => {
    setTimeout(() => {
      dispatch(increment())
    }, delay)
  }
}
```

**Comment by davezuko** [comment]
We are already using redux-thunk, so is there a different way you imagine structuring the middleware application? I can add this when I do the refactor into modules.

**Comment by justingreenberg** [comment]
my intuition says `DevTools` should probably be renamed something like `createDevTools` and put in the `redux/middleware` folder discussed in #248, leaving `container` directly nice and clean :sparkles:

**Comment by davezuko** [comment]
@justingreenberg how's this? https://github.com/davezuko/react-redux-starter-kit/pull/290
