### ISSUE TITLE
Container / smart / dumb components

### ISSUE THREAD

**Issue by ioRekz** [davezuko/react-redux-starter-kit#26]
The project contains a containers directory. Just to be clear, we speak about that kind of "containers".
https://medium.com/@learnreact/container-components-c0e67432e005

Also https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

If yes, it could make sense to add it to the doc/readme. It would also helps understanding why there are different types of components/directories: views, containers and components. 
That would also explains why it is nice to have styles and tests close to the component that is now dumb a easily reusable.

**Comment by ioRekz** [comment]
I can give it a try in a PR if that sounds good.

**Comment by davezuko** [comment]
Not sure how this got buried, my bad dude :(

The views/layouts/components directories have now been documented. As far as the tests being close to the components, this has now changed so it's no longer valid unfortunately.
