### ISSUE TITLE
Browsersync

### ISSUE THREAD

**Issue by hamishtaplin** [davezuko/react-redux-starter-kit#261]
Is there any way of adding browsersync to this? I would imagine it needs to either replace or proxy the Express server.

**Comment by davezuko** [comment]
Hey, I've never used browsersync so unfortunately can't offer any advice on this. If I have a chance I'll try to play around it, but hopefully somebody else can point you in the right direction.

**Comment by mtsr** [comment]
I see no point in using it from how it’s described on the site.

We already have Hot Module Reloading and history replaying with redux, which gives us a far more powerful set of tools, AFAICT:
* Change your reducers, and the state will be rebuilt by replaying all actions.
* Change your view and it will be rerendered.
* Etc.

**Comment by davezuko** [comment]
@mtsr the one thing we don't get that browsersync offers is the ability to manipulate one window and have those changes be mirrored across a bunch of other browsers/devices.

**Comment by mtsr** [comment]
Sure, but that hardly seems something to want in a starter kit. If one is after proper cross-browser testing, it’s not enough, anyway.

It might be nice for a cross-browser manual happy-flow, but that’s not really a core requirement.

**Comment by davezuko** [comment]
Agreed, and I don't really have anything to add about how to integrate it for users who _do_ want it. @hamishtaplin I'll leave this open for a few more days in case anybody else drops by who might have some advice.

**Comment by hamishtaplin** [comment]
It's definitely a "nice to have" for cross-browser testing but not essential, as you say. Feel free to close.

**Comment by davezuko** [comment]
@hamishtaplin I have seen some browsersync-related code in react-starter-kit, maybe give that a shot? At least see what they're up to?
