### ISSUE TITLE
DEBUG=kit:* enabled by default; opinions

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#273]
@justingreenberg brought this up in https://github.com/davezuko/react-redux-starter-kit/pull/271. For an explanation, I enabled it because I wanted users to know what was happening with webpack, especially for things like the development server (i.e. where is it running?). I understand that the [debug](https://www.npmjs.com/package/debug) package was designed so that debug output would be disabled by default and selectively enabled, so maybe a good compromise would be to do one of the following:

1) Use `console.log` for output that we want to always be shown (`Server running at...`).

2) Use a separate namespace for those types of outputs ^^, and configure the `DEBUG` environment variable to only show these by default. This still strays slightly from its intended usage, but I think defaulting to more feedback is better than not, especially when it's easy to disable by editing the `.env` file.

There are always options 3 and 4: disable it entirely by default, or keep it as is.

Personally, I like seeing all the output for the build pipeline (which is probably obvious seeing as I'm the maintainer, -_-), so I slightly disagree with disabling the debug output, but it's open for discussion.

**Comment by justingreenberg** [comment]
i like seeing all output for build pipeline too! it's nice and colorful and makes me happy. i agree with keeping all output and just dropping the `kit:` prefix. 

```
  kit:config Create configuration. +0ms
  kit:config Apply environment overrides. +16ms
  kit:webpack:_base Create configuration. +935ms
  kit:webpack:development Create configuration. +11ms
  kit:webpack:development Override devtool with cheap-module-eval-source-map. +0ms
  kit:webpack:development Enable Hot Module Replacement (HMR). +0ms
  kit:webpack:development Apply react-transform-hmr to babel development transforms +6ms
  kit:server:webpack-dev Enable Webpack dev middleware. +68ms
  kit:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +28ms
  kit:bin:server Server is now running at localhost:3000. +160ms
```

becomes:

```
  config Create configuration. +0ms
  config Apply environment overrides. +16ms
  webpack:_base Create configuration. +935ms
  webpack:development Create configuration. +11ms
  webpack:development Override devtool with cheap-module-eval-source-map. +0ms
  webpack:development Enable Hot Module Replacement (HMR). +0ms
  webpack:development Apply react-transform-hmr to babel development transforms +6ms
  server:webpack-dev Enable Webpack dev middleware. +68ms
  server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +28ms
  bin:server Server is now running at localhost:3000. +160ms
```

doesn't lose any information, can still target using `DEBUG:webpack`, still nice and colorful :)

**Comment by davezuko** [comment]
@justingreenberg interesting, it makes sense. My original rationale was to avoid conflicting with `webpack` and whatever else should they ever implement debug (and it would also help avoid confusing as to what was coming from webpack/express/etc. and what was local to the kit). That said, I can see it making sense to want to, for example, enable everything webpack-related, and dropping the `kit:*` prefix would solve that.

**Comment by davezuko** [comment]
https://github.com/davezuko/react-redux-starter-kit/pull/274 I'm still debating it, as well as what should be enabled by default (I'd like to er on the side of more debug info with documentation about how to disable it using `.env`), but the code is there in case we want to move forward with this change. I'll be gone for the rest of the day, so maybe a day break will help put things in perspective.

**Comment by patrickheeney** [comment]
I like the kit namespace or at least a common word. The kit only bootstraps the application so we are talking about ~10-15 lines in the console about what is going on. Immediately after adding this to the project I noticed that my install was hitting parts of webpack it shouldn't have. So I would be in favor of keeping it as other packages may be prefixed with (config, webpack, bin, etc) as they are generic words.

**Comment by justingreenberg** [comment]
@davezuko @patrickheeney maybe `kit:` could just be `app:`? for me the issue wasn't so much the namespacing, it was more hardcoding the name `kit` into each debug instance

**Comment by patrickheeney** [comment]
:+1: For app. That is what I had renamed mine to.

**Comment by davezuko** [comment]
Cool, `app` it is then if that's agreeable. I'll decline the PR and make the change tomorrow or Monday when I get back, unless somebody wants to submit a PR before then.

**Comment by justingreenberg** [comment]
enjoy your break dude :palm_tree:  :beers:
