### ISSUE TITLE
Localtunnel support broken

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#275]
Not that this was ever something officially supported, but something changed in recent commits that broke the ability to use localtunnel to view apps remotely. The errors I get are something like:

```
GET http://localhost:3000/vendor.3a5c825bfb7f691bd203.js net::ERR_CONNECTION_REFUSED
swcllxsnja.localtunnel.me/:1
GET http://localhost:3000/app.3a5c825bfb7f691bd203.js net::ERR_CONNECTION_REFUSED
```

I haven't yet narrowed down exactly when it stopped working, but I have some older projects that tunnel fine. I'll try to track it down unless there's something obvious you know of.

**Comment by davezuko** [comment]
Could it be related to this? https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_development.js#L13

**Comment by neverfox** [comment]
That looks suspiciously relevant lol. I'll do a quick pre/post commit test and get back to you.

**Comment by neverfox** [comment]
No, it was this commit: 2076d1e4c47c57e93c93f20b5370e7cbe80bf39d

**Comment by neverfox** [comment]
It looks like localtunnel depends on relative paths so there's no way to implement this fix and keep localtunnel support. Might be something to raise with localtunnel.

**Comment by davezuko** [comment]
@neverfox that fix was put in to fix asset imports in css files. If you aren't using those you can try just setting it back to '/'; does that fix it?

**Comment by neverfox** [comment]
Yes, it's a simple matter of the fact that, by using absolute URLs, the browser sends a request to localhost, which of course isn't valid when running through a remote tunnel. I wonder if there's another way to address the issue mentioned on SO. It mentions that something [more could be done with ExtractTextPlugin](https://github.com/webpack/webpack/issues/1022) to avoid the issue.

**Comment by davezuko** [comment]
@neverfox is there anything you'd recommend we change in the webpack configuration, or can this be laid to rest? At a minimum I'll maintain it in the references/resources issue.

**Comment by davezuko** [comment]
@neverfox trying to clean up issues right now, let me know if we need to take any action around this and I can reopen if necessary.

**Comment by neverfox** [comment]
No action needed.
