### ISSUE TITLE
ESLint semi-colon repair throws an error (but still works)

### ISSUE THREAD

**Issue by tcrosen** [davezuko/react-redux-starter-kit#276]
`npm run lint:fix` is throwing an error.  It still seems to fix the semi-colons, but I thought I should log this anyways.

```sh
⇒  npm run lint:fix   

> react-redux-starter-kit@0.18.0 lint:fix /Users/terry/Desktop/Projects/react-redux-starter-kit
> eslint **/* --fix


/Users/terry/Desktop/Projects/react-redux-starter-kit/src/index.html
  1:2  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)


npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:fix"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.18.0 lint:fix: `eslint **/* --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@0.18.0 lint:fix script 'eslint **/* --fix'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint **/* --fix
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.
```

**Comment by davezuko** [comment]
Thanks, I'm aware of this but am struggling to get eslint to ignore this file... I tried using the '--ext' cli flag to lock it to js files and it didn't seem to have any effect.

Will definitely patch this ASAP, but as you said at least it does its job for now.

**Comment by neverfox** [comment]
I cannot get it to work either. Frustrating.

**Comment by neverfox** [comment]
And `**/*.js` doesn't work either. It just skips all of the files!

**Comment by davezuko** [comment]
@neverfox can't get it to ignore the html file or get it to fix at all? I'm gone until Sunday night so won't be able to play with it until then.

**Comment by neverfox** [comment]
I cannot get it to ignore `index.html` without ignoring everything. Also, if the `dist` folder is there, you get a bunch of unnecessary warnings about every .js in there:

```
warning  File ignored because of your .eslintignore file. Use --no-ignore to override
```

**Comment by davezuko** [comment]
@neverfox that snuck in in a PR and I haven't had a chance to remove it yes, it's definitely not intentional.

**Comment by patrickheeney** [comment]
I got it to ignore it by adding `src/index.html` to `.eslintignore`. `*.html` and others did not work for me. 

Secondly, might consider adding `--quite` to the CLI command as that will only show errors (not warnings which still cause things to fail because a skipped file is a warning).
