### ISSUE TITLE
eslint errors kill index.html bundling

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#278]
It seems that any eslint error now prevents index.html from from ending up in the bundled files and you get a resource not found error (from express?). To recreate, just add a semicolon at the end of a line anywhere, run or restart dev, and you'll get a `Cannot GET /` error in the browser (and you won't see index.html in the bundle asset list).

If this was intentional, I think it goes too far. While eslint errors should paint red all over your console so you'll fix it, it shouldn't stop a valid codebase from running (as it didn't before). For one, it blocks quick and dirty things like throwing in a quick debugger statement.

If it was unintentional, any ideas on how to fix it so things don't just blow up? Might this be a side-effect of switching to express with middleware over the webpack-dev-server? (Sorry for being a bit behind on catching up with recent changes).

**Comment by neverfox** [comment]
No eslint errors:
```
                         Asset       Size  Chunks             Chunk Names
vendor.9acd1bc49dacc181d997.js    2.27 MB       0  [emitted]  vendor
   app.9acd1bc49dacc181d997.js    1.07 MB       1  [emitted]  app
                    index.html  461 bytes          [emitted]
webpack: bundle is now VALID.
```

Any eslint errors (note the missing index.html):
```
                         Asset     Size  Chunks       Chunk Names
vendor.9acd1bc49dacc181d997.js  2.27 MB       0       vendor
   app.9acd1bc49dacc181d997.js  1.07 MB       1       app

ERROR in ./src/app.js

.../src/app.js
  19:55  error  Extra semicolon  semi

✖ 1 problem (1 error, 0 warnings)

webpack: bundle is now VALID.
```

**Comment by neverfox** [comment]
Ah! It started when the eslint-loader was added. This loader causes eslint errors to count as webpack errors. One of the gotchas is using it with the `NoErrorsPlugin`, because now even eslint errors will prevent a build.

This is a conundrum because the NoErrorsPlugin is important to keep hot reloading robust to small errors, but, as I said, I think preventing a build on eslint errors is a bit heavy-handed. Any ideas on how you want to handle this?

**Comment by davezuko** [comment]
@neverfox that snuck in in a PR and I haven't had a chance to remove it yet, it's definitely not intentional.

**Comment by mtsr** [comment]
This can be fixed by adding `webpackConfig.eslint.emitWarning = true;` to `build/webpack/_development.js`

**Comment by neverfox** [comment]
@mtsr Ah, I had assumed that turned eslint errors into warnings (thereby making them indistinguishable from eslint warnings), but trying it, I see that's not the case. Rather it making eslint errors into *Webpack* warnings. I consider that an acceptable solution. and I'll put in a PR for it.
