### ISSUE TITLE
Use the starter kit without all the server related stuff

### ISSUE THREAD

**Issue by faeronsayn** [davezuko/react-redux-starter-kit#28]
How easy would it be to modify this boilerplate so it's not using koa, and simply becomes a boilerplate for react and redux?

**Comment by davezuko** [comment]
Hey, it's super easy. As far as webpack goes, literally all you need to do is remove the server entry point in `~/webpack.config.js`. That file can now just read:

```js
module.exports = exports = [
  require('./src/entry-points/client')
];
```

Webpack will now only ever bundle your client application. If you want to remove all the extra stuff that's now unneeded, you can delete these folders/files:

- `~/build/webpack/server`
- `~/server`
- `~/src/entry-points/server.js`

And then all that's left is to remove the Koa-related dependencies. You may have to tweak the npm scripts in `package.json` so they don't try to do anything with the server (I believe there are only 2 relevant scripts).

But yeah, that's pretty much it. The server stuff is all pretty well isolated and can just be ignored.

**Comment by davezuko** [comment]
Closing this since [there's now a branch for this](https://github.com/davezuko/react-redux-starter-kit/tree/no-server).
