### ISSUE TITLE
Webpack HMR plugin conflict

### ISSUE THREAD

**Issue by patrickheeney** [davezuko/react-redux-starter-kit#291]
I have a custom loader for my application that is something like this:

```
{
  test: /custom.js$/,
  exclude: /node_modules/,
  loader: paths.client('lib/bundler'),
}
```

This conflicts with the HMR loader in `_development.js` because it checks for `/js/` in `loaders.test` then adds to this array `loader.query.env.development.plugins[0][1].transforms`. This conditional looks to be babel specific so instead of the regex test, what about just testing for the loader `if (loader.loader === 'babel')`?

**Comment by davezuko** [comment]
@patrickheeney I like that a lot more, good suggestion. Do you mind submitting a PR for this?

**Comment by patrickheeney** [comment]
@davezuko Sure, running out of time tonight but will be at it again tomorrow.

**Comment by davezuko** [comment]
Awesome, thank you.

**Comment by davezuko** [comment]
@patrickheeney while you're at it, do you think you could take a stab at updating this:

https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack/_production.js#L20

Along similar lines, we should probably just check if the loader has `css` as a loader and then apply it, that way if somebody swaps out sass for less then it will still perform as expected.
