### ISSUE TITLE
Adding custom routes to the express server 

### ISSUE THREAD

**Issue by tonyalaribe** [davezuko/react-redux-starter-kit#300]
I have tried adding a route to sign certain file upload requests from the react app, but thee route seems to be ignored.

Here is what I  tried:

```javascript
app.use('/s3', require('react-dropzone-s3-uploader/s3router')({
    bucket: "oddjobz",
    region: 'us-west-2', //optional
    //headers: {'Access-Control-Allow-Origin': '*'}, // optional
    ACL: 'public' // this is default:private
}));
```

**Comment by davezuko** [comment]
Hey, where are you adding these in the server? Because the Express server uses HMR middleware, you'll probably want to try placing these routes before those are passed into Express.

**Comment by tonyalaribe** [comment]
Hello @davezuko I added the rout to the app.js file under the server folder.

```javascript
import express from 'express'
import historyApiFallback from 'connect-history-api-fallback'
import config from '../config'

const app = express()
const debug = require('debug')('kit:server')
const paths = config.utils_paths

app.use(historyApiFallback({
  verbose: false
}))

app.use('/s3', require('react-dropzone-s3-uploader/s3router')({
    bucket: "oddjobz",
    region: 'us-west-2', //optional
    //headers: {'Access-Control-Allow-Origin': '*'}, // optional
    ACL: 'public' // this is default:private
}));

...
export default app

```

**Comment by mtsr** [comment]
I think you’ll need to put it before historyApiFallback, since that resolves every possible route. It needs to go after every specific route.

**Comment by sarunast** [comment]
Is there a way to watch/restart for nodejs server endpoints ?

**Comment by davezuko** [comment]
[Nodemon](https://github.com/remy/nodemon) works great.

**Comment by sarunast** [comment]
@davezuko I was just trying it out. Which task would you recommend running on dev with nodemon ?

**Comment by davezuko** [comment]
@sarunast this is where it's a bit tricky, I've never really used nodemon _while_ doing webpack development. So normally it would just make sense to re-run to whatever script starts the server (in this case it's `npm start`), but I'm not convinced on how well this would work if you're also doing webpack development, since it's going to restart the webpack compiler.

**Comment by tonyalaribe** [comment]
hello @mtsr I tried that but i'm still getting the error: 
'Warning: Location "/s3" did not match any routes'

my app.js is now:
```javascript
import express from 'express'
import historyApiFallback from 'connect-history-api-fallback'
import config from '../config'

const app = express()
const debug = require('debug')('app:server')
const paths = config.utils_paths

app.use('/s3', require('react-dropzone-s3-uploader/s3router')({
    bucket: "oddjobz",
    region: 'us-west-2', //optional
    //headers: {'Access-Control-Allow-Origin': '*'}, // optional
    ACL: 'public' // this is default:private
}));

app.use(historyApiFallback({
  verbose: false
}))

// Serve app with Webpack if HMR is enabled
if (config.compiler_enable_hmr) {
  const webpack = require('webpack')
  const webpackConfig = require('../build/webpack')
  const compiler = webpack(webpackConfig)

  app.use(require('./middleware/webpack-dev')({
    compiler,
    publicPath: webpackConfig.output.publicPath
  }))
  app.use(require('./middleware/webpack-hmr')({ compiler }))
} else {
  debug(
    'Application is being run outside of development mode. This starter kit ' +
    'does not provide any production-specific server functionality. To learn ' +
    'more about deployment strategies, check out the "deployment" section ' +
    'in the README.'
  )

  // Serving ~/dist by default. Ideally these files should be served by
  // the web server and not the app server, but this helps to demo the
  // server in production.
  app.use(express.static(paths.base(config.dir_dist)))
}

export default app
```

**Comment by davezuko** [comment]
If you replace the dropzone uploader middleware with a dummy middleware, do you get the expected response?

```
app.use('/s3', (_, res) => res.send('Hello World'))
```

**Comment by tonyalaribe** [comment]
@davezuko Thanks for that. I got a response, And I just retried my earlier implementation, and it works. So I believe the issue was with keeping the handler before the HistoryApiFallback as @mtsr said.

Thanks. I'm closing this issue.

**Comment by davezuko** [comment]
Awesome, I'll consider adding a note to the server so other people don't run into this.
