### ISSUE TITLE
Bug: Uncaught TypeError: Monitor.reducer is not a function (EPEERINVALID)

### ISSUE THREAD

**Issue by inooid** [davezuko/react-redux-starter-kit#301]
After removing my `node_modules/` folder, running `npm cache clean` and running `npm install` I run into an `EPEERINVALID` error.

**Note**: this is on a fresh pull from *master*
(`git clone https://github.com/davezuko/react-redux-starter-kit.git`)

![screen shot 2015-12-14 at 14 08 59](https://cloud.githubusercontent.com/assets/1291263/11781770/72f96ac4-a26c-11e5-84e6-6460e7a81d71.png)

Environment:
- OS: `OS X 10.11.1`
- Node: `v.5.2.0`
- NPM: `3.3.12`

This happend on both my and a colleague of mine's macbooks. Probably some issue with Node 5.2?

The `npm start` command runs fine and it compiles, but in the browser there's a error and the app is broken.

Terminal:
![screen shot 2015-12-14 at 14 13 51](https://cloud.githubusercontent.com/assets/1291263/11781823/04940430-a26d-11e5-984e-468bf0907209.png)

Browser:
![screen shot 2015-12-14 at 14 15 06](https://cloud.githubusercontent.com/assets/1291263/11781835/214b2a54-a26d-11e5-97c0-9cf07d348951.png)

**Comment by inooid** [comment]
All of the issues above, seems to be fixed with an npm update of: `redux`, `react-redux`, `redux-devtools`, `redux-devtools-dock-monitor` and `redux-devtools-log-monitor`.

Setting up a PR now!

**Comment by mdramos** [comment]
same issue on Node v4.2.2

**Comment by mdramos** [comment]
roger, confirmed that works

**Comment by gaearon** [comment]
`redux-devtools@3.0.0` requires both monitors to be >= `1.0.1`. It won't work with betas.

**Comment by inooid** [comment]
Fixed by #299

**Comment by davezuko** [comment]
Thanks @inooid :+1:
