### ISSUE TITLE
Uncaught TypeError: Monitor.reducer is not a function

### ISSUE THREAD

**Issue by tpisto** [davezuko/react-redux-starter-kit#302]
I installed the react-redux-starter-kit as instructed, run "npm install" and then "npm start", but when loading the localhost:3000 using Chrome, I only get error "createDevTools.js:35   Uncaught TypeError: Monitor.reducer is not a function"

I have tried the latest master and v0.18.0. Both with Node v4.2.2. and 5.0.0, but always get the same error. Any pointers?

**Comment by inooid** [comment]
Same as #301. I fixed it in #303 by updating the following dependencies:

Dependencies:
- `react-redux`: `^4.0.1`
- `redux`: `^3.0.5`,

DevDependencies:
- `redux-devtools`: `^3.0.0`,
- `redux-devtools-dock-monitor`: `^1.0.1`
- `redux-devtools-log-monitor`: `^1.0.1`

**Comment by tpisto** [comment]
Great, thank you! And sorry for duplicate question.

**Comment by davezuko** [comment]
@inooid this is fixed then now that https://github.com/davezuko/react-redux-starter-kit/pull/299 (same as your PR) has been merged, right?
