### ISSUE TITLE
Revert to original Route convention

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#306]
@justingreenberg What's the reason for switching the order of the component and path props in the route definitions? I think two good reasons for sticking with how it was before:

* Matches style of canonical examples and react-router docs (less confusing, perhaps, for new users)
* Perhaps more importantly (though also somewhat subjective) it's much easier to read as a route specification when the path is listed first, and it's closer to how the routes are actually handled (first, match path; second, render component)

It's a minor thing, but thoughts?

**Comment by davezuko** [comment]
:+1:

**Comment by justingreenberg** [comment]
no worries.. .if it was me that switched them, it was probably an attempt to satisfy a certain somebody's fondness of aligning operators @davezuko :wink:

**Comment by davezuko** [comment]
@justingreenberg shots fired
