### ISSUE TITLE
Understanding aliases and picking a convention

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#307]
I see that the alias configuration is not there anymore (in favor of auto-resolving relative to `src`), I can see some imports taking advantage of this, like `import CoreLayout from 'layouts/CoreLayout'` and others not:

```
import routes from './routes'
import Root from './containers/Root'
import configureStore from './redux/configureStore'
```
Yet, getting rid of the `./` works fine.

Should we pick a convention (leaning on this auto resolution vs. always being explicit with `./`) and make sure it's used everywhere? I can see new users being confused about whether they have to use `./`  or not (even though the answer is "it doesn't matter"). My preference would be for the auto-resolution since it's cleaner looking that a bunch of relative paths. On the other hand, relative paths are probably more robust to refactoring directories.

**Comment by davezuko** [comment]
I wanted to avoid it in certain places (i.e. with `redux/*`) since that could be _very_ confusing for some people. I do agree that there should be some standardization, but this is my key hangup.

**Comment by neverfox** [comment]
Oh, good point!

**Comment by davezuko** [comment]
In that light, I'd like to err on the side of using explicit paths as much as possible, and maybe use the aliases in routes or something where it's much more obvious that the imports are local. Keeping them explicit everywhere else will still help to retain some sense of consistency.

I'd _love_ to just use the root require alias, but the potential for confusion is a bit too high.

**Comment by davezuko** [comment]
@neverfox I've updated the paths to always be relative except in the routes where a note has been added (tests also still use the alias, but are less likely to be looked at before `routes/index.js` is, so the note there should suffice).
