### ISSUE TITLE
Npm start error

### ISSUE THREAD

**Issue by sarunast** [davezuko/react-redux-starter-kit#313]
I am running app with npm commands `start` and `dev:nw`, I always get this when starting error:
`app:webpack:development ERROR: react-transform must be the first plugin +0ms`

The applications still runs though, however I am not sure if this is breaking anything.

Using the latest changes.

**Comment by davezuko** [comment]
Thanks, I'll take a look.

**Comment by davezuko** [comment]
Didn't catch that in an earlier PR, it's been fixed here: https://github.com/davezuko/react-redux-starter-kit/commit/f388897b89fff4a9fad94aedabac7badf904df83
