### ISSUE TITLE
DevTools chrome extension

### ISSUE THREAD

**Issue by sars** [davezuko/react-redux-starter-kit#317]
Could you please tell what advantages of using 

devtools-dock
devtools-dock-monitor
redux-devtools-log-monitor

against just chrome/firefix devtools extension?

https://github.com/zalmoxisus/redux-devtools-extension#advantages
Also it allows to keep less code in your sources...

**Comment by davezuko** [comment]
I'd still like to keep the local devtools sidebar, just so people get more functionality out of the box w/o needing an extension, but this might be a good replacement for the `dev:nw` script.

**Comment by sars** [comment]
@davezuko Thanks, got it
