### ISSUE TITLE
redux-dev-tools not removed when compiling for production env

### ISSUE THREAD

**Issue by ipanasenko** [davezuko/react-redux-starter-kit#319]
Hey, guys!
I run following command: `NODE_ENV=production npm run compile` and I see redux-dev-tools code in `dist/app.**.js`

This command worked fine yesterday. Can you have a look, please?

**Comment by davezuko** [comment]
I have an idea of what it might be, but absolutely no idea _why_. Checking.

**Comment by ipanasenko** [comment]
I've created PR, ICYMI: https://github.com/davezuko/react-redux-starter-kit/pull/320
