### ISSUE TITLE
Error in redux module

### ISSUE THREAD

**Issue by mtsr** [davezuko/react-redux-starter-kit#322]
There's an error here https://github.com/davezuko/react-redux-starter-kit/blob/master/src/redux/modules/counter.js#L36

It should be `[COUNTER_INCREMENT]` instead, as right now it only works because the action name and the reducer just happen to have the same name. The reducer should use the action name const.

**Comment by davezuko** [comment]
Ah thank you, this was an oversight from the debate over `redux-actions` and FSA-style actions. I'll get this fixed momentarily.

**Comment by mtsr** [comment]
No worries, it's just a tiny mistake.
