### ISSUE TITLE
"npm start" causes error 

### ISSUE THREAD

**Issue by donpinkus** [davezuko/react-redux-starter-kit#325]
After cloning the repo, I ran `npm install`, then `npm start`. `npm start` caused this error:

```
Donalds-MacBook-Pro-2:react-redux-starter-kit-master · npm start

> react-redux-starter-kit@0.18.0 start /Users/donaldpinkus/Desktop/react-redux-starter-kit-master
> npm run dev


> react-redux-starter-kit@0.18.0 dev /Users/donaldpinkus/Desktop/react-redux-starter-kit-master
> node -r dotenv/config bin/server --hot

node: bad option: -r

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.18.0 dev: `node -r dotenv/config bin/server --hot`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@0.18.0 dev script 'node -r dotenv/config bin/server --hot'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -r dotenv/config bin/server --hot
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/donaldpinkus/Desktop/react-redux-starter-kit-master/npm-debug.log

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.18.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@0.18.0 start script 'npm run dev'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/donaldpinkus/Desktop/react-redux-starter-kit-master/npm-debug.log
```

And here is the output in `npm-debug.log`:

```
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart react-redux-starter-kit@0.18.0
7 info start react-redux-starter-kit@0.18.0
8 verbose unsafe-perm in lifecycle true
9 info react-redux-starter-kit@0.18.0 Failed to exec start script
10 verbose stack Error: react-redux-starter-kit@0.18.0 start: `npm run dev`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-redux-starter-kit@0.18.0
12 verbose cwd /Users/donaldpinkus/Desktop/react-redux-starter-kit-master
13 error Darwin 14.1.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error react-redux-starter-kit@0.18.0 start: `npm run dev`
18 error Exit status 1
19 error Failed at the react-redux-starter-kit@0.18.0 start script 'npm run dev'.
19 error This is most likely a problem with the react-redux-starter-kit package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run dev
19 error You can get their info via:
19 error     npm owner ls react-redux-starter-kit
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by donpinkus** [comment]
just needed to update version of node & npm

**Comment by realadeel** [comment]
I'm seeing this error on the latest node and npm.

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-starter-kit@0.18.0~prestart: react-redux-starter-kit@0.18.0
6 silly lifecycle react-redux-starter-kit@0.18.0~prestart: no script for prestart, continuing
7 info lifecycle react-redux-starter-kit@0.18.0~start: react-redux-starter-kit@0.18.0
8 verbose lifecycle react-redux-starter-kit@0.18.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@0.18.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/adeel/Projects/react-redux-starter-kit/node_modules/.bin:/Users/adeel/.rvm/gems/ruby-2.2.3/bin:/Users/adeel/.rvm/gems/ruby-2.2.3@global/bin:/Users/adeel/.rvm/rubies/ruby-2.2.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/heroku/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/Users/adeel/.rvm/gems/ruby-2.2.2@warsaw/bin:/Users/adeel/.rvm/gems/ruby-2.2.2@global/bin:/Users/adeel/.rvm/rubies/ruby-2.2.2/bin:/Users/adeel/.rvm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/sbin:/usr/sbin:/Users/adeel/bin:/Users/adeel/.rvm/bin:/Development/android-sdk-macosx/platform-tools:/Development/android-sdk-macosx/tools
10 verbose lifecycle react-redux-starter-kit@0.18.0~start: CWD: /Users/adeel/Projects/react-redux-starter-kit
11 silly lifecycle react-redux-starter-kit@0.18.0~start: Args: [ '-c', 'npm run dev' ]
12 silly lifecycle react-redux-starter-kit@0.18.0~start: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@0.18.0~start: Failed to exec start script
14 verbose stack Error: react-redux-starter-kit@0.18.0 start: `npm run dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-redux-starter-kit@0.18.0
16 verbose cwd /Users/adeel/Projects/react-redux-starter-kit
17 error Darwin 14.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.3.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error react-redux-starter-kit@0.18.0 start: `npm run dev`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@0.18.0 start script 'npm run dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
