### ISSUE TITLE
Super power hungry!

### ISSUE THREAD

**Issue by jessep** [davezuko/react-redux-starter-kit#326]
I love the project. It is kinda crazy, though, how much power my machine uses after running `npm start`. Even plugged in, my battery charge gradually gets drained throughout the day. 

Not sure there's anything to do about this, but wanted to flag it in case others have the same experience or if people have any insights into whether I could be doing something wrong.

**Comment by davezuko** [comment]
Do you experience this with other projects? This kit doesn't use anything outside of fairly standard webpack tooling (no additional watchers or anything of that sort), so I'm skeptical that similar projects could be any less resource intensive.

**Comment by jessep** [comment]
Thanks for the response. I haven't experienced it with other projects.

**Comment by davezuko** [comment]
You're welcome to keep it open, I just don't have any ideas off the top of my head because nothing special is really happening on top of webpack.

**Comment by mtsr** [comment]
I’ve noticed something similar with erikras’ boilerplate, even when not actually doing anything. This one used to be much less power hungry, but it seems to have become a bit worse recently, although it could be that webpack is just rebuilding more often as I’m making more changes.

**Comment by davezuko** [comment]
@mtsr and @jessep I'll keep my eyes out for any possible optimizations, and maybe if I have some spare time I get do some profiling, but unfortunately there's nothing I can think of that would cause this to be abnormally resource intensive.

**Comment by jessep** [comment]
@davezuko @mtsr Turns out that it was a dropbox issue. I've always kept my side projects in dropbox without issue, to avoid the need for always setting up a remote git repo as backup. But it seems that something about the repo tripped up Dropbox (or else something changed in Dropbox) and it was just going nuts. I removed the project from Dropbox and things are back to normal.
