### ISSUE TITLE
Use 'nock' gives "cannot resolve module 'fs'"

### ISSUE THREAD

**Issue by baopham** [davezuko/react-redux-starter-kit#327]
I followed the [docs](https://github.com/rackt/redux/blob/master/docs/recipes/WritingTests.md#async-action-creators) and keep getting this error: 

```
WARNING in ./~/nock/lib/scope.js
Module not found: Error: Cannot resolve module 'fs' in /<path>/node_modules/nock/lib
 @ ./~/nock/lib/scope.js 18:7-20

WARNING in ./~/nock/lib/back.js
Module not found: Error: Cannot resolve module 'fs' in /<path>/node_modules/nock/lib
 @ ./~/nock/lib/back.js 17:7-20

ERROR in ./~/mkdirp/index.js
Module not found: Error: Cannot resolve module 'fs' in /<path>/node_modules/mkdirp
 @ ./~/mkdirp/index.js 2:9-22
17 12 2015 22:40:41.238:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket OuFUwRmrq82W5fl8AAAA with id 78948690
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "fs"
```

**Comment by baopham** [comment]
This is probably why: https://github.com/webpack/webpack/issues/689

**Comment by choonkending** [comment]
@baopham 

You can add 

```javascript 
      node: {
        fs: "empty"
      }
```

into your webpack config.

**Comment by baopham** [comment]
@choonkending I tried that but it didn't work.

**Comment by mario-camacho2** [comment]
This worked for me (same idea but different code)
```
externals: {
        fs: '{}'
},
```
taken from here https://github.com/request/request/compare/master...pho3nixf1re:webpack-tests

**Comment by timmyLan** [comment]
+1 @mario-camacho2 it works for me

**Comment by Lohann** [comment]
+1 @mario-camacho2 works for me too, thank you.

**Comment by vinceferro** [comment]
Is nock working for you? 
I'm trying to mock axios API calls in redux actions but it hits the real server instead.

**Comment by gontard** [comment]
@vinceferro nock can't  work with karma. Karma launch test in browser and nock works only in node. https://github.com/node-nock/nock/issues/409
