### ISSUE TITLE
Live reloading of styles/SCSS inconsistent?

### ISSUE THREAD

**Issue by zth** [davezuko/react-redux-starter-kit#331]
Hi!

I'm getting a very inconsistent live reload behavior when editing styles/SCSS and I'm guessing I'm missing something fairly rudimentary here in the setup. Basically, I've cloned the latest (083b1cff53156e0b97ffeaa7324abf285abe9f4e) and sometimes live reload of the styles works, but most often it doesn't. I've made no other changes to the repo since cloning, so this should be very easy to reproduce.

For instance, I can can change the background color of body _sometimes_ in the _core.scss file, but most often it doesn't work. It doesn't take effect after a full and hard refresh either always. I can add new jsx/html just fine and it gets hot reloaded, but adding styles for the new markup doesn't work for me. In short, the live reload of the styles only works occasionally and is most often absent completely.

This seems like a very temporary thing, but could someone point me in the right direction of how to get the live reloading of styles back...?

Thanks a lot in advance, I love this starter kit by the way and I've used various versions of it for quite a few projects now with great satisfaction.

**Comment by davezuko** [comment]
If prior experience serves me right, I think this is due to the nature of the style-loader, and how webpack inserts styles into the page during development. This _may_ have stopped working 100% correctly once CSS modules were added, but I'd have to play around with it to know _why_ (assuming that is the problem).

If you disable CSS modules do you get the expected behavior? You can find this in `~/config/base.js` under `compiler_css_modules`.

**Comment by davezuko** [comment]
Just for debugging purposes, you may want to refer to: https://github.com/webpack/style-loader/issues/66. I'm a bit tied up at the moment but can mess with it later.

**Comment by zth** [comment]
Yes, disabling CSS modules did the trick. Great, thanks a ton for your quick reply! And thanks again for all your work.

**Comment by davezuko** [comment]
Cool, well at least now we know for certain that that's the cause. Glad it's working for you, but I'll try to figure something out so that it works properly for both setups.
