### ISSUE TITLE
.babelrc ignored?

### ISSUE THREAD

**Issue by alxlu** [davezuko/react-redux-starter-kit#335]
I'm trying to add [transform-decorators-legacy](https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy) to my `.babelrc` and it looks like this:
```JSON
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": ["transform-runtime", "add-module-exports", "transform-decorators-legacy"]
}
```

When I run `npm start`, I get the following error:
```
ERROR in ./src/views/AboutView.js
Module build failed: SyntaxError: /Users/alexlu/Documents/Other/react-redux-starter-kit/src/views/AboutView.js: Decorators are not supported yet in 6.x pending proposal update.
   9 | @Radium
> 10 | export class AboutView extends React.Component {
     | ^
  11 |   render () {
  12 |     return (
  13 |       <div style={styles.base}>
```

However, when I run babel from the cli (using the same `.babelrc`), the file transpiles correctly. Is there something that is overriding the babel config somewhere? Based on https://github.com/davezuko/react-redux-starter-kit/pull/228, it seems like just editing the `.babelrc` file should work. Is there something I'm missing?

**Comment by alxlu** [comment]
Looks like #228 has been reversed.

I went in and removed the following lines and it seems to work now:
[__base.js#L68-L69](https://github.com/davezuko/react-redux-starter-kit/blob/75d64ab3dd01a3ff5438dcfc4e3fe95ec5f91ac1/build/webpack-environments/_base.js#L68-L69)

Will doing so break something else I'm not aware of?

**Comment by davezuko** [comment]
@alxlu you will be fine for the most part, except you can no longer use `react-transform-hmr` and bundle your webpack application with `NODE_ENV` as "development" without HMR enabled. I.e., if you try to run `npm run compile` or `npm run test` when `NODE_ENV` is "development" and you're using that plugin, you'll run into issues, since HMR isn't enabled in those tasks. If that isn't part of your workflow, then you're safe to continue.

As some background, `react-transform-hmr` is designed to throw if it's applied to a bundle that doesn't have `module.hot` enabled, which I _originally_ planned to petition against but after reading https://github.com/gaearon/react-transform-hmr/issues/5 I realized it was better to go back to our old system where babel is configured directly in the loader.

Does that clear it up?

**Comment by alxlu** [comment]
Thanks for the info. In theory if I wanted to enable those cases, would the guidance be to add the extra plugin to `_base.js` as opposed to removing the two entries from it?

And sorry if this is an uninformed question, but could you provide more info on what the use case is for running `npm run compile` or `npm run test` with `NODE_ENV` set to development?

**Comment by alxlu** [comment]
Also, other than it being a little clunky, is there anything wrong with adding this to `_base.js` so I don't need to repeat my babel config?

```js
import fs from 'fs';
import path from 'path';
const babelrc = fs.readFileSync(path.join(__dirname, '../..', '.babelrc'), 'utf8');
const {plugins, presets} = JSON.parse(babelrc);
```

and then in the `webpackConfig` object:
```js
loaders: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          cacheDirectory: true,
          plugins,
          presets,
          env: {
            development: {
              plugins: [
                ['react-transform', {
                  // omit HMR plugin by default and _only_ load in hot mode
                  transforms: [{
                    transform: 'react-transform-catch-errors',
                    imports: ['react', 'redbox-react']
                  }]
                }]
              ]
            }
          }
        }
      }
```

**Comment by davezuko** [comment]
@alxlu per your last question, yeah, that would totally work. I just avoided it to keep the two configurations distinct. Also, not sure I'm understanding your first question:

> In theory if I wanted to enable those cases, would the guidance be to add the extra plugin to _base.js as opposed to removing the two entries from it?

If you're using `react-transform-hmr` and your `NODE_ENV` is "development", you _have_ to have HMR enabled. So if you do this you'd probably just want to make sure that whenever you deploy your application you're running the tests/compile script with an explicit NODE_ENV of stage/production/etc.

**Comment by davezuko** [comment]
As an FYI, I added a note about this here: https://github.com/davezuko/react-redux-starter-kit/commit/c9ab499ba6d9c8099d8b20454d5e0100207f606e

**Comment by davezuko** [comment]
Closing since this has been solved, but ping me if you're still having issues.
