### ISSUE TITLE
Programmatically change routes

### ISSUE THREAD

**Issue by abachuk** [davezuko/react-redux-starter-kit#342]
How do I change the route programmatically? I tried history.pushState - it changes the URL but doesn't load the view, meaning the app state never changes. 

This one, pushPath('/about') (from redux-simple-router) doesn't do anything at all. Link on the other hand works great. Not sure if there is something specific needs to happen inside view or component in order to change the route. Thanks!

**Comment by davezuko** [comment]
Interesting, that's definitely broken... might have to see if it's a bug with redux-simple-router? I'll look around when I get a chance.

**Comment by davezuko** [comment]
Just as an example, I changed the increment button to:

```
<button className='btn btn-default'
  onClick={() => this.props.history.pushState(null, '/about')}>
  Increment
</button>
```

And it worked as expected. Further experimentation hasn't yielded any issues. Could you post a small code snippet that reproduces the problem?

**Comment by abachuk** [comment]
Sure, below example is for sign in but I tried that for simple clicks as well. In my case I have to do some logic in handleSubmit before redirecting user to correct route. Thanks for your help!

```
import { createHistory } from 'history'
let history = createHistory()

handleSubmit (e) {
  if(login.auth) {
     history.pushState(null, '/about')
 }
}

<form className='login' onSubmit={this.handleSubmit.bind(this)}>
...
</form>




```

**Comment by davezuko** [comment]
I don't think that will work because it's a new history instance. You'll want to use the history that's passed by react-router into your component's props (any component that lives at a route receives a `history` prop). Can you try doing this using `this.props.history` and see if it works?

**Comment by abachuk** [comment]
Yes, that worked!!! thank you very much. All I needed was this.props, like this

```
static propTypes = {
    history: React.PropTypes.object
}

handleSubmit (e) {
  if(login.auth) {
     this.props.history.pushState(null, '/about')
 }
}
```

**Comment by davezuko** [comment]
Cool, glad that fixed it!
