### ISSUE TITLE
suggestion: Provide a container for Navigation with bootstrap navbar

### ISSUE THREAD

**Issue by mikedevita** [davezuko/react-redux-starter-kit#346]
**edit:** added a working base example, can probably be expanded/refined a bit more

----
i think a working example in the starter kit that shows how to do a bootstrap navbar would help a lot of people get started a bit quicker who are ... newer to react/redux.

I myself am not sure how to go about it entirely, and still trying to figure it out.. but this is what i have so far.

I would think it would be more logical to put a Navigation container in, and then include it on any of the layouts that you want a navbar in. Rather than dropping the `Navigation` container in Root.js where it has the props already for `history, store, routes`

**src/containers/Navigation.js**
```es6
import React from 'react'
import { Router } from 'react-router';
import { Navbar, Nav, NavItem } from 'react-bootstrap'
import { LinkContainer, IndexLinkContainer } from 'react-router-bootstrap'

export default class Navigation extends React.Component {
  static propTypes = {
    routes: React.PropTypes.array.isRequired,
  }

  render () {
    const { routes } = this.props;
    var navitems = routes[0].childRoutes.map(function(route, index){
      return(<LinkContainer to={route.path} key={index}>
        <NavItem eventKey={index+1}>{route.name}</NavItem>
      </LinkContainer>);
    });

    return (<Navbar>
      <Navbar.Header>
        <Navbar.Brand>
          <a href='#'>React-Bootstrap</a>
        </Navbar.Brand>
      </Navbar.Header>
      <Nav>
        <IndexLinkContainer to='/'><NavItem eventKey={1}>Home</NavItem></IndexLinkContainer>
        {navitems}
      </Nav>
    </Navbar>)
  }
}
```

**src/layouts/CoreLayout.js**
```es6
import React from 'react'
import '../styles/core.scss'
import Navigation from '../containers/Navigation'

// Note: Stateless/function components *will not* hot reload!
// react-transform *only* works on component classes.
//
// Since layouts rarely change, they are a good place to
// leverage React's new Statelesss Functions:
// https://facebook.github.io/react/docs/reusable-components.html#stateless-functions
//
// CoreLayout is a pure function of it's props, so we can
// define it with a plain javascript function...
function CoreLayout ({ children }) {
  return (
    <div className='page-container'>
      <div className='nav-container'>
        <Navigation routes={ children.props.routes } />
      </div>
      <div className='view-container'>
        {children}
      </div>
    </div>
  )
}

CoreLayout.propTypes = {
  children: React.PropTypes.element
}

export default CoreLayout

```

**Comment by davezuko** [comment]
I think this might be a good addition to an example application using this starter kit, not necessarily to the base project. I'll mull it over over the holiday, thanks for the suggestion.

**Comment by mikedevita** [comment]
no problem. would it at least be possible to have an index of example apps in the read me or something? 

I can cobble a few together just not sure how good they'll be since I'm still quite new to react

**Comment by samrocksc** [comment]
There is actually a boilerplate that accomplishes this on awesome-redux that uses the exact same stack

https://github.com/erikras/react-redux-universal-hot-example

I think it would be better to keep this repo stripped down, it makes for faster scaffolding.

**Comment by davezuko** [comment]
Thanks for pointing that out @samrocksc .

Closing this for now @mikedevita, if I figure out a good solution for showcasing an example application we can move forward with it then. Or, if you have an app that does use this kit I'd _love_ to showcase it in the readme.
