### ISSUE TITLE
Consider create a react-native branch?

### ISSUE THREAD

**Issue by JuoCode** [davezuko/react-redux-starter-kit#347]

**Comment by davezuko** [comment]
I haven't done any react-native, but this would be _great_ to put in a separate fork, but not a branch of this project. If you have plans on making anything let me know and I'd be happy to contribute.

**Comment by ACPK** [comment]
@JuoCode - Have you converted this starter pack over to React Native? I'd be happy to work with you on it!

**Comment by wkrause13** [comment]
@ACPK  - I recently started work on a React Native version of this project. Differences are unavoidable, but I think the important thing is to try to use as many of the same conventions related to project structure as possible. 

Happy to take pull requests that make my project more closely adhere to the conventions established in this project. Here it is:

https://github.com/wkrause13/react-native-redux-starter-kit
