### ISSUE TITLE
isomorphic / universal support?

### ISSUE THREAD

**Issue by pkieltyka** [davezuko/react-redux-starter-kit#349]
Thanks for this very clean starter-kit! what are you thoughts about adding server-side rendering into this example? .. or perhaps as a branch? ..

**Comment by davezuko** [comment]
This has been brought up a few times now, and while I'm 100% for universal support, it inevitably leads to a very opinionated architecture (see react-universal-hot-example) . See: https://github.com/davezuko/react-redux-starter-kit/issues/212 for more on this.

With all the interest around this I might end up caving, but it would be as a separate repo.

**Comment by pkieltyka** [comment]
I think a separate repo would be a great idea, as well, add a note in this README mentioning #212 :) or something of the sort.. to get less of these questions

**Comment by pkieltyka** [comment]
Btw.. This could be a good approach

https://twitter.com/dan_abramov/status/678944667472412672

**Comment by michaelguild13** [comment]
@pkieltyka , for a good simple example of doing Universal with React.
https://github.com/jackfranklin/universal-react-example

It uses Express with React-Dom to pre-render.

**Comment by davezuko** [comment]
Closing this for now, I'll figure out what to do in way of example/documentation/fork sometime this week. Part of what separates this kit from others is the (relative) simplicity of the configuration.

**Comment by pkieltyka** [comment]
Yea this starter kit is very clean and simple, but would be awesome to figure out a minimal addition to offer universal support.

Can't the server/main.js add this fairly easily? To offer the init state and render to string?

**Comment by davezuko** [comment]
@pkieltyka sadly it's not that easy. Due to the use of webpack's `resolve.root` configuration, CSS modules, and the recent addition of webpack's ProvidePlugin, I'm not too sure how this plays out. We would have to pre-bundle the application so it could be consumed by the server, and that creates a very irksome development environment. There is https://github.com/halt-hammerzeit/webpack-isomorphic-tools but that just complicates things... so... yeah, not sure :/

**Comment by pkieltyka** [comment]
Ah .. Def sounds much too complicated. I wonder if webpack2 simplifies this? 

As well, webpack2 improves support for async module loading where you can bundle your base app and admin module separately for example and load admin module on-demand as its referenced. I haven't pulled it off yet, but as apps grow, it would be a major improvement to app load times to only load code as its needed. That would be the holy grail.

**Comment by pkieltyka** [comment]
btw, this is an example of webpack2 with its new code splitting -- https://github.com/webpack/webpack/tree/master/examples/code-splitting-harmony
