### ISSUE TITLE
Error importing modules

### ISSUE THREAD

**Issue by juanda99** [davezuko/react-redux-starter-kit#351]
I'm developing an app using your kit, and first thing I was trying was to add localization.
I made i18n directory with index.js and a localization file for each language: es.js, it.js and en.js.

index.js content (so I can use import * later on):

    export { default as es } from './es'
    export { default as it } from './it'
    export { default as en } from './en'

I try to load localization messages:

    import * as i18n from 'i18n'
    ...
    const intlData = {
      locale: 'en',
      messages: i18n['en']
    }

However messages variable is undefined.

When I checked the console log with: 

    window.console.log(i18n)

I get undefined:

    Object {__esMOdule: true}
     es:undefined
     get es: function get()
     it: undefined
     get it: function get()
     en: undefined
     get en: function get()
     __proto__: Object

Where I should get something like:

    Object {__esMOdule: true}
     es: Object
     it: Object
     en: Object
     __proto__: Object

Maybe some Babel6 option is causing the error?

**Comment by davezuko** [comment]
Hey, I won't be on much for the next few days so I can't be of much immediate help, but I'm curious what your `./es`, etc. files look like. To my eyes it looks like what you have should work, so I'm wondering _where_ in fact it's going wrong.

```js
import es from './es'

console.log(es) // what does this give you?
export es
```

The only additional plugin we're really using is `add-module-exports` (here: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack-environments/_base.js#L68) but I can't see that being the cause of this.

I'll try to reproduce this after this holidays are over; let me know if you make any progress or figure anything out. Good luck!

**Comment by juanda99** [comment]
I use https://github.com/yahoo/react-intl for localization
es file:
```
/*eslint-disable max-len,quotes*/
export default {
  'about.librariesIntro': 'xxxx:',
  'about.specialThanks': 'Prueba'
}
```

console message:
```
Object {about.librariesIntro: "xxxx:", about.specialThanks: "Prueba"}
```

**Comment by juanda99** [comment]
I'll have a look at  add-module-exports plugin. 
Thank you!

**Comment by davezuko** [comment]
@juanda99 it's definitely that plugin, if you remove it you should be OK. I just ran into the same issue with another package... I'll try to drop it from the repo within the next few days.

**Comment by davezuko** [comment]
Since I can't stay away, try making the changes that were made in this PR https://github.com/davezuko/react-redux-starter-kit/pull/354.

**Comment by juanda99** [comment]
Thank you, I've followed your PR.
I reported the issue: https://github.com/59naga/babel-plugin-add-module-exports/issues/20

**Comment by davezuko** [comment]
Thanks for the report. I've compromised by removing it _only_ from the webpack loader configuration, but it still exists for project bootstrap files to make that more convenient. Eventually I'll remove the plugin entirely. PR: https://github.com/davezuko/react-redux-starter-kit/pull/361

**Comment by juanda99** [comment]
Upgrading babel-clil to 6.4.5 fixes the issue.
