### ISSUE TITLE
refactor(webpack) Re-structure react transforms

### ISSUE THREAD

**Issue by patrickheeney** [davezuko/react-redux-starter-kit#353]
Currently we configure the react development transforms in _base rather then in development overrides, which makes it difficult to tell what is being overwritten in development. So I propose that the react-transform configuration get moved entirely to the `development` overrides.

This can also be simplified by using this preset with less to configure and maintain: https://github.com/danmartinez101/babel-preset-react-hmre. 

```
webpackConfig.module.loaders = webpackConfig.module.loaders.map(loader => {
    if (/babel/.test(loader.loader)) {
        debug('Apply react-transform-hmr to babel development transforms')
        loader.query.env = {
          ...loader.query.env || {},
          development: {
            presets: ["react-hmre"]
          }
        }
    }
    return loader
})
```

**Comment by davezuko** [comment]
:+1: I like it, will get to it after the holidays are over. :santa: Thanks!

**Comment by davezuko** [comment]
@patrickheeney https://github.com/davezuko/react-redux-starter-kit/pull/362

I will replace the plugins with react-hmre in a separate PR. Let me know your thoughts.
