### ISSUE TITLE
Problem compiling with Superagent

### ISSUE THREAD

**Issue by OKNoah** [davezuko/react-redux-starter-kit#366]
I get several errors like this, only apparently with super agent, when doing `npm run compile`. The dev server runs fine.

    ERROR in ./~/superagent/package.json
    Module parse failed: /Users/MyUser/Documents/dev/MyProject/node_modules/superagent/package.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "name": "superagent",
    |   "version": "1.6.1",
    |   "description": "elegant & feature rich browser / node HTTP with a fluent API",
     @ ./~/superagent/lib/node/index.js 25:10-39

     ERROR in ./~/superagent/~/mime/types.json
    Module parse failed: /Users/MyUser/Documents/dev/MyProject/node_modules/superagent/node_modules/mime/types.json Line 1: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {"application/andrew-inset":["ez"],"application/applixware":["aw"],"application/atom+xml":["atom"],"application/atomcat+xml":["atomcat"],"application/atomsvc+xml":["atomsvc"],
      ...
      @ ./~/superagent/~/mime/mime.js 87:12-35

    ERROR in ./~/superagent/~/form-data/~/mime-types/~/mime-db/db.json
        Module parse failed: /Users/MyUser/Documents/dev/MyProject/node_modules/superagent/node_modules/form-data/node_modules/mime-types/node_modules/mime-db/db.json Line 2: Unexpected token :
        You may need an appropriate loader to handle this file type.
        | {
        |   "application/1d-interleaved-parityfec": {
        |     "source": "iana"
        |   },
         @ ./~/superagent/~/form-data/~/mime-types/~/mime-db/index.js 11:17-37

**Comment by sandyjoshi** [comment]
can you share what changes you have done to use superagent ?

**Comment by davezuko** [comment]
Is this with our without a `json-loader`?

**Comment by OKNoah** [comment]
@sandyjoshi I just did `npm install --save superagent`

@davezuko I did `npm install --save jason-loader`, but I did not import it anywhere or anything.

**Comment by davezuko** [comment]
@OKNoah not sure what version of this project you're using, but make sure you have this: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack-environments/_base.js#L77

**Comment by OKNoah** [comment]
@davezuko This seems to let it compile, thanks. Very curious why that is since every other node module should have a `package.json` just the same.

**Comment by davezuko** [comment]
@OKNoah not sure TBH :/, mind if I close this?

**Comment by OKNoah** [comment]
@davezuko Sure.

**Comment by rusenask** [comment]
Hey, having same issue, what was the solution? (since that "https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack-environments/_base.js#L77" doesn't exist anymore)
