### ISSUE TITLE
How to contains header, footer, navigation, sidebar and other similar components to the layout?

### ISSUE THREAD

**Issue by GangRock** [davezuko/react-redux-starter-kit#374]
Hi,guys! I have a question, In my project, How can I contains header, footer, navigation, sidebar and other similar components to the layout?

Thanks so much!

**Comment by SpencerCDixon** [comment]
Not sure if I understand exactly what you're asking but in side the layout you can include components for <Header>, <Footer> etc and then just render the children where you want.  For example:

```
function CoreLayout ({ children }) {
  return (
    <div className='page-container'>
      <div className='view-container'>
        <Header />
          <Main>
            {children}
          </Main>
        <Footer />
      </div>
    </div>
  );
}

CoreLayout.propTypes = {
  children: React.PropTypes.element
};

export default CoreLayout;
```

What I do is actually wrap my routes in layouts sometimes.  For example I have all my routes that require a Navbar wrapped in a route that includes the navbar like this:

```
export default (
  <Route path='/' component={CoreLayout}>
    <Route component={NavLayout}>
      <IndexRoute component={HomeView} />
      <Route path='/about' component={AboutView} />
    </Route>
  </Route>
);
```

Hope this helps!

**Comment by davezuko** [comment]
@SpencerCDixon thanks for the explanation, pretty much exactly what I was planning to say. @GangRock does that clear things up at all?

**Comment by GangRock** [comment]
I'm sorry, I did not express clearly what my intent, but @SpencerCDixon reply is what I need. 
thanks @SpencerCDixon and @davezuko
