### ISSUE TITLE
Use nodemon for live server development

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#385]
This was pulled out at the same time as isomorphic rendering, but it would be helpful for people who _do_ end up implementing server logic.

**Comment by SimonSelg** [comment]
Why use an extra binary for this? I just use https://www.npmjs.com/package/piping for this purpose.

For example for my api server I have this in /bin/api.js:

```js
#!/usr/bin/env node
if (process.env.NODE_ENV !== 'production') {
  if (!require('piping')({
    hook: true,
    ignore: /(\/\.|~$|\.json$)/i
  })) {
    return
  }
}
require('babel-register')
require('../api/api')
```

Get's the job done w/o the need of an additional binary (nodemon)

**Comment by davezuko** [comment]
I don't do a lot of node development so nodemon was the only package I was aware of, so definitely not tied to it in any way. If this does the job then :+1:

**Comment by kid** [comment]
Hey there :)
You might want to look into https://github.com/este/este/pull/461 they have moved away from piping as it seems slower than nodemon in some cases.

**Comment by SimonSelg** [comment]
@kid Thx good to know! Will test that.

**Comment by davezuko** [comment]
Using nodemon for now just to get something out the door, but will consider alternatives if there are valid reasons to switch.
