### ISSUE TITLE
Ideas for Improving Webpack Configuration

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#391]
Trying to come up with ideas to improve the ease which with webpack can be configured. Abstracting over configuration isn't easy, because there's bound to be use cases that don't fit nicely, but opening it up for discussion in case anybody has experimented with this themselves.

Here's just one idea that I've been fiddling around with, it's currently a functional prototype but very barebones (/cc @patrickheeney):

```js
class WebpackConfig {
  constructor (config) {
    this._config = Object.assign({}, {
      module: {}
    }, config)

    this._config.module.loaders = this._config.module.loaders || []
  }

  use (adapter) {
    adapter(this._config)
    return this
  }
}
```

Which then allows plugins/loaders to be easily contained within an "adapter", rather than spread out across the webpack config file. Example:

```js
const webpackConfig = new WebpackConfig(...)

webpackConfig
  .use(require('./webpack-adapters/sass-loader')({
    config: {
      includePaths: paths.client('styles')
    }
  }))
  .use(require('./webpack-adapters/extract-text-plugin')())
```

where, as an example, the extract-text-plugin adapter looks like this:

```js
import ExtractTextPlugin from 'extract-text-webpack-plugin'

const DEFAULT_OPTIONS = {
  filename: '[name].[contenthash].css',
  pluginOpts: {
    allChunks: true
  },
  matchLoader: (loader) => {
    return (
      loader.loaders &&
      loader.loaders.find(name => /css/.test(name.split('?')[0]))
    )
  }
}

export default function makeExtractTextPluginAdapter (opts) {
  const options = Object.assign({}, DEFAULT_OPTIONS, opts)

  return function extractTextPluginAdapter (config) {
    config.module.loaders = config.module.loaders.map(loader => {
      if (!options.matchLoader(loader)) {
        return loader
      }

      const [firstLoader, ...restOfLoaders] = loader.loaders
      loader.loader = ExtractTextPlugin.extract(firstLoader, restOfLoaders.join('!'))
      delete loader.loaders
      return loader
    })

    config.plugins.push(new ExtractTextPlugin(options.filename, options.pluginOpts))
    return config
  }
}
```

So yeah, just playing around. Any thoughts/contributions are appreciated.

**Comment by patrickheeney** [comment]
I like it in theory. I think the goal is to abstract away as much of webpack config as possible with babel like presets. This may even be outside the scope of the starter-kit but is related to the challenge vjeux posted on twitter recently and the goal of making it easier for prototyping and getting started with react, es6, babel, etc. There were lots of good responses to that with some possible ideas for abstractions.

If the goal is to make it easier for the user, I think having as minimal config as possible with popular presets or defaults would be the way to go. Something like `.use(require('./webpack-adapters/extract-text-plugin')())` doesn't mean anything to anyone not experienced with webpack. What is `extract-text-plugin`, what does it do, why do I need it, etc. If I know all that already it would probably be easier to just manage my own config and the abstraction would be frustrating. 

I don't think it would need to cover every use case, but just enough of the defaults to eliminate the boilerplate like babel presets. You can always create your own adapter or write your own config entirely. 

Some concept idea:
```
const config  = new WebpackConfig({
  root: paths.dir_client,
})
config.use('sass') // or
config.use('css') // or 
config.use('css-modules')

if (process.env === 'development') { 
  config.use('hot-reload')
}

config.use(require('./config/my-custom-config'))

console.log('Test', config.print())

// This could all be simplified even with
const config  = new WebpackConfig({
  root: paths.dir_client,
  presets: ['css-modules', process.env === 'development' ? 'hot-reload': '', './config/my-custom-config']
})
```

The goal wouldn't be to have configuration options for everyone. It would provide the best configuration as a starting point (sane defaults, production ready, best practices) with an easy way to extend.

**Comment by patrickheeney** [comment]
You could also go a step further by making this webpack config generator a separate library included in this project to removing the coupling with the starter-kit. It could generate a json config file, or even the webpack.config.js that could be bundled with the project. I could see it being popular on its own.

```
webpackconfig --print --presets 'css-modules:hot-reload' > webpack.development.json 
const config = require(`webpack.${process.env}.js`)
export default config
// or
import configGenerator from 'webpack-config-genator'
const config = new configGenerator({})
export default config
```

**Comment by davezuko** [comment]
@patrickheeney a lot of good ideas, but I do have an issue with the following (I understand it's all hypothetical):

```
config.use('sass') // or
config.use('css') // or 
config.use('css-modules')
```

Configuration based off of string literals means the config must come pre-packaged with this functionality. Approaching it from a more middleware-like perspective has the added benefit of being independently versioned and modular, but also complicates the process for applying these loaders/configs/whatever-you-call-em.

**Comment by patrickheeney** [comment]
I would say you should pre-package 90% of the config, loaders, etc that every typical webpack install should have like hot loading, text extracting, etc. CSS is a different story since every project is different and that is probably an example of what not to bundle at all (since some may just use external css libraries entirely). 

I definitely think it could get complicated if one were to use config that overlap or that remove things. However you could always add a way to do something like this to override anything at the end:

```
config.use(webpack => {
  webpack.loaders = []
  webpack.loaders.push({})
  return webpack
})
```

I guess the questions become:

- Would this make it easier for someone new to js, es6, react, etc, get started? 
- Is it easy to change styles?
- Do I have to learn anything about webpack?

If the abstraction is solving these real problems, then I think supporting complicated webpack config is likely outside the scope of this config generator. There is always the possibility of using a CLI tool to just output the config like I mentioned before as that is the best of both worlds. Edit the config if you want to work with it directly or edit the config generator if you don't know anything about it.

**Comment by davezuko** [comment]
Will be opening a gitter room for 2.0.0 discussion.
