### ISSUE TITLE
Default homepage shows nothing

### ISSUE THREAD

**Issue by jwyuen** [davezuko/react-redux-starter-kit#393]
The title is set but the page is otherwise blank.  It doesn't look like it's rendering the HomeView (which I think is what's supposed to render but I'm not sure since I'm a noob).  I've tested this on the latest commit  (e708c5202ef2e7b310757056294e24f230972e6a) and also the stable version (0.18) and both seem to have the same issues.  My original set up was to reverse proxy to the koa server using Nginx, but hitting the koa server directly on port 3000 seems to have the same issue.

**Comment by davezuko** [comment]
Very strange, are you getting any console errors? I could see maybe having missed something with the latest switch to Koa, but this is the first I've heard of any problems w/ any previous release.

**Comment by netpoetica** [comment]
@jwyuen Which node version are you using? Also, which browser/OS? And lastly, if you open the Chrome Developer Tools and refresh (ideally Shift + Refresh) do you get any errors that you can paste here?

I am also curious - same as Dave - if you have any errors in the console after running "npm start", or if you got any errors after running "npm install".

**Comment by jwyuen** [comment]
oh doh, I'm not running the server locally but on a EC2 instance and gave it a domain name.  Forgot to change the server_host param in config/_base.js.  My bad.....

On a related note, I guess changing the config doesn't recompile the app (whatever it is that's watching from 'npm start')?
