### ISSUE TITLE
Question: View/Container distinction

### ISSUE THREAD

**Issue by SpencerCDixon** [davezuko/react-redux-starter-kit#404]
As I've used this starter kit on three separate projects now I've noticed that my Views are often becoming Containers by connecting via redux.  Was wondering if other people do that as well or do you make a point of refactoring the connection into its own Container and keeping your View components strictly for layout of the page.

I realize its not THAT big a deal and is more a stylistic thing but just curious

**Comment by davezuko** [comment]
I think for _most_ projects `containers` largely remains empty and/or solely be used for component wrappers. As an example, I use it most often for components that need to be connected in various ways, whereas views will almost always use the same container logic.

**Comment by pkieltyka** [comment]
I think containers and components is enough. As well, I also like the idea of "ducks" as modules. See https://github.com/pkieltyka/rapp/tree/master/src

**Comment by SpencerCDixon** [comment]
Okay awesome just wanted to make sure I was using the View/Container paradigm/distinction properly :)

**Comment by davezuko** [comment]
Awesome :)
