### ISSUE TITLE
<Link> component requires 2 clicks on the back button

### ISSUE THREAD

**Issue by GerritWanderer** [davezuko/react-redux-starter-kit#409]
It looks like that with commit e34df30ecce786578523bec8abe7576dfde842b1 the behavior of the back button broke.
Can be reproduced in the latest master. Just Follow a Link element and afterwards it requires 2 clicks on the native back button to get back to the previous page.

**Comment by davezuko** [comment]
Interesting, will take a look.

**Comment by davezuko** [comment]
Submitted https://github.com/davezuko/react-redux-starter-kit/commit/e7d67d33512c5266e269e9d250ab80a942d5995f, does this fix it for you as well? If not we can always use a `<base>` tag.

**Comment by GerritWanderer** [comment]
Yes, thank you. This fixed the back button behavior in our project (and I guess also in the counter example)

**Comment by davezuko** [comment]
:tada:
