### ISSUE TITLE
Reducer Hot Loading Broken

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#42]
Since updating Redux package versions to 2.0.0 there's an error (as reported by https://github.com/iamstarkov in https://github.com/davezuko/react-redux-starter-kit/commit/4c8f393cf562193bf49cdc65e2439d240a5a48d3).

```
"<Provider> does not support changing store on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/rackt/react-redux/releases/tag/v2.0.0 for the migration instructions."
I got this error from the start, so probably with this deps-update source fore reducers also should be updated.
```

**Comment by davezuko** [comment]
@iamstarkov this will be fixed shortly with this PR: https://github.com/davezuko/react-redux-starter-kit/pull/43 as soon as the tests pass.

Another problem arises from this in that the `createReducer` util no longer works correctly, but I'll file that as a separate issue.

**Comment by davezuko** [comment]
Fixed with https://github.com/davezuko/react-redux-starter-kit/pull/43

**Comment by iamstarkov** [comment]
yay, thank you
