### ISSUE TITLE
how to require test helpers properly given the root.resolve from webpack

### ISSUE THREAD

**Issue by SpencerCDixon** [davezuko/react-redux-starter-kit#422]
So I want to be able to have like a test/support file where I house all my test helper methods that I can import when needed.  Problem I'm running into is it won't let me export/import because of the wepback root.resolve to /src.  Is there a way to override this for the test directory or include the test/support folder in the resolution chain?

I've tried doing something like: `../tests/support/<myfile>/` but that doesn't seem to work either.  Any thoughts?

**Comment by davezuko** [comment]
@SpencerCDixon I'll probably be updating the test suite to use webpack's `require.context` which will allow you to more easily load a bunch of helpers before your tests run and expose them globally. For now, you could add an alias for tests:

```
alias: {
  tests: paths.base('tests')
}
```

And that _should_ work, but if not hopefully I can get to the new bundler in the next day or two.

**Comment by SpencerCDixon** [comment]
Nice I'll have to read into webpacks require.context feature!  And thanks I will try the alias out and let you know if it works

**Comment by davezuko** [comment]
Updated tests to use `require.context`: https://github.com/davezuko/react-redux-starter-kit/pull/436

If you want to include any global utils before your tests, just add a pattern in `tests/test-bundler.js`:

```
// require all `tests/**/*.spec.js`
const testsContext = require.context('./', true, /\.spec\.js$/)
testsContext.keys().forEach(testsContext)

// require all `src/**/*.js` except for `main.js` (for isparta coverage reporting)
const componentsContext = require.context('../src/', true, /^((?!main).)*\.js$/)

componentsContext.keys().forEach(componentsContext)
```

**Comment by SpencerCDixon** [comment]
:+1: dope thanks
