### ISSUE TITLE
Suggestion: Use chai-enzyme

### ISSUE THREAD

**Issue by simplyianm** [davezuko/react-redux-starter-kit#423]
Has anyone managed to get https://github.com/producthunt/chai-enzyme working with this?

I think it should be included in the starter kit.

**Comment by SpencerCDixon** [comment]
I use enzyme in my app but not with that package

**Comment by davezuko** [comment]
Is there a specific error you're having with it, or is this just a suggestion to include it?

**Comment by simplyianm** [comment]
Suggestion to include it. I think it's better than what's currently in the
boilerplate.

**Comment by davezuko** [comment]
Added this to the roadmap!
