### ISSUE TITLE
Issues in debugging in chrome devtools

### ISSUE THREAD

**Issue by shobhitg** [davezuko/react-redux-starter-kit#424]
Hi,

Not sure where to ask this ask this.
I start with this starter kit, and now using it with React-DnD.

Right now I am facing this debugging related issue with some DnD related code, but I have experienced this elsewhere as well earlier while using this kit.

Consider this code:
```
  drop(props, monitor, component) {
    const item = monitor.getItem();
    const delta = monitor.getDifferenceFromInitialOffset();
    var test = monitor.getClientOffset();
    debugger;
    console.log(delta);
    console.log(test);
    return { campaignId: props.data.campaign.id, sceneId: props.data.scene.id };
  }
```
Lets say I am debugging in chrome devtools on the `debugger` breakpoint, and within console if I write `monitor.getDifferenceFromInitialOffset()` or `monitor.getClientOffset()` then I get null.
Whereas, if I inspect variables `delta` or `test`, then I can see the actual value. This not being able to run code in console to try out things is really hurting my dev process.

I am clueless as to why this is happening. I feel this is some kind of side effect of Babel's transpilation or maybe something that webpack does.
Has anyone else ever experienced such kind of issues?
If anyone knows what issue I might be experiencing, please let me know. Thanks.

**Comment by SpencerCDixon** [comment]
I experienced a similar issue when using React DnD but it wasn't with this starter kit.  Whenever I called monitor.getItem() inside a debugger it returned undefined but worked fine when actually running.  Can't remember what I did that fixed it, have you tried using firefox yet to see if it works fine in firefox vs. chrome just to confirm it might not be the starter kit?

**Comment by davezuko** [comment]
Closing this until there is evidence that this is related to this project (ty for the followup @SpencerCDixon). Unfortunately I don't have the time to attempt to reproduce this when it's not clear that it's related to this project, but if you figure out that it is in some way specific to this project then I'd be more than happy to re-open and dig into it.

**Comment by shobhitg** [comment]
Update: I tried in firefox and do not face this issue. So the issue is most likely not related with this starter kit. Thanks.
