### ISSUE TITLE
Error after deploying to production

### ISSUE THREAD

**Issue by maticrivo** [davezuko/react-redux-starter-kit#426]
I used `NODE_ENV=production npm run compile`. I have my ngnix configuration to redirect all traffic to dist/index.html and if i try to go to a url thats not the index, for example http://domain.com/about i get the following javascript error:
`Uncaught SyntaxError: Unexpected token <`

if i go the the index, http://domain.com/ and from there press a link to the about page it all works perfect.

any idea what can be wrong?

**Comment by maticrivo** [comment]
The issue was with me..
I added `compiler_public_path     : '/',` to the `config/_production.js` and now all works perfect.

**Comment by brancusi** [comment]
Had the same issue and the above fixed it. Hosting on firebase btw.

Would love to know if there is a more fundamental issue here.

Thanks

**Comment by ArnaudValensi** [comment]
Shoudn't we add `compiler_public_path : '/',` in `config/_production.js` by default?

**Comment by ranjithnori** [comment]
Had the same issue when hosted on AWS s3. I have set the `compiler_public_path : '/',` in `config/_production.js` and it doesn't work. I'm using the 1.0.0 version of the starter kit. Can anyone help ?

**Comment by brandonmp** [comment]
having this same issue with Firebase hosting. Not sure if `config/_production.js` is a legacy file, as it's not in my project, but the `config/environments.js` file has this:

````
production: (config) => ({
    compiler_public_path: '/',
    compiler_fail_on_warning: false,
    compiler_hash_type: 'chunkhash',
    compiler_devtool: null,
    compiler_stats: {
      chunks: true,
      chunkModules: true,
      colors: true
    }
  })
````

Is this what above posters were referring to re: `compiler_public_path`?

If so, is there another fix? like OP, `<Link>`ing from my index page works fine, but navigating directly there works not-fine.

**Comment by abhinavzspace** [comment]
I am facing the same issue @brandonmp . Did you find any solution?

**Comment by brandonmp** [comment]
ah sorry @abhinavzspace , i must have found a solution b/c it works fine now, but i genuinely can't remember at all what i did :/ if I can remember I'll update here

**Comment by ranjithnori** [comment]
@abhinavzspace What kind of history you use with React router ?
When I got this kind of issue a while back, I was using browserHistory. I switched to hashHistory and everything worked perfectly. 

Unfortunately, I have no clear idea why this is so. I'll have to take a deep dive into React router histories myself.

**Comment by abhinavzspace** [comment]
Thanks! I will try hashHistory and let you know.
