### ISSUE TITLE
problem with incorporating jquery-ui css styles 

### ISSUE THREAD

**Issue by geohuz** [davezuko/react-redux-starter-kit#428]
In core.css I have:
```
@import 'jquery-ui.css';
@import 'jquery.ui.theme.css';
```

but then I notice some of the the css styles defined in the jquery-ui doesn't work as expected, like this rule:

```
.ui-icon,
.ui-widget-content .ui-icon {
	background-image: url(images/ui-icons_222222_256x240.png);
}
```

was rendered as:

```
.ui-icon, .ui-widget-content .ui-icon {
    background-image: url(http://localhost:5000/ff3ebbdd4d6268067b88442076c6dbf0.png);
}
```

and the icon isn't shown there. I know there must be something to go with the webpack configuration file, but I can't figure out how to change the file to make it work, I also read through the issue reports, I guess it may be related to 'css rule rewriting', still can't find a proper way to fix it, hope somebody can help me here.

**Comment by neiled** [comment]
Where did you put the images that it uses?

**Comment by geohuz** [comment]
I create a new images folder under styles, and put the the two jquery-ui css in the styles folder. I also tried 

```@import '../../node_modules/jquery-ui/themes/black-tie/jquery-ui.min.css';
@import '../../node_modules/jquery-ui/themes/black-tie/theme.css'```

and it doesn't work

**Comment by geohuz** [comment]
ok, now I have changed to version 1.0, I'm trying to include jquery-ui css in my project, in the core.scss I have 
```
:global {
@import '../../node_modules/jquery-ui/themes/black-tie/jquery-ui.min.css';
@import '../../node_modules/jquery-ui/themes/black-tie/jquery.ui.theme.css';
}

but I'm having the following issue:

```
ERROR in ./~/css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/jquery-ui/themes/black-tie/jquery-ui.min.css
Module not found: Error: Cannot resolve module 'images/ui-bg_highlight-hard_100_f9f9f9_1x100.png' in /Users/geohu/Codings/Web_front/orgchart/node_modules/jquery-ui/themes/black-tie
```

I'm not able to fix this error, could you please give me a hint? Thanks

**Comment by pixeldrew** [comment]
@geohuz even if you solve the url path for this module the rule is being rewritten by the cssloader module which means you would have to include this module as a js include to retrieve the correct classname. (I'm guessing the rewritten class names would also not work within jquery-ui's javascript)

Side note, you should be able to write @import 'jquery-ui/themes/black-tie/jquery-ui.min.css';

**Comment by geohuz** [comment]
I finally resolved my problem by adding the following lines in the core.scss:
```
:global {
@import 'node_modules/jquery-ui/themes/black-tie/jquery-ui.min';
@import 'node_modules/jquery-ui/themes/black-tie/jquery.ui.theme';
}
```
and put the image files in the src/styles folder.

**Comment by pixeldrew** [comment]
@geohuz does that work? Does the javascript actually map correctly to the correct classnames? I'm pretty sure the jquery-ui rules are being rewritten

**Comment by geohuz** [comment]
Yeah it does work for me on 1.0, in 0.8 the png file loaded but it only shows a blank square. I'm not sure if  I do understand the rewritten of the rule, and the url is like background-image: url(data:image/png;base64,iVBOR...). And finally, I was facing another problem, I'm trying to use icon font for the icons: https://github.com/mkkeck/jquery-ui-iconfont, and I can only see the blank squares again. I have tried hours to made it work but fails.
