### ISSUE TITLE
Server aborting after a while

### ISSUE THREAD

**Issue by neiled** [davezuko/react-redux-starter-kit#431]
Hi,

Anyone else noticed the ```npm start``` command aborting after a while?
When I say aborting I mean the entire process just dying like so:

```
Time: 1220ms
                                   Asset           Size  Chunks             Chunk Names
          vendor.428ec3bfcdc84f16dd1e.js         897 kB       0  [emitted]  vendor
             app.428ec3bfcdc84f16dd1e.js         407 kB       1  [emitted]  app
    1.6e543c52781077034ad8.hot-update.js        3.98 kB       1  [emitted]  app
    6e543c52781077034ad8.hot-update.json       36 bytes          [emitted]
      vendor.428ec3bfcdc84f16dd1e.js.map        1.07 MB       0  [emitted]  vendor
         app.428ec3bfcdc84f16dd1e.js.map         499 kB       1  [emitted]  app
1.6e543c52781077034ad8.hot-update.js.map        1.77 kB       1  [emitted]  app
                             favicon.ico  NaN undefined          [emitted]
                              index.html        1.26 kB          [emitted]
webpack: bundle is now VALID.
[1]    15697 abort      npm start
```

Notice the last line is the process aborting. I can't see any reason why it would be doing this.

The only other clue is this in the console:

```
net::ERR_INCOMPLETE_CHUNKED_ENCODING
```

So steps to reproduce, clone the repo, ```npm start``` then wait 30 mins. See if your process dies.

**Comment by davezuko** [comment]
I haven't noticed this, and haven't had a chance to try to repro. Does this happen while you're actively developing, or only if you let it sit idle?

**Comment by neiled** [comment]
Actually just sitting idle. I've not noticed it for a while now either, let
me do some tests again tomorrow and I'll close the incident if I don't see
it again otherwise I'll try and find a dump or something.

**Comment by davezuko** [comment]
Ok well ping me back if you're still having issues, I'm going to try it for a few more days and if neither of us can repro I'll close this issue.

**Comment by neiled** [comment]
OK thanks, it's definitely happened again but I forgot to check for a dump. I thought it might be because I was doing an `npm run compile` whilst `npm start` was running, but that seems to work fine. I'll try again to reproduce consistently.

**Comment by davezuko** [comment]
There's been some changes to move some of the prod-only plugins from the development (e.g. dedupe and occurrence order), which has fixed any remaining issues I've had w/ the build process. If you could upgrade to latest then post back here if you still experience issues that would be great. Thanks.

**Comment by KalebPortillo** [comment]
+1
