### ISSUE TITLE
React rendering PropType errors not caught on test

### ISSUE THREAD

**Issue by simplyianm** [davezuko/react-redux-starter-kit#433]
<img width="985" alt="screen shot 2016-01-12 at 12 08 25 am" src="https://cloud.githubusercontent.com/assets/401263/12258090/b3d13a8a-b8c0-11e5-9bd9-e4d9702179e0.png">

**Comment by simplyianm** [comment]
These should fail the test.

**Comment by davezuko** [comment]
Why should those fail the test? I've never known those errors to be anything other than warnings for the developer. Can you point me to somewhere where those _do_ fail the test?

That said, the tests should be fixed.

**Comment by davezuko** [comment]
From React docs:

> When an invalid value is provided for a prop, a warning will be shown in the JavaScript console. Note that for performance reasons propTypes is only checked in development mode.

So perhaps there's some plugin/tool that you can use to modify this behavior to force React to throw real errors, but I don't think that's the default behavior. Correct me if I'm wrong.

**Comment by CurtisHumphrey** [comment]
I add the following lines in a beforeEach to trigger them as real errors. I view this as really important to test as the interaction between components typically is a big source of real errors.

```javascript
beforeEach( () => {
  sandbox = sinon.sandbox.create();
  sandbox.stub(console, 'error', (message) => {
    throw new Error(message);
  });
});
afterEach( () => {
  sandbox.restore();
});
```

**Comment by davezuko** [comment]
:+1: @CurtisHumphrey that might be a nice util to add. Will look into incorporating that once I restructure the test suite.

**Comment by CurtisHumphrey** [comment]
FYI: I'm also having issues with code coverage not pickup up files that do not have a test spec written against it too.

**Comment by simplyianm** [comment]
Did not know that was not an error. Thanks for the snippet!
