### ISSUE TITLE
Koa interprets URLs with dots as static

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#434]
At least I think that's what's going on. I have paths in my app with dots in them. Works fine in React, but if I try to directly boot the app from that path (e.g. bookmarks), the app doesn't boot and I get a 404 not found from the server.

**Comment by davezuko** [comment]
Lovely. Is this the same issue as https://github.com/davezuko/react-redux-starter-kit/issues/432 ? Would like to track this in one place.

**Comment by neverfox** [comment]
Not quite, though that warning is thrown under those circumstances. This is a case where Koa is behaving "correctly" (it sees a dot and assumes a file extension, then looks for it; though it does this even with a trailing slash), but there are cases where that's clearly the wrong thing to do. So the only good solution I can think of is to be able to configure what kinds of extensions to handle as static, treating everything else as a basic pathname (i.e. making no assumptions).

**Comment by davezuko** [comment]
Ah ok, I understand now. Might look into using a custom middleware replacement for `koa-static` since it's just a tiny wrapper around `koa-send`.

**Comment by davezuko** [comment]
@neverfox did you ever figure out a workaround for this? I haven't had time this week to write a custom wrapper, so not sure if you just went back to using express or what.

**Comment by neverfox** [comment]
No, I punted and just got rid of the offending URLs in my app.

**Comment by davezuko** [comment]
Ok, closing for now since this seems to be an edge case and isn't directly related to the kit. Might open an issue in one of the two koa libs.

**Comment by andest01** [comment]
This thread was a lifesaver. I too have periods (dots) in some of my routes. I'm using them for longitude and latitude, e.g. `/someRoute/someOtherRoute/foo@-94.1335,42.1434`.  This is a valid route, and it works fine in `react-router` and `react-router-redux`. It just doesn't work in `koa-static`.

I know it's not this project's bailiwick, but guidance on this would be very helpful :+1:

**Comment by skrobek** [comment]
I have a similar issue and I'm not sure how to solve it. Any hints?

**Comment by clkao** [comment]
I have a smaller test case for this:

1. Change the path matching for the Counter route to: `counter(/:path)`
2. Add `<Link className='btn btn-default' to='/counter/foobar.baz'>Test</Link>` to the counter component
3. go to /counter, click the "Test" link, route dispatch is correct.
4. reload the url which is now /counter/foobar.baz, observe a `Not found` message from Koa.
