### ISSUE TITLE
Version 0.18.0: outdated redux-devtools dependencies

### ISSUE THREAD

**Issue by Thiruppathi** [davezuko/react-redux-starter-kit#435]
Got the following error on `npm install`  

```
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package redux-devtools@3.0.0-beta-3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer redux-devtools-dock-monitor@1.0.1 wants redux-devtools@^3.0.0
npm ERR! peerinvalid Peer redux-devtools-log-monitor@1.0.1 wants redux-devtools@^3.0.0

```

Updated the package.json with latest redux-devtools as follows and it worked well.

```
    "redux-devtools": "3.0.0",
    "redux-devtools-dock-monitor": "^1.0.1",
    "redux-devtools-log-monitor": "^1.0.1",

``` 

Will this be addressed in next release? Please correct me if I'm wrong.

**Comment by davezuko** [comment]
I probably just haven't caught this yet, will take a look. Thanks.

**Comment by davezuko** [comment]
current package.json has:

```
    "redux-devtools": "^3.0.0",
    "redux-devtools-dock-monitor": "^1.0.1",
    "redux-devtools-log-monitor": "^1.0.1",
```

is that not correct? Those all appear to be latest.

**Comment by Thiruppathi** [comment]
I was looking at the stable release version(0.18.0).

https://github.com/davezuko/react-redux-starter-kit/blob/v0.18.0/package.json

On Tue, Jan 12, 2016 at 3:36 PM, David Zukowski <notifications@github.com>
wrote:

> current package.json has:
>
>     "redux-devtools": "^3.0.0",
>     "redux-devtools-dock-monitor": "^1.0.1",
>     "redux-devtools-log-monitor": "^1.0.1",
>
> is that not correct? Those all appear to be latest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davezuko/react-redux-starter-kit/issues/435#issuecomment-170949395>
> .
>



-- 
Thanks,
Thiru

**Comment by davezuko** [comment]
Hmm, you are right. Not sure how to properly update and tag that, however.

**Comment by Thiruppathi** [comment]
hmm.. am a novice in handling PR & Release Stuff.. :-) 
please do the needful.

**Comment by davezuko** [comment]
Released https://github.com/davezuko/react-redux-starter-kit/releases/tag/v0.18.1 :)

**Comment by Thiruppathi** [comment]
Thanks.. :+1:
