### ISSUE TITLE
Prefered way to add globals to environment configs?

### ISSUE THREAD

**Issue by martinbeck** [davezuko/react-redux-starter-kit#437]
Hi,

what's the preferred way to add an environment specific global to the configuration files, e.g. an API_URL pointing to localhost or another domain. With the current settings, by editing config/_production.js I cannot override the config.globals object coming from _base.js, can I?

**Comment by davezuko** [comment]
You could, although I admit I should make the config override process cleaner.

```js
export default (config) => ({
  // ...
  compiler_globals: {
    ...config.compiler_globals,
   API_URL: '<your-api-url-here>'
  }
})
```

Might eventually change it so you don't have to override properties but simply return the config, which would make this a bit more intuitive.

**Comment by martinbeck** [comment]
Thx, I needed to do
```
export default (config) => ({
  // ...
  globals: {
    ...config.globals,
   API_URL: JSON.stringify('<your-api-url-here>')
  }
})
```
but afterwards it works like a charm.

**Comment by damiangreen** [comment]
I tried this in the up to date code base (environments.config.js)

```
production: (config) => ({
    globals:{
      ...config.globals,
      'API_URL': JSON.stringify('/api/')
    },
```
but it blows up on the spread operator.

Omitting the spread part entirely causes the whole global property to be overwritten, causing the NODE_ENV environment variable to not exist

**Comment by urbaitel** [comment]
I don't see an environments.config.js and am having a hard time getting project.config.js to work .. any examples?

**Comment by HawiCaesar** [comment]
So we simply require this in our webpack.config.json?

I am confused. The snippets only show the config files. Where do we explicitly say use development config?
