### ISSUE TITLE
Code coverage NOT pickup up all files

### ISSUE THREAD

**Issue by CurtisHumphrey** [davezuko/react-redux-starter-kit#439]
the isparta loader for karma is not picking up all files so its code coverage reports are wrong as it only includes files one has imported into a test. I think this was working in version 0.18 when you had the karma.entry.js file

**Comment by davezuko** [comment]
Hey @CurtisHumphrey, I saw you mention that in another PR/issue. I just pushed a fix for this an hour or two ago and the problem appears to be fixed. Could you verify?

Thanks!

**Comment by CurtisHumphrey** [comment]
It does appear to work now!  I'll have to figure out what different between my snapshot and your current build.
