### ISSUE TITLE
[question & help] Page Not Display at Android(4.4.2) Browser With Latest Firebox

### ISSUE THREAD

**Issue by chenkaiC4** [davezuko/react-redux-starter-kit#441]
Great repo!

I want to use this great repo to start my project working on mobile browser, BUT after downloaded master branch, installed all npm packages and start it successfully, I open my browser(Firefox version 43.0) on my Android Phone (system version is 4.4.2), The Page Is Empty.

However, Desktop Google browser works fine!!

I'm not familar with those magic configuration steps. Is it because lack of some configuration results in this problem.

**Comment by thangngoc89** [comment]
Well. As far as I know, this repo won't work on mobile browser with HMR enabled. Try to compile your project first and serve those compiled file to your mobile browser

**Comment by chenkaiC4** [comment]
@thangngoc89 thanks! Maybe I should have a try to find why HMR cause this problem at weekend.

**Comment by davezuko** [comment]
Sounds like this is HMR related and not specific to this kit, so closing for now. If you experience otherwise please let me know and I can look into it.
