### ISSUE TITLE
Can't use breakpoints in chrome devtools

### ISSUE THREAD

**Issue by RyanVice** [davezuko/react-redux-starter-kit#445]
I'm having issues debugging using chrome devtools. The main issue is that i can't set breakpoints. Well to be clear I can set them but the browser won't stop on them. However, if I use ```debbuger``` statements it will break. Once I do break in code I'm also not able to see the values of an variables that are created via import statements. Is this just something you sacrifice when using this type of tooling or am I doing something wrong? I'm on chrome 47, canary.

**Comment by RaitoBezarius** [comment]
@RyanVice: It may be related to the type of devtool you're using, do you break inside of `webpack://` virtual folder? You can try to switch to a true `source-maps` devtool, but the build time / recompile time will be slower, at least, you will be able to debug better, take a look to this [Webpack doc](https://webpack.github.io/docs/configuration.html#devtool) about dev tools.

**Comment by davezuko** [comment]
We are currently back to using `source-maps` so this should no longer be an issue. Will be looking into a better solution with `2.0.0` so we can get back to `cheap-eval-source-map`.

**Comment by RyanAtViceSoftware** [comment]
@RaitoBezarius I switched to regular source-maps and that fixed it. In case anyone else gets stuck on this I removed the code below from ```webpack-environments\development.js```

```
    debug('Override devtool with "cheap-module-eval-source-map".')
    webpackConfig.devtool = 'cheap-module-eval-source-map'
```


@davezuko i didn't see that fix on origin/master but may have just missed it.

Thanks all!

**Comment by markerikson** [comment]
Out of curiosity, what was the reason for switching sourcemap settings back and forth?

**Comment by davezuko** [comment]
@markerikson some browsers don't read the source maps properly when using `cheap-module-eval-source-map` (Canary is one, last I checked), so to fix it for all users I temporarily reverted it to just regular `source-maps`. It will be reverted (for the last time) back to `cheap-module-eval-source-map` as it's 2-3x faster on average, and I will be adding a note so people whose source maps _don't_ work can just revert locally.
