### ISSUE TITLE
Sass files don't seem to be included 

### ISSUE THREAD

**Issue by pilgrimtech** [davezuko/react-redux-starter-kit#446]
I pulled a new copy of this solution down, and ran it. Attempted to modify bot core.scss and _base.scss within the src/styles folder. Simple change to modify the background of the body showed no results after saving (waiting for the hot reload) as well as stopping webpack and rebuilding/restarting. 

What am I missing to get styles working?

**Comment by davezuko** [comment]
That's weird, definitely not intended. I'm currently traveling so a bit tied up at the moment, but will look at this as soon as I get a chance.

**Comment by jjordy** [comment]
@pilgrimtech I am not having this issue with a fresh checkout can you try another git clone and verify everything installed properly?

**Comment by davezuko** [comment]
Just as an FYI, CSS Modules don't work with HMR out of the box. I believe there are some workarounds out there, but if you want HMR in the kit you'd need to write the `module.accept` handlers yourself.

That said, if this is that it isn't picking up on your styles _at all_, then that's definitely a bug.

**Comment by pilgrimtech** [comment]
Not sure what the deal was- I deleted everything and reinstalled. It works fine now, Sorry guys.
