### ISSUE TITLE
Suggestion: Browsersync vs koa

### ISSUE THREAD

**Issue by jdbence** [davezuko/react-redux-starter-kit#449]
Why koa? Browsersync is more useful for development compared to a low lift Node server. I have it working with this project instead of koa.

**Comment by davezuko** [comment]
Eh, it's a tradeoff either way.

I find it more enjoyable to use Koa when writing API's, and have not used browsersync. In my opinion the expressiveness and terseness of Koa reflects the (ultimate) goal of this kit to remain lean.

If you'd like us to reconsider this, please bring it up in the 2.0.0 thread. Thank you!

**Comment by hamishtaplin** [comment]
@jdbence I'd be interested to see how you swapped Koa for bs, can you share the code please?
