### ISSUE TITLE
Maintain Todo Example

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#45]
There have been a lot of changes to the starter kit recently, so the todo branch needs to be updated accordingly.

**Comment by agdolla** [comment]
I'd give it a try, what's your preference ?

**Comment by davezuko** [comment]
Hey thanks @agdolla! Honestly I don't have much of a preference, though it would probably be nice to stick as close to the Redux TodoMVC example as possible. There's currently a branch setup with the example, but it's quite a bit behind master so you're welcome to just start over if you're up for it. If not, no worries.

**Comment by agdolla** [comment]
Sent a PR

**Comment by davezuko** [comment]
Thanks so much! Just merged it, and am going to close this issue for now then.
