### ISSUE TITLE
node version>=5.0.0 instead of LTS 4.2.x

### ISSUE THREAD

**Issue by cguedes** [davezuko/react-redux-starter-kit#450]
@davezuko Why do you choose to use (package.json) node version 5 instead of a LTS version?

**Comment by timtyrrell** [comment]
I was wondering the same thing today.

**Comment by davezuko** [comment]
Because it comes with npm3 by default, and I thought it would be weird to require `4.2.x` but enforce npm3.

If that's _not_ weird I'd have absolutely no problem dropping the version to 4.2.x.

**Comment by davezuko** [comment]
I didn't notice that I had the `npm` engine specified, will go update the README/package.json to point to `>=4.2.0`.

**Comment by cguedes** [comment]
Nice, tnks.

**Comment by davezuko** [comment]
https://github.com/davezuko/react-redux-starter-kit/commit/c4a2732d5bf7bda0ad8443b8cfeddcd17a0ad01b should do the trick (don't want to lock it to `4.2.x` because some people do use `^5.0.0`). Thanks for bringing this up, it was a stupid decision on my part.
