### ISSUE TITLE
[question] - how do you define env specific configs like API URLs, API Keys, etc.

### ISSUE THREAD

**Issue by mikedevita** [davezuko/react-redux-starter-kit#451]
as the title states.. I have things like API endpoints, URLs and API Keys that i need to change out depending on the build task and environment..

does anyone have an example of getting this implemented using 0.18 of the kit? I figured two constants files one for each environment and loading them in via the webpack configs.. just not sure though.

**Comment by GerritWanderer** [comment]
Have a look at issue https://github.com/davezuko/react-redux-starter-kit/issues/437, should probably also work with 0.18

**Comment by davezuko** [comment]
ty @GerritWanderer
