### ISSUE TITLE
[question] - You've tried to incorporate a scss linter?

### ISSUE THREAD

**Issue by matias91** [davezuko/react-redux-starter-kit#454]
Hi! Sorry to bother you.

i'm using the same stack on a project.
I've spent a few days trying to add a scss linter without success.
maybe you have tried something or you know something.
i've tried with:
 * sass-lint - sasslint-loader (for webpack).
 * stylelint - stylelint-loader (for webpack).

Thanks in advance!

**Comment by davezuko** [comment]
Personally I just use sass lint independently of webpack (I'm not huge on putting all my eggs in one basket), so unfortunately I don't have any experience integrating their loaders. What issues are you running into in particular?

**Comment by matias91** [comment]
Hi! Sorry for the delay, and thanks for your answer.
I have found that the error is from the "eslint" and not from the "sass-lint".
Sorry for the confusion.

This is the error:

>ERROR in ./src/styles/component/counter.scss
Module parse failed: C:\www\redux-boilerplate\src\styles\component\counter.scss Line 1: Unexpected token .
You may need an appropriate loader to handle this file type.
| .counter{
|     padding-top:30px;
|
 @ ./src/components/counter.js 11:0-43

It occurs when i do "require('../styles/component/counter.scss');" in the components .js files.
Really weird.

Again, sorry to bother you and thanks!

**Comment by vkvelho** [comment]
@matias91 It seems you try to load a CSS module from global styles, but that's explicitly prevented in webpack.config.js:

```
// Don't treat global SCSS as modules
webpackConfig.module.loaders.push({
  test: /\.scss$/,
  exclude: /src/,
  loaders: [
    'style',
    'css?sourceMap',
    'postcss',
    'sass'
  ]
})
```

You probably want to move the counter.scss to the same directory as the component (javascript) and require/import it with using ```('./counter.scss')``` as a path.

Does that make sense?

**Comment by davezuko** [comment]
@matias91 do you have a branch showcasing this example?

**Comment by matias91** [comment]
@davezuko, I could find the problem. I forgot to notify here, sorry!
It was a dumb error. In the **webpack.config.js**  the configuration of the loader was wrong:
> test: /\scss$/

instead of

> test: /\.scss$/

Without the "." it didn't take the "s" into account. So it was testing for css, apparently.
Thanks for your time & help!

**Comment by davezuko** [comment]
Oh wow, well that's easy, it's always the little thing. Glad you fixed it!
