### ISSUE TITLE
Are there any website that use React Redux Starter Kit to build, Whether the source code can be shared ?

### ISSUE THREAD

**Issue by WenXuanYuan** [davezuko/react-redux-starter-kit#463]
I am a fresher in redux and find that use React Redux Starter Kit is a good way to  start, but this example in React Redux Starter Kit is not so clear for me , can you share some more complex to me? thank you!

**Comment by davezuko** [comment]
I have a few projects but none that are currently open sourced :(

**Comment by WenXuanYuan** [comment]
My email address tj1151824@hotmail.com, can you send me one project , I just study .  > . <

**Comment by davezuko** [comment]
@WenXuanYuan I think you'd have better success pinging the gitter channel, as the issues for this repo are normally reserved for bug reports. I don't have anything to offer you right now, but I will be making a point to include example projects in the documentation once we get `2.0.0` out the door.

Link to gitter: https://gitter.im/davezuko/react-redux-starter-kit

Good luck!
