### ISSUE TITLE
Import header component in layout folder or view folder ? 

### ISSUE THREAD

**Issue by WenXuanYuan** [davezuko/react-redux-starter-kit#464]
In my project, my header component will receive props from other components, also in some there are header, in some page not, I think I should have two different layout, one have header, the other not, but when I put header component in layout , I can`t find a perfect way to transmit props to header, how should I do ? I need your help ! thank you !

**Comment by davezuko** [comment]
Hey, can you please take this to the Gitter chat? I'm sure many people there would love to help!

Thank you!
