### ISSUE TITLE
Windows: Hot reloading issues

### ISSUE THREAD

**Issue by koustuvsinha** [davezuko/react-redux-starter-kit#465]
Hi, using this starter kit I cant get to make the Hot reloading work. In console it is displaying `[HMR] connected` but still if I change some piece of code, neither the webpack is getting rebuilt nor any changes are reflected in the browser.

node version 5.4.1

**Comment by vkvelho** [comment]
If I run `npm start` I don't see `[HMR] connected` anywhere. Could you paste the real output you get when you run `npm start`?

For the current `master` I get this:

```
npm start

> react-redux-starter-kit@1.0.0 start /xxxxx
> better-npm-run start

running better-npm-run in /xxxxx
Executing script: start

to be executed: node -r dotenv/config bin/server 
  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +3ms
  app:webpack:config Create configuration. +782ms
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +3ms
  app:server:webpack-dev Enable webpack dev middleware. +131ms
  app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +54ms
  app:bin:server Server is now running at localhost:3000. +7ms
webpack built dfee6659474436fa2e6d in 5470ms
Hash: dfee6659474436fa2e6d
Version: webpack 1.12.9
Time: 5470ms
                             Asset           Size  Chunks             Chunk Names
    vendor.dfee6659474436fa2e6d.js         900 kB       0  [emitted]  vendor
       app.dfee6659474436fa2e6d.js         412 kB       1  [emitted]  app
vendor.dfee6659474436fa2e6d.js.map        1.07 MB       0  [emitted]  vendor
   app.dfee6659474436fa2e6d.js.map         506 kB       1  [emitted]  app
                       favicon.ico  NaN undefined          [emitted]  
                        index.html      549 bytes          [emitted]  
webpack: bundle is now VALID.
```

Now whenever I do some changes to a component that is **NOT** a stateless functional component, the HMR kicks in and the output goes...

```
webpack: bundle is now INVALID.
webpack building...
webpack built d646ba00d41d9159c57a in 1969ms
Hash: d646ba00d41d9159c57a
Version: webpack 1.12.9
Time: 1969ms
                                   Asset           Size  Chunks             Chunk Names
          vendor.d646ba00d41d9159c57a.js         900 kB       0  [emitted]  vendor
             app.d646ba00d41d9159c57a.js         412 kB       1  [emitted]  app
    1.dfee6659474436fa2e6d.hot-update.js        5.64 kB       1  [emitted]  app
    dfee6659474436fa2e6d.hot-update.json       36 bytes          [emitted]  
      vendor.d646ba00d41d9159c57a.js.map        1.07 MB       0  [emitted]  vendor
         app.d646ba00d41d9159c57a.js.map         506 kB       1  [emitted]  app
1.dfee6659474436fa2e6d.hot-update.js.map        3.14 kB       1  [emitted]  app
                             favicon.ico  NaN undefined          [emitted]  
                              index.html      549 bytes          [emitted]  
webpack: bundle is now VALID.
```

For example try to change HomeView.js or HomeView.scss. That should work.

**Comment by koustuvsinha** [comment]
I meant in the browser console. when i run `npm start` i get the same output as you do, but when i change any file the auto build process is not initiating. I think it might not be watching the files for changes at all. Is there any config to add files into the watcher?

**Comment by nhagen** [comment]
I'm also having issues, but I forked about 3 weeks ago. Interested in
hearing more on how to debug this.

**Comment by koustuvsinha** [comment]
I cloned yesterday.

**Comment by divramod** [comment]
its the same for me here.

**Comment by davezuko** [comment]
Will need more information, I can't reproduce this locally at all.

**Comment by vkvelho** [comment]
Ah, sorry! Yeah, this is the output of browser console on change:

```
[HMR] connected
client.js:106 [HMR] bundle rebuilding
client.js:108 [HMR] bundle rebuilt in 530ms
```

Anyways, the problem can't be on the browser side if the server doesn't respond to changes either.

I'm new to Webpack and I don't know the technique behind watching changes. It probably depends on operating system too. A new clone from master works for me on OS X (10.11.2) out of box, so I can't help you much. However, I'd probably start debugging by creating a new "project" in isolated directory, just to test Webpack in watch mode, by following this documentation:

https://webpack.github.io/docs/tutorials/getting-started/

**Comment by divramod** [comment]
```
> $ npm version
{ npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.4.1',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

> $ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"

webpack -h
webpack 1.12.11
```

**Comment by justingreenberg** [comment]
i cannot replicate this locally either, can you update to npm 3.5 clear cache and try again?

```bash
npm i -g npm@3.5.3
npm cache clean
```

**Comment by divramod** [comment]
i was able to solve it now.
had to set up the max_user_watches on ubuntu
here is a link possible other problems: http://stackoverflow.com/questions/26708205/webpack-watch-isnt-compiling-changed-files

**Comment by koustuvsinha** [comment]
@divramod perfect solution, now hot reloading working with watches firing on the server side. :+1: 
@davezuko u might want to put a notice in the readme for this issue. closing it now

**Comment by davezuko** [comment]
Glad you figured it out @divramod.

@koustuvsinha will definitely add this to the FAQ, good idea.

**Comment by markerikson** [comment]
Just did a clone of master, and it doesn't look like edits are causing recompiles.  I'm on Windows 7, so the previous comments don't really help me.  Anyone have any further ideas?

**Comment by markerikson** [comment]
As a follow-up: checked out tag 1.0.1, installed and started it, and both watching and hot-reloading worked immediately.  So, something recent busted things.  This is admittedly a hazard of grabbing master instead of a stable release, but worth noting.

**Comment by davezuko** [comment]
@markerikson that's very strange, I can't think of what would cause this off the top of my head. Could you share your console output from `npm start` when you get a minute?

Reopening so I don't forget about this.

**Comment by markerikson** [comment]
Copying and pasting:

```
> react-redux-starter-kit@1.0.0 start c:\Projects\redux\rr-starter-2
> better-npm-run start

running better-npm-run in c:\Projects\redux\rr-starter-2
Executing script: start

to be executed: node -r dotenv/config bin/server
  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +2ms
  app:webpack:config Create configuration. +1s
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +7ms
  app:server:webpack-dev Enable webpack dev middleware. +301ms
  app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +67ms
  app:bin:server Server is now running at localhost:3000. +99ms
webpack: wait until bundle finished: /__webpack_hmr
webpack built 8f8a435dc0616fa78e35 in 5145ms
Hash: 8f8a435dc0616fa78e35
Version: webpack 1.12.9
Time: 5145ms
                             Asset           Size  Chunks             Chunk Names
    vendor.8f8a435dc0616fa78e35.js         909 kB       0  [emitted]  vendor
       app.8f8a435dc0616fa78e35.js         413 kB       1  [emitted]  app
vendor.8f8a435dc0616fa78e35.js.map        1.09 MB       0  [emitted]  vendor
   app.8f8a435dc0616fa78e35.js.map         509 kB       1  [emitted]  app
                       favicon.ico  NaN undefined          [emitted]
                        index.html      549 bytes          [emitted]

webpack: bundle is now VALID.
```

Page loads, everything runs, but any edits to, say, HomeView.jsx or Root.jsx don't trigger recompiles.

**Comment by davezuko** [comment]
Work week is over so will try to debug this :s, any luck since your last comment?

**Comment by vkvelho** [comment]
The troubleshooting documentation of Webpack tells the reason could relate to the path separator, but I thought this shouldn't be an issue in modern Windows versions. Don't know what's the case with Windows 7.

https://github.com/webpack/docs/wiki/troubleshooting#windows-paths

**Comment by davezuko** [comment]
Only place I see an explicit path separator in the webpack config is here: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L26

Will update this just in case.

**Comment by davezuko** [comment]
There have been a lot of changes since this was originally reported, so going to close for now. If this is still occurring please let me know and I'll reopen and reinvestigate.
