### ISSUE TITLE
Warnings in vendor.[hash].js from Uglify.js

### ISSUE THREAD

**Issue by flipjs** [davezuko/react-redux-starter-kit#468]
Npm run deploy produces these warnings, which start from this:

WARNING in vendor.3a656842b4a8556239e3.js from UglifyJs
Condition always false [./~/fbjs/lib/invariant.js:26,0]
Dropping unreachable code [./~/fbjs/lib/invariant.js:27,0]
Condition always false [./~/fbjs/lib/warning.js:25,0]
Dropping unreachable code [./~/fbjs/lib/warning.js:26,0]
Condition always false [./~/react/lib/ReactMount.js:119,0]
....

The ffc1e42 tree, which is the last merge I did on my project doesnt have these warnings.

Is this Koa-related issues? The app (the build one from dist folder) seems to be working fine though. I tried merging it with my project, and it seems to be ok too. Im just concerned with these warnings when I deploy my project on the server.

Is it safe to ignore these warnings and just go ahead and merge the latest commit to my project?

**Comment by davezuko** [comment]
These are just standard warnings from UglifyJS letting you know that it's removing unused code from the project. You can configure it to suppress these warnings, but they are not anything to worry about.

```js
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
```

**Comment by flipjs** [comment]
Thanks for the quick response!
