### ISSUE TITLE
How to use koa as API

### ISSUE THREAD

**Issue by Hnus-** [davezuko/react-redux-starter-kit#470]
> The Koa server that comes with the starter kit is able to be extended to serve as an API

Please can you show me how? I am using `koa-route` and I would like to know where to put my routes so I can call them from client. I can't get hot-reloading and api to work together only one of them at a time.

Could you demonstrate it on this simple route please?

`app.use(route.get('/api/hello', function *() { this.body = 'hello' }))`

**Comment by davezuko** [comment]
Whipped something up: https://github.com/davezuko/react-redux-starter-kit/tree/demo/koa-api

Does that help at all?

**Comment by Hnus-** [comment]
I haven't expected such a fast response. Amazing! Thank you very much

**Comment by davezuko** [comment]
Awesome, I'll delete the branch in a week, so you have plenty of time to take a look.

**Comment by jackokerman** [comment]
@Hnus- Any chance you have a copy of the branch @davezuko made for you that got deleted? I'm having trouble figuring out how to use koa for an api as well as for the dev server.

**Comment by marr** [comment]
I have an example of that but somewhat stipped down (redux is added in the server-wip) branch but master should show you the webpack middleware + koa approach that i found to work well. Its under marr/webpack-dev on github
