### ISSUE TITLE
Changing asset links from localhost:3000/* to https://localhost/blog/*

### ISSUE THREAD

**Issue by makeitrein** [davezuko/react-redux-starter-kit#482]
Currently setting up a blog for my company based off the 0.18.0 version of this starter kit - things have been going fantastically up until today.

I have a SSL reverse proxy with nginx setup such that any HTTPS requests matching "/blog" will be passed upstream to localhost at port 3000.

Therefore, my goal is to change the base url of all asset links in my application from http://localhost:3000 to https://localhost/blog yet continue to serve my application from http://localhost:3000. 

I've tried changing the compiler_public_path from `http://${config.server_host}:${config.server_port}/` to `https://${config.server_host}/blog` but that was a naive approach - it appears to stop the Express server from serving up my app at port 3000.

I've also created a Webpack plugin that swapped ":3000" with "/blog" in my script tags in index.html after HtmlWebpackPlugin has done its job, but this does not solve the problem of changing the URLs of any assets in my other files.

```
// Hacky index.html <script> tag replacement plugin
const changeScriptLocationPlugin = {
  apply: function (compiler) {
    compiler.plugin('compilation', function (compilation) {
      compilation.plugin('html-webpack-plugin-after-html-processing', function (htmlPluginData, callback) {
        const pattern = `:${config.server_port}`;
        const regex = new RegExp(pattern, 'g');
        htmlPluginData.html = htmlPluginData.html.replace(regex, "/blog");
        callback();
      });
    });
  }
};
```

What's the missing piece to this puzzle? If there's a new addition to the starter kit that handles this situation, I'm happy to incorporate that into my existing code base.

Thx,
Jordan

**Comment by davezuko** [comment]
Hey, been super busy with work so apologies for the delay, will try to look into a solution as soon as I get a chance.

**Comment by makeitrein** [comment]
@davezuko - Thx so much - if there's a solution you think is worth testing, happy to do some grunt work to help solve this one.

**Comment by alexhawkins** [comment]
I did this for my company just last night. In _base.js add  
```
 '__BASENAME__' : JSON.stringify('/blog'),
```
Or if you only want blog in production only do this is production.js config and leave _base.js as is
```
globals: {
    ...config.globals,
   '__BASENAME__' : JSON.stringify('/blog'),
  }
})

```

**Comment by davezuko** [comment]
@makeitrein ^^ does that help at all?

**Comment by makeitrein** [comment]
Hah, it did help out with an unrelated issue, although the real solution was to just serve my app over HTTPS with Express while working locally. Guide I followed was here: http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/

Thx for following up!

**Comment by web2style** [comment]
@davezuko So how can I change assets links in production? @alexhawkins's solution has no effect.

**Comment by makeitrein** [comment]
@web2style 

Does changing the compiler_public_path work for you?

Here's my config/production.js file...

export default (config) => ({
  compiler_fail_on_warning : false,
  compiler_hash_type       : 'chunkhash',
  compiler_inline_manifest : true,
  compiler_source_maps     : false,
  compiler_public_path: `https://company.com/blog/`,
  globals             : {
    ...config.globals,
    __API_URL__: JSON.stringify("https://company.api.com/api/"),
  }
});

**Comment by web2style** [comment]
I get the following console output when I run `set NODE_ENV=production && npm run compile` I'm using windows, so it is a bit different, not `NODE_ENV=production npm run compile`.

```
...
  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "PRODUCTION ". +3ms
  app:config No configuration overrides found for NODE_ENV "PRODUCTION " +2ms
  ...
```

Why doesn't it find any overrides if I change `/config/_production.js`? Even if I make a js error in this file, nothing happens (I assume it should fail in this case).

Any ideas?

**Comment by makeitrein** [comment]
@web2style Hmm... running an OS X environment here, maybe try setting NODE_ENV=production in your .env file?

**Comment by web2style** [comment]
@makeitrein Thank you, it worked out when I set `NODE_ENV=production` manually in `.env` file. So it if for sure another windows-related problem.
