### ISSUE TITLE
Material UI causes staging / production builds to fail

### ISSUE THREAD

**Issue by tyleriguchi** [davezuko/react-redux-starter-kit#484]
Running `npm run compile` with the node environment set to staging or production causes `node -r dotenv/config --harmony bin/compile` to error out. Tested using different versions (4.2.x and 5.5.0) of Node and NPM (v3).  Same as issue #318. Tried versions material ui versions 13 and up.

**Comment by davezuko** [comment]
Closing in favor of https://github.com/davezuko/react-redux-starter-kit/issues/318
