### ISSUE TITLE
Multiple actions in view component

### ISSUE THREAD

**Issue by zsherman** [davezuko/react-redux-starter-kit#491]
Probably just missing something from the documentation, but I'm having issues when attempting to add additional actions to the connect call here https://github.com/davezuko/react-redux-starter-kit/blob/master/src/views/HomeView/HomeView.js#L55.

Previously this was done with `mapDispatchToProps` but that seems to be gone.

**Comment by davezuko** [comment]
It's still using `mapDispatchToProps`, just not as a named function for succinctness. If you wanted to apply additional actions you could try something like this:

```js
const mapDispatchToProps = (dispatch) => ({
  ...bindActionCreators({
    ...counterActions,
    yourCustomAction,
    anotherAction,
  }, dispatch)
})
export default connect(..., mapDispatchToProps)(HomeView)
```

**Comment by zsherman** [comment]
Awesome, thanks @davezuko.
