### ISSUE TITLE
Update redux-simple-router to react-router-redux

### ISSUE THREAD

**Issue by juanda99** [davezuko/react-redux-starter-kit#493]
I've updated dependency to     
"react-router-redux": "^2.1.0"

However after changing module imports, I got an error the first time I execute the actions (increment or double async).
Can't find the error :-(

**Comment by davezuko** [comment]
Yeah I'm getting a bug on page load:

`Uncaught TypeError: Cannot read property 'substring' of undefined`

Is that what you're seeing?

**Comment by juanda99** [comment]
yes

**Comment by juanda99** [comment]
Can't fix the error, that's what I meant :-(

**Comment by davezuko** [comment]
Yeah, I know, just wanted to make sure we were having the same error.

PR out at https://github.com/davezuko/react-redux-starter-kit/pull/494, but waiting to figure out this bug first... digging through redux-simple-router and history right now.

**Comment by davezuko** [comment]
Tracking https://github.com/rackt/react-router-redux/issues/237 in case it's related

**Comment by davezuko** [comment]
Figured it out, merged here: https://github.com/davezuko/react-redux-starter-kit/commit/53e7f466662d67c5d9c4b51095d41b68fe619672
