### ISSUE TITLE
Does hot-reloading mean browser reload?

### ISSUE THREAD

**Issue by LarryEitel** [davezuko/react-redux-starter-kit#50]
I have been cutting my teeth on a variety of reactjs examples. I have successfully installed and can run this project on Windows! :) However when I update the line `Welcome to the React Redux Starter Kit!` and save the file. Console shows module reloaded however, I have to reload the page to see the change. Is this normal? I have seen other projects where the change refreshed without reloading the page.

**Comment by davezuko** [comment]
So it's actually an interesting scenario that you've encountered, and it may be a bit counterintuitive at first. The starter kit _does_ work with hot-reloading (views, stores, styles, etc.), however that line "Welcome to the React Redux Starter Kit" is simply the initial state of a reducer. So when you update the reducer file, the reducer function that gets hot reloaded but the state within the app doesn't reset (and therefore doesn't reload the initial state).

If you wanted to check out hot reloading, you could go to home view and edit something in the render function. For example, change:

```
<h1 className='text-center'>
  {this.props.sampleStore.message}
</h1>
```

to

```
<h1 className='text-center'>
  {this.props.sampleStore.message} TEST
</h1>
```

And you should see the view get hot reloaded. The only reason I put the message in the store was to demonstrate connecting to the store, but I'm now realizing that it's somewhat unclear. Also, I'm not sure if you're using the latest version of the starter kit, but if you are, you'll notice the sample reducer has a handler:

```
  [SAMPLE_ACTION] : (state, payload) => {
    console.log('sample action received.'); // eslint-disable-line

    // noop
    return state;
  }
```

So, to demonstrate the hot reloading of a reducer, you could change what occurs in that console.log statement, save the file, and the next time the action occurs the handler will be updated.

Hopefully that clears things up, if not just let me know.

**Comment by gaearon** [comment]
>So it's actually an interesting scenario that you've encountered, and it may be a bit counterintuitive at first. The starter kit does work with hot-reloading (views, stores, styles, etc.), however that line "Welcome to the React Redux Starter Kit" is simply the initial state of a reducer. So when you update the reducer file, the reducer function gets hot reloaded but the state within the app doesn't reset (and therefore doesn't reload the initial state, which is what you modified).

The initial state should be re-evaluated with Redux DevTools enabled.

**Comment by davezuko** [comment]
@gaearon Interesting, didn't know that. Thanks.

**Comment by davezuko** [comment]
@LarryEitel In case you were using the very latest of the starter kit, I accidentally removed react-hot-loader with a recent refactor... it doesn't sound like this affected you, but it's fixed now just in case.

**Comment by LarryEitel** [comment]
Yes, it **was** the latest. Thank you for explaining the behavior. :)
