### ISSUE TITLE
Very slow server requests (development)

### ISSUE THREAD

**Issue by madshargreave** [davezuko/react-redux-starter-kit#502]
Hi

I have a local instance of my APi running on port 8080, but for some reason my webpack devserver sends network requests very slowly.

A small JSON requests takes 5+ seconds (as reported by chrome devtools) to send.

My webpack configuration is the defaults.
I use Axios as my network lib

**Comment by davezuko** [comment]
Sorry this got buried, are you still experiencing this?

**Comment by davezuko** [comment]
Closing until more details are provided. If this is still a problem I'd _love_ to help get it resolved, but I haven't had much luck reproducing it.
