### ISSUE TITLE
Can't get function this.props.dispatch

### ISSUE THREAD

**Issue by chenfanggm** [davezuko/react-redux-starter-kit#505]
Hi Dave,
This a so excellent start-kit, you help me work through a way to learn redux.
I encountered a problem that might be silly, is I don't get dispatch function from the this.props within a connected components. Thank you in advance.

Example (this.props.dispatch) is undefined:
```
export class HomeView extends React.Component {
  static propTypes = {
  };

  render () {
    console.log(this.props.dispatch)
    return (
      <div>
      </div>
    )
  }
}
export default connect(mapStateToProps, counterActions)(HomeView)
```

I also tried this:
```
const mapDispatchToProps = (dispatch) => bindActionCreators({
  ...authActions,
  ...sidebarActions
}, dispatch)

export default connect(mapStateToProps, mapDispatchToProps)(AuthRequiredWrapper);
```

**Comment by davezuko** [comment]
If you provide a `mapDispatchToProps`, `dispatch` is not automatically included as a prop. You'll need to update your code snippet to:

```js
const mapDispatchToProps = (dispatch) => bindActionCreators({
  dispatch,
  ...authActions,
  ...sidebarActions
}, dispatch)

export default connect(mapStateToProps, mapDispatchToProps)(AuthRequiredWrapper);
```

That should do the trick. A bit curious why you need `this.props.dispatch` if you're binding all your action creators already though?

**Comment by chenfanggm** [comment]
You are awesome! Thank you.
I have the same question as your last one. The following is what I want to achieve.
You could see it uses 3 actions: authActions.isLoggedIn(), sidebarActions.showSidebar(), and route to Login View by "routeActions.push" which need that dispatch. Should I wrap the "routeActions.push" to redux module as others? Thanks, again.

```
componentWillMount() {
    if (this.props.isLoggedIn()) {
      this.props.showSidebar()
      let redirectAfterLogin = this.props.location.pathname;
      dispatch(routeActions.push(`/login`));
    }
  }
```

**Comment by davezuko** [comment]
You could wrap them just like the others yes. However, if you're using react-router-redux (formerly redux-simple-router), you can just use the regular history API without having to dispatch any actions at all.

Closing this since the original question has been answered, but we can keep the discussion going despite that if you'd like.
