### ISSUE TITLE
Creating a global css entrypoint

### ISSUE THREAD

**Issue by tarjei** [davezuko/react-redux-starter-kit#506]
Hi, thanks for a great starter kit!

Anyhow, I'm struggling with css. Or to be more precise, I'm trying to get away from the the bootstrap loading file that the kit has and to defining an entrypoint that is the main scss file and getting that into the build so that I can use that to build the local css that we got (basically Foundation 6 + modifications).

T

**Comment by neverfox** [comment]
What's issues have you had just removing the bootstrap tag and importing Foundation in to core.scss? Foundation has [an npm package](https://github.com/blai/foundation).

**Comment by tarjei** [comment]
The foundation package you linked to is 2 versions old :)

I solved it by changing the bottom of webpack.config.js from
```js
if (!__DEV__) {
  debug('Apply ExtractTextPlugin to CSS loaders.')
  webpackConfig.module.loaders.filter(loader =>
    loader.loaders && loader.loaders.find(name =>
/css/.test(name.split('?')[0]))
  ).forEach(loader => {
    const [first, ...rest] = loader.loaders
    loader.loader = ExtractTextPlugin.extract(first, rest.join('!'))
    delete loader.loaders
  })

  webpackConfig.plugins.push(
    new ExtractTextPlugin('[name].[contenthash].css', {
      allChunks: true
    })
  )
}

```
to
```
if (!__DEV__) {
  debug('Apply ExtractTextPlugin to CSS loaders.')
  webpackConfig.module.loaders.filter(loader =>
    loader.loaders && loader.loaders.find(name =>
/css/.test(name.split('?')[0]))
  ).forEach(loader => {
    const [first, ...rest] = loader.loaders
    loader.loader = ExtractTextPlugin.extract(first, rest.join('!'))
    delete loader.loaders
  })

  webpackConfig.plugins.push(
    new ExtractTextPlugin('[name].[contenthash].css', {
      allChunks: true
    })
  )
} else {
  debug('Apply ExtractTextPlugin to CSS loaders.')
  webpackConfig.module.loaders.filter(loader =>
    loader.loaders && loader.loaders.find(name =>
/css/.test(name.split('?')[0]))
  ).forEach(loader => {
    const [first, ...rest] = loader.loaders
    loader.loader = ExtractTextPlugin.extract(first, rest.join('!'))
    delete loader.loaders
  })
  webpackConfig.plugins.push(
    new ExtractTextPlugin('[name].[contenthash].css', {
      allChunks: true
    })
  )
}

```
This works in dev mode, but I still need to figure out how to handle
hotloading of extra resources.

;)
T

2016-01-30 19:51 GMT+01:00 Roman Pearah <notifications@github.com>:

> What's issues have you had just removing the bootstrap tag and importing
> Foundation in to core.scss? Foundation has an npm package
> <https://github.com/blai/foundation>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davezuko/react-redux-starter-kit/issues/506#issuecomment-177274963>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by neverfox** [comment]
My bad. Clearly I don't use Foundation, however you're solution stills strikes me as unnecessary. It's hard for me to imagine that Foundation, even in it's latest incarnation, doesn't work like any other npm-based CSS framework.

Is [this](https://github.com/zurb/foundation-sites) it? If so, I still don't see why you cannot simply import (as global CSS) the foundation-sites.scss file from the scss folder and call it a day. Did you try that?

**Comment by davezuko** [comment]
@tarjei I see you mentioned that this is solved except for the HMR-related piece, should I keep this open?

**Comment by tarjei** [comment]
@davezuko I'm sorry for not getting back to you faster I've been ill.

Yes, this can be closed.
