### ISSUE TITLE
Issues accessing deployed app

### ISSUE THREAD

**Issue by IljaDaderko** [davezuko/react-redux-starter-kit#508]
I was trying to deploy my app today, generated dist folder without any issues however once accessing index.html error I get following error in the console.

> Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///mypath/index.html' cannot be created in a document with origin 'null'.

**Comment by marr** [comment]
Ilja, you have to access the app via `http(s)` so you could use something like `node-static` to run a server to test it locally. I had an index.html file in my root and serve it like so:

```
var static = require('node-static');

var fileServer = new static.Server('.');
require('http').createServer(function (request, response) {
  request.addListener('end', function () {
    fileServer.serve(request, response, function (e, res) {
      if (e && (e.status === 404)) { // If the file wasn't found
        fileServer.serveFile('index.html', 200, {}, request, response);
      }
    })
  }).resume();
}).listen(8080);
```
