### ISSUE TITLE
Add persist state option 

### ISSUE THREAD

**Issue by tnrich** [davezuko/react-redux-starter-kit#509]
Hey there @davezuko,

Awesome boilerplate, many thanks!

I was going to suggest that you also include the persist state functionality that comes with redux-devtools. I find this to be one of the best addons to redux, and think that users should at least have the option to use it. 

Here's what my `configureStore.js` looks like with it it place. 

```
import { persistState } from 'redux-devtools';

function getDebugSessionKey() {
  // You can write custom logic here!
  // By default we try to read the key from ?debug_session=<key> in the address bar
  const matches = window.location.href.match(/[?&]debug_session=([^&]+)\b/);
  return (matches && matches.length > 0) ? matches[1] : null;
}

function withDevTools (middleware) {
  const devTools = window.devToolsExtension
    ? window.devToolsExtension()
    : require('containers/DevTools').default.instrument()
  return compose(middleware, devTools, persistState(getDebugSessionKey()))
}
```

Also, I just found this boilerplate, so maybe I am missing something. If so, please let me know. 

Cheers,
Thomas

**Comment by davezuko** [comment]
I'll give it a shot, thanks for the recommendation. Sorry for the slow reply.

**Comment by davezuko** [comment]
Slowly formalizing `2.0.0` milestone, moved this to topics for consideration: https://github.com/davezuko/react-redux-starter-kit/wiki/v2.0.0-Plans. Will create a new issue when it's a confirmed feature (just trying to parse through the issues right now and filter it out to problematic issues while keeping recommendations/requests in another doc).

I realize this should be fairly trivial, just haven't had time to get to it unfortunately.
