### ISSUE TITLE
Import sass in a component

### ISSUE THREAD

**Issue by OKNoah** [davezuko/react-redux-starter-kit#512]
Am I still able to do 

    import './homeview-style.scss'

in a component and have it load? This seemed to work in an older version.

**Comment by chenfanggm** [comment]
I use it like this:
```
import classes from './Blog.scss'
<h3 className={classes.subTitle}>
  Architecture
</h3>
```

**Comment by davezuko** [comment]
^^ exactly, or you can just disable css_modules and import as you would previously.

https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L125

**Comment by davezuko** [comment]
Closing for now since this should be working per the above comments, please let me know if it's not for whatever reason.

**Comment by kamalbennani** [comment]
how can i disable css_modules

**Comment by dfalling** [comment]
@kamalbennani  https://github.com/davezuko/react-redux-starter-kit/#configuration
`  compiler_css_modules     : false,`
