### ISSUE TITLE
Dispatch from onEnter route

### ISSUE THREAD

**Issue by 5h1rU** [davezuko/react-redux-starter-kit#515]
I'm trying to dispatch an action when the route change but I can't figure out what's the correct way.

the idea is trigger an action when the route change, but the `<Provider>` is placed inside `Root.js` and has the store like a property. 

My idea is use something like

`<Route path='/foo' component={Foo} onEnter={method(store)}/>` from ```routes/index.js```

How can I get access to the store from this point?
Any ideas?

Thanks

**Comment by marr** [comment]
There was a gist posted the other day that may be useful https://gist.github.com/EmperorEarth/474373cb16b006fc8fbc I am not sure if its working or best practice but it may unblock you for now.

**Comment by gaearon** [comment]
Yes, `createRoutes(store)` is how we recommend to get store into your routes. No magic!

**Comment by marr** [comment]
Dan I was just trying to achieve this using a closure around the store object but store is unavailable in my `debugger` point here https://gist.github.com/marr/a63f4ada9239610fd0be. Is that not the intended method to use?

**Comment by marr** [comment]
if I replace that `debugger` with `this.store = store` it does keep a reference to the `store` variable passed in to the wrapping function. I guess I need to brush up on Functional programming stuff!

**Comment by 5h1rU** [comment]
solved

`routes/index.js`
```js
export default (store) => {
  return (
    <Route path='/' component={CoreLayout}>
      <IndexRoute component={HomeView} />
      <Route path='/login' component={Login} onEnter={method(store)} />
    </Route>
  );
};
```

`Root.js`
```js
  get content () {
    return (
      <Router history={this.props.history}>
        {this.props.routes(this.props.store)}
      </Router>
    );
  }
```

Thanks for help @gaearon @marr

**Comment by marr** [comment]
@gaearon Any idea why this dispatch might not be working? https://github.com/marr/console/blob/master/app/app.js#L40

I am running the app from a browserify build with `node-static` and I see the URL in the browser change, but the page itself doesn't change to reflect the new route.

When I console.log out store.getState and the nextState argument in the onEnter handler I see a difference in the keys of the state object:

store.getState: Object {routing: Object, home: Object, user: Object}
nextState: Object {routes: Array[2], params: Object, location: Object}

**Comment by gaearon** [comment]
It's best to ask in a for related to react-router-redux. For example, on Discord.

**Comment by leeir** [comment]
@5h1rU  I have the same issue but According to your method 
`TypeError: this.props.routes is not a function`

What else do you need to change?

**Comment by haydencarlson** [comment]
@leeir You need to import the routes file.

```
export default (store) => {
  return (
    <Route path='/' component={CoreLayout}>
      <IndexRoute component={HomeView} />
      <Route path='/login' component={Login} onEnter={method(store)} />
    </Route>
  );
};
```

This ^^

And from there you pass in the store from your root component.
