### ISSUE TITLE
Enabling proxy in _development.js causes dependency error

### ISSUE THREAD

**Issue by davecapper** [davezuko/react-redux-starter-kit#516]
D:\React\react-redux-starter-kit-master>npm start

> react-redux-starter-kit@1.0.0 start D:\React\react-redux-starter-kit-master
> better-npm-run start

running better-npm-run in D:\React\react-redux-starter-kit-master
Executing script: start

to be executed: node -r dotenv/config bin/server
  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +3ms
  app:webpack:config Create configuration. +2s
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +2ms
module.js:341
    throw err;
    ^

Error: Cannot find module 'co-request'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (webpack-proxy.js:8:15)
    at Module._compile (module.js:413:34)
    at loader (D:\React\react-redux-starter-kit-master\node_modules\babel-regist
er\lib\node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\React\react-r
edux-starter-kit-master\node_modules\babel-register\lib\node.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (main.js:32:21)
    at Module._compile (module.js:413:34)
    at loader (D:\React\react-redux-starter-kit-master\node_modules\babel-regist
er\lib\node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\React\react-r
edux-starter-kit-master\node_modules\babel-register\lib\node.js:140:7)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\davidc\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@1.0.0 start: `better-npm-run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@1.0.0 start script 'better-npm-ru
n start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-k
it package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

**Adding co-request as per the following fixes the issue:**

D:\React\react-redux-starter-kit-master>npm i co-request --save
react-redux-starter-kit@1.0.0 D:\React\react-redux-starter-kit-master
└── co-request@1.0.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.6

D:\React\react-redux-starter-kit-master>npm start

> react-redux-starter-kit@1.0.0 start D:\React\react-redux-starter-kit-master
> better-npm-run start

running better-npm-run in D:\React\react-redux-starter-kit-master
Executing script: start

to be executed: node -r dotenv/config bin/server
  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +3ms
  app:webpack:config Create configuration. +2s
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +2ms
  app:server:webpack-dev Enable webpack dev middleware. +463ms
  app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +29ms
  app:bin:server Server is now running at localhost:3000. +6ms
webpack built c971eb11977343516f17 in 4110ms
Hash: c971eb11977343516f17
Version: webpack 1.12.9
Time: 4110ms
                             Asset       Size  Chunks             Chunk Names
       app.c971eb11977343516f17.js     414 kB       0  [emitted]  app
    vendor.c971eb11977343516f17.js     911 kB       1  [emitted]  vendor
   app.c971eb11977343516f17.js.map     510 kB       0  [emitted]  app
vendor.c971eb11977343516f17.js.map    1.09 MB       1  [emitted]  vendor
                       favicon.ico    24.8 kB          [emitted]
                        index.html  527 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  444 kB       0
webpack: bundle is now VALID.

**Comment by davecapper** [comment]
It looks like co-request needs to be a specific version (e.g. 0.2.0) otherwise it throws an error about requestThunk not being a function.

**Comment by davezuko** [comment]
Argh, ok, will investigate.

**Comment by davezuko** [comment]
`co-request` wasn't being installed for some reason, I've added it as part of this PR: https://github.com/davezuko/react-redux-starter-kit/pull/529
