### ISSUE TITLE
Why not cleaning the dist folder before running complie

### ISSUE THREAD

**Issue by web2style** [davezuko/react-redux-starter-kit#523]
Every time I run `NODE_ENV=production npm run compile`, new .js and .css files are created in the dist folder. The old ones remain there and are not deleted. Why not adding a `clean` process into the very beginning of `compile`?

**Comment by blurrd** [comment]
Use `npm run deploy` instead.
That means npm run clean && npm run compile together.

**Comment by davezuko** [comment]
Exactly what @blurrd said, hope that helps. Keeping compile separate allows a little bit more flexibility in the deployment process should people choose to mess with it.

**Comment by web2style** [comment]
Oh, thanks for the explanation. Would be reasonable to mention it in the readme.

**Comment by davezuko** [comment]
Fair enough; I'm about to head out for the weekend but will add it to my todo list for next week :)
