### ISSUE TITLE
App fails to load fonts in production

### ISSUE THREAD

**Issue by madshargreave** [davezuko/react-redux-starter-kit#525]
Hi

Once I deploy to production, I get the following errors while trying to use Font-Awesome

```
Failed to decode downloaded font: https://....herokuapp.com/css/staticnode_modules/font-awesome/fonts/fontawesome-webfont.woff2
dashboard:1 OTS parsing error: invalid version tag
```

I just installed FA using NPM and import it in my ```_base.scss``` file

```
@import '~font-awesome/css/font-awesome.css';
```

I noticed that a 

```
/node_modules/font-awesome/fonts
```

Folder get's created in my `dist` folder, is this the intended behavior?

**Comment by davezuko** [comment]
Shouldn't be, will look into it.

**Comment by davezuko** [comment]
@madshargreave so I just installed font-awesome and imported it in `_base.scss`:

```scss
/*
Application Settings Go Here
------------------------------------
This file acts as a bundler for all variables/mixins/themes, so they
can easily be swapped out without `core.scss` ever having to know.

For example:

@import './variables/colors'
@import './variables/components'
@import './themes/default'
*/
$fa-font-path: "~/font-awesome/fonts";
@import '~font-awesome/scss/font-awesome';
```

And it correctly compiled into `dist`. I can't get it working with CSS modules, since I'm guessing the icon names are being distorted, but it works perfectly with CSS modules disabled. I will keep playing around with it to try to get it working with them in enabled...

**Comment by davezuko** [comment]
Never mind, ignore my previous comment... it _was_ working until I added the correct font path (meaning it was never working, hah).

**Comment by davezuko** [comment]
This has _not_ been fixed, but there is an ongoing discussion about improving how fonts/assets for styles are handled, so closing this to keep the discussion in one place.

See: https://github.com/davezuko/react-redux-starter-kit/issues/621
