### ISSUE TITLE
Integrating a vendor js library (Material Design Lite)

### ISSUE THREAD

**Issue by rpnna** [davezuko/react-redux-starter-kit#528]
What is the most efficient way to integrate a vendor js into the project ?
In my case, i have to work with Material Design Lite js.
I temporarily put the script tag before body end in index.html, but maybe Webpack should take care of injecting the code in a vendor bundle file.

`<body>
  <div id="root" style="height: 100%"></div>
  <script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
</body>
</html>`

Thanks

**Comment by thangngoc89** [comment]
If you are working on a React project, you should use the react wrapper of MDL https://github.com/tleunen/react-mdl

Btw, webpack is a bundle tool, so adding a script tag to html is not its job

**Comment by rpnna** [comment]
ok, thanks for the link. Btw, I'm working on this React-Redux starter kit.
Yes, I know the usage of Webpack..I'm not interested in putting a script tag in html `<body>`.
I want to set a new entry vendor in Webpack config that is managed and compiled in a existent/new output vendor js file.

**Comment by thangngoc89** [comment]
You can install it via npm or bower (if available) and import that file to app's entry point. Webpack will bundle everything for you

**Comment by rpnna** [comment]
Ok, this sounds good. Maybe Bower is the perfect choice to manage vendor libs.
I'll make a try.

**Comment by rpnna** [comment]
Ok I've installed MDLite via npm, then:

1. Removed the `<script>` tag from the body in index.html
2. Added 'material-design-lite' to the list of vendors in config/_base.js
`compiler_vendor : [
    ... ,
    ... ,
    'material-design-lite'
  ]`

This way, the MDLite javascript is bundled into the vendor.js output as desired.

**Comment by davezuko** [comment]
Thanks for the help @thangngoc89 , I'll make sure to add this to the "recipes" section once that becomes a thing.
