### ISSUE TITLE
BrowserSync feature request

### ISSUE THREAD

**Issue by vvatikiotis** [davezuko/react-redux-starter-kit#536]
Are there any plans to include a Browser Sync script option. What's the best way to go about adding such a feature?

**Comment by davezuko** [comment]
It's been brought up before and I brushed it off to keep the repo trim, but I'll look into it so we can at least get some sort of recipe if it isn't outright implemented.

**Comment by christiansakai** [comment]
@vvatikiotis @davezuko here is the recipe for that https://github.com/Browsersync/recipes/tree/master/recipes/webpack.react-transform-hmr

**Comment by davezuko** [comment]
@christiansakai thanks so much for the link. Looking at it I think it makes sense to keep it out of the starter kit but add it to the FAQ until a recipes doc is created.

**Comment by christiansakai** [comment]
@davezuko seems like it! would love to see a recipe doc for that!

**Comment by davezuko** [comment]
Added to https://github.com/davezuko/react-redux-starter-kit/wiki/Recipes. Once I migrate all other issues with recipes over to this page and clean up the formatting I will drop it in the readme.
