### ISSUE TITLE
Cannot read property 'instrument' of undefined

### ISSUE THREAD

**Issue by nudelx** [davezuko/react-redux-starter-kit#539]
function withDevTools (middleware) {
  const devTools = window.devToolsExtension
    ? window.devToolsExtension()
    : require('containers/DevTools').default.instrument() -> error 
  return compose(middleware, devTools)
}

Uncaught TypeError: Cannot read property 'instrument' of undefined

**Comment by davezuko** [comment]
There was a breaking change in a dependency that has since been fixed in master. I'd recommend pulling the latest master and running `npm update`, or looking at https://github.com/davezuko/react-redux-starter-kit/pull/529 if you wish to apply the fixes yourself.

**Comment by davezuko** [comment]
Closing since this should be fixed, please let me know if you're still having issues.
