### ISSUE TITLE
Remove cssnano dependency

### ISSUE THREAD

**Issue by hamczu** [davezuko/react-redux-starter-kit#543]
Correct me if I'm wrong, but css-loader documentation states that minification by cssnano is already implemented there:
https://github.com/webpack/css-loader#minification

and it's easy to confirm by checking package.json.

In this starter-kit we declare cssnano dependency as well and we apply that transformation explicitly. So in fact we end up with the same dependency installed twice (once as this project dependency, and second as css-loader dep), and I suspect that every css file is processed twice.

When I removed cssnano dependency from the project, css output is still minified. So I think we can remove that dependency and rely on css-loader processing.

**Comment by davezuko** [comment]
Never knew, looks like you're totally right. Will finish reading the docs and submit a fix later today/tomorrow. Thanks!

**Comment by kid** [comment]
It also causes with the `@value` from css-modules, see css-modules/css-modules#104

**Comment by davezuko** [comment]
Would it be easier to configure css-loader to _not_ use cssnano and instead explicitly configure it in the app, or drop it entirely from the app and require users to configure css-loader? Thinking about https://github.com/davezuko/react-redux-starter-kit/issues/547

**Comment by hamczu** [comment]
@davezuko I think it's to have cssnano here, because it makes this project almost production-ready and this is how I see different approaches:
1. current (cssnano in both project and css-loader)
- double process of files
- just wrong

2. disabled cssnano in css-loader and cssnano dependency in this project
- cssnano dependency is defined twice
+ nicer (not query) config

3. remove cssnano from that project and rely on css-loader
+ only one cssnano dependency
- we need to translate current config to "query" format accepted by css-loader

**Comment by davezuko** [comment]
:+1: @hamczu great points. I will keep cssnano because npm3 should (hopefully) prevent duplicates from being installed, and then we get the nicety of more explicit/easy configuration.

**Comment by hamczu** [comment]
Can't we have both? Nice options object and remove that dependency in the same time? If format of options is important, maybe we can translate options object to query somehow?

Or, even better - according to the webpack docs: https://webpack.github.io/docs/using-loaders.html#query-parameters
"Most loaders accept parameters in the normal query format (...) and as JSON object", so maybe we can just pass that cssnano config object directly to css-loader? I need to try it out.

I would recommend against keeping cssnano dependency here because:
- every dependency needs to be updated and kept in sync, so fewer is better
- versions of that dependency could be different here and in css-loader which can lead to different config syntax etc.
- users familiar with css-loader would expect to have cssnano there and use that implementation

but as I said, I'm new to that project, so it's your decision

**Comment by davezuko** [comment]
I believe you can only use the query object with a single loader, not in an array of loaders like we have with scss, css, postcss. I'd argue that css-loader should _not_ in fact have this dependency, as it's not at all its concern. To me it feels more maintainable to keep css nano usage explicit since:

1) it keeps it separate from CSS loader, we are no longer depending on a loader doing more than it needs to.
2) it's easier to configure since our options don't have to get passed through another loader and properly translated. We can just look at the docs for cssnano and apply the settings ourselves.
3) users on npm3 probably won't even get duplicate dependencies installed. If they do, oh well, but it's not like node_modules are ever not wasteful.
4) translating an object to its query string representation is possible, but roundabout and unintuitive when you could just pass that object directly to the loader (again, if it was the only loader, a la `babel` for JS).

**Comment by hamczu** [comment]
I see your point here - I will make a PR with disabled minification in css-loader then, to have only one minification processor. 

Now I'm struggling to disable css minifacation completely - I disabled cssnano locally, I passed "-minimize" option to css-loader and the CSS is still minified, I am impressed!

**Comment by danwad** [comment]
This just tripped me up the same as #547 and prevented my fonts from being output to dist.

As a beginner of webpack, the trickiest part in figuring out why my fonts were not being output was realising that enabling UglifyJsPlugin causes my CSS to be minified by cssnano. I think this is quite unexpected.

I turned this off by using the `-minimize` query parameter with css-loader and then letting the postcss/cssnano config do its thing - `@font-face` rules are preserved and fonts are placed in dist. 

Could anyone shed any light exactly on why my font-faces are omitted when I let UglifyJsPlugin enable css-loader minification with cssnano? I even edited [this file](https://github.com/webpack/css-loader/blob/master/lib/processCss.js#L179) to use the exact same options as given in webpack.config.js to postcss/cssnano and still font-faces were removed. Explicitly setting `discardUnused: false` didn't help.

In fact, I am having the same issue as @hamczu - I have commented out the cssnano bit from `webpackConfig.postcss` and still the CSS is minified :confused: 

Which part of the pipeline is minifying CSS?

**Comment by davezuko** [comment]
Disabled minimization w/ css-loader via https://github.com/davezuko/react-redux-starter-kit/commit/b0b5e7177ecb34032801557ff857e07b10d79da9.

**Comment by davezuko** [comment]
Though the issue @danwad is still occurring, so keeping this open for the time being...

**Comment by davezuko** [comment]
Will be re-opening a new issue to deal with the minimization mentioned by @danwad, decided to close this just for ease of tracking.
