### ISSUE TITLE
@font-face is being removed by cssnano

### ISSUE THREAD

**Issue by renanvalentin** [davezuko/react-redux-starter-kit#547]
Hey guys!

I was unable to make @font-face working on my projects, it seems cssnano options is not being called on postcss-loader.

```javascript
webpackConfig.postcss = function () {
  return [
    cssnano({
      sourcemap: true,
      autoprefixer: {
        add: true,
        remove: true,
        browsers: ['last 2 versions']
      },
      safe: true,
      discardComments: {
        removeAll: false
      },
      discardUnused: false
    })
  ];
};
```

I tried to use @discardUnused options, but still fail :/

Thanks!

**Comment by hamczu** [comment]
Please check #543 - this configuration is in fact never used. Probably cssnano built into css-loader is creating the issue you have.

**Comment by renanvalentin** [comment]
@hamczu indeed! 

I was able to make it work by disabling cssnano from css-loader passing the flag -minimize.
```javascript
const cssLoader = !config.compiler_css_modules
  ? 'css?sourceMap&-minimize'
  : [
    'css?modules&-minimize',
    'sourceMap',
    'importLoaders=1',
    'localIdentName=' + (__DEV__ ? '[name]__[local]___[hash:base64:5]' : '[hash:base64:5]')
  ].join('&');
```

**Comment by davezuko** [comment]
Awesome, moving further discussion of this to https://github.com/davezuko/react-redux-starter-kit/issues/543
