### ISSUE TITLE
routerActions.push() not change routes after upgrade to 4.0.0-beta

### ISSUE THREAD

**Issue by chenfanggm** [davezuko/react-redux-starter-kit#552]
After upgrading to 4.0.0-beta by 0df26907dce6b2cf52f4f3d63fdce092188de139
dispatch(routerActions.push('/')) not functioning.
From redux state change, I could see a CALL_HISTORY_METHED action with type PUSH has been performed, but not affecting the route state.
Anyone has the same issue?

**Comment by davezuko** [comment]
You have to enable the middleware, it's fairly easy: https://github.com/reactjs/react-router-redux/tree/synchronicity#what-if-i-want-to-issue-navigation-events-via-redux-actions

I will update master to include the middleware later tonight.

**Comment by chenfanggm** [comment]
Thanks @davezuko

**Comment by Hnus-** [comment]
I am really confused about how I should go about route navigation. In components I use `this.context.router.push('/somewhere')` because it is the only thing that works for me. But how it is done outside of my components is still mystery to me. In current available version I can now use `dispatch(routerActions.push('/'))` which was not possible before? Or is there still a better way how to do navigation?

**Comment by gaearon** [comment]
In components, use `context.router`.

Outside you have some choices. Usually you can just `import { browserHistory } from 'react-router'` and call `browserHistory.push()` directly. This is the easiest way. However you might want to avoid using history singleton, for example, if you are fetching data while rendering on the server. In this case you can indeed dispatch those actions provided by the library. Only if you want those actions, you will need to include the middleware. The only thing it does is converting those actions into the underlying history API calls. 

There is no magic there. Read the source. It’s quite straightforward in 4.x, especially the part with actions and middleware. 4.x also does not require you to use actions and middleware: in most cases it is much more convenient to use singleton histories offered by React Router 2.0.

**Comment by Hnus-** [comment]
Thank you @gaearon for quick answer. Ill read the source and then it hopefully be more clearer.
