### ISSUE TITLE
Should I expect webpack-proxy to work?

### ISSUE THREAD

**Issue by tarjei** [davezuko/react-redux-starter-kit#558]
Hi, I tried to get the functionality in  server/middleware/webpack-proxy.js to work, but it seems I'm missing something. It explodes with the following stacktrace:

  TypeError: requestThunk is not a function
      at Object.<anonymous> (webpack-proxy.js:113:19)
      at /home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:137:8
      at new Promise (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/core-js/modules/es6.promise.js:197:7)
      at Object.thunkToPromise (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:135:10)
      at Object.toPromise (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:119:55)
      at next (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:99:29)
      at onFulfilled (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:69:7)
      at /home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:54:5
      at new Promise (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/core-js/modules/es6.promise.js:197:7)
      at Object.co (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:50:10)
      at converted (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/koa-convert/index.js:17:15)
      at dispatch (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/koa-compose/index.js:41:32)
      at next (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/koa-compose/index.js:42:18)
      at createGenerator (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/koa-convert/index.js:24:16)
      at [object Generator].next (native)
      at onFulfilled (/home/tarjei/htdocs/frisvold/fistup/ask/node_modules/co/index.js:65:19)

**Comment by chenfanggm** [comment]
I had the same issue, and switched to use Koa-proxy

**Comment by davezuko** [comment]
To be honest I haven't tested it in a while, it was a PR for a use case that I don't commonly use, and without tests I've only really been hoping that it does work. If you have a better alternative I'd love a PR; if not I'll look at fixing it/switching.

**Comment by tarjei** [comment]
Based on https://github.com/koajs/koa/issues/198 I ended up with this:

```javascript server/main.js

import Koa from 'koa'
import convert from 'koa-convert'
import webpack from 'webpack'
import webpackConfig from '../build/webpack.config'
import historyApiFallback from 'koa-connect-history-api-fallback'
import serve from 'koa-static'
import _debug from 'debug'
import config from '../config'
import webpackProxyMiddleware from './middleware/webpack-proxy'
import webpackDevMiddleware from './middleware/webpack-dev'
import webpackHMRMiddleware from './middleware/webpack-hmr'

import httpProxy from 'http-proxy'
import http from 'http'
import url from 'url'

let proxy = null

const debug = _debug('app:server')
const paths = config.utils_paths
const app = new Koa()

// This rewrites all routes requests to the root /index.html file
// (ignoring file requests). If you want to implement isomorphic
// rendering, you'll want to remove this middleware.
app.use(convert(historyApiFallback({
  verbose: false
})))

// ------------------------------------
// Apply Webpack HMR Middleware
// ------------------------------------
if (config.env === 'development') {
  const compiler = webpack(webpackConfig)

  // Enable webpack-dev and webpack-hot middleware
  const {
    publicPath
  } = webpackConfig.output

  if (config.proxy && config.proxy.enabled) {
    const options = config.proxy.options
    proxy = httpProxy.createProxyServer(options);
      //    app.use(convert(webpackProxyMiddleware(options)))
  }

  app.use(webpackDevMiddleware(compiler, publicPath))
  app.use(webpackHMRMiddleware(compiler))

  // Serve static assets from ~/src/static since Webpack is unaware of
  // these files. This middleware doesn't need to be enabled outside
  // of development since this directory will be copied into ~/dist
  // when the application is compiled.
  app.use(convert(serve(paths.client('static'))))
} else {
  debug(
    'Server is being run outside of live development mode. This starter kit ' +
    'does not provide any production-ready server functionality. To learn ' +
    'more about deployment strategies, check out the "deployment" section ' +
    'in the README.'
  )

  // Serving ~/dist by default. Ideally these files should be served by
  // the web server and not the app server, but this helps to demo the
  // server in production.
  app.use(convert(serve(paths.base(config.dir_dist))))
}

const server = http.createServer(function (req, res) {
  var path = url.parse(req.url).pathname
  if (proxy !== null && /^\/api\/.*/.test(path)) {
    let host = req.headers.host.replace(/:.+/, '')
    return proxy.web(req, res, {
      headers: {
        host: host
      }
    })
  }
  app.callback(req, res)
})

export default server

```

**Comment by tarjei** [comment]
Please note that I have updated the code above once to fix a hang.

**Comment by davezuko** [comment]
@tarjei sorry for the slow response, but in case you're curious there's been a fixed pushed to master for this: https://github.com/davezuko/react-redux-starter-kit/commit/9327561cac2e128c272090087a79cb785af45c41.

Thanks for the bug report and detailed walkthrough.

**Comment by tarjei** [comment]
Hi, did you test this? AFAIK koa-proxy does not work with koa 2.0. I tried going that route before the solution detailed above.

**Comment by chenfanggm** [comment]
@tarjei koa-proxy works for me, by transform from koa-converter
```
// koa-proxy
  if (config.proxy && config.proxy.enabled) {
    app.use(convert(proxy(config.proxy.options)))
  }
```

**Comment by tarjei** [comment]
OK, it didn't for me but I'll investigate some more later :)

Thanks

2016-03-01 6:06 GMT+01:00 Chen Fang <notifications@github.com>:

> @tarjei <https://github.com/tarjei> koa-proxy works for me, by transform
> from koa-converter
>
> // koa-proxy
>   if (config.proxy && config.proxy.enabled) {
>     app.use(convert(proxy(config.proxy.options)))
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davezuko/react-redux-starter-kit/issues/558#issuecomment-190548450>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by davezuko** [comment]
@tarjei I did test it and it worked perfectly on my end. If you are having issues let me know and I can try to help debug.
