### ISSUE TITLE
ESLint unmet dependency

### ISSUE THREAD

**Issue by kevinchiu** [davezuko/react-redux-starter-kit#564]
With NPM 3.7.1 I'm getting this error after npm i:

└── UNMET PEER DEPENDENCY eslint@2.0.0-rc.1

npm WARN eslint-loader@1.2.1 requires a peer of eslint@^1.6.0 but none was installed.
npm WARN eslint-plugin-babel@3.1.0 requires a peer of eslint@>=1.0.0 but none was installed.
npm ERR! code 1

**Comment by kevinchiu** [comment]
I found the issue for the first problem: I had eslint 2.0.0 installed in global. Uninstalling that got rid of the unmet dependency error.

The other two warnings are still there though. Not sure what to do about them.

**Comment by davezuko** [comment]
The others are just warnings for now, they should not actually interfere with the application. I will be upgrading a bunch of dependencies once they all support ESLint `^2.0.0`. Glad you figured out the issue!
