### ISSUE TITLE
LOCATION_CHANGE on state change 

### ISSUE THREAD

**Issue by schickling** [davezuko/react-redux-starter-kit#568]
First of all: Thank you so much for creating and maintaining the great starter kit. It's a huge help!
I'm currently building a new app based on this project but constantly get `@@router/LOCATION_CHANGE` after another state change has occurred.

PS: I already opened up an issue here: https://github.com/reactjs/react-router-redux/issues/286#issuecomment-184884017

**Comment by brentkirkland** [comment]
I can agree I'm getting something similar. When I use Link to='/' or whatever url, LOCATION_CHANGE is called but the app attempts to goto the specified route (the url flickers), but there is no transition (the url goes back to source url).

**Comment by brentkirkland** [comment]
Seems like LOCATION_CHANGE is being wonky right now

**Comment by gaearon** [comment]
Can you please provide an example reproducing the problem>

**Comment by brentkirkland** [comment]
I forked the repo and tried to replicate the issue. Bug doesn't exist. The issue is on my end.

**Comment by schickling** [comment]
Turns out it was another problem. Sorry. I triggered a state change based on an anchor tag `<a href='#' onClick={callAction}`.
