### ISSUE TITLE
module structure on the split directory under redux

### ISSUE THREAD

**Issue by leeir** [davezuko/react-redux-starter-kit#575]
Do not understand why you want action and Constants There Reducer in a file, this will not lead to less clear, could split into three separate files
Something like this：

module1-
               -- moduleAction
               -- moduleReducer

**Comment by chenfanggm** [comment]
@leeir I actually like the compact style, all in one file make it more modularity. I don't need switch between files to make a redux/flux flow. Leave the action at the top and reducer in the bottom make it navi easier. Also, use comment make each block searchable.

**Comment by davezuko** [comment]
I've split constants/actions/reducers into separate files in the past, but it generally leads to a lot of boilerplate that doesn't actually accomplish anything (and makes it a pain to create/modify actions). Users are totally free to take this boilerplate and edit it to fit their needs, I simply wanted to demo an alternative approach to the traditional file structure.
