### ISSUE TITLE
What's generating hashed json.gzip files in the root dir?

### ISSUE THREAD

**Issue by a-axton** [davezuko/react-redux-starter-kit#579]
I have about 100 gzipped json files in my root dir, is this from HMR? Is there a way to clean this up?

**Comment by davezuko** [comment]
It's the cache directory from babel-loader:

https://github.com/babel/babel-loader#using-cachedirectory-fails-with-enoent-error
> cacheDirectory: Default false. When set, the given directory will be used to cache the results of the loader. Future webpack builds will attempt to read from the cache to avoid needing to run the potentially expensive Babel recompilation process on each run. If the value is blank (loader: 'babel-loader?cacheDirectory') the loader will use the default OS temporary file directory.

https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L112

Closing this just so I can prune some issues that aren't directly related to the starter kit, but I am also interested in finding ways to clean this up. The weird thing is that the only environment I can reproduce it in ("it" being "the gzip.json files are in my project directory") is Ubuntu. What about you?

**Comment by davezuko** [comment]
See: https://github.com/babel/babel-loader/blob/master/lib/fs-cache.js#L127-L129

I just tested on Ubuntu 14.04 and `os.tmpdir()` just spits out my current directory, so I believe it's related to that, if you can confirm your OS.

**Comment by a-axton** [comment]
Thanks for the info, I'm on OSX el capitan 10.11, node v5.4.0. I'm starting to think it's either a permissions issue or an issue with nvm. For now, I set cacheDirectory to a dir name and put that in the gitignore

**Comment by mccarter** [comment]
@a-axton Do you have an example so I can copy your setup? { test: /\.js$/, exclude: /node_modules/, loaders: ["react-hot", "babel?cacheDirectory"] }

**Comment by a-axton** [comment]
It's just a quick fix, never actually got around to solving the issue. You can assign a string to the cacheDirectory option to choose a dir to save the json files to. I'm using the query object for my setup, but for you it's probably something like `"babel?cacheDirectory=cache"`. Lastly, I added the cache dir to my .gitignore

**Comment by mccarter** [comment]
sweet! that worked. Thank you. I created a folder called 'babel-cache' one directory up from my config.js file. Example: loaders: ["react-hot", "babel?cacheDirectory=__dirname/../babel-cache"]

**Comment by ubergarm** [comment]
I had this issue when running inside a `docker` container. The fix for me was to read the `babel-loader` docs:

```cacheDirectory: Default false. When set, the given directory will be used to cache the results of the loader. Future webpack builds will attempt to read from the cache to avoid needing to run the potentially expensive Babel recompilation process on each run. If the value is blank (loader: 'babel-loader?cacheDirectory') the loader will use the default OS temporary file directory.```  https://github.com/babel/babel-loader

So depending on which version of this repo you have, update the `cacheDirectory` to be an actual directory instead of `true`.  In my case the change was in: `react-redux-starter-kit/config/index.js`. Older version might use: `build/webpack.config.js`.

```js
 compiler_babel : {
    cacheDirectory : '/tmp',
    plugins        : ['transform-runtime'],
    presets        : ['es2015', 'react', 'stage-0']
```
