### ISSUE TITLE
Accessing localhost from a remote device

### ISSUE THREAD

**Issue by amangeot** [davezuko/react-redux-starter-kit#581]
Hello, thank you for the great starter-kit, it is really helpful!

I am trying to access `localhost` from another machin, using local IP address (shared WiFi). The development environment's port is open and antivirus disabled (I am on Windows), but browsers on remote devices will only display the page title and favicon, page content being empty. (I also tried using `localtunnel` npm package)

I am quite new to web development so pardon me if my question should not land here. Is there any chance the problem could come from webpack's configuration ?

**Comment by slavik0329** [comment]
try changing ./config/_base.js 'server_host' line to your machines IP and rerun

**Comment by amangeot** [comment]
Awesome, it is working for devices sharing a WiFi (localtunnel working too)! Disabling an antivirus or adding a rule to open the application port is not needed either.

However the problem remains if devices are on different networks. Do you know why `localtunnel` reaches a node server (favicon and page title) but no files from webpack (page content) ?

**Comment by amangeot** [comment]
If anyone is interested, it is possible to publicly access a local server using `localtunnel` by specifying the compiler public path (`config.compiler_public_path`). `localtunnel` will serve from http://>subdomain<.localtunnel.me.

Using npm package `concurrently` to start a local server in parallel with a tunnel:

@package.json
```javascript
  "scripts": {
    "dev:lt": "concurrently --kill-others \"better-npm-run dev-localtunnel\" \"lt -s <subdomain> -p <port>\"",
    // ...
  },
  "betterScripts": {
    "dev-localtunnel": {
      "command": "nodemon --exec babel-node bin/server",
      "env": {
        "NODE_ENV": "development",
        "SUBDOMAIN": <subdomain>,
        "PORT": <port>,
        // ...
      }
    },
    // ...
  }
```

@_development.js
```javascript
export default (config) => ({
  compiler_public_path: process.env.SUBDOMAIN ?
    `http://${process.env.SUBDOMAIN}.localtunnel.me/` :
    `http://${config.server_host}:${config.server_port}/`,
  // ...
})
```

**Comment by davezuko** [comment]
Thanks for the info @amangeot , adding this to my todo list for the readme.
