### ISSUE TITLE
Unable to npm-start

### ISSUE THREAD

**Issue by CreativeManix** [davezuko/react-redux-starter-kit#585]
I am using this kit first time. NPM install was fine, when I start, It throws following error

`ERROR in ./~/css-loader?sourceMap&-minimize!./~/postcss-loader!./~/sass-loader?sourceMap!./src/views/HomeView/HomeView.scss
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".counter--green", ".counter--green" is weird
    at D:\RND\react-redux-starter-kit\node_modules\postcss-modules-scope\lib\index.js:26:13
    at Array.map (native)
    at getSingleLocalNamesForComposes (D:\RND\react-redux-starter-kit\node_modules\postcss-modules-scope\lib\index.js:20:26)
    at D:\RND\react-redux-starter-kit\node_modules\postcss-modules-scope\lib\index.js:106:26
    at D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:92:28
    at D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:73:26
    at Rule.each (D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:60:22)
    at Rule.walk (D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:72:21)
    at Rule.walkDecls (D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:90:25)
    at D:\RND\react-redux-starter-kit\node_modules\postcss-modules-scope\lib\index.js:105:12
    at D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:110:28
    at D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:73:26
    at Root.each (D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:60:22)
    at Root.walk (D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:72:21)
    at Root.walkRules (D:\RND\react-redux-starter-kit\node_modules\postcss\lib\container.js:108:25)
    at D:\RND\react-redux-starter-kit\node_modules\postcss-modules-scope\lib\index.js:101:9
 @ ./src/views/HomeView/HomeView.scss 4:14-209 13:2-17:4 14:20-215
`
I also get "Not Found" message while browsing the app.

**Comment by davezuko** [comment]
My guess is that the file is not being processed with the loader for CSS modules. Could you try a couple things for me please?

* In `~/config/_base.js`, change `path_base` to: `process.cwd()`.

Does that work? If not:

* In `~/build/webpack.config` update lines `185 -> 187` to:

```js
const cssModulesPaths = new RegExp('(' + [
  paths.base('src')
].join('|') + ')')
```

Does that work? If so, keep that and revert `path_base` to the previous implementation and see if that works. My guess is that it's because the path is not correct on a Windows machine, so I'm trying to eliminate that forward slash in `path_base`.

**Comment by davezuko** [comment]
Alternatively, pull the latest version of master (pushed what _should_ be a hotfix for this for you) and see if that resolves it.

**Comment by arthow4n** [comment]
+1
https://github.com/davezuko/react-redux-starter-kit/issues/585#issuecomment-186886743
Tried the solution above on Windows 7 but still fails with same error.

**Comment by evandu** [comment]
+1

**Comment by gemilangpermata** [comment]
+1

**Comment by CreativeManix** [comment]
When I remove following line from HomeView.scss it works fine.

`composes: counter;`

**Comment by davezuko** [comment]
Can one of you please put a `console.log` statement after https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L185-L187 and tell me what it shows? Something is wrong in the regex, I'm almost certain of it.

**Comment by Marsup** [comment]
Escaping the path worked for me :
```js
  const cssModulesPaths = new RegExp('(' + [
    paths.base(config.dir_client).replace(/[\^\$\.\*\+\-\?\=\!\:\|\\\/\(\)\[\]\{\}\,]/g, '\\$&')
  ].join('|') + ')')
```

**Comment by davezuko** [comment]
Oh god that's awful, but proves that it _is_ path related. I'm not a Windows user, obviously, but shouldn't Node's `path` module insert the correct path separators when using `path.resolve`?

**Comment by davezuko** [comment]
Oh, nevermind, it looks like your regex just (as you said... sorry, it's early) escapes the _forward_ slash, it doesn't insert back slashes. Interesting.

**Comment by Marsup** [comment]
It's not really windows related, any character that have a special meaning in a regexp would fail you, whatever the OS.

**Comment by Marsup** [comment]
By the way what's the point of joining a single element array ?

**Comment by davezuko** [comment]
Yeah that makes total sense, I'm just confused as to why it's not causing issues on my machine.

@Marsup the reason for the join is because there are some other (now closed) issues where people need to enable CSS modules for specific npm packages. Keeping this as an array makes it easy for somebody to just add another package name without having to mess with a regex. See https://github.com/davezuko/react-redux-starter-kit/issues/582 for an example.

**Comment by Marsup** [comment]
Try to have a path with a +, should fail for you too. Windows has \ in any path so it's 100% success rate ;)

**Comment by davezuko** [comment]
Using @Marsup 's fix (thank you!) until I can figure out something that is a bit cleaner. See https://github.com/davezuko/react-redux-starter-kit/commit/8a0c7d7e2a610d68dc5b1cdb278e75491a741ccb#diff-e58978bae3eedc0610421c987c874e3eR160 for the relevant change.

If you guys could verify that this works for you then we can go ahead and close this out for now, sorry for the inconvenience.

**Comment by CreativeManix** [comment]
It works for me now after updating webpack.config.js as per above commit.

Thanks

**Comment by davezuko** [comment]
:tada:
