### ISSUE TITLE
help wanted: how to use generators with this starter kit?

### ISSUE THREAD

**Issue by jokeyrhyme** [davezuko/react-redux-starter-kit#588]
I'd like to use https://github.com/yelouafi/redux-saga which makes use of ES2015 generators.

When I try to `npm start` or `npm run deploy` with either redux-saga or my own generator functions in the code, the build succeeds but at runtime (in the browser) there is a blank page with a console error:

> _regeneratorRuntime is not defined

I've tried adding the https://www.npmjs.com/package/babel-polyfill module in a few places:

- https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_base.js#L39 adding to the top of the `compiler_vendor` array

- https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L30 adding to the start of the `webpackConfig.entry.app` array

- https://github.com/davezuko/react-redux-starter-kit/blob/master/src/main.js#L1 adding an `import "babel-polyfill"` to the very top

I can confirm that the build output size increases with these changes, but I still get the runtime error.

Has anyone successfully got generators working with this starter kit? What am I doing wrong?

**Comment by jokeyrhyme** [comment]
I suspect what I've done wrong is include redux-saga in the vendor bundle. What tentatively works is having redux-saga in the app bundle, and babel-polyfill in the vendor bundle. I'm going to experiment further with this today and confirm that this solves the problem for me.

**Comment by jokeyrhyme** [comment]
Yep, everything is working now. This starter injects the vendor and app bundle script tags in that order, so as long as babel-polyfill is in the vendor bundle, and all generator functions are in the app bundle, it all just works. :)

**Comment by davezuko** [comment]
Awesome, glad you figured this all out before I even had a chance to take a look! Haha.

**Comment by jokeyrhyme** [comment]
I failed, had a good night's sleep, then figured it out the next day. I think this is the essence of good troubleshooting. :)

**Comment by jokeyrhyme** [comment]
If you're curious, this is the commit where I add babel-polyfill and redux-saga: https://github.com/jokeyrhyme/react-redux-starter-kit/commit/f3f095b547ee63474b9361128bb95d370da04b35

**Comment by davezuko** [comment]
Thank you! I've done that in our apps at work but totally neglected it here. Not sure if it's necessary to add to the repo out of the box, but I will probably at least add a link to your commit SHA in the readme FAQ.

**Comment by jokeyrhyme** [comment]
Found another gotcha: you can't use `Promise` in the same file as generators. It's okay to be in files that are required / imported by a generator file, but if I put them in the same file than I get the regenerator runtime error again. Weird.
