### ISSUE TITLE
CLI to complement this awesome starter kit!

### ISSUE THREAD

**Issue by SpencerCDixon** [davezuko/react-redux-starter-kit#595]
Hey @davezuko I created a redux-cli to help me develop apps a bit quicker and get all the nice generators I loved when I was working primarily in Rails.  Initially I was going to keep it super opinionated to just my workflow but figured it might be useful for others/if people wanted to contribute we could make it be very tightly coupled to your starter kit.  Lemme know your thoughts!

https://github.com/SpencerCDixon/redux-cli

**Comment by davezuko** [comment]
Funny that you posted that as I just started working on a branch that will allow people to start from a clean slate: https://github.com/davezuko/react-redux-starter-kit/tree/new-project. Will definitely give your project a look, though, it's probably much more thorough.

**Comment by SpencerCDixon** [comment]
Oh sweet.  I could easily add the commands you created in that branch to the `redux new` command of the CLI in order to have the project start from a clean slate.  Or it could be an option to the new command so people have a choice to see some boilerplate for inspiration or if they're experienced with the kit they can start from scratch.

I know it helped me a lot to see some boilerplate when I was brand new to the kit in order to gain some context

**Comment by davezuko** [comment]
Will add a note to the readme about this mañana.

**Comment by borlaym** [comment]
Yeah a cli would be awesome. It would also allow you to add optional features that not everyone would want. (Flow please!)

**Comment by davezuko** [comment]
By tomorrow I meant in 5 days, of course. Added a note to the README @SpencerCDixon : https://github.com/davezuko/react-redux-starter-kit#starting-a-new-project. I've been slammed as usual, but will jump back over to your repo when I get a chance to look at what I need to do to get the `.template` (I think?) directory/config created.

**Comment by davezuko** [comment]
Note: will be adding more issues for `redux-cli` integration as they crop up, closing this is not the end of it.

**Comment by SpencerCDixon** [comment]
Sweet, I've spent a lot of time refactoring the CLI to use blueprints like in ember-cli.  Blueprints essentially give you a way to override the templates and some hooks for the templating process.  Once my PR with that functionality is done I will make some basic blueprints for this project and submit a PR.  Then you/your starter kit users will be able to manage the blueprints yourself as things change.

**Comment by SpencerCDixon** [comment]
right now when users start a new project it automatically creates a dotfile that works out of the gate with this starter kit so no need for you to do more work.  I'll let you know if I need anything from you though.  Only thing I can think about is settling on branch/version to use for the git pull when users use the cli to generate a project from scratch

**Comment by davezuko** [comment]
I might tag a `1.x.0` version today or a `2.0.0-alpa.0` just so that they can pull in something stable. I know there are a few straggling issues out there, but it seems to be stable _for most users_.

**Comment by SpencerCDixon** [comment]
excellent.  Once you have a stable release that you want the 'redux new' command to pull down just let me know here or in the redux-cli repo and I'll use that until I add functionality for the new command to pass in specific branches (which is in the works)

Last question for you: do you want a flag on the 'new' command that will automatically run your `npm project:make` command after the pull?

**Comment by SpencerCDixon** [comment]
@davezuko released version that has the support for blueprints.. here is a link to explanation: https://github.com/SpencerCDixon/redux-cli#creating-blueprints
