### ISSUE TITLE
How can i have multiple env's like test,qa in addition to dev,prod.

### ISSUE THREAD

**Issue by mikedevita** [davezuko/react-redux-starter-kit#596]
So my team is building an internal enterprise app with an SAP backend, using your react boilerplate.

we have several environments.

* development - local development, using a json-server as a mock SAP backend that stubs out a small snapshot of our DB and presents a local json REST api
* test - should be connected to our test SAP backend, we need to rev proxy between it
* qa - should be connected to our qa SAP backend, we need to rev proxy between it
* prod - hosted on ECC with no rev proxy, just serving up dist basically

I have development and prod working great, i use `_development.js` and build out the proxy stuff there. Production works fine too i just change a global config variable called `API_BASE` and point it to our SAP backend base API urls `/sap/bc/webrfc?_function=`

### development.js
```javascript
  globals: {
    ...config.globals,
    API_BASE: JSON.stringify('http://localhost:3000/api')
  },
```

### production.js
```javascript
  globals: {
    ...config.globals,
    API_BASE: JSON.stringify('http://sapecpd1.example.com:8000/sap/bc/webrfc')
  },
```

however for instances where test/qa is our environment were still using webpack/koa to host the app locally and want to use rev proxy to connect to our backend SAP. to do this we need different `config/_environment.js` files for each.. Is this natively supported where NODE_ENV is auto matched to `config/_environment.js`?

For example if i set my `NODE_ENV=QA` will webpack autoload `config/_qa.js`?

**Comment by davezuko** [comment]
As a quick answer to your last question: yes, it just uses your NODE_ENV and prefixes it with an underscore (I just did that for sorting in the file tree). Excuse my awful old code here: https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L12-L24. You'll have to tweak any deploy scripts that are hard coding a NODE_ENV, but that should be it.

Have to run but will read through the rest in greater detail when I have some time later.

**Comment by davezuko** [comment]
Just added more documentation to the README to highlight this, hopefully. I will be continuing to work on improving this process so that the config used is not necessarily tied to the `NODE_ENV`, but it works for 99% of use cases right now.
