### ISSUE TITLE
better-npm-run ignoring NODE_ENV

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#597]
Neither the NODE_ENV in its own config or explicitly set on the command line has any effect. Deploy or compile still uses `development`.

**Comment by davezuko** [comment]
Wonder when that broke...

**Comment by neverfox** [comment]
I'll admit I haven't confirmed that with the sample kit, only a project of mine, so I'll do that now.

**Comment by davezuko** [comment]
I don't doubt it at all, I just wish we could totally drop `better-npm-run` altogether but it's a pain to manage things for both Windows/Unix users otherwise.

**Comment by neverfox** [comment]
OK, apparently this is a false alarm, as the sample kit does go in to "production" mode with `npm run deploy`. I'll have to track this down in my own project.

**Comment by neverfox** [comment]
I think it might be because I still have the `.env` floating around from before.
