### ISSUE TITLE
npm start Never Gets Beyond Starting Web Server (on only 1 machine)

### ISSUE THREAD

**Issue by netpoetica** [davezuko/react-redux-starter-kit#598]
Hi, I have an issue that is very strange that has left me pretty baffled. At this point, not sure where to even begin in debugging this.

Essentially, *only on one machine* on my team, who is running exact same computer, OS version, node version, and npm version as me, does this issue present. A web server is started but no bundle is ever generated. The output ends up looking like this:

```
➜  react-redux-starter-kit git:(master) npm start

> react-redux-starter-kit@1.0.0 start /Users/netpoetica/Desktop/temp/react-redux-starter-kit
> better-npm-run start

running better-npm-run in /Users/netpoetica/Desktop/temp/react-redux-starter-kit
Executing script: start

to be executed: babel-node bin/server 
  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +1ms
  app:webpack:config Create configuration. +842ms
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +1ms
  app:server:webpack-dev Enable webpack dev middleware. +417ms
  app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +28ms
  app:bin:server Server is now running at http://localhost:3000. +4ms
```
and then the process just hangs. This is on Mac OSX 10.10.5, and here is some system info although I doubt it matters:

```
Darwin Kernel Version 14.5.0: Tue Sep 1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```
Currently, we have to run `npm run compile` and just go manual on this. If we do `npm run compile && npm start`, we will be able to see the dev server but will have none of the features of file-system watching, hot reloading, etc.

We have tested this on multiple versions of node and npm, but particularly it was discovered on node v4.3.1.

Any advice on how you might debug something like this would be great.

**Comment by davezuko** [comment]
Does that machine have troubles with any other boilerplates? What about with a very rudimentary webpack + HMR + react transform setup?

I will try to get to this tomorrow, but until then the above information might help us narrow down the cause.

**Comment by netpoetica** [comment]
Hey @davezuko - thanks for replying. We tried with both npm2 and npm3 with the same results. Do you have any recommendations for boilerplates we may be able to try? I will see if we can just work with webpack examples to start out. Thanks again

**Comment by grayfuse** [comment]
Having the same problem here, or at least similar...

```
to be executed: babel-node bin/server
/Users/jgray/Desktop/j3ffgray-react/webpack-j3ff-simple/bin/server.js:1
(function (exports, require, module, __filename, __dirname) { import config from '../config';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/jgray/Desktop/j3ffgray-react/webpack-j3ff-simple/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jgray/Desktop/j3ffgray-react/webpack-j3ff-simple/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at /Users/jgray/Desktop/j3ffgray-react/webpack-j3ff-simple/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/Users/jgray/Desktop/j3ffgray-react/webpack-j3ff-simple/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:397:26)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@1.0.0 start: `better-npm-run start`
npm ERR! Exit status 1
```

**Comment by davezuko** [comment]
@netpoetica I will try to find some minimal kits to try, might not get a chance to until tomorrow though, unfortunately.

@grayfuse that's... very strange. When I get back tomorrow I will try to do a fresh install and see if I can reproduce, but I can't think of why babel wouldn't be transpiling those imposrts.

**Comment by tonytainguyen** [comment]
same issue here.

**Comment by davezuko** [comment]
@tonytainguyen what's your node/npm version and are you on the latest version of master?

**Comment by CreativeManix** [comment]
I have same issue on MAC
NPM V3.3.12
Node V5.5.0

**Comment by josephluck** [comment]
Same issue on mac after fresh clone and npm install
NPM V3.6.0
Node V5.6.0

**Comment by davezuko** [comment]
@CreativeManix @tonytainguyen @josephluck are you all on the latest version of master w/ a complete reinstall of node_modules? If not, could you try? Same issue as the OP or the latter one mentioned by @grayfuse ? Do any of you have any other details?

I've been trying to repro but cannot... will bump my node version today and see if that's at all related.

**Comment by CreativeManix** [comment]
Found it, It just my mistake

What I did is created my own module and copied files from this repo, while doing that I didnt copied many hidden files. I hope these files are used by babel. When I included all hidden files everything is fine.

I think others who reported this issue also did the same!

**Comment by netpoetica** [comment]
In the case of my coworker, it was a completely fresh clone of the repo - no dragging and dropping around Finder or anything. All via terminal, all hidden files properly there. This seems to be some sort of enigma to do with this particular machine, because we've tried multiple node versions, multiple versions of npm, making sure no packages were installed globally that might have conflicting version numbers.

**Comment by davezuko** [comment]
@netpoetica could you possibly try https://github.com/coryhouse/react-slingshot and see if that works?

**Comment by netpoetica** [comment]
@davezuko react-slingshot works on said machine without any trouble. We ran "npm start" and were able to get the server started and the build generated. We also confirmed that by making some changes, we could watch the build occur and successfully view those changes.

The good news is we fixed this issue. My coworker had a default NODE_ENV=DEV in his bashrc, and when there is a NODE_ENV other than the supported ones, the npm start command hangs. We simply unset it so that it would default to development and we were gold.

Thanks for your help! Gonna close this, sorry if this caused you anywhere near the anxiety it caused me ^_^

**Comment by davezuko** [comment]
Wow that is rough, really glad you figured it out though. No wonder I couldn't repro...

Thank you _so much_ for digging into this though, I really appreciate it. I'm going to reproduce it locally and figure out a way to fix it so it doesn't just silently hang...
