### ISSUE TITLE
Alternative to space-infix-ops: 0

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#599]
That's a pretty blunt instrument just to handle Flow syntax, because it's a pretty important linting rule for JS generally. Any ideas about a better way to handle it?

**Comment by davezuko** [comment]
Totally agreed, I just haven't had the time to research the issue.

**Comment by davezuko** [comment]
Tracking https://github.com/eslint/eslint/issues/5211

**Comment by davezuko** [comment]
Removed for now: https://github.com/davezuko/react-redux-starter-kit/commit/96bd1cdd8b79f0a44836e71882c1e7122d2ced21
