### ISSUE TITLE
Server the app to computers on same wifi network

### ISSUE THREAD

**Issue by sulliwane** [davezuko/react-redux-starter-kit#601]
I changed to ```server_host : '0.0.0.0',``` in _base.js, but still nothing load in other computers browser. My computer firewall has port 8080 opened and can be pinged. 

Any idea why it's blocked?

many thanks

**Comment by davezuko** [comment]
Could you take a look at https://github.com/davezuko/react-redux-starter-kit/issues/581 and see if that helps you out at all?

**Comment by sulliwane** [comment]
@davezuko many thanks, that solved the problem!
