### ISSUE TITLE
error about eslint

### ISSUE THREAD

**Issue by leeir** [davezuko/react-redux-starter-kit#602]
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint:fix' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prelint:fix', 'lint:fix', 'postlint:fix' ]
5 info lifecycle react-redux-starter-kit@1.0.0~prelint:fix: react-redux-starter-kit@1.0.0
6 silly lifecycle react-redux-starter-kit@1.0.0~prelint:fix: no script for prelint:fix, continuing
7 info lifecycle react-redux-starter-kit@1.0.0~lint:fix: react-redux-starter-kit@1.0.0
8 verbose lifecycle react-redux-starter-kit@1.0.0~lint:fix: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@1.0.0~lint:fix: PATH: d:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;d:\www\c2h\nmwcf\MWCF\node_modules\.bin;c:\Users\zhuhonglei\bin;.;C:\Program Files (x86)\Git\local\bin;C:\Program Files (x86)\Git\mingw\bin;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\bin;c:\Program Files (x86)\Common Files\NetSarang;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;c:\Windows\system32;c:\Windows;c:\Windows\System32\Wbem;c:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;c:\Program Files\TortoiseSVN\bin;d:\wamp\bin\php\php5.4.3;d:\xampp\php;c:\ProgramData\ComposerSetup\bin;d:\Program Files\nodejs\;c:\Ruby200-x64\bin;C:\Program Files (x86)\Git\cmd;d:\software\.nvmw;c:\Python27;d:\Program Files\nodejs;c:\Users\zhuhonglei\AppData\Roaming\npm
10 verbose lifecycle react-redux-starter-kit@1.0.0~lint:fix: CWD: d:\www\c2h\nmwcf\MWCF
11 silly lifecycle react-redux-starter-kit@1.0.0~lint:fix: Args: [ '/d /s /c', 'npm run lint -- --fix' ]
12 silly lifecycle react-redux-starter-kit@1.0.0~lint:fix: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@1.0.0~lint:fix: Failed to exec lint:fix script
14 verbose stack Error: react-redux-starter-kit@1.0.0 lint:fix: `npm run lint -- --fix`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-redux-starter-kit@1.0.0
16 verbose cwd d:\www\c2h\nmwcf\MWCF
17 error Windows_NT 6.1.7601
18 error argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint:fix"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error react-redux-starter-kit@1.0.0 lint:fix: `npm run lint -- --fix`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@1.0.0 lint:fix script 'npm run lint -- --fix'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run lint -- --fix
23 error You can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mmermerkaya** [comment]
This might help: https://github.com/davezuko/react-redux-starter-kit/issues/398#issuecomment-188495208

**Comment by davezuko** [comment]
Thanks for the explanation @mmermerkaya. I'm not going to pull this into the repo for reasons explained [here](https://github.com/eslint/eslint/issues/2409#issuecomment-169041991), but will add it to the FAQ.

**Comment by mmermerkaya** [comment]
You're welcome, and thanks for adding it to the FAQ.

**Comment by leeir** [comment]
@mmermerkaya Thanks

**Comment by davezuko** [comment]
Started a wiki page and dropped this in there, https://github.com/davezuko/react-redux-starter-kit/wiki/Troubleshooting, once I've formatted and migrated the rest of the troubleshooting from the readme to this page I will link to it in the readme.

**Comment by voiceofvega** [comment]
Hello,
How can we load a "plain" CSS file from a module ?
I try to use the facebook's fixed-data-table module ( https://facebook.github.io/fixed-data-table ). After installation with npm, I can import the JS in my Presentational components:
`import { Table, Column, Cell } from 'fixed-data-table'`
But the styling is lost. I tried importing the CSS file from various places:
- With an SCSS file in styles/global (referenced by core.scss):
`@import '../../node_modules/fixed-data-table/dist/fixed-data-table.css'`
- From the Component, or AppContainer.js:
`import 'fixed-data-table/dist/fixed-data-table.css'`
- From an SCSS file in the same folder as the Component.

The problem is that the class names from the imported CSS file are transformed:
`.public_Scrollbar_main` becomes `.fixed-data-table__public_Scrollbar_main___14sP3`, which is not recognized by the React component, that expects `.public_Scrollbar_main`.

How can I either process the fixed-data-table component to use processed CSS class names, or import the CSS file (short of explicitely declaring in index.html) ?
