### ISSUE TITLE
run-script make:project  is missing

### ISSUE THREAD

**Issue by rkmax** [davezuko/react-redux-starter-kit#610]

**Comment by davezuko** [comment]
I'm a bit confused, this isn't a documented script anywhere. Could you explain in a bit more detail what exactly the issue is? Closing until then since this does not appear to be immediately relevant.

**Comment by baopham** [comment]
The script is documented here: https://github.com/davezuko/react-redux-starter-kit/commit/7ba4f81c30a2ce33f91e1037210e3b3c217136ea

**Comment by rkmax** [comment]
@davezuko in the readme you can found this section https://github.com/davezuko/react-redux-starter-kit#starting-a-new-project but that script is missing on the code

**Comment by davezuko** [comment]
Ah yes, that's a script _on_ that branch though:

```
git checkout -b <your-project-name> new-project
```

So you have to branch off of the branch `new-project`.

**Comment by davezuko** [comment]
Sorry for the confusion, I had my mind focused on the master branch.

**Comment by davezuko** [comment]
Added a chore to make this less obtuse: https://github.com/davezuko/react-redux-starter-kit/issues/611
