### ISSUE TITLE
Npm run deploy giving error: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by tonytainguyen** [davezuko/react-redux-starter-kit#612]
everything works fine when in dev, but I guess when it's trying to compile, it gives errors. Here's my npm log:
[npm-log.txt](https://github.com/davezuko/react-redux-starter-kit/files/150395/npm-log.txt)

Not sure what's wrong.

**Comment by davezuko** [comment]
From what I can see it looks like it might be an issue with `better-npm-run`.

**Comment by davezuko** [comment]
@tonytainguyen if you rewrite the scripts to not use `better-npm-run` (its sole purpose is to set environment variables correctly for windows/unix users), do you have any more luck? For example:

```
// regular npm script, not a `betterScript`:
"deploy": "NODE_ENV=production DEBUG=app:* npm run clean && babel-node bin/compile"
```

**Comment by davezuko** [comment]
Also see https://github.com/davezuko/react-redux-starter-kit/issues/571 if you are having deploy problems.

**Comment by davezuko** [comment]
Closing until more details/feedback are provided.
