### ISSUE TITLE
Clean up example code 

### ISSUE THREAD

**Issue by kapakos** [davezuko/react-redux-starter-kit#614]
Hi,

I want to use the react-redux-starter-kit as a base for a project I'm starting. It has all the good packages I like. I only have a problem executing the 'Starting a new project' step. the line: 
$ git checkout -b <your-project-name> new-project

doesn't seem to do what it's supposed to. I'm using it like this: 
$ git checkout -b myproject new-project
I get this message: 
fatal: Cannot update paths and switch to branch 'myproject' at the same time.
Did you intend to checkout 'new-project' which can not be resolved as commit?

Am I missing something?

Thanks.

**Comment by davezuko** [comment]
Looks like I need to update the example, but for now you can do:

```bash
git fetch origin new-project
git checkout new-project
git checkout -b myproject new-project
```

There's a more succinct way to do this, I just have to think about it for a minute.

**Comment by davezuko** [comment]
Fixed in latest master, will revisit to condense the amount of work needed when time allows. Thanks for reporting this.

**Comment by yipcma** [comment]
I'm also interested in how to maintain independent repo while fetching updates from this kit repo for my projects based on this kit.
