### ISSUE TITLE
Distributed scripts and referencing assets on other host

### ISSUE THREAD

**Issue by madshargreave** [davezuko/react-redux-starter-kit#615]
I have a JS plugin that users can embed into their website

Right now using file/url-loader, it generates something like:

src:url(/fonts/icomoon.eot?slmpmq)

When I reference URLs, but this looks for the assets on the widget user's website, and not my server where they download it from?

How can I get it to reference my specific domain, even though the script is running on theirs?

**Comment by davezuko** [comment]
Wouldn't just using an explicit url solve the issue? Or am I misunderstanding?

`url(http://your-domain/fonts/icomoon.eot)`

Or does that not work?

**Comment by davezuko** [comment]
Not sure what steps to take from here, if you are still having issues please just ping me on here and we can reopen.
