### ISSUE TITLE
Error: Cannot resolve module 'ansi-to-html-umd'

### ISSUE THREAD

**Issue by agoransson** [davezuko/react-redux-starter-kit#617]
I get the following error on a clean clone (last commit is `dbeb6a5da2b9cb42058993c922bb39912abf8102`)

    ERROR in (webpack)-hot-middleware/client.js?path=http://localhost:3000/__webpack_hmr
    Module not found: Error: Cannot resolve module 'ansi-to-html-umd' in /Users/myuser/testproject/node_modules/webpack-hot-middleware
    @ (webpack)-hot-middleware/client.js?path=http://localhost:3000/__webpack_hmr 82:11-38

**Comment by davezuko** [comment]
Awesome, looks like a breaking dependency change somewhere. My app was working until I did a fresh npm install.

_Looking into it_.

**Comment by davezuko** [comment]
This has been reported. Tracking https://github.com/glenjamin/webpack-hot-middleware/issues/80

**Comment by nathanielks** [comment]
Fixed in 2.8.1!

**Comment by agoransson** [comment]
Yep, it works if I update `webpack-hot-middleware` from `2.6.0` to `2.8.1`.
