### ISSUE TITLE
I can`t use the css imported in my component , but use link is well . 

### ISSUE THREAD

**Issue by WenXuanYuan** [davezuko/react-redux-starter-kit#626]
I wrote 
   .wenke{
       color: red
    }
the style in src/styles/core.scss and wrote
   div className='page-container'
      p className='wenke'>Hello</p
      div className='view-container'
in src/layouts/CoreLayouts.js, but the <p> element didn`t get the wenke style as I expected, why is it? I am a fresher in react , I need your help. Thank you very much.

**Comment by davezuko** [comment]
This project is using CSS modules, so you have to either disable them or import the classes as a JS object and apply them accordingly. CSS Modules:

https://github.com/davezuko/react-redux-starter-kit/blob/master/src/views/HomeView/HomeView.js#L6
https://github.com/davezuko/react-redux-starter-kit/blob/master/src/views/HomeView/HomeView.js#L36

Disabling:

https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_base.js#L28

**Comment by davezuko** [comment]
Closing this since I don't think this is an actual issue. If the recommendation does not in fact work, please feel free to ping me and we can re-open.
