### ISSUE TITLE
Nested routes - Refresh not working 

### ISSUE THREAD

**Issue by CreativeManix** [davezuko/react-redux-starter-kit#627]
I have following nested route configuration.

I could navigate to '/auth/login' using Link component. However If I refresh the page (crtl+r), it shows blank screen.

I require this when the above link is placed on external application. How can I do this, should configure anything special? 

```
export default (store) => (
  <Route path='/' component={CoreLayout}>
    <IndexRoute component={HomeView} />
    <Route path='/auth' component={AuthLayout}>
    	<Route path='/login' component={LoginView}/>
    </Route>
  </Route>
)

```

**Comment by davezuko** [comment]
My guess is that the history API fallback isn't working properly, but beside that I'm not sure. Are there any network errors or console errors?

**Comment by CreativeManix** [comment]
Got it...

The history API fallback don't like '/' in the nested routes, following works now.

```
export default (store) => (
  <Route path='/' component={CoreLayout}>
    <IndexRoute component={HomeView} />
    <Route path='auth' component={AuthLayout}>
        <Route path='login' component={LoginView}/>
    </Route>
  </Route>
)
```

**Comment by davezuko** [comment]
Thanks for diving into it. I'm tracking the two issues you just created, so will take it from there since this is not an issue with this project in particular.
