### ISSUE TITLE
estraverse-fb missing

### ISSUE THREAD

**Issue by estaub** [davezuko/react-redux-starter-kit#629]
I just downloaded, installed and attempted to run 2.0.0-alpha.1.  "npm start" complained that estraverse-fb was missing.  I did a save-dev install of estraverse-fb, and now all appears to be fine.  I see no errors in the "npm install" log, and no references to estraverse-fb.

**Comment by davezuko** [comment]
Are you on npm2 or 3?

**Comment by wkw** [comment]
same error for me. I'm on:  `npm -v ==> 3.3.12`
save-dev for estraverse-fb worked as reported by @estaub

**Comment by estaub** [comment]
I’m on NPM 3.3.6.

**Comment by davezuko** [comment]
Guessing this is a breaking change from one of our dependency's dependencies, since I don't recognize this package at all.

**Comment by estaub** [comment]
I think it's probably this: https://github.com/eslint/eslint/issues/5476

**Comment by lsunsi** [comment]
I just installed it without saving to package.json. Seems to be about eslint, like @estaub just mentioned.

**Comment by tonytainguyen** [comment]
err, same issues here. 

Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)

**Comment by davezuko** [comment]
It's not an issue with this starter kit but a related dependency. I'm away on vacation and unable to submit a patch, so I suggest installing locally as a temporary solution or waiting for the appropriate babel/eslint fix since that's the cause, unless you'd like to submit a PR.

**Comment by zirho** [comment]
+1 
I resolved it by installing it afterwards.

**Comment by jhabdas** [comment]
This is an issue with `babel-lint` as suggested here: https://github.com/eslint/eslint/issues/5476#issuecomment-192704497

To resolve temporarily consider updating your `package.json` files and set `"eslint": "~2.2.0"` as [shown by example here](https://github.com/jhabdas/react-native-webpack-starter-kit/blob/9cf91170960bc1850db95d6cd035b49bbe24fce2/package.json#L40).

**Comment by davezuko** [comment]
ty @neverfox

**Comment by zirho** [comment]
thank you it worked
