### ISSUE TITLE
Running `npm run deploy` renders a blank page

### ISSUE THREAD

**Issue by harijoe** [davezuko/react-redux-starter-kit#631]
I ran `npm run deploy` and oppened the generated `index.html` file and the result is an empty blank page. 
![image](https://cloud.githubusercontent.com/assets/10897494/13575886/5da619ea-e48b-11e5-854a-b0929e4b26ed.png)

The router seems to have no path registered. I tried switching the environment with same result.
The project runs well with the koa server.

Any idea why the router behaves like that in the dist folder ?

**Comment by jimmystridh** [comment]
since you are running from a sub-directory you will end up at a non-existing route

try
```
npm install -g http-server
http-server dist
```
and check out http://localhost:8080

The dist build is presumed to be running at the root of the web server afaik

**Comment by harijoe** [comment]
@jimmystridh Thank you. It worked.

It's obviously a beginner mistake but maybe it deserves a line in the documentation. What do you think ?
