### ISSUE TITLE
I got a question about testing

### ISSUE THREAD

**Issue by zirho** [davezuko/react-redux-starter-kit#635]
Hi, 

Is there any built-in way I can keep the test runner open and see it going?
just like other task runners to run tests such as gulp watch or watchify?
Should I have to write that portion myself to achieve that?

Thank you for the great redux repo!

**Comment by davezuko** [comment]
Hey, check out  `npm run test:dev`, that should be what you're looking for.

**Comment by zirho** [comment]
Thank you!
I'll try that

Have a nice week!
