### ISSUE TITLE
 Cannot find module 'eslint-config-standard-jsx' from ...

### ISSUE THREAD

**Issue by hetii** [davezuko/react-redux-starter-kit#636]
When use this project to generate new redux environment after npm run start I get:

Module build failed: Error: Cannot find module 'eslint-config-standard-jsx' from '.... /node_modules'

**Comment by hetii** [comment]
sorry this issue probably should be reported to https://github.com/SpencerCDixon/redux-cli

**Comment by davezuko** [comment]
Closing per your above comment, let me know if this should be an issue in this repo.
