### ISSUE TITLE
npm start fails on new-project branch

### ISSUE THREAD

**Issue by levivoelz** [davezuko/react-redux-starter-kit#638]
`Error: Cannot find module 'estraverse-fb'`

I added the 'estraverse-fb' package locally and `npm start` works.

**Comment by thangngoc89** [comment]
This is an upstream bug. https://github.com/eslint/eslint/issues/5476

**Comment by davezuko** [comment]
Need to update this branch (it's fixed on master), moving this issue into https://github.com/davezuko/react-redux-starter-kit/issues/638. Thanks for the report.
