### ISSUE TITLE
Issues with new-project branch

### ISSUE THREAD

**Issue by kyleect** [davezuko/react-redux-starter-kit#639]
There are actually two issues I'm seeing when following [Getting Started](https://github.com/davezuko/react-redux-starter-kit#getting-started) after running `npm run flow:check`

1) Version issue with flow in `.flowconfig`:

> .flowconfig:2 Wrong version of Flow. The config specifies version 0.22.0 but this is version 0.22.1

2) After fixing the first issue, I'm now seeing this when run

> src/main.js:5
  5: import { useRouterHistory } from 'react-router'
              ^^^^^^^^^^^^^^^^ Named import from module react-router. This module has no named export called useRouterHistory.
src/main.js:6
  6: import { syncHistoryWithStore } from 'react-router-redux'
                                          ^^^^^^^^^^^^^^^^^^^^ react-router-redux. Required module not found
src/main.js:13
 13:   basename: \_\_BASENAME__
                 ^^^^^^^^^^^^ identifier \_\_BASENAME__. Could not resolve name

**Comment by davezuko** [comment]
Need to get that branch up to date and then I will look into this, thanks.

**Comment by davezuko** [comment]
Also see https://github.com/davezuko/react-redux-starter-kit/issues/638.

**Comment by davezuko** [comment]
Rebased the branch, will update `flow-interfaces` library later to fix the flow errors.

**Comment by davezuko** [comment]
`flow-interfaces` has been updated to solve the immediate issues, will probably have to spend some more time on this later, but may wait for `flow-typed` to catch up and switch to that.

https://github.com/davezuko/react-redux-starter-kit/commit/fd5930ea69a3ed5ff53300e6eaf432f770ece0f3 fixes the `__BASENAME__` issue.
