### ISSUE TITLE
Deprecations?

### ISSUE THREAD

**Issue by chasm** [davezuko/react-redux-starter-kit#642]
On running `npm install` in a new project, I get the following:

```
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

**Comment by davezuko** [comment]
These are dependencies of our dependencies, so not much can be done beside reporting them in the appropriate projects. Thank you for bringing it up, though.

**Comment by chasm** [comment]
Yes, I realized that. But thought it would be good to have a list. I haven't had a chance to track down which modules have those dependencies yet. Thought they might have newer versions. Funny how we can never really escape dependency hell.

**Comment by davezuko** [comment]
@chasm I will do some digging this week, I just got back from vacation so will be making a bunch of PR's this week to update dependencies, which will hopefully clear up some of these warnings.

Was just trying to clean up some of the reported issues that I'd missed and keep them on target, so definitely not dismissing yours.

**Comment by davezuko** [comment]
See also https://github.com/erikras/react-redux-universal-hot-example/issues/1019

**Comment by richb-hanover** [comment]
See also https://github.com/shama/gaze/issues/212 (it's a twofer - both lodash@1.02 and graceful-fs@1.2.3) 

If anyone has Windows debugging skills, shama would like some help making the newest tests work for Windows.
