### ISSUE TITLE
Does the redux run in the server?

### ISSUE THREAD

**Issue by lockelee1015** [davezuko/react-redux-starter-kit#643]
At first.I'm so thankful for this repo.It help me a lot to build my webApp.
I have a question here.Does the redux run in the server?
What if I wanna do some fetch in action and the fetch is over origin ?
(I wanna build a docker management by this,how do I call api over origin)
thanks!

**Comment by kevinchiu** [comment]
I found this for you. It might help. http://redux.js.org/docs/recipes/ServerRendering.html

**Comment by davezuko** [comment]
Thank you for your kind words! See @kevinchiu 's helpful comment, it should explain most of this. If not, I recommend posting in this project's Gitter channel (it's a badge in the readme) as there are often people in there willing to answer more architectural/design questions. I don't believe this necessarily deserves an issue in this project, so going to close this for now, but we can continue discussing here if things are still unclear (just trying to clean up some of the issues).
