### ISSUE TITLE
Confirming navigation

### ISSUE THREAD

**Issue by ericwooley** [davezuko/react-redux-starter-kit#645]
I am trying to implement this
https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md

But can't seem to find a good way to get access to the router from a component.

Anyone have an idea?

**Comment by davezuko** [comment]
You should be able to access the router via context, see: https://github.com/reactjs/react-router/blob/master/docs/Troubleshooting.md#thiscontextrouter-is-undefined or https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#changes-to-thiscontext.

**Comment by ericwooley** [comment]
@davezuko Oh cool. I didn't realize it had all been moved to the history prop. Thanks!
