### ISSUE TITLE
 TypeError: requestThunk is not a function

### ISSUE THREAD

**Issue by leeir** [davezuko/react-redux-starter-kit#649]
sorry ，The problem has been found in the same issue

**Comment by leeir** [comment]
[issue](https://github.com/davezuko/react-redux-starter-kit/issues/558)   thanks !

**Comment by davezuko** [comment]
Is this still an issue for you, or are you on an older version of this project?

**Comment by leeir** [comment]
oh sorry my version is too old！I'll go under the bar Update， thanks

**Comment by davezuko** [comment]
Okie doke.
