### ISSUE TITLE
Is there a way to dispatch an event to another store from a store?

### ISSUE THREAD

**Issue by satjinder** [davezuko/react-redux-starter-kit#651]
Thanks for pulling together this, it is quite helpful. I want to dispatch event from one store to another, but the action handlers don't have access to dispatch method or the parent store.
For example if I have got a notifications module and want the counter module to add notification when counter reaches 100.

**Comment by davezuko** [comment]
You shouldn't be dispatching actions from the reducers (if I'm reading this correctly). Each reducer should handle the same action separately. Can you provide an example code snippet?

**Comment by godcore** [comment]
@satjinder probably meant the case when one state branch depends on another one. In such case you must either refactor your state tree to avoid this or handle conditions in your action creators (with thunk middleware).

```
function someActionCreator() {
  return (dispatch, getState) => {
    const { counter } = getState();

    if (counter  === 100) {
      dispatch(notify());
    }
  };
}
```

**Comment by satjinder** [comment]
Thanks for the replies, perhaps I was not clear in my questions. Lets me explain the example bit further. So I want some messaging component, which would display notifications, alerts etc, with its own store and module to handle actions such as SEND_ALERT, SEND_INFO, SEND_WARN etc.. Now if user has submitted a form, I want the reducer of that form to notify the message component about the success or failure by calling SEND_INFO or SEND_WARN. Similarly other modules can add the message/notification in the queue to inform user about certain actions. 

@godcore , This would mean that I have to convert all my action handlers to this someActionCreator  form, I would prefer not to. But if I could access dispatch function or the parent store in the action handlers, it solves the purpose. Not sure if that violates some design principle as @davezuko warned.

**Comment by neverfox** [comment]
> I want the reducer of that form to notify the message component about the success or failure by calling SEND_INFO or SEND_WARN

As @davezuko said, never ever ever dispatch actions from a reducer. It's the core no-no of redux. From the docs:

> the reducer must be pure. **Given the same arguments, it should calculate the next state and return it. No surprises. No side effects. No API calls. No mutations. Just a calculation.**

Instead, you want to respond to an action that relates to form submission and fire another action. This is a great case for using [redux-saga](https://github.com/yelouafi/redux-saga). You can write a saga that waits for the first action, then fires the appropriate actions in response).

**Comment by davezuko** [comment]
Thanks for the detailed response @neverfox. Regardless of what @satjinder ultimately chooses to do, this is not an issue with the starter kit. Feel free to continue posting here once the issue is closed, or heard to the gitter channel and/or the redux repo itself.
