### ISSUE TITLE
Update dependences

### ISSUE THREAD

**Issue by aralroca** [davezuko/react-redux-starter-kit#652]
There are a lot of dependences to update:

* babel-core  ^6.5.2  →      ^6.7.2 
* babel-loader  ^6.2.1  →      ^6.2.4 
* babel-plugin-transform-react-display-name  ^6.3.13  →      ^6.5.0 
* babel-plugin-transform-runtime    ^6.3.13  →      ^6.6.0 
* babel-polyfill   ^6.3.14  →      ^6.7.2 
* babel-preset-es2015  ^6.3.13  →      ^6.6.0 
* babel-preset-react    ^6.3.13  →      ^6.5.0 
* babel-preset-stage-0      ^6.3.13  →      ^6.5.0 
* babel-register    ^6.3.13  →      ^6.7.2 
* babel-runtime    ^6.3.19  →      ^6.6.1 
* body-parser   ^1.14.1  →     ^1.15.0 
* compression    ^1.6.0  →      ^1.6.1 
* express   ^4.13.3  →     ^4.13.4 
* express-session     ^1.12.1  →     ^1.13.0 
* hoist-non-react-statics     ^1.0.3  →      ^1.0.5 
* http-proxy     ^1.12.0  →     ^1.13.2 
* invariant   ^2.2.0  →      ^2.2.1 
* less   ^2.5.3  →      ^2.6.1 
* less-loader  ^2.2.1  →      ^2.2.2 
* lru-memoize  ^1.0.0  →      ^1.0.1 
* react   ^0.14.2  →     ^0.14.7 
* react-bootstrap    ^0.28.1  →     ^0.28.3 
* react-dom   ^0.14.1  →     ^0.14.7 
* react-helmet    ^2.2.0  →      ^2.3.1 
* react-inline-css   ^2.0.0  →      ^2.1.0 
* react-redux   ^4.0.0  →      ^4.4.1 
* redux    ^3.0.4  →      ^3.3.1 
* redux-async-connect   ^1.0.0-rc2  →  ^1.0.0-rc4 
* scroll-behavior  ^0.3.2  →      ^0.3.3 
* serialize-javascript   ^1.1.2  →      ^1.2.0 
* socket.io   ^1.3.7  →      ^1.4.5 
* socket.io-client  1.3.7  →      ^1.4.5 
* superagent   ^1.4.0  →      ^1.8.1 
* webpack-isomorphic-tools    ^2.2.18  →     ^2.2.31 
* autoprefixer-loader   ^3.1.0  →      ^3.2.0 
* babel-eslint  ^5.0.0-beta6  →      ^5.0.0 
* babel-plugin-react-transform   ^2.0.0  →      ^2.0.2 
* babel-plugin-typecheck   ^3.6.0  →      ^3.8.0 
* bootstrap-sass    ^3.3.5  →      ^3.3.6 
* bootstrap-sass-loader   ^1.0.9  →     ^1.0.10 
* chai    ^3.3.0  →      ^3.5.0 
* clean-webpack-plugin   ^0.1.6  →      ^0.1.8 
* eslint-loader   ^1.0.0  →      ^1.3.0 
* font-awesome   ^4.4.0  →      ^4.5.0 
* karma       ^0.13.10  →    ^0.13.22 
* karma-cli   ^0.1.1  →      ^0.1.2 
* karma-mocha   ^0.2.0  →      ^0.2.2 
* karma-sourcemap-loader   ^0.3.5  →      ^0.3.7 
* mocha   ^2.3.3  →      ^2.4.5 
* react-addons-test-utils    ^0.14.0  →     ^0.14.7 
* react-transform-catch-errors  ^1.0.0  →      ^1.0.2 
* react-transform-hmr    ^1.0.1  →      ^1.0.4 
* redbox-react      ^1.1.1  →      ^1.2.2 
* redux-devtools     ^3.0.0-beta-3  →      ^3.1.1 
* redux-devtools-dock-monitor   ^1.0.0-beta-3  →      ^1.1.0 
* redux-devtools-log-monitor    ^1.0.0-beta-3  →      ^1.0.5 
* sass-loader  ^3.1.2  →      ^3.2.0 
* sinon   ^1.17.2  →     ^1.17.3 
* strip-loader    ^0.1.0  →      ^0.1.2 
* webpack    ^1.12.9  →    ^1.12.14 
* webpack-dev-middleware   ^1.4.0  →      ^1.5.1 
* webpack-hot-middleware  ^2.5.0  →     ^2.10.0

**Comment by davezuko** [comment]
These are all using `^` for versioning, so the changes you mention (that I can see) are only superficial, both range specifications will install the same versions.

**Comment by davezuko** [comment]
Also note that we are using https://david-dm.org for dependency tracking: https://david-dm.org/davezuko/react-redux-starter-kit

**Comment by aralroca** [comment]
Ah okey, just I checked with npm-check-updates before use this project. Thank you! Is not possible to get conflicts in the future if all the dependences are with `^` for versioning?

By the way, good job with react-redux-starter-kit :+1:

**Comment by davezuko** [comment]
There is risk with it, since packages can always accidentally release breaking changes in a non-major version, but this is how many projects operate. Even if I locked all of the dependencies it wouldn't be completely safe since those dependencies don't lock their dependencies' versions (i.e. we could lock eslint to 2.4.0 but it may define its dependencies using `^`).

The only way to guarantee safety is to use shrinkwrap, but that's a bit too much for this project.

Hope that helps

**Comment by davezuko** [comment]
Thanks for the notice, but going to close this for now since there isn't any action required.
