### ISSUE TITLE
Empty Routes after npm run deploy

### ISSUE THREAD

**Issue by chapati23** [davezuko/react-redux-starter-kit#654]
Running locally via npm start works fine, but if I compile and access the index.html then my routes are always empty.

**Comment by davezuko** [comment]
What do you mean by empty? Are there any errors?

**Comment by chapati23** [comment]
my bad, the issue was that i just opened the generated index.html locally without a webserver. so of course browserHistory doesn't work. had to replace it with hashHistory.

might be worth mentioning in the README, though, in case other people make the same mistake.
