### ISSUE TITLE
Sample tests should include testing with React Router

### ISSUE THREAD

**Issue by tarjei** [davezuko/react-redux-starter-kit#660]
Hi, one issue I've often struggled with when testing React is the react-router integration. Therefore I would suggest that the example tests contain an example of how this is best integrated into the tests.

All and any input will be very welcome! The most basic need is to be able to check the href attribute of rendered links.

**Comment by davezuko** [comment]
Thanks for the request, added to consideration for `2.0.0` here: https://github.com/davezuko/react-redux-starter-kit/wiki/v2.0.0-Plans. Trying to keep feature requests from piling up in issues.
