### ISSUE TITLE
Feature request: add redux-immutable-state-invariant

### ISSUE THREAD

**Issue by jamesdwilson** [davezuko/react-redux-starter-kit#663]
https://github.com/leoasis/redux-immutable-state-invariant

**Comment by davezuko** [comment]
Not sure this warrants being included with the base kit, but it definitely deserves a mention in the FAQ or recipes section. Moved to feature consideration for `2.0.0`, thank you!

**Comment by jokeyrhyme** [comment]
This isn't necessary if you're using Immutable.js, which is effortlessly wired up for you by [redux-bootstrap](https://github.com/redux-bootstrap/redux-bootstrap) :D :electric_plug:
