### ISSUE TITLE
HELP for npm start error "better-npm-run"

### ISSUE THREAD

**Issue by a757375927** [davezuko/react-redux-starter-kit#664]
![qq 20160323142335](https://cloud.githubusercontent.com/assets/5990860/13977315/f4afc20e-f102-11e5-940a-a6f366d4a598.png)

**Comment by a757375927** [comment]
more information
![qq 20160323151531](https://cloud.githubusercontent.com/assets/5990860/13978200/3ccee0fe-f10a-11e5-8b21-4b195589677a.png)

**Comment by rohanpujaris** [comment]
+1 Same issue. Using node v4.4.0 and npm v2.14.20.

**Comment by davezuko** [comment]
This project does not support npm2, unfortunately -- it's too much hassle to ensure dependencies resolve correctly due to how different the installers are between v2 and v3.

If you can reproduce on npm3 please let me know and we can re-open and investigate further.

**Comment by rohanpujaris** [comment]
Thanks @davezuko. Works fine with npm3

**Comment by a757375927** [comment]
i update npm 3.7.3 but it still this error  @rohanpujaris @davezuko

**Comment by marksb** [comment]
@a757375927 

I ran into this issue earlier and it worked when I upgraded. I am using `node v4.4.1` and `npm 3.7.3`

**Comment by rohanpujaris** [comment]
@a757375927 delete node_modules folder and do npm install again. It should work

**Comment by a757375927** [comment]
@rohanpujaris i do as you say and it work! i spend two day and more for this = =, thank you very much!

**Comment by rohanpujaris** [comment]
np @a757375927

**Comment by nilamben** [comment]
Hi, I am facing the same issue. Can anyone help me out?
 I have node 4.5.0 and npm 3.10.6.  I have also tried with remove node modules and reinstall it. Still it is not working.

**Comment by lanc8** [comment]
I have the same problem. I am using Node node v7.2.0 and npm  v3.10.9. Can anyone help me?

**Comment by davezuko** [comment]
@nilamben and @lanc8 , what OS are both of you using?

**Comment by lanc8** [comment]
@davezuko . I am using Windows 7: Windows_NT 6.1.7601. Thanks for your reply.

**Comment by lanc8** [comment]
Are there any ways to solve this issue? :(

**Comment by davezuko** [comment]
@lanc8 Pull the latest copy of master. A recent commit had a breaking change which looks to be the issue you're having.
