### ISSUE TITLE
Unlock webpack-dev-middleware

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#667]
See: https://github.com/davezuko/react-redux-starter-kit/issues/666

**Comment by mgmcdermott** [comment]
This was fixed for me in webpack-dev-middleware@1.6.1.

View this commit: https://github.com/webpack/webpack-dev-middleware/compare/v1.6.0...master
The change from req.url to req.path was reverted.

**Comment by davezuko** [comment]
Thanks @mgmcdermott , this has been bumped.
