### ISSUE TITLE
Require a module before React

### ISSUE THREAD

**Issue by davidsteinberger** [davezuko/react-redux-starter-kit#668]
This is actually not really an issue, more a config question.

I wanted to include [react-polymer](https://github.com/jscissr/react-polymer) in my start-kit-project, however, no matter where I do a `import reactPolymer from 'react-polymer';` I always get an error like:  `Uncaught Error: react-polymer must be required before react`. Is there a way to configure webpack to import this module first?

**Comment by anatoliyarkhipov** [comment]
Did you try to place `react-polymer` in this file before `react`?

https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_base.js

**Comment by davidsteinberger** [comment]
In the `compiler_vendor` array? Well yes, but that won't work. I need a reference to that module in some view, but I can't import it there before like:

    import reactPolymer from 'react-polymer';
    import React, { PropTypes } from 'react'

**Comment by anatoliyarkhipov** [comment]
Yes, I mean `compiler_vendor`. I just tried this and looks like it works:

```
  compiler_vendor : [
    'history',
    'react-polymer', // <---
    'react',
    'react-redux',
    'react-router',
    'react-router-redux',
    'redux'
  ],
```

This config works fine, but it throws the error when I put `react-polymer` after `react`.

**Comment by davidsteinberger** [comment]
That doesn't work for me. Are you able to include it in e.g.: `src/views/HomeView/HomeView.js` without an error then?

**Comment by anatoliyarkhipov** [comment]
Yep, I see only the warning about Polymer:

![image](https://cloud.githubusercontent.com/assets/1934180/14044850/29207216-f2ae-11e5-9e6c-acf7040549ee.png)

Can you publish your repo?

**Comment by davidsteinberger** [comment]
Sure: https://github.com/davidsteinberger/react-polymer-test; I thought I haven't changed that much, but apparently I did manage to break it.

**Comment by anatoliyarkhipov** [comment]
Looks like that you are using bower to install some deps?

**Comment by davidsteinberger** [comment]
Yes ;-(. Is there some way to include Polymer w/o bower? I think the mentioned issue came from me having react-polymer in the dev-deps. Is there a way to to tell webpack to export Polymer as a global before any other modules are loaded?

**Comment by anatoliyarkhipov** [comment]
For some reasons webpack is compiling `react-polymer` into the `app.js` instead of `vendor.js`, even if we add the dependency to the `compiler_vendor` array. I have no idea why it happens. And it's causes the problem. 

But if we place `react-polymer` dependency directly in the `build/webpack.config.js` file, like this (line 33):

```js
  vendor: [
    'react-polymer',
    ...config.compiler_vendor
  ]
```

then it works fine. I tried this in your repo and the error has gone.

**Comment by davezuko** [comment]
Closing as resolved since this is not an issue directly related to the starter kit. Feel free to continue the discussion, though.

**Comment by davidsteinberger** [comment]
Sorry, wanted to close this on the weekend, but had fallen sick. @anatoliyarkhipov thanks for your help!
