### ISSUE TITLE
Password protect a route?

### ISSUE THREAD

**Issue by kevinchiu** [davezuko/react-redux-starter-kit#671]
Is there a simple way to password protect a specific route? For example, if I'm trying to protect /admin for a website, what is the simplest thing I could do?

**Comment by ppiekarczyk** [comment]
This uses a higher order component technique:

https://github.com/joshgeller/react-redux-jwt-auth-example

**Comment by davezuko** [comment]
@ppiekarczyk 's is a great example, or you could just make use of the route's `onEnter` hook to check against the store (or some other source of truth) to determine whether the user is allowed to continue or not. We've also used the following approach:

```js
<Route onEnter={verifyAuthentication}>
  <Route path='/' component={Dashboard} />
  {/* more routes... */}
</Route>
```

Which will run that hook for each route, without having to explicitly add authentication to each individual route.

Will keep this open for another day or two to encourage discussion, but ultimately it's not an issue with the starter kit so I will close it after that. Feel free to continue the discussion here or head to the gitter channel; react-router docs/issues/chat would also be helpful, I imagine.

**Comment by davezuko** [comment]
@ppiekarczyk probably depends on the app, but every route in our apps is password protected, so we just created a single top-level route to handle the authentication logic. Every route below that can just be a normal component without their own `onEnter` hooks.

**Comment by davezuko** [comment]
Closing as resolved, I recommend using the gitter channel for longer discussions. Thanks!

**Comment by abury** [comment]
For future readers, [here](https://gist.github.com/abury/dc2448bfa70bcb1b04f773ade883e5f9) is an example of auth using Plain routes:

I really struggled to get this to work as all the examples I read up on (including tickets in this repo) are using JSX routing (which is a tad frustrating given that this project uses plain routing). Maybe it's just a beginner thing.

**Comment by brandonmp** [comment]
super helpful, thanks @abury. for some reason, when I'd pass an `onEnter` function to one route, but not others, all routes would call it. 

passing a generic `public()` function to public routes, as you did, did the trick

**Comment by mikedevita** [comment]
i have two parent routes `/auth/` and `/app` i have an `onEnter` on `/app that checks auth for its route and all child routes.
