### ISSUE TITLE
Need Help - Error: Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by yans3n** [davezuko/react-redux-starter-kit#672]
i got errors like : 
```
ERROR in ./src/layouts/CoreLayout/CoreLayout.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../components/Footer/Footer in /home/taralite-account/taralite-ui-akun-saya/src/layouts/CoreLayout
 @ ./src/layouts/CoreLayout/CoreLayout.js 46:14-55
```
when npm run compile.
i use npm v3.3.12 & node v5.5.0, OS ubuntu 14

thanks

**Comment by davezuko** [comment]
Can you link to your branch/fork?

**Comment by yans3n** [comment]
https://github.com/yans3n/react-redux-starter-kit-express
thats my link,
on my mac os 100% work perfectly, but when i try to compile on my ubuntu server i got that error

thanks

**Comment by yans3n** [comment]
sorry its totally my fault, something wrong with foldering, i just rename from lower case to uppercase, but on bitbucket didn't change.
thanks for reply
love this starter kit so much, well done
i will close this issue
