### ISSUE TITLE
Where does the webpack configuration live? [Webpack is slow]

### ISSUE THREAD

**Issue by ppiekarczyk** [davezuko/react-redux-starter-kit#673]
I'll start off by saying this is awesome and you've definitely made my life a little easier!

My only concern is that everything is tucked away and it's hard to debug webpack.

For example, my webpack build time has gotten **really** slow and my project isn't even that big yet. It might be `eslint` or it might be babel parsing `node_modules`, but right now I have no easy way to figure out what the bottleneck may be.

I did a quick search for `loader` and then `sass-loader` but it looks like they're all abstracted out somewhere in a node module.

Is there a specific package I can peek in?

Thanks again,
Peter

**Comment by davezuko** [comment]
`eslint-loader` is _ridiculously_ slow, so the first thing I'd do is disable that (I have plans to). The entire configuration is located in a single file (https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js) which is much better than it used to be (spread out across multiple files). It does use some configuration options from `~/config`, but those are mostly global declarations and things of that nature, not anything crazy.

The only craziness really occurs with the logic for selectively enabling CSS modules, but other than that hopefully it's documented well enough. Feel free to ping me w/ any further questions though.

**Comment by ppiekarczyk** [comment]
Didn't even think about searching something besides `sass-loader`! Silly me. Thank you!

**Comment by davezuko** [comment]
Awesome, let me know how disabling eslint-loader goes; personally, our team saw a drastic reduction (~2-3x in build/rebuild times). If it's still unreasonably slow after that point let me know, but there really is not _too_ much going on in our webpack configuration that would be it noticably slower than configs with similiar features.

**Comment by ppiekarczyk** [comment]
Eslint did the trick. Rebuilds are almost instant!

Thanks,

Peter Piekarczyk

https://twitter.com/peterpme
http://github.com/ppiekarczyk

On Tue, Mar 29, 2016 at 7:26 AM David Zukowski

<
mailto:David Zukowski <notifications@github.com>
> wrote:

Awesome, let me know how disabling eslint-loader goes; personally, our team saw a drastic reduction (~2-3x in build/rebuild times). If it's still unreasonably slow after that point let me know, but there really is not

too

much going on in our webpack configuration that would be it noticably slower than configs with similiar features.

**Comment by davezuko** [comment]
Removed with https://github.com/davezuko/react-redux-starter-kit/commit/c336108000c8006a61d95a4169d8f47c5f16fa6f.
