### ISSUE TITLE
Browser caching and deep URLs

### ISSUE THREAD

**Issue by egeriis** [davezuko/react-redux-starter-kit#676]
Hi there!

We're using this awesome starter kit in all our front-end projects at Dixie.io, and are very happy doing so.

To put the following question into context, we're serving our React apps through nginx with `Cache-Control: no-cache` and `ETag`s. This means that the browser should cache our static files as long as the server responds with 304 Not Modified.

But a caveat we haven't been able to find a solution for, is the ability to have the browser understand that all URLs within a certain "namespace", e.g. `/app`, will serve the browser with the same markup. 
So for each URL in our SPA the browser will cache the markup, meaning that caching is not utilized for `/app/deep-url` if the browser has yet to visit the app on this URL to bootstrap the app.

Does anyone in this community know of a solution with this regard—or are we so much ahead in terms of the power of JavaScript and History manipulation, that browser caching is yet to follow?

Hope to hear your thoughts 🙃

**Comment by davezuko** [comment]
Sorry to see that this went neglected for so long. At the time I had nothing to add to help, but left it open hoping somebody else would be able to help you out. It appears as though that's not the case, so I'm going to close this in an effort to clean up some of the inactive issues. Sorry again, good luck with everything.

**Comment by egeriis** [comment]
@davezuko No worries Dave. My assumption is that there is no resolution for this issue at the moment. I haven't been able to track down any notes on in. Someday, maybe 🎉
