### ISSUE TITLE
keep my project up to date with react-redux-starter-kit?

### ISSUE THREAD

**Issue by chovy** [davezuko/react-redux-starter-kit#692]
Thanks for putting this together, its a great way to start doing react without knowing much about webpack.

I used the angular-fullstack-generator previously, and one of the problems I had was once I forked and created my project from it, I no longer got any updates (ie: bug fixes, etc).

I followed the guide here to get started, I cloned this repo, made a branch called `new-project` then deleted the .git directory.

How should I pull in changes upstream into my local project?

**Comment by davezuko** [comment]
Hey, this has been brought up a few times. Unfortunately there is not an automated way to do this just yet. However, if you check out [this issue](https://github.com/davezuko/react-redux-starter-kit/issues/545), I mentioned:

> To come. We actually use a modified version of this boilerplate at my work, and have an update utility that will sync all apps based on the template to include the latest changes, but it's not yet open sourced. If that changes, I will definitely let you know.

There are a couple of other issues scattered about with this question, and it's been brought up in the gitter channel, so there's definitely a demand. I will try to push our team to open source the tool when work dies down a bit, but for now I can't offer much beyond that. I try my best to provide good release notes and clean commit messages, which should make following commit history easier, so maybe that offers some solace in the meantime.

**Comment by chovy** [comment]
Is there anyway I can just have an upstream remote that pulls in changes without deleting files?

**Comment by bhj** [comment]
Take a look at https://help.github.com/articles/syncing-a-fork/

**Comment by davezuko** [comment]
@chovy it's a fairly simple script, it clones the master repo to a `/temp` directory and compares a list of tracked files (webpack config, karma config, etc.) between the local project and the template, overriding the local files that are found to be out of date (we use the `diff` module to pretty print changes). The key piece is that it's not simply merging a remote project onto the local one, since we only care about tracking certain files.

**Comment by chovy** [comment]
@davezuko thanks. I will do something like this. I guess the question is which critical files should I track?

I see bug fixes like fixes to the history api in the router, etc. Those are the sorts of changes I want synced back to my project.

**Comment by davezuko** [comment]
We track the following:

```
/bin/**
/build/**
/config/**
.babelrc
.flowconfig
.eslintingore
.eslintrc
package.json
```

I forgot to mention, the other part of the script is that it smartly merges package.json diffs, but that should be fairly easy to handle manually in the event that conflicts arise (unlikely).

**Comment by chovy** [comment]
I see master has just been upgraded to 2.0 alpha -- I'm on previous version is there a maintenance branch for 1.x I can track updates on? I don't see one.

**Comment by davezuko** [comment]
@chovy there is not, sorry. If I receive bug reports from an older version I do go back and push fixes, such as https://github.com/davezuko/react-redux-starter-kit/releases/tag/v1.0.1, but there is no dedicated branch for older versions, they are generally just meant as tagged known-stable releases so people are able to safely clone the template.

**Comment by chovy** [comment]
Is there a list of breaking changes between 1.x and 2.x?

**Comment by davezuko** [comment]
Just the `2.0.0` release notes: https://github.com/davezuko/react-redux-starter-kit/releases/tag/v2.0.0-alpha.0. There aren't that many _removals_, it's more just fixes, cleanup, and additions.

Closing since there is not any action for us to take on this. Happy to keep helping, though.
