### ISSUE TITLE
browserHistory.push() not updating router state

### ISSUE THREAD

**Issue by gaborluk** [davezuko/react-redux-starter-kit#695]
I'm doing this in a component:
```javascript
import { browserHistory } from 'react-router'
...
browserHistory.push(`/route/${someParam}`)
```
The URL in the address bar gets updated without any problem, however, in the `mapStateToProps` of the component's parent view, `ownProps.location` and `ownProps.params` are not updated – they still contain the old location's data.

I've read https://github.com/davezuko/react-redux-starter-kit/pull/541 and have updated the kit to contain the current latest versions of `main.js`, `configureStore.js`, and `rootReducer.js`, as well as updated the affected Node modules, but the issue persists.

I've seen suggested the use of `this.context.router` instead, but my `this.context` does not contain a `router`, so this might have been outdated information.

I do have a `history` in `ownProps` which seems to expose methods such as `push`, however, when I use that, I receive a deprecation warning.

Does anyone know what's the current state of this, and what is the desired way of performing a navigation with proper state updates from within a component?

Thanks in advance, guys.

**Comment by davezuko** [comment]
For context, make sure you're defining `contextTypes` or you won't actually have access to it. Just tested:

```js
export class HomeView extends React.Component<void, Props, void> {
  static propTypes = {
    counter: PropTypes.number.isRequired,
    doubleAsync: PropTypes.func.isRequired,
    increment: PropTypes.func.isRequired
  };

  static contextTypes = {
    router: PropTypes.object,
  };

  _handleNavigate () {
    this.context.router.push('/foo')
  }

// ...
```

And it works as expected. Not sure why the changes made by `browserHistory.push` are not reflected in the store, since I thought react-router-redux was supposed to sync. Give the example above a shot first, though.

**Comment by agoransson** [comment]
I have the same issue, `this.context.router` doesn't seem to exist. `this.props.history.push` works like a charm (if I ignore the warning). I cloned the project fresh this morning.

Here's the full component for reference, nothing fancy as you can see...

```
export class LoginView extends React.Component<void, Props, void> {
  static propTypes = {
    login: PropTypes.func.isRequired,
    user: PropTypes.object.isRequired
  };
  constructor (props) {
    super(props)
    this.doLogin = this.doLogin.bind(this)
  }
  doLogin (form) {
    this.props.login(form.username, form.password)
  }
  componentWillReceiveProps (nextProps) {
    if (nextProps.user.token && !nextProps.user.isUpdating) {
      this.props.history.push('/')
    }
  }
  render () {
    return (
      <div className={classes.container}>
        <Panel className={classes.formWrapper}>
          <LoginForm onSubmit={this.doLogin} />
        </Panel>
      </div>
    )
  }
}

const mapStateToProps = (state) => ({
  user: state.user
})
export default connect((mapStateToProps), {
  login
})(LoginView)
```

**Comment by agoransson** [comment]
Adding

```
static contextTypes = {
  router: PropTypes.object,
};
```

as @davezuko says worked for me.

**Comment by davezuko** [comment]
Awesome. Going to close this as I'm convinced it's just misunderstandings of various API's and not directly related to this project.

**Comment by gaborluk** [comment]
Indeed, I merely needed this snippet, I somehow missed that part. Thank you both for the help, gentlemen.

**Comment by fewspider** [comment]
@davezuko  thanks a lot

**Comment by andresgutgon** [comment]
I was having the same issue with `ownProps` not updating `params` on redux connect `mapStateToProps` function.

I changed from returning a function to returning an object and `browserHistory.push` worked as expected
``` javascript

// NOT WORKING returning function 
const mapStateToProps = (_state, ownProps) => {
  return (state) => {
    return {
       something: state.something[ownProps.params.id];
    }
  }
}

// WORKING returning object 
const mapStateToProps = (_state, ownProps) => {
  return {
     something: state.something[ownProps.params.id];
  }
}

```
