### ISSUE TITLE
Including images in CSS

### ISSUE THREAD

**Issue by marcelloromanelli** [davezuko/react-redux-starter-kit#696]
Is it possible to include images in CSS in a similar way as it is done on a JSX component?
```
.gallery:before {
	content: '';
	width: 100px;
	height: 100px;
	display: inline-block;
	background: url('/gallery_mini.png');
}
```
with the above code the build is successful but I cannot see the image on the app (it does not get inlined). Any idea what I'm doing wrong? Is this even possible?

This is the produced output
```
.AdPromoteModal__gallery___2ymzT:before {
    content: '';
    width: 100px;
    height: 100px;
    display: inline-block;
    background: url(/gallery_mini.png);
}
```

**Comment by davezuko** [comment]
Webpack does not look for/inline images referenced in the styles, it only does that when you are importing an image inside of your JS.

If you want to reference a static image from your styles, you should put your image in the static files (possibly `static/images/foo.png` and reference it as `url(/images/foo.png)`). There's probably a different way to do this, but my early morning brain can't think of it at this time. You may also want to reference https://github.com/davezuko/react-redux-starter-kit/issues/369.

**Comment by marcelloromanelli** [comment]
Thanks for the super quick reply @davezuko !

**Comment by davezuko** [comment]
No problem. Ping me if you are still having issues and we can reopen.

**Comment by colinshen** [comment]
@davezuko  followed the way you said. 
I put image in static/images/bg.jpg, and used it in scss like
```
.auth{
  height: 100%;
  background: url('/images/bg.jpg') no-repeat center center fixed;
  background-size: cover;
  position: relative;
}
```

No errors, but the images didn't show, 
chrome dev
```
.Auth__auth___34Ell {
    height: 100%;
    background: url(/images/background.jpg) no-repeat 50% fixed;
    background-size: cover;
    position: relative;
}
```
right click url to check the image, I got this   
chrome-devtools://devtools/images/background.jpg

**Comment by sokal1** [comment]
Hello, @davezuko I am having same issue as @colinshen 
Image URL resolve to chrome-devtools://devtools/images/background.jpg
Could you please provide some advice ?

**Comment by AlexSandiyarov** [comment]
+1

**Comment by romanenko** [comment]
Same situation.

![image](https://cloud.githubusercontent.com/assets/336141/15967528/e31e8f22-2f49-11e6-8b06-4f9cfbe80b0f.png)

If I just re-type generated `url(/images/bg.jpg)` in the element.style section above — it works. I still don't understand what's wrong, but, maybe, this will help to investigate this issue.

**Comment by tsi** [comment]
Same issue here

**Comment by chuchangming** [comment]
Same issue here
