### ISSUE TITLE
Module not found: Error: Cannot resolve module

### ISSUE THREAD

**Issue by tusharchhibber** [davezuko/react-redux-starter-kit#699]
I get this error while running npm run test. 
I guess I messed up some config somewhere that takes care of setting the relative path right in the tests files and can't figure out where or how.
I think the configuration related to this is webpack [resolve.root](http://webpack.github.io/docs/configuration.html#resolve-root) which is also used in karma.conf.js. I have not changed them but still its giving me this error.
Any help is appreciated. 

`ERROR in ./tests/layouts/CoreLayout.spec.js
Module not found: Error: Cannot resolve module 'layouts/CoreLayout' in /Users/tusharc/Documents/react-redux-starter-kit/tests/layouts
 @ ./tests/layouts/CoreLayout.spec.js 11:18-49
07 04 2016 23:20:55.319:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
07 04 2016 23:20:55.343:INFO [launcher]: Starting browser PhantomJS
07 04 2016 23:20:56.396:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#lj7JqRtJbbrWysZLAAAA with id 22794440
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "layouts/CoreLayout"
  at  /Users/tusharc/Documents/react-redux-starter-kit/tests/test-context.js:8724 <- webpack:///tests/layouts/CoreLayout.spec.js:3:0
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "layouts/CoreLayout"
  at /Users/tusharc/Documents/react-redux-starter-kit/tests/test-context.js:8724 <- webpack:///tests/layouts/CoreLayout.spec.js:3:0

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.114 secs / 0 secs)

Finished in 0.114 secs / 0 secs`

**Comment by davezuko** [comment]
Could you link to a branch or commit?

**Comment by davezuko** [comment]
These are the core lines in the karma config as far as `resolve.root` is concerned: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/karma.conf.js#L29-L35. It's not explicitly shown in that snippet, but it's being spread into the overrides from the base webpack config, which is imported from here: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L18

**Comment by tusharchhibber** [comment]
@davezuko Thanks for the prompt reply. I figured that out last night and now when I run my tests it gives me back this:-

`START:
08 04 2016 10:44:35.075:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
08 04 2016 10:44:35.090:INFO [launcher]: Starting browser PhantomJS
08 04 2016 10:44:36.222:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#9fBECzPsmcGN5WozAAAA with id 1641761
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Invariant Violation: _registerComponent(...): Target container is not a DOM element.
  at /Users/tusharc/Documents/react-redux-starter-kit/tests/test-context.js:9701
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Invariant Violation: _registerComponent(...): Target container is not a DOM element.
  at /Users/tusharc/Documents/react-redux-starter-kit/tests/test-context.js:9701

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.493 secs / 0 secs)


Finished in 0.493 secs / 0 secs

SUMMARY:
✔ 0 tests completed
`
If I just use a single file say at 'tests/layout/CoreLayout.spec.js' to test by changing the Karma config to 

`  files: [
    './tests/layouts/CoreLayout.spec.js'
  ],
  singleRun: true,
  frameworks: ['mocha'],
  // frameworks: ['mocha', 'chai-sinon', 'chai-as-promised', 'chai'],
  preprocessors: {
    'tests/layouts/CoreLayout.spec.js': ['webpack']
  },`

It gives me this: 
'START:
08 04 2016 10:56:30.923:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
08 04 2016 10:56:30.934:INFO [launcher]: Starting browser PhantomJS
08 04 2016 10:56:31.887:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#dMxrMyXvxO66Yw_WAAAA with id 98203187
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
  at /Users/tusharc/Documents/OrionTushar/Dev/SrcCode/PopHealthExplorer/population-health-explorer/web/cohort-builder-web/tests/layouts/CoreLayout.spec.js:10282
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
  at /Users/tusharc/Documents/OrionTushar/Dev/SrcCode/PopHealthExplorer/population-health-explorer/web/cohort-builder-web/tests/layouts/CoreLayout.spec.js:10282

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.277 secs / 0 secs)


Finished in 0.277 secs / 0 secs

SUMMARY:
✔ 0 tests completed
'

Any idea what this is?

Thanks & Regards

**Comment by davezuko** [comment]
Looks like you need the phantomjs bind polyfill, https://github.com/davezuko/react-redux-starter-kit/blob/master/build/karma.conf.js#L12

**Comment by tusharchhibber** [comment]
@davezuko Yaa, if I have that i get this error

`START:
08 04 2016 10:44:35.075:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
08 04 2016 10:44:35.090:INFO [launcher]: Starting browser PhantomJS
08 04 2016 10:44:36.222:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#9fBECzPsmcGN5WozAAAA with id 1641761
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
Invariant Violation: _registerComponent(...): Target container is not a DOM element.
at /Users/tusharc/Documents/react-redux-starter-kit/tests/test-context.js:9701
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
Invariant Violation: _registerComponent(...): Target container is not a DOM element.
at /Users/tusharc/Documents/react-redux-starter-kit/tests/test-context.js:9701

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.493 secs / 0 secs)

Finished in 0.493 secs / 0 secs

SUMMARY:
✔ 0 tests completed`


My karma.conf.js looks like this:

`  files: [
    './node_modules/phantomjs-polyfill/bind-polyfill.js',
    {
      pattern: `./${config.dir_test}/test-context.js`,
      watched: false,
      served: true,
      included: true
    }
  ],
  singleRun: true,
  frameworks: ['mocha'],
  // frameworks: ['mocha', 'chai-sinon', 'chai-as-promised', 'chai'],
  preprocessors: {
    [`${config.dir_test}/test-context.js`]: ['webpack']
  },`

**Comment by davezuko** [comment]
As far as: `Invariant Violation: _registerComponent(...): Target container is not a DOM element.`, I'd have to see your tests. This just looks like a code mistake.

**Comment by davezuko** [comment]
I'm closing this only because it's not directly an issue with the starter kit, but with your specific project overrides. This is not at all ending the discussion, I'm more than willing to keep helping, but just closing it for record keeping purposes. If you could link me to your tests or post a failing snippet per my above note that would help me troubleshoot the issue.
