### ISSUE TITLE
Use proptypes-parser for cleaner PropTypes

### ISSUE THREAD

**Issue by joonhocho** [davezuko/react-redux-starter-kit#703]
I've created [proptypes-parser](https://github.com/joonhocho/proptypes-parser) to make it easier to write PropTypes for React components.

Instead of writing

```javascript
const propTypes = {
  number: PropTypes.number,
  string: PropTypes.string.isRequired,
  boolean: PropTypes.bool,
  function: PropTypes.func.isRequired,
  date: PropTypes.instanceOf(Date).isRequired,
  object: PropTypes.object.isRequired,
  shape: PropTypes.shape({
    nested: PropTypes.number,
    array: PropTypes.arrayOf(PropTypes.number),
    must: PropTypes.bool.isRequired,
  }).isRequired,
  array: PropTypes.arrayOf(
    PropTypes.Number.isRequired,
  ).isRequired,
  arrayOfObjects: PropTypes.arrayOf(
    PropTypes.shape({
      value: PropTypes.string,
    }).isRequired
  ),
  node: PropTypes.node
  element: PropTypes.element.isRequired,
  message: PropTypes.instanceOf(Message).isRequired,
  any: PropTypes.any.isRequired,
};
```
Write
```javascript
const propTypes = parsePropTypes(`{
  number: Number
  string: String!
  boolean: Boolean
  function: Function!
  date: Date!
  object: Object!
  shape: {
    nested: Number
    array: [Number]
    must: Boolean!
  }!
  array: [Number!]!
  arrayOfObjects: [{
    value: String
  }!]
  node: Node
  element: Element!
  message: Message!
  any: Any!
}`);
```
It's cleaner, easier, and less error-prone way to write PropTypes.
It's also fast!

I will be happy to make PR if you'd like to use it.

**Comment by anatoliyarkhipov** [comment]
Just to clarify, you can also write `propTypes` like this:

```
const propTypes = {
  number: number,
  string: string.isRequired,
  boolean: bool,
  function: func.isRequired,
  date: instanceOf(Date).isRequired,
  object: object.isRequired,
  shape: shape({
    nested: number,
    array: arrayOf(PropTypes.number),
    must: bool.isRequired,
  }).isRequired,
  array: arrayOf(
    number.isRequired,
  ).isRequired,
  arrayOfObjects: arrayOf(
    shape({
      value: string,
    }).isRequired
  ),
  node: node
  element: element.isRequired,
  message: instanceOf(Message).isRequired,
  any: any.isRequired,
}
```

**Comment by joonhocho** [comment]
That's true, but that requires many local variables and could cause some name collisions. I personally think it's cleaner to define PropTypes with string.

**Comment by davezuko** [comment]
This is cool, and I appreciate the suggestion, but in an effort to reach as wide of an audience and possible while simultaneously limiting the number of new concepts introduced, I'd like to hold off for now. I'm personally a big fan of using Flow over propTypes anyways since they are statically analyzable, so if we go further in any direction my guess is that will be it. I will leave this open for another day or so though to get you a bit more exposure in case anybody else is lurking in the issues board.

**Comment by marshallford** [comment]
I can see this helper/parser being very useful for those writing a ton of propTypes however I would agree with @davezuko that this project should focus on a more "classic" approach. I would hate for someone new to React or Redux to be confused over the amount of "magic" tooling used to abstract away the "hard" parts of the React/Redux world. Infact, in my opinion placing Flow into the project is already pushing it a bit.

Side note: Thank you @davezuko for your great work. As a longer time lurker I appreciate your continued improvements and maintenance.

**Comment by joonhocho** [comment]
Thank you for your opinions. I will close this issue. :)
