### ISSUE TITLE
npm start (fresh install) errors

### ISSUE THREAD

**Issue by Jasperras** [davezuko/react-redux-starter-kit#705]
Hi, running npm start after fresh install which i checked out to the new-project branch. I did run npm install which went OK.

Stack trace:
[npm-debug.txt](https://github.com/davezuko/react-redux-starter-kit/files/213610/npm-debug.txt)

**Comment by davezuko** [comment]
May just have to update the branch. Does master work for you?

**Comment by Jasperras** [comment]
Hi, both have not worked so far sadly. Updating had no success aswell. I have also tried installing babel, babel-cli and better-npm-run globally because it seemed like either one of those couldn't be found on the path. However that didn't do anything, still the same error msg.

**Comment by davezuko** [comment]
@Jasperras do you have issues running any other major starter kits or node projects? I'm at a bit of a loss here at the moment, unfortunately.

**Comment by Jasperras** [comment]
@davezuko It seems fixed now after running npm update. Might have been a dependency? Still kind of clueless, but windows' filesystem has given me more problems along the way and i've learnt that using short paths tends to solve alot of these problems.

**Comment by davezuko** [comment]
Sometimes doing `npm run rebuild` can help as well since that will rebuild your local binaries.

**Comment by davezuko** [comment]
Closing since this is technically resolved, but would still like to know what exactly caused it.
