### ISSUE TITLE
webstorm doesn't like HomeView.js

### ISSUE THREAD

**Issue by chovy** [davezuko/react-redux-starter-kit#708]
![screenshot 2016-04-11 21 22 44](https://cloud.githubusercontent.com/assets/27381/14449730/9c13006a-002b-11e6-9c31-3a998aeb1232.png)

**Comment by davezuko** [comment]
I know for a fact webstorm can work with flow since we use it [flow] at work and some of the team uses webstorm. I don't personally know what their setup is, but you may want to try the following:

http://blog.jetbrains.com/webstorm/2015/09/webstorm-11-eap-142-5255/

**Comment by anthonyettinger** [comment]
Is there anyway to remove flow? I don't want it.

**Comment by davezuko** [comment]
Remove the config, npm script, and dependency. Even with to those there's nothing forcing you to use it.

**Comment by davezuko** [comment]
Also you can just omit the `/* @flow */` pragma, in which case your code will not be type checked (and therefore the flow scripts/etc. are irrelevant). The dependencies only truly need to be removed if you're keeping your dependencies slim. Closing since the original question is resolved.
