### ISSUE TITLE
Add option for linting during development without deprecating eslint-loader entirely

### ISSUE THREAD

**Issue by jflayhart** [davezuko/react-redux-starter-kit#713]
Some of us want to still have the option to run lint during development, but without having to comment and uncomment the webpack config code. For example, `npm run dev` works the same, but if I want to lint while I develop I will use `npm run dev:lint`. Just another script feature.

Prototyped this in a PR:
https://github.com/davezuko/react-redux-starter-kit/pull/712

**Comment by davezuko** [comment]
Awesome, appreciate the PR. I will consider this (it's completely reasonable) but just want to make sure I'm not flip-flopping on things by simply throwing them behind flags. Let's continue the discussion in your PR, though.

Thanks for the contribution.
