### ISSUE TITLE
Globally providing routes

### ISSUE THREAD

**Issue by mariotacke** [davezuko/react-redux-starter-kit#721]
I'm trying to provide a global object to my code through the `_base.js` configuration and its overrides. I tried to follow the [docs](https://github.com/davezuko/react-redux-starter-kit/#globals) on globals but get an undefined error for any custom globals. `__DEV__` and other predefined ones work correctly.

My goal is to provide environment specific routes. Maybe there is a better way to do this?

Here is my globals section in `_base.js`:

```js
config.globals = {
  'process.env'  : {
    'NODE_ENV' : JSON.stringify(config.env)
  },
  'NODE_ENV'     : config.env,
  '__DEV__'      : config.env === 'development',
  '__PROD__'     : config.env === 'production',
  '__TEST__'     : config.env === 'test',
  '__DEBUG__'    : config.env === 'development' && !argv.no_debug,
  '__DEBUG_NEW_WINDOW__' : !!argv.nw,
  '__BASENAME__' : JSON.stringify(process.env.BASENAME || ''),
  '__URLS__': {
    auth: {
      login: 'http://localhost:3000/auth/login',
      logout: 'http://localhost:3000/auth/logout',
      refresh: 'http://localhost:3000/auth/refresh',
      activate: 'http://localhost:3000/auth/activate'
    }
  }
}
```

and my `.eslint.rc`

```json
  "globals" : {
    "Action"       : false,
    "__DEV__"      : false,
    "__PROD__"     : false,
    "__DEBUG__"    : false,
    "__DEBUG_NEW_WINDOW__" : false,
    "__BASENAME__" : false,
    "__URLS__"     : false
  },
```

Any idea what I am missing?

**Comment by davezuko** [comment]
Is there a reason they need to be defined in the config and not at compile time? You could always have a `routes.dev.js` and `routes.prod.js` file and do something like:

```js
// in ~/src/routes/index.js
if (__PROD__) {
  module.exports = require('./routes.prod.js')
} else {
  module.exports = require('./routes.dev.js')
}
```

And from within there you can export whatever it is you need. They don't even have to be separate files, but the above just shows that it is possible. Seems like it would be easier than managing them via the webpack config, but perhaps I'm just not understanding the desired effect.

**Comment by mariotacke** [comment]
You are absolutely right. It is probably better to define them in a separate file outside of webpack. I was wondering if the starter kit had any opinion about it. Your example makes a lot of sense. Thank you!
