### ISSUE TITLE
Someone should make a blog post about this starter kit

### ISSUE THREAD

**Issue by MeetThePatel** [davezuko/react-redux-starter-kit#722]
I am looking at this code, and I have no idea where to begin

**Comment by mklinga** [comment]
I just found this starter kit today while starting a new hobby project, and I think I'll give it a go. 

I could try to write some thoughts about where to start and how all the pieces fit together while hacking away during the weekend and the next week.

**Comment by davezuko** [comment]
@mklinga That would be great. Just to note, just this morning we merged a significant PR that drastically changed how much of the application is setup. If you're looking for something a bit smaller I recommend trying the `2.0.0` branch, but you're welcome to give the latest master version a shot if you're up for it.

**Comment by MeetThePatel** [comment]
@mklinga Can you make a PR when you finish the blog post that updates the README with a "learning resource"?

**Comment by mklinga** [comment]
@MeetThePatel sure, that sounds good.

I decided to go with the 3.0.0 - version since I really like the 'fractal structure'. I won't probably go too deeply into internal details but try to keep it on the beginner-friendly overview level with some small example in the end.

**Comment by davezuko** [comment]
Resolved with @mklinga 's awesome post and PR: https://github.com/davezuko/react-redux-starter-kit/pull/761
