### ISSUE TITLE
Switch to react-hot-loader v3

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#726]
See @gaearon 's post here: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by justingreenberg** [comment]
Tracking https://github.com/gaearon/react-hot-loader/issues/249

**Comment by levithomason** [comment]
FYI [react-hot-loader@3.0.0-beta.0](https://github.com/gaearon/react-hot-loader/pull/250#issuecomment-215978690) is out.

**Comment by gaearon** [comment]
Better yet, `beta.1` is out which fixes many longstanding issues including full RR support.

**Comment by levithomason** [comment]
Thanks for the heads up, updating.

**Comment by davezuko** [comment]
I have an ongoing branch for this but still can't seem to get it working right with react-router. Will mess with it more this weekend maybe.

**Comment by gaearon** [comment]
If you think there’s an issue please file it, we’d like to know!

**Comment by levithomason** [comment]
@davezuko after we tried this the other day, it is suddenly working for me.  I'm blaming bad npm installs since literally nothing was changed on my end besides nuking and reinstalling.

**Comment by simonjoom** [comment]
Hi i did the react hot load integration with yur boilerplate. I can share it

**Comment by Skatanic** [comment]
@simonjoom I'd like to see your react-hot-loader integration with this project! Thanks

**Comment by UnsungHero97** [comment]
@davezuko what happened with the `react-hot-loader` feature? this issue was closed, but it doesn't seem like anything changed. was this closed because `react-hot-loader` won't be adopted?

**Comment by levithomason** [comment]
David could answer more precisely, but I asked him offline and said it is not being implemented. He mentioned trying to remove as much code instrumentation/manipulation as possible.

**Comment by davezuko** [comment]
@levithomason thanks for answering that. To further clarify, since it's been in beta for so long, in order to align with simplifying this project my approach is to keep it out until it at least reaches a stable v3, at which point we can reconsider.

**Comment by jonaswindey** [comment]
What's the added value with adding react-hot-loader when we have webpack-hot-middleware for hot-reloading?

**Comment by davezuko** [comment]
@jonaswindey `react-hot-loader` transform your React components so that webpack HMR knows how to reload the individual component. Without it, all code changes bubble up to the root of the application, at which point you can re-render the entire app, but you cannot preserve local component state. This is mostly mitigated by moving most of your state to redux.
