### ISSUE TITLE
koa-proxy

### ISSUE THREAD

**Issue by jkupcho** [davezuko/react-redux-starter-kit#727]
Trying to proxy an API on 8080, and it 404s.

Here's what I have within _development.js

```
proxy: {
  enabled: true,
  options: {
    // koa-proxy options
    url: 'http://localhost:8080',
    match: /^\/api\/.*/
  }
}
```

Not sure what I'm doing wrong.

Thanks!

**Comment by davezuko** [comment]
Just getting around to this, sorry for the delay. Any updates? If not, I will take a look as soon as possible.

**Comment by davezuko** [comment]
Make sure your proxied server is correctly matching the path, for example, when hitting `localhost:3000/api/foo` with the proxy options:

```js
    proxy: {
      enabled: true,
      options: {
        host: 'http://localhost:8080',
        match: /^\/api\/.*/
      }
    }
```

```js
const app = require('express')()

// this will not work
const app = require('express')()

app.get('/foo', function (req, res) {
  res.send({
    foo: 'bar'
  })
})

// this will work
app.get('/api/foo', function (req, res) {
  res.send({
    foo: 'bar'
  })
})

app.listen(8080)
```

If you need to match something different, you can pass whatever options you need to koa-proxy via the options object (there are more available than what we have in the config). See: https://github.com/popomore/koa-proxy.

I just tested this and it seems to be working as intended, but let me know if you still have trouble. Sorry for the slow response.

**Comment by NoZiL** [comment]
Hi Dave,
I use this thread for extend my problem. How can I rewrite my URL with koa-proxy ?
Eg : localhost:3000/api/users -> localhost:9000/users

**Comment by NoZiL** [comment]
Koa-proxy give a map option so I have resolved this issue with :
```javascript
proxy: {
  enabled: true,
  options: {
    host: 'http://localhost:9000',
    map: (path) => (path.replace(/^\/api\//, '/')),
    match: /^\/api\//,
  },
},
```
