### ISSUE TITLE
Curious why store is passed in here

### ISSUE THREAD

**Issue by jcreamer898** [davezuko/react-redux-starter-kit#729]
I noticed in this method, the `store` is passed in as an argument, and isn't being used?

https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/index.js#L12

Am I missing something?

Thanks! Still digging through your setup and really liking it.

**Comment by justingreenberg** [comment]
Routes may need to access store, for example to dynamically load a reducer or to check authentication state in a Route.onEnter handler

**Comment by davezuko** [comment]
@justingreenberg beat me to it.

**Comment by jcreamer898** [comment]
Ah, so you could pass it in to a component as a prop?

**Comment by davezuko** [comment]
Most common use case is to use it in route hooks (e.g. `onEnter`) in order to perform some action based on the store state (i.e. redirecting if not logged in).

**Comment by jcreamer898** [comment]
Makes sense. Thanks!!

**Comment by davezuko** [comment]
No problem :)
