### ISSUE TITLE
Import and initialize jQuery

### ISSUE THREAD

**Issue by sapei** [davezuko/react-redux-starter-kit#731]
I would like to use react-owl-carousel (https://www.npmjs.com/package/react-owl-carousel). The package does need jQuery, but I do not want to import it manually using the `<script>` tag. I have defined the dependency to jQuery in the package.json and imported it as follows:

import $ from 'jquery';
import jQuery from 'jquery';

Moreoever I also added the following entries in the webpack.config.js:

  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    'window.jQuery': 'jquery'
  })

However I still get the error "owl.carousel.js:1507 Uncaught ReferenceError: jQuery is not defined". Could somebody please give me a hint how to cope with this problem?

Thank you in advance.

**Comment by davezuko** [comment]
I will give this a shot today. Have you by chance figured it out since the original post?

**Comment by sapei** [comment]
Thank you for your reply. I have switched all carousels to the swiper carousel so that I do not need any jQuery. Therefore there is no need anymore to fix this problem.

**Comment by davezuko** [comment]
Ok, cool. I'm going to close it then even though it's unresolved just because this seems like a more general webpack question anyways. Good luck!
