### ISSUE TITLE
Having 2 separate CoreLayout components with individual SCSS files

### ISSUE THREAD

**Issue by GerritWanderer** [davezuko/react-redux-starter-kit#732]
Hey folks,

we want to introduce a second coreLayout (AppLayout and PageLayout). One is used for the actual app, the other one is just a landingpage. Each Layout Component should have a separate Core CSS file included (i.e. app.scss and page.scss).
However, both SCSS files are being included into the index.html when either a View with AppLayout or PageLayout Component is rendered.

Do you've a good hint how to solve this issue?

Cheers,
Gerrit

**Comment by davezuko** [comment]
I don't have anything to add to this just yet (sorry), but going to merge this into https://github.com/davezuko/react-redux-starter-kit/issues/733 since they are essentially the same issue and the other is a bit more generic.
