### ISSUE TITLE
Update CLI generators to work with Fractal Structure

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#734]
/cc @justingreenberg @SpencerCDixon

**Comment by danhuynhdev** [comment]
Are you working on this ?

**Comment by SpencerCDixon** [comment]
Sorry I've been pretty MIA - company just underwent acquistion... I can work on this over the weekend unless @danhuynhdev you're down to tackle it?

**Comment by davezuko** [comment]
@SpencerCDixon I can also work on it, but curious if you have any thoughts on how to best get it to work with the fractal structure.

**Comment by danhuynhdev** [comment]
#767 This is what i got so far. What do you think about it @SpencerCDixon.

**Comment by SpencerCDixon** [comment]
It looks good from a first glance.  I havn't actually used the fractal structure personally yet though.  Have you tested all the generators to make sure they put files in the proper locations?

@davezuko what are some of the challenging aspects of making the generators specific to the fractal structure?  If it's just a matter of putting files in the right place that should be easy.  

We can also extend the generators to do even more for free if we wanted.  For example, in a UI kit I'm building at work whenever I generate a new component it automatically appends the `export { NewComp } from './components/NewComp;` in the file that exports all my components.

Also, I know that the commenting is important for new users to understand the why's and how's of the starter kit so the PR would need the OK from Dave.

**Comment by mccambridge** [comment]
@davezuko is this still an issue?

**Comment by ericwooley** [comment]
@mccambridge A pr was just merged. But it didn't auto close this issue for whatever reason. Maybe it's good to keep this open because the new blueprints could definitely be improved.

**Comment by davezuko** [comment]
Closing for now with @ericwooley 's latest PR, but I still welcome improvements to the blueprints.
