### ISSUE TITLE
Webpack: setup DLL for core vendor libs, use CommonChunk for others

### ISSUE THREAD

**Issue by justingreenberg** [davezuko/react-redux-starter-kit#737]
@davezuko I will try to get around to setting up webpack DLL over the next few days :)

I will take care of #726 (RHL v3), which should remove nearly all the rendering boilerplate from main.js—There are a few issues with react-router I'm currently tracking (see issue)

I also have some general cleanup on fractal branch (ie. the devools extension you already fixed), I will put everything into a PR over the weekend

 Finally, I didn't forget about #717.. I whipped up a little alias/noParse demo for you will push up soon

**Comment by davezuko** [comment]
Awesome, the DLL plugin sounds super sane so it would be a great addition to the project.

Thanks for the other comments and all your work.

**Comment by tsaiDavid** [comment]
@justingreenberg - curious to see if there are any findings regarding using DLL for those core vendor libs. Would love to update the webpack docs to make it easier to set up too :)

**Comment by justingreenberg** [comment]
@tsaiDavid I've been busy during the days so working on this late night, hopefully i'll get this in sometime this week :) in the meantime, check out #753 (i encourage you to merge in and give it a whirl)... TLDR, a balanced combination of parallelization with DLL referencing is what i'm aiming for

**Comment by davezuko** [comment]
Closing in favor of a PR.
