### ISSUE TITLE
Ask - Code Splitting

### ISSUE THREAD

**Issue by yansenarmandau** [davezuko/react-redux-starter-kit#738]
hi David,

i'm very very love with this starter kit, in my project before i use code splitting too. but my application is come very delay (lagging).
that i test using 2G network, i can see on my screen like blink after sec delay when route is change,
ex: from home => contact us
url changed already to /contactus but on my screen still home page (0.5s delay i think)

you can test too, this production project:
https://www.taralite.com

that maybe this starter kit come with my problem too?

thanks

**Comment by justingreenberg** [comment]
There is no way around network latency. The webpackJsonp request is triggered at the split point created by `require.ensure` in `Route.getComponents`, maybe you could set a loading state [in route config](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/index.js#L6)... 

some pseudocode to illustrate (not tested!):
```js
export default (store) => ({
  getComponent (nextState, next) {
    store.dispatch({ type: 'CHUNK_LOADING', payload: nextState.location })

    require.ensure([], (require) => {
      const Test = require('./containers/Test').default
      const reducer = require('./modules/test').default

      injectReducer(store, { key: 'test', reducer })

      store.dispatch({ type: 'CHUNK_LOADED', payload: Test.displayName })
      next(null, Test)
    })
  }
})
```

**Comment by yansenarmandau** [comment]
Omg i love that solution, maybe i can try to use loader to wait until the chunk loaded.

Thanks @justingreenberg that should be good solution, cool

**Comment by davezuko** [comment]
Awesome demo as always, closing as resolved.

**Comment by mangungur** [comment]
Sorry before, i'm not understand my thats point. It's like a spam for me.
[triflex capsule](http://www.obatsakitpinggangterbaik.com/triflex-capsule-green-world/)

**Comment by simonedavico** [comment]
I spent some time thinking about this today and I created a decorator for async routes (i.e., routes with `getComponent`) that allows to specify `onStart` and an `onComplete` callbacks:

```javascript
export const decorateAsyncRoute = ({ onStart, onComplete }) =>
  (asyncRoute) => (store) => {

    const route = asyncRoute(store);

    return {
      ...route,
      getComponent: (nextState, cb) => {
        onStart(store);
        return route.getComponent(
          nextState,
          decorateCb(() => onComplete(store))(cb)
        )
      }
    }

  };

export const withLoadingFeedback = (asyncRoute) =>
  decorateAsyncRoute({
    onStart: (store) => { store.dispatch(showLoading()) },
    onComplete: (store) => { store.dispatch(hideLoading()) }
  })(asyncRoute);
``` 

It can be used simply by decorating an async route definition like the ones in the starter kit:

```
const SomeRoute = (store) => ({ path: ..., getComponent: ... })
export default withLoadingFeedback(SomeRoute)
```
