### ISSUE TITLE
New project state is behind 2.0 release

### ISSUE THREAD

**Issue by michaelmior** [davezuko/react-redux-starter-kit#740]
It seems like the `new-project` branch is slightly out of date. It would be great if this could be updated to match the latest release.

**Comment by davezuko** [comment]
Thanks, I have to create a new-project-2.0 and new-project-3.0 branch, since it needs to also work for those on 2.0.

**Comment by davezuko** [comment]
Created:

* https://github.com/davezuko/react-redux-starter-kit/tree/new-project-v2
* https://github.com/davezuko/react-redux-starter-kit/tree/new-project-v3

You should use `new-project-v2`. Hope that helps.

**Comment by michaelmior** [comment]
Thanks!
