### ISSUE TITLE
Failure on npm start: SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by EwanValentine** [davezuko/react-redux-starter-kit#743]
I'm getting this when I run `npm start` 
```
SyntaxError: Unexpected reserved word
(function (exports, require, module, __filename, __dirname) { import config from '../config';
```

**Comment by davezuko** [comment]
Strange, `npm start` should be pre-processing that file with `babel-node`. Not sure what to think of this really, beside: do you have a `.babelrc` file in a parent directory that could be conflict with the project settings? Also, what are your node and npm versions?

**Comment by EwanValentine** [comment]
@davezuko Got it working now! I think there was a conflict between another .babelrc I had in my project root
