### ISSUE TITLE
The kit and the counter example resizes itself.

### ISSUE THREAD

**Issue by 5amfung** [davezuko/react-redux-starter-kit#744]
When running the counter example in Google Chrome browser, you can see that the page is rendered, then the screen flickers and immediately the duck image and text are resized slightly smaller.  I thought I could live with it because it only happens when I first load up the page.  However, I later found that it's an issue.  For example, I incorporated the [vertical linear stepper](http://www.material-ui.com/v0.15.0-beta.1/#/components/stepper) from material-ui into the project.  When the page is first loaded, you can see that the stepper was rendered perfectly for a split second, and then all of sudden the content is resized down, leaving the vertical line misaligned and the step number circle smaller.

**Comment by davezuko** [comment]
I'll have to take a look at the vertical linear stepper, but is this just FoUC (Flash of Unstyled Content)? If so, it should _only_ happen in development due to webpack dynamically inserting style tags as styles are imported, whereas when ExtractTextPlugin is used the stylesheet will be bundled in full and injected a single time into the head.

**Comment by 5amfung** [comment]
So far I only tried in development mode.

**Comment by 5amfung** [comment]
Not sure if I'm looking into the right direction, but if I comment out [normalize](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/styles/core.scss#L3), the counter example doesn't flick and resize.  That makes sense because the css is no longer applied, but I don't understand how that would affect [Stepper](http://www.material-ui.com/v0.15.0-beta.2/#/components/stepper).

**Comment by Valentin-Seehausen** [comment]
I use react-toolbox, because material-ui is not working properly. You only need to fix node-sass to version  3.3.3 in package.json
