### ISSUE TITLE
Question: Removing previous state

### ISSUE THREAD

**Issue by xdgimf** [davezuko/react-redux-starter-kit#746]
I have a home and add route that uses async component and reducers.
The problem i got is when switching to another page, the previous page state isn't destroyed. 

1. Push `Home`, creates `homeView` state
2. Push `Add` from `Home` creates `addView` state

In this case `homeView` state still exists.

routes/Home/index.js
````
import { requireAuth } from '../utils'
import { injectReducer } from '../../store/reducers'
import { showHome } from 'modules/route'

export default (store) => ({
  onEnter: requireAuth(store),
  getComponent: (nextState, next) => {
    require.ensure([
      './containers/HomeView',
      './modules/homeView'
    ], (require) => {
      const HomeView = require('./containers/HomeView').default
      const reducer = require('./modules/homeView').default

      injectReducer(store, { key: 'homeView', reducer})

      next(null, HomeView)
    })
  }
})
````

routes/Add/index.js
````
import { injectReducer } from '../../../store/reducers'

export default (store) => ({
  path: 'add',
  getComponent: (nextState, next) => {
    require.ensure([
      './containers/AddView',
      './modules/addView'
    ], (require) => {
      const AddView = require('./containers/AddView').default
      const reducer = require('./modules/addView').default
      
      injectReducer(store, { key: 'addView', reducer})

      next(null, AddView)
    })
  }
})
````

I want to remove the previous state, what are your recommended ways?

**Comment by justingreenberg** [comment]
there should rarely be a need to do this, but the async reducer logic is very flexible... a simple solution would be to use `react-router-redux` to reset state in the home reducer, ie:

```js
// home redux module
import { LOCATION_CHANGE } from 'react-router-redux'
// ...
const ACTION_HANDLERS = {
  [LOCATION_CHANGE]: (state, { payload }) => {
    if (payload.pathname !== '/') return {}
    return state
  }
}
```

alternatively, you can add a `removeReducer` helper....

```js
// in store/reducers.js
export const removeReducer = (store, { key }) => {
  Reflect.deleteProperty(store.asyncReducers, key)
  store.replaceReducer(reducers(store.asyncReducers))
}
```

however this would have to be invoked in every other route definition, ie:

```js
// routes/Add/index.js
import { injectReducer, removeReducer } from 'store/reducers'
// ...
removeReducer(store, { key: 'homeView' })
```

this will add a lot of boilerplate. another option is to use middleware to create a wrapper around `removeReducer` and detect when the router transitions away from home, ie:

```js
// store/createStore.js
import { removeReducer } from 'store/reducers'
// ...
const resetHomeMiddleware = store => next => action => {
  const storeLocation = store.getState().router.locationBeforeTransitions
  if (storeLocation && storeLocation.pathname === '/') {
    removeReducer(store, { key: 'homeView' })
  }
  return next(action)
}
// ...
let middleware = applyMiddleware(thunk, resetHomeMiddleware, routerMiddleware(history))
// ...etc
```

i haven't tested any of this code, but it should all work. i don't know enough about your requirements to make a recommendation but hopefully this gives you some ideas

**Comment by xdgimf** [comment]
> this is not a problem, this is redux! why do you want to destroy the state?
Yeah! I also think that redux should work this way, but for some reason it started to bother me.

For example, in my case
1. Push Home, creates homeView state.
````
{
  homeView: { ... }
}
````
2. Push Add from Home creates addView state.
State:
````
{
  homeView: { ... }
  addView: { ... } 
}
````
3. Saving add returns an error
State:
````
{
  homeView: { ... }
  addView: { error: 'Theres an error' } 
}
````
4. Cancel add and go back to home
State:
````
{
  homeView: { ... }
  addView: { error: 'Theres an error' } 
}
````
5. Push to home
State:
````
{
  homeView: { ... }
  addView: { error: 'Theres an error' } 
}
````
6. Push add for 2nd time
State:
````
{
  homeView: { ... }
  addView: { error: 'Theres an error' } 
}
````

As you can see in #6 going from Home to Add for the 2nd time, since the state is not resetting/removing the previous state, it already has an error.

**Comment by davezuko** [comment]
You guys are welcome to continue the discussion, but this is not so much a question/issue with the starter kit as it is a question about larger redux best practices, so going to close for now.
