### ISSUE TITLE
Implement of sub reducers

### ISSUE THREAD

**Issue by MQuy** [davezuko/react-redux-starter-kit#755]
As doc says about structure:
```markdown
modules      # Collections of reducers/constants/actions
```
I wonder how we can implement these reducers to load from routes folder. For example in Home from routes?
The only way, I know, is load in from reducers root

Besides, can we have a detail example for this boilerplate? 💯

**Comment by amangeot** [comment]
Have you tried using `injectReducer` (to define in your root reducer): https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/index.js.

I have another question linked to sub reducers. Is it possible to inject reducers synchronously ? The idea would be to 'hide' a particular `/modules` under `/routes/sub-app` even if no code splitting is implemented yet. I have tried something similar to:
```
export default (store) => {
  injectReducer(store, { key: 'someReducer', someReducer })

  return <Route /* ... */> /* ... */ </Route>
}
```
But it shows a nice redbox saying that `someReducer` can not be found on `undefined`. It sounds like `store` is not initialized at this point (but it should), however if the reducer is added in the root reducer, everything runs smoothly.

Does anybody know what happens ?

**Comment by justingreenberg** [comment]
>Is it possible to inject reducers synchronously ?

absolutely! this is a drop in replacement...

```js
import { injectReducer } from '../../store/reducers'

import Counter from './containers/CounterContainer'
import reducer from './modules/counter'

export default (store) => {
  injectReducer(store, { key: 'counter', reducer })
  return { path: 'counter', component: Counter }
}
```

>Anyway, Is it bad practice to add sub-reducers from '/routes' with no code splitting ?

the store should not reflect any nested hierarchy in your app; ideally it should be [flat and normalized](https://github.com/gaearon/normalizr)

i'm not sure i understand your use-case, but if you find yourself needing nested or conditional reducers, i suggest looking into https://github.com/slorber/rereduce or even something like https://github.com/salsita/redux-elm, which provides truly fractal support for nested reducers and actions

**Comment by amangeot** [comment]
Sorry the last post was more of a debugging log than a reply!

My use-case is a landing page, with links. Each link redirects you to a sub-app. Each sub-app exports routes and reducers as you've just described. (By the way I just reorganized my app to follow the fractal app structure you suggested, and it is very comfortable to work with. It super-fits my needs, thank you a lot!)

These sub-app reducers can either be injected when making sub-app routes:
```
// @ /routes/Counter/index.js
import counter from './modules/counter'

export default (store) => {
  injectReducer(store, { key: 'counter', counter})
  return { path: 'counter', component: Counter }
}
```
Or combined as we used to do:
```
// @ /store/reducers.js
import counter from 'routes/Counter/modules/counter

export const reducers = (asyncReducers) => {
  return combineReducers({
    router,
    counter
    // ...
    ...asyncReducers
  })
}
```
The second case, combining, runs without any problem. The first case, injection, gives me `undefined` for `state.counter` when accessing the `/counter` route. The error appears in a mapStateToProps in a container component.

I am not actually using Counter, but it is the very same code for combining/injecting reducers. I can't figure out why it doesn't work when injecting, do you have an idea ?

**Comment by justingreenberg** [comment]
@amangeot thanks for the kind words :) i'm not sure what's going on there, i just spun up my local fork and dropped in the snippet I provided and injectAsync works...  are you using a plain object for your route definition?

**Comment by amangeot** [comment]
Yes, I'm using JSX routes for now. That's actually the reason for not splitting code yet, I wanted to make sure everything else works fine before rebuilding all my routes with plain routes.

I was hoping JSX routes would not cause an issue as we inject the reducer before returning routes. Could the routes mess up with reducers ?

**Comment by justingreenberg** [comment]
i think that's the issue, i tried using JSX and got the same error. i've run into this before, i'm not sure why but jsx/pojo routes don't seem to play well together

**Comment by amangeot** [comment]
I just tried returning a POJO route from the sub-app routes, and it gave me a very ugly error as the rest of routes are JSX. 

I'm going to be away for a few days but I'll definitely try with all routes defined as plain objects and let you know, thanks!

**Comment by justingreenberg** [comment]
@amangeot sounds good! out of curiousity, did you try passing the plain object route to jsx childRoutes, ie `<Route childRoutes={PojoRoute} />` ?

**Comment by MQuy** [comment]
hi, just found out that we can use `contextTypes` to get store from component. I wonder that is it good practice when we injectReducer in component's `consturctor`

**Comment by davezuko** [comment]
Closing since this is not an issue with the starter kit itself. Feel free to continue the discussion, though!
