### ISSUE TITLE
css not saved to separate css file on deploy & compile?

### ISSUE THREAD

**Issue by marshallford** [davezuko/react-redux-starter-kit#756]
I noticed that when running `npm run deploy` and `npm run compile` that the project's styles get put into the `app.js` bundle. Wouldn't writing it out to a dedicated `style.css` file help with browser rendering as well as browser caching? I don't have any hard facts on performance improvements, (I am looking into it) however it seems to be the best practice amongst web designers to always use an external stylesheet.

Thanks to all the project maintainers for the great work! Stuck on 2.0.0 for now (thanks for breaking off a release), but I like the direction your taking the project.

**Comment by davezuko** [comment]
Hey, this changed a couple weeks back. `npm run deploy` no longer explicitly sets `NODE_ENV=production`, so you need to do it yourself. There is also `npm run deploy:prod` as a helper to do it for you. Hope that helps!
