### ISSUE TITLE
hardcoded "http://localhost:3000" prevents preview on other device (e.g. phone)

### ISSUE THREAD

**Issue by jokeyrhyme** [davezuko/react-redux-starter-kit#757]
I tried to preview a work-in-progress on my phone today (running `npm start`). The initial HTML request is returned as expected, however, the script and stylesheet URLs all have "http://localhost:3000" hardcoded into them, which means there's only one machine that can successfully load it: the same one running `npm start`.

Is there an option I have missed to control this? Any suggestions? Cheers!

P.S. I'm super excited about this template. Thanks so much for the great work so far. :)

**Comment by marshallford** [comment]
Hey! I have run into this issue as well. I'll take a stab at adding this feature and submit a pull request. I may uses something like [dev-ip](https://github.com/shakyshane/dev-ip) which browser-sync uses to get a local ip address.

**Comment by fixpunkt** [comment]
Actually, I found that you can just set `compiler_public_path` to `/` in `config/*.js`.

**Comment by fixpunkt** [comment]
Damn, I just found out that this will break HMR.

**Comment by fixpunkt** [comment]
Actually, for this case HMR should not break, only if you change the path part of `compiler_public_path` to something other than `/` (`/assets`, for example). HTH.

**Comment by creatorkuang** [comment]
set your server_host with you own ip address.  `/config/index` `server_host : '192.168.31.180'`

**Comment by marshallford** [comment]
@creatorkuang That works however in a team environment collaborators would be constantly overwriting/adjusting the hardcoded ip address.

**Comment by jokeyrhyme** [comment]
Is there a way to make this dynamic? So the client just uses `location.hostname` or something to figure out where to connect? And there are no hardcoded origins on the server side at all?

**Comment by marshallford** [comment]
@jokeyrhyme That was the purpose of my pull request (#758). I must be misunderstanding your question...

**Comment by jokeyrhyme** [comment]
@marshallford Cool, I'll go test the PR now.

**Comment by fixpunkt** [comment]
Again: if you remove the hostname from `compiler_public_path` and make it domain-relative instead, it doesn't matter what IP address you have.

**Comment by davezuko** [comment]
@fixpunkt I'm willing to remove it if you can verify that using a relative path no longer causes http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts/34133809#34133809. Unless there's some other workaround you are using.

**Comment by davezuko** [comment]
Moving all future discussion to @marshallford 's PR: https://github.com/davezuko/react-redux-starter-kit/pull/758.
