### ISSUE TITLE
Question: Sending actions from layout to child routes component

### ISSUE THREAD

**Issue by xdgimf** [davezuko/react-redux-starter-kit#760]
Lets say I have a `HomeLayout` that has child routes: `Products` and `Services`

````
export default (store) => ({
  component: HomeLayout,
  getChildRoutes: (location, next) => {
    require.ensure([], (require) => {
      next(null, [
        require('./Products').default(store),
        require('./Services').default(store)
      ])
    })
  }
})
````

The home layout has my `Header` with a `Refresh` button, when the refresh button is clicked it should refresh the product list or service list.

Right now I do this by dispatching refresh actions based on the router location
if location is /products dispatch refreshProducts()
else if location is /services dispatch refreshServices()

Am I doing the right thing? Or Is there a better way to do this?

**Comment by davezuko** [comment]
When you start to have actions that start to do different things based on your current route, it's a sign that you need to rethink that action's responsibility and possibly break it down into separate more targeted actions. However, that's difficult to do with your use case, so I'd say it's somewhat of a necessary evil.

I'm at a bit of a loss as far as figuring out an alternative, and if I were in your position I'd probably move the refresh button to a component that's tied more directly into the current route (i.e. the button can be provided a callback to do exactly what you want).

Sorry I couldn't be more of help. I suggest posting this in StackOverflow or another community more targeted at helping understand best practices.
