### ISSUE TITLE
switching eslint to use a different style guide causes lots of linting errors

### ISSUE THREAD

**Issue by marshallford** [davezuko/react-redux-starter-kit#762]
Alright so let me explain what I mean here. According to the readme the starter kit...
> Uses Standard Style by default, but you're welcome to change this. 

However I have run into an issue while switching to [airbnb's config](https://www.npmjs.com/package/eslint-config-airbnb). When I run `npm run lint` eslint parses the entire project including what I would describe as "behind the scenes" js that a normal user of the kit would not want to adjust. This includes files like webpack configuration and javascript in the `bin` directory. 

What I am getting at is even if a user of this kit wrote all their project specific files according to the eslint standard they chose, they would still get hundreds of false negatives when linting. What I would propose is changing the `npm run lint` command to something a bit more specific. Maybe `"lint": "eslint src tests",` ?

Thanks!

**Comment by davezuko** [comment]
We should just add `bin`, `build`, etc. to the `.eslintignore` file if they are not already there. If that doesn't do what we need, then your approach also sounds sane.

**Comment by marshallford** [comment]
The issue I have with both of the options (`.eslintignore` additions or a `package.json` adjustment) is that it would "hide" linting issues from project maintainers and contributors. Maybe a conditional ignore somehow or two npm run commands?

**Comment by davezuko** [comment]
@marshallford added your suggestion here: https://github.com/davezuko/react-redux-starter-kit/commit/2eff2726721c3d582b76ec6364025d62ce525ab3

**Comment by marshallford** [comment]
That is a step in the direction however the `server` directory still includes many files folks probably don't want to mess with. Maybe I suggest the following?

```javascript
"scripts": {
    ...
    "lint": "eslint src tests",
    "lint-contribute": "eslint .",
    "lint:fix": "npm run lint -- --fix", // scope the fixes to `src` and `test` possibly? 
    ...
  },
```

Lastly, update the `CONTRIBUTING.md` documentation and CI builder to use `lint-contribute`. Thoughts?
