### ISSUE TITLE
Webpack Failing to Compile

### ISSUE THREAD

**Issue by allxie** [davezuko/react-redux-starter-kit#768]
Webpack is failing to compile for me on line 13 of webpack-compiler.js. This is working just fine on my coworker's computer, but not on mine. I am using version 1.0.0 of react-redux-starter-kit and have replicated the problem after removing my node modules branch and re-installing. 

Npm version : 3.8.8
node version: v5.5.0

Error:

...../build/webpack-compiler.js:37
      var jsonStats = stats.toJson();
                           ^

TypeError: Cannot read property 'toJson' of undefined
    at webpack-compiler.js:13:25

Thanks!

**Comment by davezuko** [comment]
That's interesting, since `stats` is just an argument provided by the webpack compiler callback, it's not our own variable. Have you compared your webpack version with your co-workers? I'll have to look at the webpack repo to see if that has any clues.

**Comment by allxie** [comment]
Hi Dave,
We have the same webpack versions. They are 1.12.9.

**Comment by davezuko** [comment]
Thanks. So looking at the `1.0.0` tags and the snippet you posted, they appear to be different. That is, in `1.0.x` the `compile` task is in `~/bin/compile`: https://github.com/davezuko/react-redux-starter-kit/blob/v1.0.0/bin/compile.js, whereas your snippet is using the newer `~/build/webpack-compiler`.

Is there any way you could post your fork or, if not, the source code in that compiler file?

**Comment by davezuko** [comment]
Haven't heard anything more on this, and `1.0.0` is no longer actively maintained, so going to close this for now. If there is anything else I can do to try to help, let me know.
