### ISSUE TITLE
Universal / Server side rendering

### ISSUE THREAD

**Issue by sauravskumar99** [davezuko/react-redux-starter-kit#775]
How can we enable server side rendering/universal for this kit?

**Comment by SteveHoggNZ** [comment]
Universal rendering isn't a feature that comes with this starter kit, so immplementing it is up to you.

Here is an example of someone doing it with version 2: https://github.com/Anomen/universal-react-redux-starter-kit

**Comment by sauravskumar99** [comment]
@SteveHoggNZ Thank you for your help! Can you suggest more such kits?

**Comment by davezuko** [comment]
https://github.com/erikras/react-redux-universal-hot-example is probably the most popular.

Closing for now since this is a duplicate of many other issues, but feel free to continue!

**Comment by janoist1** [comment]
I've recently added SSR / universal feature to this starter kit, check out [my forked version](https://github.com/janoist1/simple-universal-style-loader) Hope this helps.
