### ISSUE TITLE
all of development and  product is blank on  mobile bowser 

### ISSUE THREAD

**Issue by virtoolswebplayer** [davezuko/react-redux-starter-kit#777]
```
npm run deploy:prod

cd dist

http-server -p 3000
```
open  http://myip:3000  on android native browser (only chrome for android is ok)
thiere is nothing

**Comment by davezuko** [comment]
Not having done any real mobile development with React, is this a _React_ issue or something specific to the starter kit? To hear it's working fine in Chrome implies that it's a browser compatbility issue, which doesn't necessarily imply something is wrong with the kit. Would like to learn more about this.

**Comment by SpencerCDixon** [comment]
Yeah this actually happened to me.  When running an older version of safari on my iPhone 6.  I can't remember what the solution was but I do remember how I solved it.  You can link your iPhone with your macbook and open the safari devtools for your phone on your mac and it will show you any JS errors.

I think the solution was a missing polyfill because one of my packages was using like Map or something but not 100%.  Hope this helps @virtoolswebplayer

**Comment by davezuko** [comment]
@SpencerCDixon not to sidetrack this thread, but thoughts on including babel-polyfill by default? Would eliminate these sorts of issues...

**Comment by marshallford** [comment]
So is `babel-polyfill` needed these days or no? I was under the impression that when babel transpiles es6/7 to es5 that the bundle includes the magic needed for it to run on most if not all modern browsers.

**Comment by davezuko** [comment]
@marshallford babel will transform most of the features, and I'm not sure the most correct/eloquent way of putting it, but it doesn't mess with native prototypes, which you'd either need a polyfill for or some other solution. I'm thinking of things like `String.prototype.includes` and the sort, which won't be transpiled and might not be available in older browsers.

**Comment by davezuko** [comment]
@virtoolswebplayer try including the babel polyfill in your entry point (you can add it to vendor or to the top of the app (`import 'babel-polyfill'` in `~/src/main.js`) and see if that solves your issue. I don't think this is necessarily an issue with the starter kit, though I will consider including it by default.
