### ISSUE TITLE
ignoring files for testing

### ISSUE THREAD

**Issue by kevinchiu** [davezuko/react-redux-starter-kit#779]
How do you ignore files (for example, similar to .eslintignore) when running npm run test?

**Comment by davezuko** [comment]
No built-in way at the moment, but 3 comments:

1) The way `test:dev` currently works is it will run _all_ tests, but then after that point will only run the ones that are changed. So you can use that to your advantage.
2) You can use Mocha's `.only()` on the `describe` block wrapping the set of tests you want to test
3) You can edit the regex in `~/tests/test-bundler.js` to only match the files you want to test.

I will eventually get around to implementing the ability to glob only the files you want, but it's not on my priority list.

**Comment by davezuko** [comment]
Added to my task list here: https://github.com/davezuko/react-redux-starter-kit/wiki/v3.0.0-Plans
