### ISSUE TITLE
Disabling some rules in eslint

### ISSUE THREAD

**Issue by IljaDaderko** [davezuko/react-redux-starter-kit#780]
I'm trying to disable some jsx related eslint rule, specificaly the "no arrow function inside jsx props".
Stumbled upon this and I think it is correct way to do this: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

But I'm struggling to find out place where I need to put this inside .eslintrc file

**Comment by davezuko** [comment]
Just drop it in `rules` and namespace it with `react`. See:

```js
{
  "parser"  : "babel-eslint",
  "extends" : [
    "standard",
    "standard-react"
  ],
  "env"     : {
    "browser" : true
  },
  "globals" : {
    "Action"       : false,
    "__DEV__"      : false,
    "__PROD__"     : false,
    "__DEBUG__"    : false,
    "__COVERAGE__" : false,
    "__BASENAME__" : false
  },
  "rules": {
    "semi" : [2, "never"],
    "max-len": [2, 120, 2],
    "react/jsx-no-bind": [2] // <-----------------------
  }
}
```

**Comment by davezuko** [comment]
Also 👍  for that rule

**Comment by IljaDaderko** [comment]
Awesome, got it working. Thanks!
