### ISSUE TITLE
Deployment to AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by GustavRitsch** [davezuko/react-redux-starter-kit#781]
Hello,

I was wondering if somebody have any experience with deploying this starter kit to amazon elastic beanstalk? I have read absolutely everything available on internet including documentation and I am still unable to make it work so I am asking here for help. 

I might be missing something obvious. I tried deploying dist folder directly or just freshly cloned repository but without success.

You are not supposed to tweak anything directly on the running instance but all settings required for application to work should be specified in special file in `.ebextensions` folder. You can also specify what node command to use to start up your application which is run after `npm install`. If I manage to get it working I could create some short tutorial for it.

Keep up a good work!

**Comment by marshallford** [comment]
I have not used AWS Elastic Beanstalk before, but it seems overkill since after running `npm run deploy:prod` you are left with static assets that don't need to be run with Node, Ruby, PHP, etc. Seems like the only feature that one would use from AWS Elastic Beanstalk is the web server piece, in which case I would guess you just need to tell AWS to look at your `index.html` file.

Note: I am assuming your not using server side rendering in which case you would probably need Node.

**Comment by GustavRitsch** [comment]
That makes sense I guess why I tough I need node is because part of my app is `koa` backend which I forgot to mention I have. So I just can server `/dist` folder through AWS S3 as mentioned here

> You can host a static website on Amazon S3. On a static website, individual web pages include static content. They may also contain client-side scripts. By contrast, a dynamic website relies on server-side processing, including server-side scripts such as PHP, JSP, or ASP.NET. Amazon S3 does not support server-side scripting.

And `koa` backend on AWS EB right?

**Comment by marshallford** [comment]
@GustavRitsch IMO you should keep your backend and frontend "seperate". Sounds like you are maybe keeping your front and back end tightly coupled, which is fine for dev but can make deployment tricky. My suggestion would be to run your frontend on s3 or Nginx and use AWS EB magic to run your node based backend. Like I said earlier, I have not used EB but it sounds like a solid solution for running your Koa backend. Good luck!

**Comment by zmelamed** [comment]
@GustavRitsch would be much appreciated if you could provide a detailed rundown how you went about your deployment on AWS utilizing elastic beanstalk. I'm in the exact same position. Or did you go another route?
