### ISSUE TITLE
something in test-bundler.js

### ISSUE THREAD

**Issue by xdgimf** [davezuko/react-redux-starter-kit#784]
`const inManifest = (path) => ~__karmaWebpackManifest__.indexOf(path)`
What does `~` do?

**Comment by acpower7** [comment]
I'd also like to know...

**Comment by davezuko** [comment]
http://stackoverflow.com/a/12299717

**Comment by acpower7** [comment]
^Thanks

Can you pls help me with my other issue? (#1100) :)

[Source](https://github.com/abzfarah/Pearson.NAPLAN.GnomeH/tree/feature/unittests)
