### ISSUE TITLE
Add multiple components to single Container / route ?

### ISSUE THREAD

**Issue by sauravskumar99** [davezuko/react-redux-starter-kit#786]
Can someone please help me with adding multiple components to a page which shows up when directed to a specified route and also give it the necessary store bindings.

**Comment by davezuko** [comment]
Hey, hopefully somebody can help, but I'd recommend pointing this question at StackOverflow, `/r/reactjs`, or even a react-router or redux-related channel. The issues here are generally reserved for issues specific to the starter kit implementation and less so for design questions, so you will probably have better responses elsewhere. That said, not against keeping this open for a couple days, just don't want you to sit on your hands awaiting an answer. Good luck!

**Comment by sauravskumar99** [comment]
Thanks... I am now sending all store data to one parent component as binded in route/comp/index.js and then passing on the data to children elements... as <ChildComp data={data} />... is this the right way to go?

**Comment by justingreenberg** [comment]
it depends... props injected by the router are only available on the handler component but the store can be accessed anywhere using connect.. for example..

```js
// route
{
  path: 'thing/:id',
  component './containers/Thing'
}
```

```js
// thing route handler container
import { connect } from 'react-redux'
import { doStuff } from '../modules/thing'

import ThingView from './components/Thing' // dumb component composes view

const container = connect(
  (dispatch, ownProps) => ({
    doStuff: () => dispatch(doStuff(ownProps.params.id)) // preload with id
  }),
  (state, ownProps) => ({
    entity: state.things[ownProps.params.id] // assuming normalized dict
  })
)

export default container(ThingView)
```

```js
// component
import OtherFeature from '../containers/OtherFeature'

export default function ThingView({ entity, doStuff }) {
  if (!entity) return <div>Not Found</div>
  
  return (
    <div>
      {entity}
      <button onClick={() => doStuff()}>stuff</button>
      
      <OtherFeature /> // connected to store, independent
    </div>
  )
}
```

**Comment by justingreenberg** [comment]
ok so as of today, [`withRouter` HOC provides access to params and location object](https://github.com/reactjs/react-router/pull/3444/files)... this means you no longer have to manually "thread" router props to leaf components...

as it is written, the `<OtherFeature />` component in example above would not have access to dynamic router params.... with the new HOC, they can easily be accessed

```js
// other feather container, can be anywhere in component tree
import { connect } from 'react-redux'
import { withRouter } from 'react-router' // HOC to inject params

import OtherFeature from './components/OtherFeature' // dumb component

const container = connect(
  (state, ownProps) => ({
    coolnessLevel: state.feature[ownProps.params.id].coolnessLevel
  })
)

export default container(
  withRouter(OtherFeature) // provide connect with decorated component
)
```

**Comment by davezuko** [comment]
Closing as resolved since this is a question of implementation and not a problem with the project.
