### ISSUE TITLE
Removing database related packages

### ISSUE THREAD

**Issue by IljaDaderko** [davezuko/react-redux-starter-kit#788]
So I was going through package.json and found out that there are several packages related to databases, I'd like to remove any unnecessary ones to make a more empty starter pack, wanted to ask which ones are safe to remove when database is set to NONE?

**Comment by marshallford** [comment]
@IljaDaderko Which npm modules are you referring to specifically? Also, I did a repository wide search and found no results for "database", did you accidentally post this issue to the wrong project?
