### ISSUE TITLE
Why use relative paths in imports ?

### ISSUE THREAD

**Issue by gcoupelant** [davezuko/react-redux-starter-kit#789]
Is there a reason to use a relative paths in imports, since webpack will resolve it from root ?

- https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/index.js#L1
- https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/index.js#L2
- https://github.com/davezuko/react-redux-starter-kit/blob/master/src/layouts/CoreLayout/CoreLayout.js#L2
- https://github.com/davezuko/react-redux-starter-kit/blob/master/src/layouts/CoreLayout/CoreLayout.js#L4

**Comment by davezuko** [comment]
We should probably be more consistent, but it's partly so people who don't read the README and aren't aware of webpack's capabilities aren't confused. It's slightly a holdover from the past setup where we had a `redux` folder such as: `redux/modules/counter.js` and if we didn't use relative imports people could have easily gotten confused.

I will add a chore to make sure we make these consistent (probably preferring the use of root resolve now that we don't have that `redux` folder). Hope that makes sense.

**Comment by gcoupelant** [comment]
It sure does, thanks.
