### ISSUE TITLE
Hot reloading not working for styles

### ISSUE THREAD

**Issue by bulby97** [davezuko/react-redux-starter-kit#79]

**Comment by davezuko** [comment]
I have an idea of what this might be; a few releases ago I made ExtractTextPlugin non-production-only, so going to switch it back and see if it resolves the issue.

**Comment by gaearon** [comment]
ExtractTextPlugin does not support hot reloading and is intended to only be used in production.

**Comment by davezuko** [comment]
Yeah I don't know why I did it, I purposely kept it out of development in the past... just an oversight. Reverting it now.

**Comment by davezuko** [comment]
@bulby97 this is fixed with https://github.com/davezuko/react-redux-starter-kit/commit/a7c3513916b8d9eac4f2cd7887b3f4ec20bd8d15. Sorry about that!

**Comment by bulby97** [comment]
@davezuko No problem ! You're doing a great work ! Thanks for your reactivity
