### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by web2style** [davezuko/react-redux-starter-kit#796]
Please, have a look at this line: https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L121

It requires default environment which is missing.

**Comment by davezuko** [comment]
Are you actually getting an error? That code is correct, since it allows ES6 modules -> CommonJS interop. I.e.

```js
// both files transpiled by babel

// file1.js
export default {
  foo: 'bar'
}

// file2.js
const module = require('./file1').default
module.foo // bar
```

**Comment by web2style** [comment]
Yes, I get the following error:

```
var overrides = environments[config.env];
                            ^

TypeError: Cannot read property 'development' of undefined
```

But my kit is not the latest version, this happened after updating `/config` folder. What else should I also update to make this work?

**Comment by davezuko** [comment]
Strange, something else must be up. Could you either link to your repo so I can scan through it directly, or, if not, post your `.babelrc` file?

**Comment by web2style** [comment]
The repo is private, I can't show it.

My `.babelrc` file:
```
// NOTE: These options are overriden by the babel-loader configuration
// for webpack, which can be found in ~/build/webpack-environments/_base
// and ~/build/webpack-environments/production.
// 
// Why? The react-transform-hmr plugin depends on HMR (and throws if
// module.hot is disbled, so keeping it and related plugins contained
// within webpack helps prevent unexpected errors.
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": ["transform-runtime", "add-module-exports"]
}
```

**Comment by web2style** [comment]
Oh, this is because of `add-module-exports` plugin. Thanks for the tip.

**Comment by davezuko** [comment]
Yeap, you're exactly right. If you need to you can adjust the `environments` file to use named exports rather than a default object with keys for the environments (should probably just do that anyways) and that should work.

Closing since this isn't an issue with the current state of the project, but I can continue to help if needed.
