### ISSUE TITLE
Using fractal sub-routes with container components

### ISSUE THREAD

**Issue by chrismllr** [davezuko/react-redux-starter-kit#797]
Hey guys - first off, wonderful work with the starter kit.. Has everything necessary to boot up what i feel is the most scalable react app possible.

Second, this more of a request or enhancement, so I apologize for the open issue... I've got a question open currently on stackoverflow [here](http://stackoverflow.com/questions/37150168/react-router-getchildroutes-not-firing-in-nested-plainroute/37153505#37153505). 

Would it be possible to include in the docs, or an example, of how to use nested fractal routes with PlainRoutes? You detail it subtly in the structure diagram...

```
│       └── Home             # Fractal route
│           ├── index.js     # Route definitions and async split points
│           ├── assets       # Assets required to render components
│           ├── components   # Presentational React Components
│           ├── container    # Connect components to actions and store
│           ├── modules      # Collections of reducers/constants/actions
│           └── routes **    # Fractal sub-routes (** optional)
```

And I am having trouble making it work if the top level (`Home`, in this case) is a `connect`ed container component. Any help or documentation would be appreciated!

Also, if there is clear documentation of this somewhere i've missed, please let me know and close issue accordingly.

Thanks again 👍

**Comment by davezuko** [comment]
I will reply more fully when I get a minute to spare, but for now you should probably take a look at @justingreenberg 's awesome documentation [here](https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure). Hopefully that answers some of your questions in the meantime.

**Comment by justingreenberg** [comment]
hey chris! `getChildRoutes` is only necessary if you need to implement some business logic—for example, conditionally loading a branch of sub-routes based off user permissions... otherwise, route definition modules can just be imported normally since async routes and split points are implemented in `getComponent`, which is lazily evaluated. From your example...

Overview Route definition
```js
import Overview from '../components/Overview'
export default { component: Overview }
```

Nested Router Config (TSP):
```js
import { injectReducer } from '../../store/reducers'

// Simple route definition for index (above)
import OverviewRoute from './routes/Overview'

// Async route definition factories for children that need access to store
import createOffersRoute from './routes/Offers'
import createReviewsRoute from './routes/Reviews'

export default (store) => (
  path: '/tsp/:id',
  indexRoute: OverviewRoute, // or just define as pojo { component: Overview } 
  childRoutes: [
    createOverviewRoute(store),
    createOffersRoute(store)
  ],
  getComponent (nextState, next) {
    require.ensure([], (require) => {
      const TSP = require('./containers/TSPContainer').default
      const reducer = require('./modules/tsp').default

      injectReducer(store, { key: 'tsp', reducer })

      next(null, TSP);
    })
  }
```

i know this answer is light on explanation, but i just feel like code is worth 1000 words, so i hope this helps steer you in the right direction... let me know if you have any questions :)

@davezuko i owe you some more documentation on this!

**Comment by chrismllr** [comment]
Hey @justingreenberg @davezuko, thanks for your responses! I actually was able to solve it, so I did need business logic and to pass one state / reducer down the chain of nested routes... Here's how I solved it...

*Disclaimer, passing the store to my child routes makes sense currently, as Id like to control state in my top level component and pass it down to my routes as if they were presentational components. I dont intend on the child routes being containers, but to have access to the state my top level route's container component is creating via `connect`... not sure if this is the proper way to do it, but at the moment seems to make sense

**`src/routes/TSP/index.js`**
```
import { injectReducer } from '../../store/reducers';

export default (store) => ({
  path: '/tsp/:id',
  indexRoute: require('./routes/Overview').default(store),
  getComponent (nextState, next) {
    require.ensure([
      './containers/TSPContainer',
      './modules/tsp'
    ], (require) => {
      const TSP = require('./containers/TSPContainer').default;
      const reducer = require('./modules/tsp').default;

      injectReducer(store, { key: 'tsp', reducer });
      next(null, TSP);
    });
  },
  getChildRoutes (location, next) {
    require.ensure([], (require) => {
      next(null, [
        require('./routes/Offers').default(store),
        require('./routes/Reviews').default(store)
      ]);
    });
  }
});
```

**`src/routes/TSP/routes/Overview/index.js`**
```
export default (store) => ({
  getComponent (nextState, next) {
    require.ensure([
      './components/OverviewView'
    ], (require) => {
      const Overview = require('./components/OverviewView').default;
      next(null, Overview);
    });
  }
});
```

**Comment by davezuko** [comment]
Awesome, closing as resolved then 🎉 .

**Comment by nelsontubaina** [comment]
I have a question:
 in these two lines here:
const TSP = require('./containers/TSPContainer').default;
const reducer = require('./modules/tsp').default;

can you change the name of the reducer? like for instance "const dinoguy = require('./modules/tsp).default" ?????

**Comment by chrismllr** [comment]
@nelsontubaina Sure can.. In this example `reducer` passed to `injectReducer` is just a shorthand property definition. read more about it ![here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer)

So you can do this instead...

```
getComponent (nextState, next) {
    require.ensure([
      './containers/TSPContainer',
      './modules/tsp'
    ], (require) => {
      const TSP = require('./containers/TSPContainer').default;
      const tspReducer = require('./modules/tsp').default;
      const otherReducer = require('./modules/other').default;

      injectReducer(store, { key: 'tsp', reducer: tspReducer });
      injectReducer(store, { key: 'other', reducer: otherReducer });
      next(null, TSP);
    });
  },
```
