### ISSUE TITLE
question: maintaining the starter kit in a production project

### ISSUE THREAD

**Issue by rosskevin** [davezuko/react-redux-starter-kit#801]
I'm just getting started with the full react/redux stack and the starter kit seems to have considered everything I can think of for building and maintaining a production application.

Here are my only concerns:
- I _hate_ copy and paste.
- There is a not so insignificant amount of code/thoughts/fixes in the current kit that I don't want to lose
- I like to update automatically if possible/stay as up-to-date as possible

I understand much of the changes are isolated, but nonetheless there are the important files that I'll want to keep up to date.

I have considered two options, I'd like to hear from others:
1. I ran across https://github.com/andrewmwhite/git-subtree.  Has anyone used something like this to maintain the starter-kit within their project?
2. write a script to clone and copy key files into my project

Any thoughts/strategies/ideas would be appreciated.

**Comment by davezuko** [comment]
Hey,

Until I can type out a more thoughtful reply, these two issues may be of interest to you:

* https://github.com/davezuko/react-redux-starter-kit/issues/692
* https://github.com/davezuko/react-redux-starter-kit/issues/336

I think there might be a couple of other issues that I can't find right now, but at least the first one touches on this slightly. I do have _plans_ to make this easier, but much of it revolves around currently-private work that is yet-to-be-open-sourced.

**Comment by roof12** [comment]
Another possibility is to fork the project, remove the example code and add your code. Every once in a while, merge this project into your own.

I'm doing this for another similar starter kit. I've done one merge, three months after the initial fork. The merge was tricky, but manageable. My changes were mostly additions of application functionality, not changes to the framework.

I bet your experience would be similar for a project based on this one.

**Comment by davezuko** [comment]
Closing as as-resolved-as-can-be.
