### ISSUE TITLE
Question: how can I control  stripping of debug?

### ISSUE THREAD

**Issue by vvatikiotis** [davezuko/react-redux-starter-kit#803]
Hello all,

Within a project, I use the npm debug package and I want to preserve these statements, even in production in order to be able to enable/disable them via the methods provided by the package. I noticed that within the JS bundles produced by webpack, all debug statements are stripped. Is there a way of controlling this behaviour within the react-redux-starter-kit?

Thx!!

**Comment by vvatikiotis** [comment]
Found a way of controlling it via the webpack UglifyJsPlugin. 

In build/webpack-environments/production.js:

`  
webpackConfig.plugins.push(
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        unused: true,
        dead_code: true,
        global_defs: {
          DEBUG: true,
        },
      },
    })
  );
`

and use the `enable/disable` methods of the debug package

**Comment by davezuko** [comment]
👍 good find. Closing this as resolved then (sounds like that's the case, at least).
