### ISSUE TITLE
Components life cycle functions 

### ISSUE THREAD

**Issue by ronydj** [davezuko/react-redux-starter-kit#804]
His guys,

I am newbie with react.

Where should I write the component life cycle functions? (componentDidMount,componentWillUnmount, etc).

I have tried something like:

Counter.componentDidMount = function () {
  alert('hi')
}

Inside the Counter.js, in Component folder, but it didn't work.

**Comment by davezuko** [comment]
You cannot use lifecycle methods on a stateless functional component (see https://facebook.github.io/react/docs/reusable-components.html#stateless-functions). If you need to use them, use a regular React class.

```js
class Counter extends React.Component {
  componentDidMount () {
  }
}
```

Closing this since it is not an issue with this project. Happy to answer questions, but you may have more luck on StackOverflow.

**Comment by ronydj** [comment]
thanks. I got it.

In you opinion, what is the best way to implement a calling action looping using the start kit?

I want to call an update action every 3 seconds. I've tried though the route "index.js" using set interval. But on the second call it trow an error (i Think it lost the dispatch context).

**Comment by leefsmp** [comment]
Hi, thanks. I agree about pure tech questions should be posted on SO directly, but I think it's cool to answer project-specific questions like this one here ;) Thanks that was useful and not obvious the first time you look at the code (unless you are a React expert)

About the update, maybe i'm misunderstanding your question, but what prevents you to place "setInterval" in the componentDidMount? My code is as follow and works fine:

    import './ViewerView.scss'
    import React from 'react'
  
    class ViewerView extends React.Component {
  
      componentDidMount () {
        console.log('componentDidMount: ViewerView')
        setInterval(()=>{
          console.log('update')
          this.props.refresh()
        }, 3000)
      }
  
      render() {
  
        const { viewerState }  = this.props
  
        return (
          <div>
            <h4>Viewer { viewerState.value }</h4>
          </div>
        )
      }
    }
  
    export default ViewerView
