### ISSUE TITLE
HMR issues after migration to v3

### ISSUE THREAD

**Issue by web2style** [davezuko/react-redux-starter-kit#806]
I migrated my webpack configuration to v3 but I'm issuing a weird problem with HMR.

When I make a change in any file I get the following output in the console:

```
[HMR] bundle rebuilding
client.js?875c:126 [HMR] bundle rebuilt in 2441ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:100[HMR] Updated modules:
process-update.js:102[HMR]  - ./src/views/wisetime.js
process-update.js:102[HMR]  - ./src/routes/index.js
process-update.js:107[HMR] App is up to date.
```

It is exactly the same as the output from a working copy of the kit.

But in my case the contents of the page is not updated. Only manual page reload helps to see the modified page.

I suppose this happens because I didn't migrate my routes configuration to the way it is in v3. It is still jsx tree:

```
export default (
  <Route path="/" component={CoreLayout}>
    <IndexRoute component={Home} />
    <Route path="/company" component={Company} />
   ...
    <Redirect from="*" to="/404" />
  </Route>
);
```

Is there any mandatory modifications to routes configuration in order to make HMR work?

Here is my `src/main.js` file:

```
import React from 'react';
import ReactDOM from 'react-dom';
import routes from './routes';
import AppContainer from './containers/AppContainer';
import configureStore from './redux/configureStore';
import {applyRouterMiddleware, browserHistory} from 'react-router';
import useScroll from 'react-router-scroll';
const initialState = window.__INITIAL_STATE__;
const store = configureStore({ initialState, history });

// ========================================================
// Render Setup
// ========================================================
const MOUNT_NODE = document.getElementById('root')

let render = (routerKey = null) => {
  ReactDOM.render(
    <AppContainer
      store={store}
      history={browserHistory}
      routes={routes}
      routerKey={routerKey}
      render={applyRouterMiddleware(useScroll(() => false))}
    />,
    MOUNT_NODE
  )
}

// Enable HMR and catch runtime errors in RedBox
// This code is excluded from production bundle
if (__DEV__ && module.hot) {
  const renderApp = render
  const renderError = (error) => {
    const RedBox = require('redbox-react')

    ReactDOM.render(<RedBox error={error} />, MOUNT_NODE)
  }
  render = () => {
    try {
      renderApp(Math.random())
    } catch (error) {
      renderError(error)
    }
  }
  module.hot.accept(['./routes/index'], () => render())
}

// ========================================================
// Go!
// ========================================================
render()
```

As you see it is almost the same except of history configuration.

Can't understand why it doesn't work and console output is as if it is correct. Really weird...

**Comment by nathanvale** [comment]
I have just spent the last 2 days going crazy over this exact issue. Im at the point now where I dont know how to move forward.

**Comment by web2style** [comment]
The same problem for me. @davezuko could you please point us to the right direction? Would really appreciate any help as it is the blocker for me at the moment.

**Comment by nathanvale** [comment]
I got it working

the render setup needs to looks something like this. you need to require a new routes object for it to re rerender.

/ ========================================================
// Render Setup
// ========================================================
let render = (key = null) => {
  const Root = require('./containers/Root').default
  const routes = require('./routes/index').default(store)
  let App
  if (__DEV__) {
    App = (
      <AppContainer  >
        <Root routerKey={key} store={store} history={history} routes={routes} />
      </AppContainer>
    )
  } else {
    App = (
      <Root store={store} history={history} routes={routes} />
    )
  }
  console.log(App)

  ReactDOM.render(App, MOUNT_ELEMENT)
}

**Comment by web2style** [comment]
@nathanvale Great!

Please, clarify, what's inside 

```
if (DEV) {
App = (



)
} else {
App = (

)
```

in your case?

Also, I see you are passing `store` to the routes when requiring them. Did you migrate the routes according to kit's v3? Can it work in my case if I don't do that?

**Comment by nathanvale** [comment]
Inside that block is hot-reload-beta3 code branch (check out the hot reload 3 branch).

Anyway the key thing here for hot reload and routes in general is require the routes and create them by passing in a store again so the render of the changes can take place when it gets called in module.hot.accept.

Also the random generated key forces react to do the reload on its diff i believe.

`// ========================================================
// Render Setup
// ========================================================
let render = (key = null) => {
  const Root = require('./containers/Root').default
  const routes = require('./routes/index').default(store)
  let App
  if (__DEV__) {
    App = (
      <AppContainer  >
        <Root routerKey={key} store={store} history={history} routes={routes} />
      </AppContainer>
    )
  } else {
    App = (
      <Root store={store} history={history} routes={routes} />
    )
  }
  ReactDOM.render(App, MOUNT_ELEMENT)
}


// ========================================================
// HMR Setup
// ========================================================
// Enable HMR and catch runtime errors in RedBox.
// This code is excluded from production bundle.
if (__DEV__ && module.hot) {
  const renderApp = render
  const renderError = (error) => {
    const RedBox = require('redbox-react')
    ReactDOM.render(<RedBox error={error} />, MOUNT_ELEMENT)
  }
  render = () => {
    try {
      renderApp(Math.random())
    } catch (e) {
      renderError(e)
    }
  }
  module.hot.accept(['./containers/Root', './routes/index.js'], () => {
    render();
  })
}`

**Comment by davezuko** [comment]
@nathanvale, thanks for the comments! Edited your posts to give us some syntax highlighting to work with :).

**Comment by web2style** [comment]
@davezuko FYI, hot reloading doesn't work for `src/routes/Home/components/HomeView.js` in `feature/react-hot-loader-v3` branch.

**Comment by davezuko** [comment]
@web2style yeah the branch is not yet working, I opened it but haven't the time or energy to debug issues while it's still in beta. Will revisit it soon, hopefully.
