### ISSUE TITLE
I'm missing something - Action handler not called.

### ISSUE THREAD

**Issue by copyhold** [davezuko/react-redux-starter-kit#810]
![screenshot from 2016-05-16 15 16 48](https://cloud.githubusercontent.com/assets/42069/15289210/45321128-1b79-11e6-94c3-a3fa60989b19.png)

**Comment by davezuko** [comment]
Not being able to see your entire code, but my guess is that you're not actually dispatching the action. You'll just need to step through it by checking if you reducer is called, and if it is, then digging further to see why the handler isn't. If you don't even see the action come through, it's probably not being dispatched.

Closing as this is not an issue with this project. I suggest posting in StackOverflow.
