### ISSUE TITLE
Integration with Django app

### ISSUE THREAD

**Issue by hamishtaplin** [davezuko/react-redux-starter-kit#812]
So I have a Django app which will serve up the main templates for the application [using this approach](http://owaislone.org/blog/webpack-plus-reactjs-and-django/).

I initially set all this up months ago and got it working but am in the process of updating our application with the newer version of the starter kit. The only issue I'm running to is that I don't want `index.html` to be served up by webpack but rather the Django app.

So far, apart from adding the plugins as per the aforementioned article, I have removed the [html-webpack-plugin](https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L49) (I assume I don't need this?)

If I [enable the proxy option](https://github.com/davezuko/react-redux-starter-kit/blob/master/config/environments.js) I can get the app to serve the template from Django but then the bundles don't get served because it's proxying everything through `localhost:8000` instead (I removed the `match` option).

Any ideas? you can see progress in [this branch of my repo](https://github.com/ONSdigital/eq-author/tree/update-webpack).

**Comment by AlexGrs** [comment]
I'm also interested by having your feedback about serving frontend from index.html in Django. Right now, I'm using this starter kit and use the proxy option to redirect all /api/ requests to the Django backend. It works really fine and I then have my frontend completely independant from the backend.

**Comment by zargold** [comment]
Is there a way to get a completely isolated front-end or is anyone aware of a front end only react-redux (with routing) starter kit?

**Comment by davezuko** [comment]
@zargold the front end here _is_ entirely isolated, the only reason the server exists is to reroute requests to the webpack dev server. Basically, if you replaced the Koa server with `webpack-dev-server`, you wouldn't notice a change (beyond not being able to immediately write a backend server). If you could clarify the desired separation I might be able to be of more help.

**Comment by zargold** [comment]
So to confirm any backend here is a devDependency? I am also building a react redux app into an existing django app. As much as I love node servers, I just want to make sure before I dive too deep into this that I won't have to run a node server in addition to the django one.

**Comment by chompomonim** [comment]
If you want hot reload for your react app, unfortunately using additional node server (for dev environment only). This weekend I will try to make fork of this kit with Django or flask as backed to show how to use react redux and we pack with Python frameworks.

**Comment by davezuko** [comment]
@zargold yes, the backend here is just a devDep.

**Comment by davezuko** [comment]
(it is marked as a `dependency` because of users struggling with `npm i` on CI environments... I may revert this workaround).
