### ISSUE TITLE
Polyfill IE11

### ISSUE THREAD

**Issue by simonvpe** [davezuko/react-redux-starter-kit#815]
I am having some issues getting my application to work in internet explorer. I've tried to add es6-polyfill plugin to the webpack configuration but i'm getting "SCRIPT445: Object doesn't support this action" when calling the Promise constructor.

**Comment by davezuko** [comment]
You should use `babel-polyfill`. See: https://github.com/davezuko/react-redux-starter-kit/commits/master.

This is in master now, so closing.
