### ISSUE TITLE
Unclear/Partial Flow References

### ISSUE THREAD

**Issue by xml** [davezuko/react-redux-starter-kit#820]
Looking at #790 & #735, it looks like Flow was once included, but has now been removed? If I've got that right, two questions:

1. Would you like a doc PR to mention that in the changelog? Changelog mentions adding/updating several of the Flow libs, but doesn't mention that they've since been removed. Which version did that happen in? 
2. The blueprints still seem designed for flow. Would you like a PR to revert them to a standard propTypes approach? 

For instance, in the docs for redux-cli, there's this example, of fairly standard propTypes on the components:

```js
import React, { Component, PropTypes } from 'react';

const propTypes = {
};

class <%= pascalEntityName %> extends Component {
}

<%= pascalEntityName %>.propTypes = propTypes;
```

But in the current blueprints here, it's more like:

```js
import React from 'react'

type Props = {}

export class <%= pascalEntityName %> extends React.Component {
  props: Props;
  render () {}
}
```

I understand that to be a syntax related to Flow, right?

----

Related question: since the blueprints seem useless without `redux-cli`, and since the `redux-cli` source includes the blueprints, why are they duplicated here as well? (Or is their presence over there considered the duplication?) Either way: it seems confusing to have the duplication, from both a least-surprise and a DRY perspective...

**Comment by davezuko** [comment]
@xml thanks for noticing this, and I really apologize for the delay in replying -- I've been away from this project for the last couple of weeks. You're absolutely correct that these should be fixed. I'm fairly certain the removal of Flow came with the `3.0.0` tag, but I'll have to investigate it further. If you're still up for doing both of the PR's for #1 and #2 I'd be more than happy to merge them in, and if not I'll get around to it sometime soon hopefully.

To answer the final blueprints question, the current blueprints are wholly incorrect after moving to the fractal structure. There's a longstanding PR out that addresses some of the problems, but essentially our blueprints _will_ be different than those in `redux-cli`. I think we originally included our own blueprints just so we had control over them if we needed to change them, and that just never happened, hence the apparent duplication.

**Comment by davezuko** [comment]
Blueprints are in the process of being cleaned up.
