### ISSUE TITLE
Adding Chai / Sinon to Unit Testing

### ISSUE THREAD

**Issue by urbaitel** [davezuko/react-redux-starter-kit#830]
Chai JS (http://chaijs.com/) is a fantastic assertion library and Sinon (http://sinonjs.org/) is great for spying.   I'm going to fork this and add it..  is that something you would like to see added to the core?

**Comment by davezuko** [comment]
Thanks for the proposal, but unless I'm missing something this is already included: https://github.com/davezuko/react-redux-starter-kit/blob/master/tests/test-bundler.js#L5-L18.

**Comment by urbaitel** [comment]
Aha!   I'm diving deep into this now.   This is great!
