### ISSUE TITLE
QUESTION how to add use  different layouts?

### ISSUE THREAD

**Issue by katcu** [davezuko/react-redux-starter-kit#831]
Hi, I am new to starter-kit. Could you show some snippets on how to using other layouts with my own templates(other than `index.html`). Thanks!

![image](https://cloud.githubusercontent.com/assets/19196404/15600439/6a14bbf2-241c-11e6-8a9b-2188edc32aea.png)

**Comment by kolpav** [comment]
Wrap your views in high order component. You can even have different layouts for different routes/sub routes
```javascript
<Route path='/' component={CoreLayout}>
    <Route path='/tea' component={TeaLayout(TeaView)} />
    <Route path='/coffee' component={CoffeeLayout(CoffeeView)} />
    <Route path='/secret' component={AuthenticatedRoute(AddTabView)} /> // Uses default core layout with authentication logic
</Route>
```

**Comment by katcu** [comment]
@kolpav  does it mean that sub layouts are derived from CoreLayout?

**Comment by kolpav** [comment]
I would think about it more like `TeaView` is rendered into `TeaLayout` which is rendered into `CoreLayout` each of them can add additional functionality/layout/styles etc. If it is still unclear let me know and I'll do some simple example

**Comment by katcu** [comment]
got it.  Thanks.  by the way,  I'm using Semantic-UI,and previously I've built a themed page using semantic-ui. and now I move it to my component code, just as following,
![image](https://cloud.githubusercontent.com/assets/19196404/15611240/05e8d4de-245c-11e6-9472-bbf5d6dbc439.png)
and the customized styles,
![image](https://cloud.githubusercontent.com/assets/19196404/15611260/28eeb994-245c-11e6-9a1a-ade878436b53.png)

The problem is that the  styles.css imported to the component are compiled, so I need to change my origin classNames to as{styles.classname}, right? do you have any suggested aproach to get around it.

**Comment by kolpav** [comment]
I am not sure if I understand but take a look at [_base.scss](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/styles/_base.scss) this is where you can import theme css files. Also I noticed you are using jquery in your components. Please just don't.. jquery have no place in react application as it doesn't bring anything you can't do without it in much more cleaner, maintainable, testable way. I am not even sure how it works together but I guess not very well.

**Comment by katcu** [comment]
pls take a look at [semantic-ui](http://semantic-ui.com/) which base on jquery, just like other theme libraries,bootstrap. Some cool animations are already out of box, so I don't want to rewrite them in react components 😴 

![image](https://cloud.githubusercontent.com/assets/19196404/15629602/e552b420-254f-11e6-9fad-bf986b785c09.png)

But if I inherited lots of styles from vendor's css, just as following,
![image](https://cloud.githubusercontent.com/assets/19196404/15629614/3f17ad12-2550-11e6-842d-da1284df59e1.png)

then I need to update all related classNames.
