### ISSUE TITLE
Slightly confused regarding shared state in this structure

### ISSUE THREAD

**Issue by EwanValentine** [davezuko/react-redux-starter-kit#832]
Hi there,

I understand the point in the routes directory, and splitting your component, and their actions, reducers etc into their own directories together. But for example, if I have a `user` state, I would want to use that reducer in my login route, my profile route, perhaps an account settings route. So what would be the suggested way to get around that?

I considered just adding a reducers, and an actions directory into the application route, but I wasn't sure how I'd get that to work with `injectReducer` or where that would be called. 

What approach would you suggest?

Cheers!

**Comment by kolpav** [comment]
Site wide reducers should go here I think https://github.com/davezuko/react-redux-starter-kit/blob/master/src/store/reducers.js#L6

**Comment by EwanValentine** [comment]
Ahhhh of course! Thanks!
