### ISSUE TITLE
QUESTION: starting new project

### ISSUE THREAD

**Issue by m4recek** [davezuko/react-redux-starter-kit#834]
Hi, 
I am about to start a new project. And I am thinking about how much will version-3 branch change until release. Is it worth starting a project on it ATM?

**Comment by davezuko** [comment]
`v3` isn't a _whole_ lot different from `v2`, other than the fact that it removes support for `react-transform` and incorporates the new fractal structure. I'd say go with `v3`, the only major change I can see coming is the incorporation of react-hot-loader `v3`.
