### ISSUE TITLE
Promise then not called in spec

### ISSUE THREAD

**Issue by SDLyu** [davezuko/react-redux-starter-kit#836]
Hi all,

I found that `Promise.then` now always called in spec file.
Add two promise statement in `tests/routes/Home/components/HomeView.spec.js`, then run `npm run test` only print out `LOG: 'test1'`

```js
import React from 'react'
import { HomeView } from 'routes/Home/components/HomeView'
import { render } from 'enzyme'

describe('(View) Home', () => {
  let _component

  beforeEach(() => {
    _component = render(<HomeView />)
  })

  it('Renders a welcome message', () => {
    const welcome = _component.find('h4')
    expect(welcome).to.exist
    expect(welcome.text()).to.match(/Welcome!/)
  })

  Promise.resolve().then(() => { console.log('test1') })

  it('Renders an awesome duck image', () => {
    const duck = _component.find('img')
    Promise.resolve().then(() => { console.log('test2') })
    expect(duck).to.exist
    expect(duck.attr('alt')).to.match(/This is a duck, because Redux!/)
  })
})
```
Any idea?

**Comment by kolpav** [comment]
I think it is because every `it` spawns iframe in which the test code runs. The callback specified in `then` is put onto queue, test finishes and frame is destroyed along with its queue so you never see `test2`.
 But you can still test promises like so `doSomethingAsync().should.eventually.equal("foo")` 
(I might be completely wrong just guessing here)

**Comment by davezuko** [comment]
You need to return the promises in your tests, or manually call `done` in each `it` block, since tests are synchronous by default.

```js
it('Should do something async', () => {
  return Promise.resolve('foo').should.eventually.equal('foo')
})

// or
it('Should do something async', () => {
  return doSomethingAsync()
    .then(() => { /* assert your success cases here */ })
})

// or
it('Should do something async', (done) => {
  return doSomethingAsync()
    .then(() => { /* assert your success cases here */ })
    .then(done) // tell mocha your test is finished
})

```

Closing since this is not an issue with the project, but if you still need help I'm happy to continue the thread anyways.

**Comment by SDLyu** [comment]
@davezuko thanks for your reply, really helpful and save my day 👍
