### ISSUE TITLE
QUESTION: Where put app logic for a simple layout not-routed application?

### ISSUE THREAD

**Issue by aabilio** [davezuko/react-redux-starter-kit#839]
I have to reimplement a big Symfony2 project, and I decided to use React with Redux for the new front.

But before, I was experimenting with a simple mini game with this starter kit, but for this game I do not need routes. I have a layout idea like this:

``` 
<App>
    <Header >
    <Game > 
    <Footer >
</App>
```

Where `Header` and `Footer` are static and in Game goes all the logic. But, in the starter kit `src/components` and `src/containers` are for "Reusable Components", and the reducers examples are always on a `src/route` directory.

How could I structure this mini game using this starter kit?

**Comment by kolpav** [comment]
I don't see the problem with puting `<Game />` component into `src/components`
> reduers examples are always on a src/route directory

That is not true you have `router` reducer not tied to any particular route in `reducers.js` so you can put more reducers here. If you don't need routes then just use `indexRoute` in which will be just your `<Game/>` component connected to the store. Fractal structure used in this project doesn't really makes sense for such simple applications as one you described.

**Comment by aabilio** [comment]
Thanks @kolpav

"Fractal structure used in this project doesn't really makes sense for such simple applications as one you described"

That's true, I know. This project is just for practice with a current real little project, then I will have to develop a big project with a real fractal structure.

**Comment by kolpav** [comment]
@aabilio good luck with your game :+1:

**Comment by davezuko** [comment]
@kolpav 's answer is totally correct, thanks!
