### ISSUE TITLE
Relative path to differanciate between importing files vs node modules ?

### ISSUE THREAD

**Issue by bulby97** [davezuko/react-redux-starter-kit#84]
Would it not be better to know which one come from app ?

``` javascript
import React        from 'react';
import { Provider } from 'react-redux';
import { Router }   from 'react-router';
import routes       from 'routes';
import invariant    from 'invariant';
import { RoutingContext } from 'react-router';
import { createDevToolsWindow } from 'utils';
import { DevTools, LogMonitor, DebugPanel } from 'redux-devtools/lib/react';
```

vs

``` javascript
import React        from 'react';
import { Provider } from 'react-redux';
import { Router }   from 'react-router';
import routes       from './routes';
import invariant    from 'invariant';
import { RoutingContext } from 'react-router';
import { createDevToolsWindow } from './utils';
import { DevTools, LogMonitor, DebugPanel } from 'redux-devtools/lib/react';
```

**Comment by davezuko** [comment]
Very good point. Do you think this is a problem with aliases in general, or specifically that it should just be more explicit when requiring a base folder (as in `routes` and `utils`)? Will definitely update at least these and the `stores` reference.

**Comment by bulby97** [comment]
I think that aliases are awesome !

 In fact,  I didn't know you could do that til tonight :). But still something should be done to differranciate modules from base folders. 

Maybe an underscore, or just a point ? Meh. Dunno :/

**Comment by davezuko** [comment]
I updated the ones you pointed out as well as a couple others. I don't know if there's a great solution other than people familiarizing themselves with the project structure :/. Closed with https://github.com/davezuko/react-redux-starter-kit/pull/87.
