### ISSUE TITLE
How to reset entirely the redux state?

### ISSUE THREAD

**Issue by nickgnd** [davezuko/react-redux-starter-kit#840]
Hi, I really love this react-redux starter kit, thanks for the great work. 

I have implemented a simple authentication flow and I'm trying to **reset** the whole `redux` state at the user logout, but I'm not able. 

I've take inspiration by [this](http://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store) snippet on SO: 
```js
const appReducer = combineReducers({
  /* your app’s top-level reducers */
})

const rootReducer = (state, action) => {
  if (action.type === 'USER_LOGOUT') {
    state = undefined
  }

  return appReducer(state, action)
}
```

but I don't understand how/where I can apply the solution above at the starter-kit.

In this past days i've already tried without success to enhance the [`makeRootReducer`](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/store/reducers.js#L17) function with a _high order reducer_ for resetting the state, but It doesn't seem the right solution.

Does anyone have some hints to point me in the right direction? Thanks!

**Comment by kolpav** [comment]
I don't think the problem is related to this repo but you can try this.
```javascript
export const makeRootReducer =
  (asyncReducers) =>
  (state, action) =>
  combineReducers({
    entities,
    snackbar,
    auth,
    paginate,
    router,
    ...asyncReducers
  })(action.type === 'STATE_RESET' ? undefined : state, action)
```

**Comment by nickgnd** [comment]
Thanks a lot @kolpav ! It works, I tried with very similar approaches in these past days but without success.

**Comment by jasongonzales23** [comment]
This just made my day 🍻 !

**Comment by patrickleemsantos** [comment]
It works! Thanks!
