### ISSUE TITLE
QUESTION: chrome devtools auto popup/focus on page load

### ISSUE THREAD

**Issue by naviehuynh** [davezuko/react-redux-starter-kit#841]
Hi,
When I navigate to the default homepage, it focuses redux devtools window automatically. Other pages such as [this](http://zalmoxisus.github.io/redux-devtools-extension/examples/router/#/AutoTodo?_k=15wbiu) doesn't have this behavior.
Also if I have a devtools opened from other pages and then navigate to the project homepage, it opens a new window instead of reusing existing one.

**Comment by kolpav** [comment]
It is not direct answer to your question but I solved this by commenting out [this](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/main.js#L29-L36) and started using [redux devtools extension to chrome](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) and I like it much more than having separate window.

**Comment by naviehuynh** [comment]
oh, I should have done a grep :stuck_out_tongue:  Thanks @kolpav.
