### ISSUE TITLE
Using babel-node

### ISSUE THREAD

**Issue by aamirnshah** [davezuko/react-redux-starter-kit#843]
Hello!

According to the babel documentation (https://babeljs.io/docs/usage/cli/), babel-node should not be used in production. I'm just wondering if there is a reason you are using babel-node to launch the server and if this pack is safe to launch in production. Thanks!

**Comment by davezuko** [comment]
It's totally safe in production. It is possible to better optimize it by precompiling the server before running it, you're right, but that's hardly necessary for any moderately sized applications. That being said, I do want to remove the babel from the codebase entirely (except for the client), but it's needed for now to support Koa.

This thread https://github.com/davezuko/react-redux-starter-kit/issues/625 may be of interest to you.
