### ISSUE TITLE
My computer gets frying hot, as it compiles on every hot load, is there a way to fix that?

### ISSUE THREAD

**Issue by bytewiz** [davezuko/react-redux-starter-kit#848]
pretty much fitted it all in the title :-)

**Comment by bhj** [comment]
Is it your editor?

https://github.com/davezuko/react-redux-starter-kit/wiki/FAQ:-Frequently-Asked-Questions#high-editor-cpu-usage-after-compilation

**Comment by bytewiz** [comment]
Might be have you encounter this "issue" with WebStorm?

**Comment by bytewiz** [comment]
@bhj Might be have you encounter this "issue" with WebStorm?

**Comment by bytewiz** [comment]
@bhj Might be have you encounter this "issue" with WebStorm?

**Comment by bytewiz** [comment]
Sorry for spamming dont know what just happend

**Comment by bhj** [comment]
@bytewiz I'm using Atom on macOS and haven't had any issues. The `dist` folder is .gitignored in this starter kit by default so that may be telling Atom to not bother indexing it... not sure. Either way, look at Task Manager to be sure what is actually responsible for the CPU usage.

**Comment by bytewiz** [comment]
@bhj I checked and it is actually the terminal who is the bad guy here, it starts running 120% as soon as I fire ``npm start``

**Comment by bhj** [comment]
If your CPU calms down after compilation that may be normal. If it stays pegged at 120% even after Webpack is finished bundling something else is going on with your system. I'd post the versions you're using of the starter kit, Node, OS, etc.

**Comment by bytewiz** [comment]
It stays Crazy high, I will post the specifications :-)

Appreciate your help!
Den 07/06/2016 7.18 PM skrev "Brandon Jones" <notifications@github.com>:

**Comment by bytewiz** [comment]
Report:
starter-kit : 3.0.0-alpha.0
node : >=4.2.0
npm : ^3.0.0
webpack-hot-middleware : ^2.6.0

Mac report: 
OS: El Capitan
Processor Name:	Intel Core i7
Processor Speed:	2,2 GHz
Number of Processors:	1
Total Number of Cores:	4

**Comment by bhj** [comment]
Do you get a similar issue with something like https://github.com/gaearon/react-hot-boilerplate ?

Make sure WebStorm is ignoring those folders mentioned in the FAQ and you might try upgrading Node as well unless you want to stay on 4.x for a reason

**Comment by davezuko** [comment]
There really is not that much happening in this project that wouldn't be in any other project with equal features, so I'm not convinced there's much that we can do besides what is provided in the FAQ.

**Comment by patrickgordon** [comment]
FWIW I'm also getting similar issues. CPU % for node jumps to 100-120 % as soon as I do `npm start`

**Comment by patrickgordon** [comment]
I did a 
`rm -rf node_modules` 

and 
`npm install` 

and this appears to have resolved my issue...

**Comment by jonaswindey** [comment]
I've also noticed that the cpu jumps to 100% when using yarn. Remove node modules and use npm install instead.
