### ISSUE TITLE
webstorm eslint errors

### ISSUE THREAD

**Issue by chovy** [davezuko/react-redux-starter-kit#851]
every file is riddled with eslint errors when I open the project in webstorm.

i have eslint enabled. is there something I'm missing?

**Comment by kolpav** [comment]
I think webstorm is producing these errors not eslint. You need to disable native ws linting I guess.

**Comment by davezuko** [comment]
It's a configuration error with webstorm, that's all it can be since the project abides by its `.eslintrc`. Not familiar with webstorm so unfortunately I don't really know what or where to look.

**Comment by chovy** [comment]
I don't think so. I have eslint enabled and checked the box that says to look for a .eslintrc file

**Comment by kolpav** [comment]
This project does not produce any eslint errors if you don't trust me you can do fresh pull and then do `npm run lint`. So even if you have eslint set up correctly the errors you are seeing are not from eslint but ws default linter which you need to disable.
I am guessing here as I don't have ws installed.
Do you think you can share screenshot or paste here code with its error message? I am pretty sure it would be error from ws code inspection or whatever it is called and not something like `react/jsx-indent error`.

**Comment by levithomason** [comment]
Screenshot is the ticket. Also, click on one of the red underlines putting your caret on the error, then check the status bar. What does it say?

Lastly, with the caret still on the error hold alt/option and press enter, in the context menu find the error and press the right arrow to expand the context menu. You'll see options for the error. My guess is that you'll see "Disable inspection" and "edit inspection settings" options. If so, these are webstorm  inspection errors, separate from eslint. 

If you're still stuck, please post the screenshot. 

Good luck.
