### ISSUE TITLE
Webpack hmr failed to load after npm run deploy

### ISSUE THREAD

**Issue by alexanderfrey** [davezuko/react-redux-starter-kit#853]
Hi,

In order to deploy the web application I run 'npm run deploy' and use the assets from the dist folder for deployment. Everything works fine on server except that I keep getting errors in the browser console that notify me about the 'ressource __webpack_hmr' could not be loaded from local localhost.
Why do I get those errors that apparently do not affect the rest of the application and why is webpack hmr still active in the deployment target ?

Thanks and kind regards

**Comment by alexanderfrey** [comment]
I search the app.js in the dist folder for my local ip and found the following line:

/* WEBPACK VAR INJECTION */}.call(exports, "?path=http://192.168.200.176:3333/__webpack_hmr", __webpack_require__(236)(module)))

Do I use the wrong deployment command for packing everything together ? Right now I use 'npm run deploy'. It gives me one app.js and one vendor.js together with an index.html with if very convenient and perfect for me to deploy. 

What am I doing wrong ?

**Comment by davezuko** [comment]
Can you please try `npm run deploy:prod`? This will disable all HMR and your bundles should work correctly.
