### ISSUE TITLE
cant inject more than 1 reducer

### ISSUE THREAD

**Issue by mouhsinelonly** [davezuko/react-redux-starter-kit#855]
when i try to inject more than one reducer with my root component only when is available with the variable reducer

const newsreducer = require('./modules/news_reducer').default

 const reducer = require('./modules/registration_period').default

 injectReducer(store, { key: 'news', newsreducer })

injectReducer(store, { key: 'registration_period', reducer })

can any one tell me what i did wrong ?

when i do console.log(store);

only the reducer with the key registration_period is available , and news is undefined

**Comment by KendallPark** [comment]
Was a solution reached for this?

**Comment by patrickgordon** [comment]
I'd love an actual explanation for this too if possible. I managed to resolve it with this... untidy fix:

```js
      var reducer
      reducer = require('./modules/roster').default
      injectReducer(store, {key: 'roster', reducer})
      reducer = require('./modules/shift').default
      injectReducer(store, {key: 'shift', reducer})
```

For some reason that I can't figure out it needs to be passed as `reducer` to `injectReducer`.

**Comment by m4recek** [comment]
That's because you need to pass 'reducer' key in that object. ES6 is expanding it for you if you have your reducer in 'reducer' variable.
'''
injectReducer(store, {key: 'shift', reducer: myReducer})
'''

**Comment by patrickgordon** [comment]
Ugh I'm so dumb... thanks a lot @m4recek !

**Comment by m4recek** [comment]
Well, I've seen two other devs at my job doing same thing within last 2 months... so it's quite common. 

Probably should be changed in counter example to be more intuitive. @davezuko ?

**Comment by davezuko** [comment]
Being valid ES6 I'd prefer to keep it but just add some comments around it to make it clear for users who are not familiar with the key/value mirroring. I'll see if I can get something in later tonight.

**Comment by latuprez** [comment]
Comments would be great - this tripped me up for a day too.
