### ISSUE TITLE
Failed to parse SourceMap Error

### ISSUE THREAD

**Issue by woniesong92** [davezuko/react-redux-starter-kit#858]
From some point, I keep getting this error from the console.
Breakpoints seem to point at wrong points in chrome developer tools because of this.
Any ideas?

<img width="394" alt="screen shot 2016-06-13 at 2 17 44 pm" src="https://cloud.githubusercontent.com/assets/2935309/16023429/9fb42e70-3171-11e6-89c5-7db2725d073c.png">

**Comment by nhagen** [comment]
I've also been getting this the last day or two

**Comment by Pintouch** [comment]
I have the same error in the Chrome Console. I'm using Version 51.0.2704.84 (64-bit) of chrome and my Webpack config file is updated from this commit : https://github.com/davezuko/react-redux-starter-kit/commit/fedfd79f0795cb0aa561424d28ce3334be3e878b

**Comment by woniesong92** [comment]
Do you think it's Chrome-specific issue or webpack is somehow involved too?

**Comment by nhagen** [comment]
I fixed this by switching to the Chrome Dev release channel. I think this is a Chrome issue (at least, mine was). Maybe there's some specific bug that this project triggered, but it appears to be fixed upstream in Chrome.

**Comment by kring** [comment]
I had similar problems in a different project, and was able to solve it with a small change to `style-loader`.  See here:
https://github.com/webpack/style-loader/pull/132

**Comment by alex-dixon** [comment]
Appears fixed in Chrome 52.0.2743.82
