### ISSUE TITLE
header test

### ISSUE THREAD

**Issue by gilesbradshaw** [davezuko/react-redux-starter-kit#860]
Am I going mad?  in header.spec.js I can make both

````
    expect(_wrapper.contains(<Link to='/counter'/>)).to.equal.false
    expect(_wrapper.contains(<Link to='/counter'/>)).to.equal.true
````

I think you need

````
    expect(_wrapper.contains(<Link to='/counter'/>)).to.be.true
````

**Comment by gilesbradshaw** [comment]
and when u fix the test it fails as Link has activeClassName

**Comment by davezuko** [comment]
Good catch. These really should use `should` expectations with actual method calls to prevent mistakes like this. Will fix.

**Comment by davezuko** [comment]
Thank you for your PR: https://github.com/davezuko/react-redux-starter-kit/pull/861. Your fix has been merged into master.
