### ISSUE TITLE
Referencing /static/* doesnt work on windows

### ISSUE THREAD

**Issue by m4recek** [davezuko/react-redux-starter-kit#862]
Hi, 
we have a problem with files under /static/\* directory. When we reference them in scss files they are not loaded. e.g. `background-image: url('/me.jpg')`.
- They are properly served by webserver. I can access `localhost:3000/me.jpg` and it works
- They are properly copied to `/dist/` directory when `npm run deploy` is run
- They are not loaded/visible in development when referenced as `/me.jpg` in scss files but work when referenced as `http://localhost:3000/me.jpg`

How should we get them working in develoment mode? 

I've been searching a bit more and it seems same as https://github.com/davezuko/react-redux-starter-kit/issues/696, maybe its because scss bundle is served from `blob:http://...` so image has wrong protocol...

**Comment by m4recek** [comment]
Did a bit more testing today and found this.

1. if you reference something static outside of `:global { }` block as `static/something.jpg` it works
2. if you do very same think inside `:global {}` block it doesnt work

**Comment by s1ddh1k** [comment]
To avoid this, you should remove sourceMap options for css-loader.

Ref: https://github.com/webpack/style-loader/pull/124

**Comment by tlaak** [comment]
This problem also exists on a Mac. There is a workaround (https://github.com/webpack/style-loader/pull/96#issuecomment-228370602), but I'm haven't managed to get it to work with this starter-kit.

**Comment by davezuko** [comment]
Closing since `static` and css modules have been moved and removed, respectively.
