### ISSUE TITLE
Use koa-static v3.0.0

### ISSUE THREAD

**Issue by jarohmh** [davezuko/react-redux-starter-kit#864]
koa-static already supports koa2, so we don't have to use convert for it. Why you don't migrated into it yet? Is there any reason for that?

**Comment by kodermax** [comment]
agree

**Comment by davezuko** [comment]
No reason, probably just never saw it. Willing to accept a PR, otherwise I'll get to it when I have a chance.

**Comment by chompomonim** [comment]
Here is PR #868
