### ISSUE TITLE
Can't access dev server from other devices (even though I added server_host = "[my_IP]")

### ISSUE THREAD

**Issue by bytewiz** [davezuko/react-redux-starter-kit#867]
Here is the config/index.js --> tried both 0.0.0.0 and [my_ip]

but when running `npm start` I can only access 0.0.0.0:3000 or [myip]:3000 on my own computer and non other devices on the same network. And [my_ip] is the local ip gotten by ifconfig |grep inet 

Any suggestions why this doesn't work?

![screen shot 2016-06-17 at 11 52 22](https://cloud.githubusercontent.com/assets/16811871/16147190/012dd36e-3482-11e6-9b8f-c8e64897ec4c.png)

**Comment by marshallford** [comment]
While manually punching in your local ip address should certainly work, you can also use the variable `localip` (assuming you are running a recent version) and your computer's local ip address should automagically be used. As for your issue, I would confirm that your network's firewall and or your computer's local firewall isn't blocking the request.

**Comment by gabeweaver** [comment]
@bytewiz i've really enjoyed using BrowserSync with this starter kit. To do so, just `npm install --save-dev browser-sync browser-sync-webpack-plugin` then `import .... from '...'` at the top of the webpack config, then in the `if (__DEV__)` plugins section, add this:
```
  new BrowserSyncPlugin({
      open: false,
      host: config.server_host,
      port: 4000,
      proxy: 'localhost:3000',
      ui: {
        port: 4001
      }
    }, {
      reload: false
    })
```
That will print out the correct local IP address to access the development environment on external devices connected to the same network. It also has all sorts of goodies...

@davezuko is this something you'd find valuable for this project? If so, i'm happy to open a PR!

**Comment by bytewiz** [comment]
Awesome I will try it out :-) thanks appreciate it!
Den 23. jun. 2016 9.41 PM skrev "Gabe Weaver" <notifications@github.com>:

**Comment by davezuko** [comment]
@gabeweaver sorry, never saw your message. I was against it in the early days of this project, but I think it's worthwhile now if you'd like to submit a PR. Closing this issue for now, but would appreciate a PR for BrowserSync still if you're up for it.
