### ISSUE TITLE
Nested SASS/SCSS 

### ISSUE THREAD

**Issue by EwanValentine** [davezuko/react-redux-starter-kit#872]
Just a quick question, can you use nested scss rules? I've recently migrated an older React project to this starter-kit. However, my nested scss rules don't seem to play ball. 

When I import scss using... `import './MyComponent.scss`' the styles don't seem to get applied. But when I use `import classes from './MyComponents.scss'` the styles are applies, but nested rules don't seem to be rendered. Say if I had... 

```
// Scss
.MyComponent {

  color: black;
  .Title {
    color: red;
   }
}

// Component
export default MyComponent = props => 
  <div className={classes.Container}>
    <h1 className={classes.Title}>This is a title</h1>
  </div>

export default MyComponent
``` 

For my the title text would be black. 

Thanks in advance!

**Comment by davezuko** [comment]
You know, to be perfectly honest, I've never tried to do this, as it's generally avoided with CSS modules.

Until I dig into it a bit more, you are able to just disable CSS modules and compile your sass normally if needed.

**Comment by EwanValentine** [comment]
@davezuko Gotcha! Yeah it's probably best practice to go with the modules approach. I'm just in the process of migrating lots of 'non-modularised' SCSS currently. How would I go about disabling the CSS modules feature for the time being?

**Comment by davezuko** [comment]
@EwanValentine It _should_ be as simple as changing this line: https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L35. You'll have to update all your usages, of course (removing `:global`, class object usage, etc.), but it should hopefully be a relatively painless process. Truth be told, I generally just write my sass w/o CSS modules and it seems to work well.

**Comment by EwanValentine** [comment]
Okay great, I'll try that out. I'll be migrating to the modules approach eventually anyway. Thanks again :)

**Comment by EwanValentine** [comment]
@davezuko I'm still having issues with this, not just in the same codebase, either. I've got a dummy project at https://github.com/EwanValentine/comchan if you look in `./ui/src/routes/Home/components/HomeView.js` I've imported a .scss file like... `import './HomeView.scss` however, the styles aren't applied. When I import them as `import classes from './HomeView.scss` they do work. 

This would be fine, but I'm working on another project where this isn't possible in some components, as they use third party components, which have style overrides, meaning I can't use a `classes` variable to override those styles. 

Thanks in advance!

**Comment by EwanValentine** [comment]
Note... https://github.com/EwanValentine/comchan/blob/master/ui/src/routes/Home/components/HomeView.js#L14 

On this line, this text isn't displayed in red

**Comment by davezuko** [comment]
Hmmm, looking.

**Comment by davezuko** [comment]
https://github.com/EwanValentine/comchan/blob/master/ui/config/index.js#L35 Did you try turning this to `false`?

**Comment by EwanValentine** [comment]
@davezuko Yeah it does work when you turn that off, but then you can't use `import classes form './Etc.scss'` is it a case of you can use either one or the other?

**Comment by davezuko** [comment]
Realistically, you can only have one sort of setup per filetype. You _could_ wrap your global classes in:

```
:global {
  .makeTextRed {
    color: red;
  }
}
```

And that _should_ work, since that tells it to insert the class into the global scope. However, I'd really recommend sticking with one system or the other, either use purely CSS modules with composition, or purely use regular sass, since I can image it being super tricky otherwise. Your other option is to maybe add a custom file extension to denote CSS modules vs. regular styles, but I think the former option of just picking one approach is the most sane.

**Comment by EwanValentine** [comment]
Okay great, thanks for all your help! :) That makes sense 

Thanks for your work on this repo as well, it's been massively useful!

**Comment by davezuko** [comment]
No problem, good luck!
