### ISSUE TITLE
Where do top-level reducers/actions/ducks go?

### ISSUE THREAD

**Issue by devinivy** [davezuko/react-redux-starter-kit#874]
I'm curious where reducers/actions/ducks should usually be placed.  I noticed each fractal route directory has its own `modules/` directory, but there are none directly in `src/`, yet at the same time it's encouraged to keep the stores flat in the top-level of the project.  Where should those go, and is the requisite wiring already in place?

I have a broader concern about keeping the stores/actions ("redux-stuff") separate from the UI components (even the state-connected ones).  It's lightly encouraged by the docs to keep actions/reducers out of the route directories, but not very much indicated by the boilerplate itself.  I'm hoping to reuse my store/reducers/actions across projects (e.g. react-dom and react-native), and nesting redux-stuff fractally does not cater very well to that.

**Comment by rochdev** [comment]
+1 Also wondering that, especially since using a "modules" folder at the root causes a `[HMR] TypeError: Cannot read property 'locationBeforeTransitions' of undefined` error.

**Comment by kolpav** [comment]
Yes creating `modules` folder in `/src`is  way to go for site wide ducks you can then think about `src` like your `/` route if that helps.

**Comment by devinivy** [comment]
Thanks, I got this figured out.  All that stuff can go at the top level without issue.  It would be nice if the codebase itself encouraged it!
