### ISSUE TITLE
Serving bundled application.js and all other static images from CDN

### ISSUE THREAD

**Issue by woniesong92** [davezuko/react-redux-starter-kit#875]
This is how you usually import images inside a `Component`

```
import LeftImg from './img/left.jpg'

...
<div>
  <img src={LeftImg} />
</div>
```

I want to change it so that it pulls the image from the CDN.

```
<div>
  <img src="cdn.com/myappname/img/left.jpg" />
</div>
```

In order to do it, I think I can place all the images inside `/static/img` folder instead of `src/components/..`. Then all the images will be served from `/img/[img_name]`.

**Q1. Is this the correct way?**
**Q2. How can I do the same for the bundled js and css files?**

**Comment by woniesong92** [comment]
Actually this was the best way to do this.

In `webpack.config.js` update `publicPath` with `CDN_URL` if it exists.

```
const CDN_URL = process.env.CDN_URL ? process.env.CDN_URL : "http://something.cdn.com"

webpackConfig.output = {
  filename: `[name].[${config.compiler_hash_type}].js`,
  path: paths.base(config.dir_dist),
  publicPath: (__PROD__ ? CDN_URL : config.compiler_public_path)
}
```

@davezuko do you want this documented?

**Comment by davezuko** [comment]
@woniesong92 I will probably just link to this from the FAQ. Your issue title and description are detailed enough that people with the same issue are likely to stumble upon it, and, if not, I'll just link them myself.
