### ISSUE TITLE
repeat example?

### ISSUE THREAD

**Issue by chovy** [davezuko/react-redux-starter-kit#878]
Is there an example somewhere of doing a repeat?

I want to iterate over an array and output an unordered list of items.

**Comment by kolpav** [comment]
Is this somewhat related to this project? If so please try to be more specific. If not please close the issue as questions like these are more suited for stackoverflow. After closing you can link it here and I will be happy to help you.

**Comment by chovy** [comment]
I'm at a loss. react is completely new to me. I just want to find an example of iterating.

**Comment by davezuko** [comment]
@chovy 

```js
render () {
  // names = [{ name: 'Bill' }, { name: 'Jill' }, { name: 'Phil' }]
  return (
    <ul>
      {this.props.names.map(name => (
        <li key={name}><{name}</li>
      ))}
    </ul>
  )
}

```

**Comment by kolpav** [comment]
@chovy I get you, I would recommend looking into ES6/ES7 first. It is quite common that most of the code you will see contains clever one liners like spread operator and object destructuring with combination of some functional programming parts of JS like `reduce`, `map` etc. and it might be a bit overwhelming at first so learn that first after that you can focus just on react and not the language in which it is written. I really like [this](http://es6-features.org/#Constants) link it compares the old javascript I didn't like very much with super cool new one I love :) Good luck

**Comment by chovy** [comment]
My problem isn't with es6 its with this new react paradigm. But I'll look more into it. @davezuko's example worked great.
