### ISSUE TITLE
list of apps?

### ISSUE THREAD

**Issue by chovy** [davezuko/react-redux-starter-kit#881]
Is there a list of apps (on github) somewhere that have been built using this starter kit?

I find its a great starting point, but I'd like to see something more in depth, and actual implementation using it

**Comment by marcusbelcher** [comment]
Seconded

 Would be nice to see a fleshed out example where route stores can modify a global stores where other components can see this stores state change... I know it follows a fractal pattern but how would you update everything at once?

**Comment by davezuko** [comment]
Unfortunately I do not have a list of apps, but somebody recent published a tutorial that uses this project that may be of help: https://github.com/davezuko/react-redux-starter-kit/issues/984.
