### ISSUE TITLE
Application Structure: Root.js in Routes folder

### ISSUE THREAD

**Issue by myqianlan** [davezuko/react-redux-starter-kit#885]
![image](https://cloud.githubusercontent.com/assets/5117885/16360446/55060cac-3b96-11e6-966f-ebef7d309da8.png)

thanks for this pretty project. I have only one question:

in this above picture, I see a 'Root.js' in Routes folder. But I can not found this file in project, and the note for this file, I can not understand. So, is there a example Root.js ?  or other ways to make me understand ?

**Comment by davezuko** [comment]
It's just an error, thank you for pointing this out.

**Comment by davezuko** [comment]
Fixed: https://github.com/davezuko/react-redux-starter-kit/commit/a8cef9323868d5da5f6686cde66606a0fd54542f
