### ISSUE TITLE
Question: Sharing Actions

### ISSUE THREAD

**Issue by joeyhipolito** [davezuko/react-redux-starter-kit#886]
I already created a global reducer named settings:

```
// ------------------------------------
// Constants
// ------------------------------------
export const REQUEST_SETTINGS = 'REQUEST_SETTINGS'
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS'

// ------------------------------------
// Actions
// ------------------------------------
export function requestSettings() {
  return {
    type: REQUEST_SETTINGS
  }
}
export function receiveSettings() {
  return {
    type: RECEIVE_SETTINGS
  }
}
export const actions = {
  requestSettings,
  receiveSettings
}

// ------------------------------------
// Action Handlers
// ------------------------------------
const ACTION_HANDLERS = {
  [REQUEST_SETTINGS]: (state, action) => {
    return Object.assign({}, state, { isFetching: true })
  },
  [RECEIVE_SETTINGS]: (state, action) => {
    return Object.assign({}, state, { isFetching: false })
  }
}

const initialState = {
  isFetching: false
}

export default function settingsReducer (state = initialState, action) {
  const handler = ACTION_HANDLERS[action.type]
  return handler ? handler(state, action) : state
}
```

And already have imported it in `reducers.js`

```
import { combineReducers } from 'redux'
import { routerReducer as router } from 'react-router-redux'
// import { authenticationReducer as authentication } from './authentication'
import settings from './settings'

export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    // Add sync reducers here
    router,
    settings,
    ...asyncReducers
  })
}

export const injectReducer = (store, { key, reducer }) => {
  store.asyncReducers[key] = reducer
  store.replaceReducer(makeRootReducer(store.asyncReducers))
}

export default makeRootReducer

```

Now how do I access it's actions from with other reducers? Let's say I have childRoute, `AccountSettings`

While it has access to `settings` reducer's properties, how do I then be able to use it's actions so that I can also update values in the global `settings`

OR

Am I just doing it wrong? Am I allowed to change global states from within the child components?

**Comment by kolpav** [comment]
If I understand your question correctly then nothing is preventing you to dispatch action from `AccountSettings` route to update the `settings`. In redux only way how to change state is through dispatching actions so as long as you can do that you can change any part of the state you want. If you want to access `settings` values in `AccountSettings` then you need to write a selector getting the values from store and place it into `mapStateToProps` in your container.

**Comment by twelch** [comment]
@joeyhipolito to add to @kolpav, take a look at the counter example in v3.0alpha of this kit.  Specifically how counter actions (async, doubleAsync) are dispatched by the Counter component, changing the counter state.  Note that CounterContainer maps the counter action creators to the props of Counter (using connect) so that Counter can be just a dumb component.

I recommend this set of videos on Redux if you're still figuring out how the pieces fit together - https://egghead.io/courses/getting-started-with-redux.  Good luck

**Comment by davezuko** [comment]
Two good answers so far, and this is more appropriate for StackOverflow or a redux channel. Going to close this for now.
