### ISSUE TITLE
Full example of router

### ISSUE THREAD

**Issue by rkmax** [davezuko/react-redux-starter-kit#889]
I'm a bit lost regarding this topic. may someone show me a full example of router example in a single screen

**Comment by kolpav** [comment]
Do [these](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/01-setting-up) then read [this](https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md) and you are react router guru in no time

**Comment by davezuko** [comment]
Thanks @kolpav . Closing since this is a more appropriate question for react-router's [discord channel](https://discordapp.com/invite/0ZcbPKXt5bYaNQ46) or our [gitter](https://gitter.im/davezuko/react-redux-starter-kit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by rkmax** [comment]
thanks @kolpav

**Comment by rkmax** [comment]
@kolpav in the past I used the router using JSX syntax but I'm still confused with this new syntax basically I'm trying yo doing
```
/ component=CoreLayout
/first component=FirstContainer(store)
/first/second component=SecondContainer(store)
```
but I dont get the getChildRoutes, getIndexRoute, and getComponents methods
