### ISSUE TITLE
Saga

### ISSUE THREAD

**Issue by navidmesbah** [davezuko/react-redux-starter-kit#890]
Any plan to migrate to Sagas?

**Comment by davezuko** [comment]
I don't really see the need, to be honest. Sagas are great, so it's nothing against them; my rationale is instead that this project is not meant to be an example application (if I could remove the entire counter example I would). I think it makes sense for people to follow the learning process of redux from synchronous action creators, to thunks (and why they're useful), to sagas and beyond. I'd much rather continue to work toward a solid foundation, and let those with experience such as yourself decide what additional dependencies and workflows to incorporate.

**Comment by navidmesbah** [comment]
Ok, thank you!
