### ISSUE TITLE
babel-rewire-plugin only works in test:dev ?!

### ISSUE THREAD

**Issue by malliapi** [davezuko/react-redux-starter-kit#898]
Hi, 

I have been trying to figure this out for quite a bit now but i can't see what the issue might be as using the babel-rewire-plugin with this karma config (unchanged) will only work if the --watch argument is set!

Can someone please help?

**Comment by malliapi** [comment]
looks like isparta was causing the issue, i have now replaced with istanbul, i suggest that this project does the same, i will create a PR shortly

**Comment by davezuko** [comment]
@malliapi thanks for the information. I look forward to the PR, but if you get tied up I'll get to it myself when I have time. Closing until then, since this is technically not something broken out of the box, though it should still be considered.
