### ISSUE TITLE
How to integrate Bourbon, Neat, etc?

### ISSUE THREAD

**Issue by jasongonzales23** [davezuko/react-redux-starter-kit#901]
Sorry for the noobish question, but the webpack config isn't easy to interpret as to how to integrate bourbon into this project.

Could you document an example of how to integrate bourbon and potentially neat?

I love this project BTW! Got me up and running on a crucial project, so many thanks!

**Comment by joeyhipolito** [comment]
+1

**Comment by jasongonzales23** [comment]
BTW, just saw the poll on the SASS vs CSS Modules question and have decided to jump whole hog into CSS modules. May not bother with Bourbon.

**Comment by marplemr** [comment]
Hi guys....I had the same question about how to integrate bourbon / neat. This worked out well for me. In /build/webpack.config.js, add
```js
const bourbon = require('node-bourbon').includePaths
const neat = require('node-neat').includePaths
```
to the top of your file. Then, in your style configuration
```js
webpackConfig.sassLoader = {
  includePaths: [paths.client('styles'), bourbon, neat]
}
```
Feel free to message me if u have any questions.

**Comment by davezuko** [comment]
Thank you @marplemr
