### ISSUE TITLE
`npm run deploy:prod` refresh route return 404 not found, but work on localhost in dev

### ISSUE THREAD

**Issue by bytewiz** [davezuko/react-redux-starter-kit#904]
visiting every other route than the "/" (root) returns 404 when the app is deployed to my nginx server, any suggestion of why this happens? as I thought the `koa-connect-history-api-fallback` would take care of this in `prod` aswell.

thanks in advance!

**Comment by zedde** [comment]
you should use `nginx`

add `try_files $uri $uri/ /index.html;` in nginx.conf
```javascript
    location / {
      try_files $uri $uri/ /index.html;
    }
```

Then will fine :-)

**Comment by nie-xin** [comment]
Just refer to browserHistory section:
https://github.com/reactjs/react-router/blob/latest/docs/guides/Histories.md

**Comment by davezuko** [comment]
@bytewiz are you actually running the app server in production, or pointing nginx directly at the compiled files? The history fallback middleware will only work in the former case, for obvious reasons.

**Comment by bytewiz** [comment]
@davezuko Just serving the compiled files with the "prod" flag on `nginx/html`

**Comment by bytewiz** [comment]
@zedde thanks, I tried to add 

`location / {
		root /usr/share/nginx/html/;
		try_files $uri $uri/ /index.html;

		}
}`

without any success still get 404 on refresh on all other routes than `/` any idea why this happens?
