### ISSUE TITLE
Adding requireAuth type function to starter kit

### ISSUE THREAD

**Issue by frankbolviken** [davezuko/react-redux-starter-kit#906]
Hello, 

I've been trying to implement this pattern but Im not entirely satisfied with it.

```
const requireAuth = (store) => (nextState, replace) => {
  const state = store.getState();
  if(nextState.location.pathname === '/login') {
    return;
  }
  if (!state.auth || !state.auth.isAuthenticated) {
      replace('/login');
  }
};

export const createRoutes = (store) => ({
  path: '/',
  onEnter: requireAuth(store),
  component: CoreLayout,
  indexRoute: Home(store, requireAuth),
  childRoutes: [
    CounterRoute(store, requireAuth),
    Login
  ]
})
```

First of all, I didn't really grasp how to get a "higher order" structure here so that onEnter would trigger on all route changes (I had to pass the function into every route, and add a onEnter there). And second, I want to keep the Login component outside of the CoreLayout, so that Headers, sidebars etc are not showing when that route is shown. Just a simple Login Form.

How can this be achieved?

Regards,
Frank B

**Comment by kolpav** [comment]
Try something like this (not tested)
```javascript
export const createRoutes = (store) => ({
  path: '/',
  getComponent: (nextState, cb) => {
    const state = store.getState()
    // Since 2.2.0 nextState has same signature as RouterState //
    // AUTH LOGIC HERE //
  },
  component: CoreLayout,
  indexRoute: Home(store, requireAuth),
  childRoutes: [
    CounterRoute(store, requireAuth),
    Login
  ]
})
```

**Comment by AubreyHewes** [comment]
You will have to nest a little more. A simple implementation answering your requirements is;
 * The root not having a component. This solves `CoreLayout` (your app layout) on all routes, though requires possible other layouts for other routes. 
 * The root contains at least one child route (authed). All authed routes are child routes of this route. The authed route enforces the `requireAuth` via `onEnter` this trickles down to the `childRoutes`... Other routes are un-authed. 

i.e. get `/login` outside the `requireAuth` without the CoreLayout

_note: the following is based on the **current** starter kit (d1751469c9b839a62e5f0297f957ffd0b2f5a016 at the time of writing). You can drop in and replace the method; though will have to create the `LoginRoute` and `requireAuth` yourself_

````js
export const createRoutes = (store) => ({
  path: '/',
  childRoutes: [
    // authed route root
    {
      component: CoreLayout,
      onEnter: requireAuth(store), // triggers on all child routes
      indexRoute: Home, // is also authed
      childRoutes: [ // all authed routes go here
        CounterRoute(store)
      ]
    },
    // non-authed routes
    LoginRoute
  ]
});
````

A more convoluted example which also uses another layout for your login;

````js
export const createRoutes = (store) => ({
  path: '/',
  childRoutes: [
    // authed route root
    {
      component: CoreLayout,
      onEnter: requireAuth(store),
      indexRoute: Home,
      childRoutes: [
        CounterRoute(store),
        ProfileRoute,
        EtcRoute
      ]
    },
    // non-authed routes
    {
      component: ModalLayout,
      childRoutes: [
        AuthRoute // has for example /login /reset
      ]
    },
    // etc.. other non authed routes
    HelpRoute,
    ContactRoute
  ]
});
````

The above works for me. Hope it helps, or gets you in the right direction ;-)

**Comment by JMacLulich** [comment]
I would love to have the time to document this as tutorial for people coming into this project for the first time.

There are a number of common use cases and `auth` is such an obvious one as almost everyone will require the ability to protect part of their site.

What do you think @davezuko? have you given some thought to documenting common use cases like this one? I would love to help.

**Comment by mygnu** [comment]
++1    Tutorial Please

**Comment by jasongonzales23** [comment]
This was super helpful, I am in the process of building this out for a production app at work. I'd be happy to write up a tute here or at Medium (linking to the repo). Let me know if you'd like me to do that and if anyone would be willing to give feedback on a draft.

**Comment by mygnu** [comment]
@jasongonzales23 Turning this to a production app would be great. For a novice like me it wold be very helpful. I'm happy to give feedback on the draft flick it to me[at]mygnu.net.

**Comment by peterpme** [comment]
@AubreyHewes did a great job with the example. There's just one tiny, tiny issue 😄 

`onEnter` should not be invoked, however. It's a callback function with the following signature: 

```
onEnter(nextState, replace, callback?)
```

[https://github.com/reactjs/react-router/blob/master/docs/API.md#onenternextstate-replace-callback](React Router onEnter)

Here's a complete, working example with the modifications

```es6
function requireAuth (store, replace) {
  const token = localStorage.getItem('@USER')
  if (!token) replace('/')


export const createRoutes = (store) => ({
  path: '/',
  childRoutes: [
    // authed route root
    {
      component: CoreLayout,
      onEnter: requireAuth,
      indexRoute: Home,
      childRoutes: [
        CounterRoute(store),
        ProfileRoute,
        EtcRoute
      ]
    },
    // non-authed routes
    {
      component: ModalLayout,
      childRoutes: [
        AuthRoute // has for example /login /reset
      ]
    },
    // etc.. other non authed routes
    HelpRoute,
    ContactRoute
  ]
})
```

**Comment by peterpme** [comment]
I put together a small article to walk you through what's happening. Let me know if this helps!

https://medium.com/@peterpme/react-router-authentication-onenter-requireauth-plainroute-a-follow-up-to-a-github-issue-71ea3e7d59c9#.ooavmmys0

**Comment by JMacLulich** [comment]
That's great @peterpme!

One thing you could possibly add is what to do if you are redirected to require auth from a page within the App.

So I do the following additional steps.

```javascript
export function redirectToSignIn(nextState, replace) {

  if (!isSignedIn()) {
    replace({
        pathname: '/signin',
        state: {
            nextPathname: nextState.location.pathname
        }
    });
  }
}
```

This is just the same function as your `requireAuth`.

and then on a successful auth I do the following:

```javascript
if (location.state && location.state.nextPathname) {
  this.props.router.replace(location.state.nextPathname)
} else {
  this.props.router.replace('/')
}
```

that way the client is redirected back to the protected resource they were trying to access.

I can provide more detail a bit later if needed, just cramming for a deadline.

Cheers, Jason.

**Comment by JMacLulich** [comment]
@mygnu I'm going to write something up and take a real-world redux app as an example without auth and then bolt auth into it step by step based on this hot loading stack. 

I'll get to it next week and I'd appreciate a review if you have the time once I'm done.

**Comment by kolpav** [comment]
Isn't it better to have HOC and in `componentWillUpdate`, `componentWillMount` have the auth logic?

**Comment by okloecker** [comment]
Just a caveat that the requiredAuth function, if it has the callback parameter, seems to interrupt the router flow if not used (I haven't tried to use it).
So: `function requireAuth (nextState, replace, callback)` stops the routing. Whereas: `function requireAuth (nextState, replace)` redirects in my example:
    
```
function requireAuth (nextState, replace) {
  if (!loggedIn()) {
    replace({
      pathname: '/login',
      state: { nextPathname: nextState.location.pathname }
    })
  }
}

export const createRoutes = (store) => ({
  path: '/',
  component: CoreLayout,
  indexRoute: Home,
  childRoutes: [
    // authed route root
    {
      onEnter: requireAuth,
      childRoutes: [
        CounterRoute(store),
        // ProfileRoute,
        // EtcRoute
      ]
    },
...
```

**Comment by peterpme** [comment]
Yep, says that in the docs. 

Thanks,

Peter Piekarczyk

https://twitter.com/peterpme
https://github.com/peterpme

On Fri, Jul 29, 2016 at 9:10 AM okloecker

<
mailto:okloecker <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Just a caveat that the requiredAuth function, if it has the callback parameter, seems to interrupt the router flow if not used (I haven't tried to use it).

So:

function requireAuth (nextState, replace, callback)

stops the routing. Whereas:

function requireAuth (nextState, replace)

redirects in my example:

function requireAuth (nextState, replace) { if (!loggedIn()) { replace({ pathname: '/login', state: { nextPathname: nextState.location.pathname } }) } } export const createRoutes = (store) => ({ path: '/', component: CoreLayout, indexRoute: Home, childRoutes: [ // authed route root { onEnter: requireAuth, childRoutes: [ CounterRoute(store), // ProfileRoute, // EtcRoute ] }, ...

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/davezuko/react-redux-starter-kit/issues/906#issuecomment-236190394
, or

**Comment by okloecker** [comment]
Ah, now I understand what docs mean (I did read them):

> Caution: Using the callback in an enter hook causes the transition to wait until it is called. This can lead to a non-responsive UI if you don't call it very quickly.

I was interpreting _using_ as in executing the callback within the onSubmit function, not just declaring the callback as an argument. Actually the UI _is_ responsive, it just doesn't show the child route which declares the hook.

**Comment by mygnu** [comment]
@JMacLulich  thanks for the explanation above, this solves the problem. There is another issue that would be great to address in the tutorial 'best way to create a router independent container with redux state' i.e. the header bar container that can deal with login and auth etc.
Thanks again

**Comment by AubreyHewes** [comment]
...Was on a little holiday.. @peterme my example was simply based on the given question and example code, which was not how `onEnter` actually worked but how to do a simple app auth with public (login) logic and private app views and such .. kudos on the fix  ;-)
@JMacLulich a public route that redirects to a authed route falls in to the auth route... ? You would only require the redirect within the code..? The redirect back to the called uri would be handled?

**Comment by AubreyHewes** [comment]
@JMacLulich  soz on the last comment.. my example was based on the _given_ `requireAuth` example..  which may not have been correct but was the given question.. Your input definitively adds to a working auth example!

A few examples off a working `requireAuth`..

````javascript
export function requireAuth(nextState, replace) {
  const state = getInstance().getState();
  if (!state.auth) { // no expiry check .. simple; have auth? (checked elsewhere; serverside..? serverside requires callbacks)
    replace({
      pathname: '/login',
      state: {nextPathname: nextState.location.pathname}
    });
  }
````

or with a client side auth expiration check

````javascript
function applyAuth (store) {
  return function (nextState, replace) {
    const state = store.getState();
    if (!isAuthExpired(state.auth)) { // check expiry.. or not.. all the same
      return;
    }
    replace({
      pathname: '/auth/login',
      state: {nextPathname: nextState.location.pathname}
    });
  };
}
````

What @JMacLulich actually did was fix the original `requireAuth` which was incorrect.. I did not even look at it ;-)

**Comment by AubreyHewes** [comment]
thumbs on a full write up or tutorial on simple auth!

**Comment by abury** [comment]
For future readers looking for a full PlainRoutes example with auth being read from the store, hopefully [this example](https://gist.github.com/abury/dc2448bfa70bcb1b04f773ade883e5f9) might save you some time (drop in replacement for the routes file in this project, except for the links to the childroutes of course)
