### ISSUE TITLE
Where to modify server URL local file match?

### ISSUE THREAD

**Issue by janoist1** [davezuko/react-redux-starter-kit#910]
I need to fine-tune the server in order not to parse URLs containing "." as local files. For example, url: `/foo/bar.baz/1`. The server returns `not found` instead of starting up my application and handle routing ...
Where can I set that?

**Comment by davezuko** [comment]
You could include it before all of the other middleware (webpack and connect-history-api-fallback) where you just rewrite the request object. I'm in the process of rewriting the koa server to express to eliminate babel, so if you are still unsure of how to do this after that is merged please let me know and I can post a code snippet.
