### ISSUE TITLE
How to mock api fetching?

### ISSUE THREAD

**Issue by AzrielLiang** [davezuko/react-redux-starter-kit#912]

**Comment by zedde** [comment]
I use [redux-api-middleware](https://github.com/agraboso/redux-api-middleware).

:-)

**Comment by nie-xin** [comment]
Plz read the FAQ section first next time: 

> Please be considerate by only posting issues that are directly related to this project; questions about how to implement certain React or Redux features are both best suited for StackOverflow or their respective repositories.

Anyway, the starter has already integrated sinon.js, so you can simply mock ajax by [stub](http://sinonjs.org/docs/#stubs).

**Comment by davezuko** [comment]
Thanks @nie-xin , closing as out of scope.
