### ISSUE TITLE
How to set up and run universal/isomorphic server?

### ISSUE THREAD

**Issue by janoist1** [davezuko/react-redux-starter-kit#914]
I'm not sure, what are the steps and requirements in order to run server with universal/isomorphic code?

**Comment by davezuko** [comment]
There are a ton of issues already regarding this, so I recommend reading those as they should hopefully either point you in the right direction or at least explain how this is out of scope for this project.

Closing per https://github.com/davezuko/react-redux-starter-kit/issues/805.

**Comment by janoist1** [comment]
If anyone was interested, check out [my forked version](https://github.com/janoist1/simple-universal-style-loader) that supports SSR / universal rendering
