### ISSUE TITLE
Module not found: Error: Cannot resolve directory (Windows 8.1)

### ISSUE THREAD

**Issue by CatVas** [davezuko/react-redux-starter-kit#916]
When running "npm start" on Windows 8.1 all is going well:

`app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "development". +62ms
  app:config Found overrides, applying to default configuration. +96ms
  app:webpack:config Create configuration. +9s
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +4ms
  app:server:webpack-dev Enable webpack dev middleware. +2s
  app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +74ms
  app:bin:server Server is now running at http://192.168.1.220:3000. +23ms
  app:bin:server Server accessible via localhost:3000 if you are using the project defaults. +1ms
webpack built 7a5ad7152217a8918634 in 6571ms
Hash: 7a5ad7152217a8918634
Version: webpack 1.13.1
Time: 6571ms`

But then suddenly:
`ERROR in multi app
Module not found: Error: Cannot resolve directory 'd:\DiskE-Job' in d:\DiskE-Job\!jobbing\WebDev\ReactJS\react-redux-starter-kit
 @ multi app

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Cannot resolve directory 'd:\DiskE-Job' in d:\DiskE-Job\!jobbing\WebDev\React
  JS\react-redux-starter-kit:
  Error: Cannot resolve directory 'd:\DiskE-Job' in d:\DiskE-Job\!jobbing\WebDev\ReactJS\react-redux-starter-k
  it

  - compiler.js:76
    [react-redux-starter-kit]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:214 Compiler.<anonymous>
    [react-redux-starter-kit]/[webpack]/lib/Compiler.js:214:10

  - Compiler.js:403
    [react-redux-starter-kit]/[webpack]/lib/Compiler.js:403:12

  - Tapable.js:67 Compiler.next
    [react-redux-starter-kit]/[tapable]/lib/Tapable.js:67:11

  - CachePlugin.js:40 Compiler.<anonymous>
    [react-redux-starter-kit]/[webpack]/lib/CachePlugin.js:40:4

  - Tapable.js:71 Compiler.applyPluginsAsync
    [react-redux-starter-kit]/[tapable]/lib/Tapable.js:71:13

  - Compiler.js:400 Compiler.<anonymous>
    [react-redux-starter-kit]/[webpack]/lib/Compiler.js:400:9

  - Compilation.js:577 Compilation.<anonymous>
    [react-redux-starter-kit]/[webpack]/lib/Compilation.js:577:13

  - Tapable.js:60 Compilation.applyPluginsAsync
    [react-redux-starter-kit]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:572 Compilation.<anonymous>
    [react-redux-starter-kit]/[webpack]/lib/Compilation.js:572:10

  - Tapable.js:60 Compilation.applyPluginsAsync
    [react-redux-starter-kit]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:567 Compilation.<anonymous>
    [react-redux-starter-kit]/[webpack]/lib/Compilation.js:567:9

  - Tapable.js:60 Compilation.applyPluginsAsync
    [react-redux-starter-kit]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:563 Compilation.<anonymous>
    [react-redux-starter-kit]/[webpack]/lib/Compilation.js:563:8

  - Tapable.js:60 Compilation.applyPluginsAsync
    [react-redux-starter-kit]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:525 Compilation.seal
    [react-redux-starter-kit]/[webpack]/lib/Compilation.js:525:7

ERROR in ./~/regenerator-runtime/runtime.js
Module not found: Error: Cannot resolve directory 'd:\DiskE-Job' in d:\DiskE-Job\!jobbing\WebDev\ReactJS\react-redux-starter-kit\node_modules\regenerator-runtime
 @ ./~/regenerator-runtime/runtime.js 1:0-111
Child html-webpack-plugin for "index.html":

    ERROR in Entry module not found: Error: Cannot resolve directory 'd:\DiskE-Job' in d:\DiskE-Job\!jobbing\WebDev\ReactJS\react-redux-starter-kit
webpack: bundle is now VALID.`

What is going on and how to solve it?

**Comment by davezuko** [comment]
Is that an exclamation point in your directory name?

`d:\DiskE-Job!jobbing\WebDev\ReactJS\react-redux-starter-kit\node_modules\regenerator-runtime`

I don't have any immediate ideas other than to remove that and try it again to see if the results are any different. Exclamation points are special characters for various webpack loaders, so I could see it leading to conflicts.

**Comment by CatVas** [comment]
Yay! It started successfully! Thank you Dave! I did not even think that an exclamation point can cause a problem)

**Comment by davezuko** [comment]
Haha, glad that fixed it!
