### ISSUE TITLE
react-transform-hmr is deprecated

### ISSUE THREAD

**Issue by woniesong92** [davezuko/react-redux-starter-kit#919]
And the recommended way is using React Hot Loader 3.
Should we replace it?

https://github.com/gaearon/react-transform-hmr

**Comment by davezuko** [comment]
Already working on it: https://github.com/davezuko/react-redux-starter-kit/issues/726, https://github.com/davezuko/react-redux-starter-kit/pull/893.

Having some issues with react-router still, so I'm not yet confident enough to merge it.

**Comment by woniesong92** [comment]
@davezuko ah, I see.

On a separate note, do you know if it's possible to get better error messages when you accidentally access `undefined`? (link: https://github.com/gaearon/redux-devtools/issues/302). This is why I integrated the new `react-hot-loader` but I still get the same error messages. `redbox-react` doesn't seem to help as well.
