### ISSUE TITLE
I want to how to do something like this to get two calls two fetch the result set

### ISSUE THREAD

**Issue by janjon** [davezuko/react-redux-starter-kit#920]
@web2style @kolpav thanks,

I used redux-api-middleware, but I had some problems.

This is my two action
```
function fetchAlbum() {
  return api(
    {
      url: 'api/album',
      actionTypes: [ALBUM_REQUEST, ALBUM_SUCCESS, ALBUM_FAILURE],
      schema: dataSchema
    })
}
export function loadAlbum() {
  return (dispatch, getState) => {
    return dispatch(fetchAlbum());
  }
}

function fetchCategory() {
  return api({
    url: 'api/category',
    actionTypes: [CATEGORY_REQUEST, CATEGORY_SUCCESS, CATEGORY_FAILURE],
    schema:dataSchema
  })
}
export function loadCategory() {
  return (dispatch, getState) => {
    return dispatch(fetchCategory());
  }
}
```
```
function doEverything() {
  return dispatch => Promise.all([
    dispatch(loadAlbum()),
    dispatch(loadCategory())
  ]);
}
```
How did this two and return a result set。

Thank you

#826

**Comment by kolpav** [comment]
Can you elaborate a bit more? In the `doEverything` you can dispatch multiple actions like so
```
const doEverything = () => dispatch => {
  dispatch(loadAlbum())
  dispatch(loadCategory())
}
```
I have a feeling you want to return something from the `doEverything` function but thats not how redux works. Result of load album will be in action payload with type `ALBUM_SUCCESS` and result of load category in action payload with type `CATEGORY_SUCCESS`.

**Comment by janjon** [comment]
@kolpav 
thank you. Thought I Thought

**Comment by janjon** [comment]
```
import { injectReducer } from 'store/reducers';

// Sync route definition
export default (store) => {
  return {
    getComponent: (nextState, cb) => {
      require.ensure([], (require) => {
        /*  Webpack - use require callback to define
            dependencies for bundling   */
        const Home = require('./containers/HomeContainer').default;
        const reducer = require('./modules/home').default;
        const actions = require('./modules/home').actions;

        injectReducer(store, { key: 'home', reducer });

        store
        .dispatch(actions.loadHome()) // set global spinner
        .then(() => cb(null, Home)) // success, data loaded, render component
        .catch(cb); 

        /* Webpack named bundle   */
      }, 'home');
    }
  }
}

export function loadHome() {
  return dispatch => {         //  this must be a promise
    dispatch(loadAlbums()),
    dispatch(loadCategory())
  };
}

export const actions = {
  loadAlbums,
  loadCategory,
  loadHome
}
```

`loadHome` must be a promise

**Comment by kolpav** [comment]
```javascript
store
  .dispatch(actions.loadHome()) // set global spinner
  .then(() => cb(null, Home)) // success, data loaded, render component
  .catch(cb);
```
Is very bad idea you are not rendering anything till all of your data is loaded, imagine you open up facebook and you have blank screen for the entire duration of loading all posts, comments, images etc. only when everything is loaded you are shown the result. You would not like that I suppose. Exact opposite is done throughout the web. You are rendering as soon as you can and "entertain" user with something more interesting than blank screen while data is loading. Some examples:

**Google showing dominant color of a thumbnail**
![image](https://cloud.githubusercontent.com/assets/19467143/16724698/51c0d6fc-4754-11e6-844d-4449de6d2b68.png)

**Medium blog post is bluring up low res version of images**
![image](https://cloud.githubusercontent.com/assets/19467143/16724722/6f2b898a-4754-11e6-97f9-5832e498fb75.png)

**Facebook post placeholder on codepen**
http://codepen.io/Mestika/pen/ByNYBa

**Comment by kolpav** [comment]
For some global indication that you are loading data you can take inspiration from [here](https://github.com/davezuko/react-redux-starter-kit/issues/856)

**Comment by janjon** [comment]
@kolpav thank you. you helped me.

**Comment by brianzinn** [comment]
Another option is redux-saga, if you're interested.  The main thing is that reducers should be 'pure' and not have side effects, so dispatch would not return the fetch results.  Sounds like you got it figured out, but I prefer redux-saga over thunk.  The thing with the thunk is you would need to write your own code, if you wanted to ensure both external calls succeeded.  Using the redux-saga you can timeout and cancel as well:
http://yelouafi.github.io/redux-saga/docs/advanced/RunningTasksInParallel.html

That will work correctly like the `promise.All([,])` from your original question. Dispatching two store events won't have the same guarantees.

**Comment by davezuko** [comment]
Looks like this is resolved, so closing for now. Thanks everyone.
