### ISSUE TITLE
Auto rebuild + hmr doesn't work on Ubuntu 15.10

### ISSUE THREAD

**Issue by Firfi** [davezuko/react-redux-starter-kit#922]
I'm trying 3.0.0-alpha.0 version currently. When I change i.e. Counter component, only ctrl+c and `npm start` again works. However, same code (actually just clone of your repo without changes) works fine on my MBP (it auto-rebuilds in console and auto-reloads in browser)

**Comment by rimlin** [comment]
Try in `server/middleware/webpack-dev.js` in function `WebpackDevMiddleware` adding this field: 
`    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }`

Shuld be: 

```
  const middleware = WebpackDevMiddleware(compiler, {
    publicPath,
    contentBase: paths.client(),
    hot: true,
    quiet: config.compiler_quiet,
    noInfo: config.compiler_quiet,
    lazy: false,
    stats: config.compiler_stats,
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
  })
```

**Comment by Firfi** [comment]
Pollings seems to work (both build and hot reload). It looks like there's some watch issue with Ubuntu file system events.

**Comment by davezuko** [comment]
Closing since I don't know what we can do about the Ubuntu issue :(
