### ISSUE TITLE
Get access to the state outside components

### ISSUE THREAD

**Issue by eeynard** [davezuko/react-redux-starter-kit#923]
Hi guys !

Is there a way to get access to the state outside components (without connect) ? I mean something like : 
```javascript
import store from 'something';

const state = store.getState();
```
In fact, I have a util function named request which is basically a decorator for fetch. In this function I  need the state to check if the user is connected and retrieve his access_token.  

Thanks for the help !

**Comment by marshallford** [comment]
I am only guessing here, but you should be able to replace `something` with a reference to your `createStore.js` file.

```js
import store from 'store/createStore';
const state = store.getState();
```

**Comment by JMacLulich** [comment]
@marshallford that should work!

@eeynard what I do in this situation is have middleware that will intercept specific types of actions that are decorated to say "this is an API" request and pulls the access token from the store automatically.

I modelled it after Dan's great example in the redux code base "redux real-world". Might be a more idiomatic way of doing all your API requests in general.

**Comment by eeynard** [comment]
@marshallford I already tried this option and unfortunately it did not work. 

@JMacLulich You are right it seems to be a much better solution. I will write my own middleware inspired by yours :smiley: 

Thanks for your help guys, appreciate it  !
