### ISSUE TITLE
Named export as well as a default export

### ISSUE THREAD

**Issue by nathanvale** [davezuko/react-redux-starter-kit#928]
I have a question.

What is the reasoning for having dumb components with a named export as well as a default export?

Why have an index.ts when you could just have Counter.js with just a default export.

Is it worth the extra boilerplate?

Just curious thanks.

**Comment by davezuko** [comment]
The point of having the `Counter.js` file separate from `index.js` is that it is more manageable to have a bunch of components open and not confuse the myriad of `index.js` files.

I am currently in the process of removing the `index.js` files because I also agree that it is too much boilerplate.
