### ISSUE TITLE
how to provide initialstate in test

### ISSUE THREAD

**Issue by agdolla** [davezuko/react-redux-starter-kit#93]
Hi
I try to update the example/todo-application to the current master and it works but I can not find out, how to modify the test.
In beforeEach when component is created with shallowRenderWithProps I try to pass the initialstate but it fails. The strange thing is that HomeView component is initialized with my props but the render method called for the second time with no props so it fails.
Any idea ?

**Comment by davezuko** [comment]
Hm, are you exporting the HomeView component as a dumb component? If you're wanting to test how it renders with certain props you don't want to test the connected component, which is currently the only export: https://github.com/davezuko/react-redux-starter-kit/blob/example/todo-application/client/views/home.jsx

**Comment by agdolla** [comment]
I rebased the branch and made all the modifications so the todo example works again, you can find it in my fork at: https://github.com/agdolla/react-redux-starter-kit/tree/example/todo-application
( I left two console.log in it intentionally)
so HomeView has this line:

    const todos = this.props.todos.toJS();

When running the tests this line fails because this.props.todos is undefined.

I tried to pass todos as you can see in HomeView.spec.js:

    beforeEach(function () {
      const createTodoItem = (copy) => Immutable.Map({
        copy     : copy,
        complete : false
      });
      const initialState = Immutable.List([
        'Read the docs',
        'Build something cool'
      ].map(createTodoItem));
      const props = {todos: initialState};
      component = shallowRenderWithProps(props);

If you try to run the tests you'll see two lines of console output, one with this.props.todos defined and one with undefined :(
Could you please try it ?

**Comment by davezuko** [comment]
Yeah I'll definitely take a look at this, though it might not be until later today. Thanks for this though, I appreciate all the work you're doing!

**Comment by davezuko** [comment]
Hey @agdolla, I tested out your branch and it looks like you just need to pass it in to the `renderWithProps` function:

```
// current
component = shallowRenderWithProps(props);
rendered  = renderWithProps();

// fixed
component = shallowRenderWithProps(props);
rendered  = renderWithProps(props);
```

Does that help at all?

**Comment by agdolla** [comment]
:monkey_face: sure, I should've read the next line :)
thanks
I try to have a few tests then send you a new PR
