### ISSUE TITLE
Deployment issue with Internet Explorer11

### ISSUE THREAD

**Issue by mickeyinfoshan** [davezuko/react-redux-starter-kit#937]
The deployed application gets an error on IE11. 

> SCRIPT5022: Minified React error #39; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=39&args[]=%20This%20may%20be%20caused%20by%20unintentionally%20loading%20two%20independent%20copies%20of%20React. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
> vendor.32945a0c52b33c8ec236.js (1,2092) 

How to get the error:
```
npm install
better-npm-run deploy:prod
cd dist
npm install -g http-server
http-server
```

The application works well with chrome and firefox.

**Comment by belliAndrea** [comment]
In compile_vendor of /config/index.js for webpack configuration you have to put babel polyfill before all vendors

like this:

```
compiler_vendor : [
    'babel-polyfill',
    'history',
    'react',
    'react-redux',
    ...
```

**Comment by webfront888** [comment]
Thanks! Helped me a lot！
