### ISSUE TITLE
IndexLink doesn't work on relative pathing

### ISSUE THREAD

**Issue by bingomanatee** [davezuko/react-redux-starter-kit#939]
In deploying my app to github pages I noticed that although the technique described in #877 worked mostly, the index link still pulled you back to the root of the domain (ignoring basename). Any suggestions for this? 

Online documentation with a concrete example about hosting on a specific subfolder/path would be great too. 

Thanks

**Comment by nie-xin** [comment]
I had a same problem and this is how I figured it out: https://github.com/davezuko/react-redux-starter-kit/issues/880
