### ISSUE TITLE
Server render and `module.name_mapper`

### ISSUE THREAD

**Issue by kuatro** [davezuko/react-redux-starter-kit#946]
Trying to make an isomorphic app using this awesome boilerplate. Got problems with .flowconfig - it seems like server can't understand short pathes defined in .flowconfig - 
`Error: Cannot find module 'containers/Navbar/index'`

Can you help me with this?

**Comment by janoist1** [comment]
Check out my forked version that supports SSR: [https://github.com/janoist1/react-redux-starter-kit/tree/feature/universal](https://github.com/janoist1/react-redux-starter-kit/tree/feature/universal)

**Comment by kuatro** [comment]
Awesome!
