### ISSUE TITLE
Switch to react-router v2.4.0

### ISSUE THREAD

**Issue by hoodwink73** [davezuko/react-redux-starter-kit#951]
Hello

Are we considering to update to the latest `react-router` and fade usage of `react-redux-router`?

With latest [react-router](https://github.com/reactjs/react-router/blob/cbdc49442aba5cc6f225ff5546ac5f4a217fa4ec/upgrade-guides/v2.4.0.md) a container component can be wrapped with `withRouter` to inject the route as a prop on the container component itself.

This will not make router a part of our redux store, but as long as there is only a *single source of truth*, it should be fine.

Also, this will make using routers more simple.

**Comment by davezuko** [comment]
Yes, I am in the process of deprecating `react-router-redux` today. Thank you!
