### ISSUE TITLE
Stacktrace file references

### ISSUE THREAD

**Issue by brandonmp** [davezuko/react-redux-starter-kit#954]
Is there a way to configure the stack traces such that they're a bit more helpful? 

My error messages via Chrome dev tools almost never point to a specific project file.  I wouldn't think anything of it, but webpack/React setups I've used in the past have generally pointed to the file/line of the error. 

I'm still learning both techs, so it's not clear to me if that's a result of different configs (hoping that it is & this is relatively easy to activate).

Here's an example of an error I'm currently tracking down. 

````
warning.js:44Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning @ warning.js:44

invariant.js:45Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
````

![image](https://cloud.githubusercontent.com/assets/14139991/17197663/cb30b67a-543c-11e6-9dc1-2125a69cd9cb.png)

**Comment by brandonmp** [comment]
After another ~month of working in this kit, I've learned the above super-vague errors can be thrown by nearly anything, e.g.:

- using an undefined variable or un-imported component
- forgetting to use `{destructuring}` brackets on `import` statements
- passing certain invalid props to components


Unfortunately, without even the file name to go on, it becomes a game of ctrl+z and prayer. 

Just wanted to ask again: is this normal behavior?  I haven't tried to adjust any settings in the guts of the kit, but I've used other projects where the error messages had actual useful info in them, so I'm assuming this is something unique to this kit.

This sort of no-details error comprises about 70-80% of the errors I encounter, and in some instances it's taken an hour to track down even a simple typo. Is anyone else having a similar experience here? 

Welcoming any sort of ideas or tips if anyone has a second to weigh-in.

**Comment by davezuko** [comment]
@brandonmp: there was an awful bug for a while after we dropped `react-transform` for hot reloading and instead rendered redbox errors ourselves.

Check out this commit: https://github.com/davezuko/react-redux-starter-kit/commit/20c8078aafa3df71bc24b8efdfe1d0e060ec600b and see if this change has been made in your project. If not, it's likely that this will solve the issue... since we were trying to render an undefined component.

**Comment by brandonmp** [comment]
Holy shit! it appears that was exactly the issue. 

... gah.  so many hours debugging/weeping.

valuable lesson for me here: compartmentalize starter kit files to make pulling bug fixes, etc., simple to do. 

Will have to browse commits in past ~90 days to see if there's anything else I've missed.

Thanks a ton @davezuko

**Comment by davezuko** [comment]
Glad that fixed it, it was indeed super annoying and I apologize for not catching it myself (and sooner). Lucky for you, there really hasn't been a ton of activity in the repo lately, as that's the most significant fix I can recall in the recent past.
