### ISSUE TITLE
babel-node in prod

### ISSUE THREAD

**Issue by amatiushenko** [davezuko/react-redux-starter-kit#957]
How come we can run the server without babel-node? Because in [docs](https://babeljs.io/docs/usage/cli/) they don't recommend use babel-node in production mode

**Comment by davezuko** [comment]
It's not worth it for small apps to pre-compile the server, you're just not going to notice a difference. I'd love to get rid of Babel altogether on the server, but it's unfortunately needed for Koa v2 at the moment (though this is pushing me back toward express, despite Koa's improvements). If you'd like to adhere strictly to Babel's recommendations you're welcome to add a compile step.

There are a few threads about this already, so going to close as a duplicate.

* https://github.com/davezuko/react-redux-starter-kit/issues/843
* https://github.com/davezuko/react-redux-starter-kit/issues/625

**Comment by amatiushenko** [comment]
Ok. Thanks for quick reply!
