### ISSUE TITLE
asyncReducer initial state in the redux store

### ISSUE THREAD

**Issue by glifchits** [davezuko/react-redux-starter-kit#960]
Hey there, I've got a couple of questions about `asyncReducers`. I very much like the `injectReducer` method and how it lets you add reducers to the store from pretty much anywhere. However, I'm finding that one of the reducers I added this way does not add its initial state to the store until its route component is mounted.

```javascript
// loginDucks.js
export default function loginReducer(state = {}, action) {
  return state
}

// loginRoutes.js
import { injectReducer } from 'store/reducers'

export default (store) => ({
  path: '/login',
  getComponent(nextState, cb) {
    require.ensure([], require => {
      const LoginPage = require('./LoginPage').default
      const reducer = require('./loginDucks').default
      injectReducer(store, { key: 'auth', reducer })
      cb(null, LoginPage)
    }, 'login')
  },
})
```

and then somewhere else
```javascript
import { connect } from 'react-redux'

const MyComponent = ({ auth }) => {
  console.log(auth)
  return <div>Hello world</div>
}

const mapStateToProps = state => ({ auth: state.auth })
export default connect(mapStateToProps)(MyComponent)
```

**Expected**: `auth` is an empty object (because that was the `loginReducer` initial state)
**Actual**: `auth === undefined`, until I navigate to `/login`, at which time `auth === {}`

So my questions: Is this behaviour by design, or a consequence of the `injectReducer` pattern? If so, what should I do instead?

**Comment by bhj** [comment]
This is by design for async reducers and enables code splitting where chunks of your store may not exist until loaded on demand. You probably want your auth stuff loaded from the get-go synchronously which happens in `src/store/reducers.js`.
