### ISSUE TITLE
react-optimize breaks production code

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#962]
This is snippet was causing our `production` compiled app to break (basically no routing, forms fields not accepting input etc.) when everything works in `development` mode. Has anyone else had this issue and know what might cause it?

```
env            : {
      production : {
        presets : ['react-optimize']
      }
    }
```

**Comment by davezuko** [comment]
I've had occasional issues, mostly with static properties on component classes. I've removed this from the boilerplate so people don't run into obscure issues in production, especially since the error messages are less than helpful.

**Comment by Dr1Ku** [comment]
This was a really rude awakening for me yesterday as well, had no idea where to start looking! I think I introduced some static props on a stateless functional component, I'll look into that, thanks @neverfox. @davezuko Should this be in the FAQ (glad to help!) ?

**Comment by marshallford** [comment]
Can an issue be submitted to [babel-react-optimize](https://github.com/thejameskyle/babel-react-optimize) from this?

**Comment by davezuko** [comment]
@Dr1Ku I've removed it from the starter kit out of the box because it causes too many issues that people don't know where to even begin debugging.

**Comment by davezuko** [comment]
Closing since this has been removed from the core of the kit.
