### ISSUE TITLE
Too many implementation details

### ISSUE THREAD

**Issue by cameronroe** [davezuko/react-redux-starter-kit#963]
Just wanting to provide some feedback on this repo. After discussing the boilerplate with another front-end dev, we think that the boilerplate has too many implementation details and distracts from the actual app code. For example, is it truly necessary to include the code-splitting API within every redux app one builds directly in their project? Ideally this would be abstracted into another module which can be used within an app.. For example:

`npm install redux-kit` -> `import { injectReducer } from 'redux-kit'`

The boilerplate currently acts like a library/framework with app specific code included. It's uber confusing to get in a look at, let alone carry to each app created as it would be duplicate code.. 

Also, the CLI is great, but could it also set reasonable defaults for webpack to leverage a variety of loaders, plugins, and hmr?

Is there an issue related to this or any chance this could be flagged for discussion?

Thanks.

**Comment by bhj** [comment]
I think the `injectReducer` pattern is good in terms of being small and un-opinionated. I totally get the frustration with the complexity of the ecosystem and that it seems like "one more thing", but the kit is trying to set you and your team up for success all the way through to production, by default. A project can easily grow to the point that a) you'll be really happy you have code splitting, and/or b) you'll be replacing a lot more than just injectReducer. 😃

Have not used the CLI yet but I know the blueprints have lagged behind the new-ish fractal file structure; PRs are definitely welcome there.

**Comment by cameronroe** [comment]
@bhj I totally agree. I'm a fan of `injectReducer` and some of the awesome features in the boilerplate, however I don't think that they should be included within the same repo that the app code is using. For example, since code-splitting is such a globally accessible feature and API that would be used across many redux apps. (it's related to the performance entirely) it should be leveraged in a package that supports those concerns. 

Again, I think that the details of the dev/production environments are great, but they are very thorough and aren't necessarily needed directly in the boilerplate.

Also, the Koa server is a nice idea, but if someone is trying to build a strict client app without a server attached to it, that is extra code that have to deal with. Ideally that is also utilized within a separate module for extending the project to a fully isomorphic app. 

There's just too much overhead with implementation of specific opinions.

In an ideal use case, it would be a single module or set of modules that help support a new redux app. This should be super light weight with only `src`, `test` directories and some high-level config files. Blueprints are cool, and could also be opted in for.

Thoughts?

**Comment by bhj** [comment]
@cameronroe Yes, even though it's a pretty small (relatively) overhead, more modularity would definitely be good there.

As far as the server stuff I can't disagree; one man's overhead is another's starting point. I'm happy Koa 2 is included because it pushed me to go ahead and use async/await. The thoroughness of the environment configs is valuable (to me) as far as showing a path to solving issues I might run into. If you don't want any server stuff have you looked at something like [React Static Boilerplate](https://github.com/kriasoft/react-static-boilerplate)?

**Comment by cameronroe** [comment]
Yes, I think more modularity would really help this boilerplate be much more approachable for more developers. 

I honestly think it should all be abstracted to the `redux-cli`. So one could just use the CLI to start the Koa server and use a `redux-kit` library to override any defaults.

**Comment by davezuko** [comment]
I am working on simplifying all of this right now after taking a hiatus from this project. 100% agree with you, but it's a hard balance to strike.

**Comment by cameronroe** [comment]
@davezuko 👍
