### ISSUE TITLE
@@INIT is called on every route change

### ISSUE THREAD

**Issue by shkfnly** [davezuko/react-redux-starter-kit#964]
I have an application with multiple routes, and every time I navigate to a new route within the application @@Init is called and the store resets to the default values. I am trying to persist the state across route changes but can't figure out how to do that. Is this a bug or a feature of this implementation.

**Comment by shkfnly** [comment]
I found this issue. It had to do with the difference between using <Link> and hrefs.

**Comment by codeslayer1** [comment]
Hi @shkfnly . I am facing the same issue that you mentioned above. I want to persist state in local storage but the state resets after every route change. How did you persist the state across url changes?

**Comment by piu130** [comment]
Use `browserHistory.push('/newURL')` in js code and `onClick={() => browserHistory.push('/newURL')}` in html. Import browser history with `import { browserHistory } from 'react-router'`.

**Comment by codeslayer1** [comment]
Thanks @piu130 . Its working fine with the code you shared.
