### ISSUE TITLE
Same CSS is injected into HTML over and over again

### ISSUE THREAD

**Issue by madshargreave** [davezuko/react-redux-starter-kit#968]
I get the following output in my HTML, any ideas?

<img width="817" alt="screen shot 2016-08-14 at 12 04 56" src="https://cloud.githubusercontent.com/assets/5479890/17648492/c8a4091e-6217-11e6-8a4a-fc2769cec214.png">

**Comment by davezuko** [comment]
I think this is just how webpack performs HMR for styles, but may be wrong. Closing due to my inability to answer issues in a timely manner (and also based on the former assumption).
