### ISSUE TITLE
Reduce size for server bundle

### ISSUE THREAD

**Issue by MrEfrem** [davezuko/react-redux-starter-kit#97]
It is possible to reduce server bundle several times if we exclude from it node_modules (https://github.com/MrEfrem/react-redux-starter-kit/blob/master/build/webpack/server.js):
```
name    : 'server',
  target  : 'node',
  entry   : {
    app : [
      paths.src('entry-points/server')
    ]
  },
  externals: fs.readdirSync('node_modules').filter(function(x) { return x !== '.bin' }),
...
```

And also I would clean UglifyJsPlugin from bundle, because differently in case of an error in stack trace it isn't clear where in bundle to look it.
And generally what sense in it for NodeJS to squeeze bundle?

**Comment by MrEfrem** [comment]
Still it is necessary to add "__ CLIENT __: false" in "definePlugin" for server bundle and "__ SERVER __: false" for client bundle that in both assemblies there were no errors like "Runtime error: __ CLIENT __ is undefined" on server side and vice versa.

**Comment by davezuko** [comment]
Wow that's brilliant, never even thought of that. I'll try to get this in in the next day or two. Thanks!

Also I definitely agree about getting rid of uglify for the server bundle, good point.

**Comment by davezuko** [comment]
Implemented both of these in https://github.com/davezuko/react-redux-starter-kit/pull/100. Thanks for the idea!
