### ISSUE TITLE
How to dispatch action when CHNAGE_LOCATION ocurred?

### ISSUE THREAD

**Issue by WenXuanYuan** [davezuko/react-redux-starter-kit#972]
I have an action
<pre>
export function resetState (state) {
    return {
        type: RESET_STATE,
        payload: {
            ...state, 
        }
    };
};
</pre>
I want to trigger it when location changed, so I wrote a reducer
<pre>
import { LOCATION_CHANGE } from 'react-router-redux';

const ACTION_HANDLERS = {
    [LOCATION_CHANGE]: (state, action) => {

        // here I want to trigger action resetState, What should I do ?

        return { ...state,
                     pathname: action.payload.pathname,
                     query: action.payload.query
        }
    };

const initialState = {
    pathname: '',
    query: {}
};
export default function locationReducer (state = initialState, action) {
  const handler = ACTION_HANDLERS[action.type]

  return handler ? handler(state, action) : state
}
</pre>

resetState will get parameters from location query, so when location changed resetState will be triggered, How should I do? I am a fresher in redux, if there are error in code ? I need your help, thank you!

**Comment by davezuko** [comment]
This is more of a question for gitter or `react-router-redux`.
