### ISSUE TITLE
Component works on separate page but not the home page

### ISSUE THREAD

**Issue by nickboris** [davezuko/react-redux-starter-kit#974]
I'm learning react/redux and wanted to create a simple button component that toggles the state of a prop, but I'm having trouble figuring out how to implement an identical component on two different pages. I was trying to insert the component on the homepage, but I kept getting an error saying that I hadn't defined the props that I specified in the presentational component file, although I thought that I had created the container correctly. I tested the component on a separate page (`/login`) and it worked correctly, but I still get a weird error in the browser console on the home page that `Failed prop type: Required prop 'submitted' was not specified in 'Login'` and likewise for my other prop, `submit`. From what I understand, this error means that I haven't properly linked the action/state properties to my react props. What do I need to add/fix in my code in order to solve this problem?

routes/Home/components/HomeView.js:

    import React from 'react'
    import Login from '../../../components/Login/Login.js'

    export const HomeView = () => (
      <div>
        <Login />
      </div>
    )
    export default HomeView

routes/Home/index.js:

````
import HomeView from './components/HomeView
export default {
  component: HomeView
}
```

components/Login/Login.js:

```
import React from 'react'

export const Login = (props) => (
  <div>
    <button onClick={props.submit}>Sign in</button>
    <p>{props.submitted ? "true" : "false"}</p>
  </div>
)

Login.propTypes = {
  submit: React.PropTypes.func.isRequired,
  submitted: React.PropTypes.bool.isRequired
}

export default Login
```

routes/Login/containers/LoginContainer.js

```
import { connect } from 'react-redux'
import { submit } from '../modules/login'
import Login from 'components/Login'

const mapDispatchToProps = {
  submit
}

const mapStateToProps = (state) => ({
  submitted: state.login.submitted
})

export default connect(mapStateToProps, mapDispatchToProps)(Login)
```

routes/Login/modules/login.js:

```
export const SUBMIT = 'SUBMIT'

export function submit () {
  return {
    type: SUBMIT
  }
}

const initialState = {
  submitted: false
}
export default function formHandler (state = initialState, action) {
  switch (action.type) {
    case SUBMIT:
      return {...state, submitted: !state.submitted}
    default:
      return state
  }
}
```

routes/Login/index.js:

```
import { injectReducer } from '../../store/reducers'

export default (store) => ({
  path: '/login',
  /*  Async getComponent is only invoked when route matches   */
  getComponent (nextState, cb) {
    /*  Webpack - use 'require.ensure' to create a split point
        and embed an async module loader (jsonp) when bundling   */
    require.ensure([], (require) => {
      /*  Webpack - use require callback to define
          dependencies for bundling   */
      const Login = require('./containers/LoginContainer').default
      const reducer = require('./modules/login').default

      /*  Add the reducer to the store on key 'counter'  */
      injectReducer(store, { key: 'login', reducer })

      /*  Return getComponent   */
      cb(null, Login)

    /* Webpack named bundle   */
  }, 'login')
  }
})
```

routes/index.js:

```
import CoreLayout from '../layouts/CoreLayout/CoreLayout'
import NotFound from './NotFound'
import Home from './Home'
import CounterRoute from './Counter'
import LoginRoute from './Login'
import SignUpView from './SignUp'

export const createRoutes = (store) => ({
  path: '/',
  component: CoreLayout,
  indexRoute: Home,
  getChildRoutes (location, next) {
    require.ensure([], (require) => {
      next(null, [
        require('./Login').default(store),
        require('./Counter').default(store),
        require('./Timeline').default,
        require('./SignUp').default,
        require('./NotFound').default
      ])
    })
  }
})

export default createRoutes
```

**Comment by m4recek** [comment]
You have to use that LoginContainer instead of Login component in HomeView. Use containers everywhere where you want to have prezentation component connected to store.

Btw: questions like this are answered much faster on stackoverflow.com

**Comment by nickboris** [comment]
Thank you! I was confused by your answer at first, but then realized that the connect function returns the Login component! Much appreciated.

**Comment by nickboris** [comment]
I accidentally closed the issue before being able to fix the problem - could you explain what you mean by replacing the component with the container? Does the `connect` function that I export from the container file return the Login component with all connected props? I'm confused as to how to implement the container into the HomeVIew

**Comment by twelch** [comment]
The [CounterContainer](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/containers/CounterContainer.js) is a good example to follow if you didn't catch it.

The require should be a direct replacement as you did.  Have you looked at the value of connectLogin at runtime after the require?  You might have exported the container improperly.  It should be a wrapped component.  You should also be able to set a break in the component render method and see that it is actually getting called and the props are passed in properly from the container with the mapped state or action creators.

**Comment by nickboris** [comment]
I fixed the problem - I had to use this syntax: `<connectLogin />` over the `{connectLogin}` syntax, since the `connect` function returns a component. Furthermore, for some reason it didn't work if I used assigned the `connect` function to any variable name other than `Login`, but I'm not sure why this is the case; Is it because the `connect` function is returning the component I passed into it, the `Login` component, and expects the `Login` component name to be referenced wherever it needs to be used in the app? Why would this be the case if the `connect` function returns a new component?

In case I explained it poorly, I needed to change the `routes/Home/components/HomeView.js` file to:

```
import React from 'react'
import classes from './HomeView.scss'
const Login = require('../../Login/containers/LoginContainer').default

export const HomeView = () => (
  <div>
    <Login />
  </div>
)

export default HomeView
```

Thank you in advance for all the help and any insight you could provide to the questions above.

**Comment by m4recek** [comment]
Here is another way to solve it.

1. you can import LoginContainer (_hint: you can use folders in `src` directory as aliases e.g. `import LoginContainer from 'containers/LoginContainer'`_
2. use LoginContainer in your component

```
import React from 'react'
import classes from './HomeView.scss'
import LoginContainer from '../../Login/containers/LoginContainer'

export const HomeView = () => (
  <div>
    <LoginContainer />
  </div>
)

export default HomeView
```
