### ISSUE TITLE
Cannot read property 'toJson' of undefiend

### ISSUE THREAD

**Issue by wlingke** [davezuko/react-redux-starter-kit#975]
I get this issue occasionally when I run the compile. It usually goes away the second time I run it. Not sure why this is happening but it looks like someone else reported this issue below.

https://github.com/davezuko/react-redux-starter-kit/issues/768

I've also updated my webpack to 2.x and made some other changes but the issue doesn't seem related to those problems.

**Comment by davezuko** [comment]
There have been multiple fixes to the compiler since this issue, so closing this for now. Sorry for the delay in responding. If you still have issues after the next PR is merged (a massive refactor to eliminate babel outside of the client) please let me know.
