### ISSUE TITLE
Import Materialize-css

### ISSUE THREAD

**Issue by FerreiraRaphael** [davezuko/react-redux-starter-kit#978]
So, i'm trying to import materialize css to my project, but ... i'm getting the following error, any ideias ?
Installed with: 
`npm install materialize-css --save`
And imported with:
import 'materialize-css/bin/materialize.css'
import 'materialize-css/bin/materialize.js'
at CoreLayout.js [https://github.com/davezuko/react-redux-starter-kit/blob/master/src/layouts/CoreLayout/CoreLayout.js](url)

and I'm getting the following error:
![image](https://cloud.githubusercontent.com/assets/11987481/17857744/5b7114c0-6859-11e6-9e43-ddd33f3d7525.png)

**Comment by kyen99** [comment]
I just did the same thing with the latest master (c3abb24) and it works as expected. This must have been a bug somewhere that was resolved. This can probably be closed.

For anyone else doing this, I would also suggest removing the bootstrap link from index.html to avoid competing style defaults. It's also worth a look at material-ui.com, which also integrates fairly seamlessly.

**Comment by davezuko** [comment]
Thanks @kyen99 !
