### ISSUE TITLE
API Backend Integration Example

### ISSUE THREAD

**Issue by mwmeyer** [davezuko/react-redux-starter-kit#979]
I am trying to figure out the best approach for integrating an API backend with this project. I see there is a setting to proxy requests to an API in environment.js:

```
development: (config) => ({
    compiler_public_path: `http://${config.server_host}:${config.server_port}/`,
    proxy: {
      enabled: false,
      options: {
        host: 'http://localhost:8000',
        match: /^\/api\/.*/
      }
    }
  }),
```

But I would like to know if there is a way to set things up to also handle backend API requests through Koa, similar to scenario 3 outlined [here](https://medium.com/@rajaraodv/webpacks-hmr-react-hot-loader-the-missing-manual-232336dc0d96#.17xv509d1). Having to run two servers in development (one for webpack, one for api) seems kind of cumbersome to me, though I am fine with doing it if there was a way to start things with a single command and structure files within the same project. ( I don't want entirely different repositories for my backend and frontend at this point )

I've tried simply setting the  proxy host to port 3000 and adding some koa routing code to main.js, but connection to the route is still refused.
```
import route from 'koa-route'

app.use(route.get('/api/foo', list));

function *list() {
  this.body = yield render('list', { foo: [1,2,3] });
}
```

Is there any documentation or examples anyone can point me to related to this?

**Comment by bhj** [comment]
Definitely, the starter kit includes Koa 2.x so you'd need to use async functions instead of generators. Also I'm using `koa-router` instead of `koa-route`. My setup is something like:

`config/environments.js`
- Proxy **not** enabled

`server/main.js`

```
import apiFoo from './api/foo'
...
app.use(apiFoo.routes())
...
```

`server/api/foo.js`

```
import KoaRouter from 'koa-router'
const router = KoaRouter()

router.get('/api/foo', async (ctx, next) => {
  ctx.body = await render('list', { foo: [1,2,3] });
})

...

export default router
```

**Comment by mwmeyer** [comment]
Thanks, that helped me get something working. I'll post a link to a full example here for others once I am finished.

**Comment by kolpav** [comment]
You can also use prefix argument like so
```javascript
const api = new Router({
  prefix: '/api'
})
api.use('/user', userApi.routes()) // etc...
```

**Comment by davezuko** [comment]
Thanks for the example @bhj . Way back when I used to have a branch demoing a server API, but since that's now gone your comment will be good to point people to.

**Comment by sschenk** [comment]
@bhj How did you get it to work I'm getting an error "await next is not a function trying to use it like that with koa router?

**Comment by sschenk** [comment]
I should probably post this in koa router but doing the following gives me an undefined this and next and an empty object on ctx:

```
router.post('/api/userupdate', async (ctx, next) => {
  console.log(this)
  }
) 
```

**Comment by bhj** [comment]
@sschenk Which version of the starter kit are you using? Latest from master no longer includes Koa, and if you want to use Koa 2 you'd need to setup Babel server-side.

@davezuko Might be worth bumping version to 4.x?

**Comment by sschenk** [comment]
i'm using the one that does use koa and my react router doesn't behave at all as described above.
