### ISSUE TITLE
Cannot seem to register single backend API route

### ISSUE THREAD

**Issue by Robinnnnn** [davezuko/react-redux-starter-kit#981]
I've perused all issues in this repo related to the API, Koa, etc., and I'm still at a loss. 

The first thing I did was head over to `/config/environments.js` and set proxy enabled to `true`.

From here I don't know where to register a basic `get` route. I checked out the [Koa 2.0 docs](https://github.com/koajs/koa) and just placed the following into `/server/main.js`:

```
... enable koa proxy...
... historyApiFallback...
... apply webpack HMR middleware...

app.use(ctx => {
  ctx.body = 'Hello Koa';
});

export default app;
```

As you can see I placed this beneath all other middleware in the file.

Now to test whether worked I made a request to `http://localhost:3000/api/` via Postman.
It immediately returned `Internal Server Error` and the console logged a crash stating `Error: connect ECONNREFUSED 127.0.0.1:8000`.

This is likely a trivial issue and I wouldn't be asking this if I hadn't exhausted all options.

Thank you in advance.

**Comment by kolpav** [comment]
You can use something like this and modify it to suit your needs. (not tested)
```javascript
// routes/hello.js //
const router = new Router()
router.get('/:name', ctx => {
  ctx.body=`Hello ${ctx.params.name}!`
})
// more routes ... //
export default router
```
```javascript
// api/index.js //
import helloApi from '../routes/hello'
const api = new Router({ prefix: '/api' })
api.use('/hello', helloApi.routes())
export default api
```

```javascript
// main.js //
const app = new Koa()
// immediately //
app.use(api.routes())
...
```
`GET : localhost:3000/api/hello/Robinnnnn => Hello Robinnnnn!`

**Comment by Robinnnnn** [comment]
@kolpav, thank you so much for your explanation.

I tried your suggestion but unfortunately am still running into trouble. 

`[GET] localhost:3000/api/hello/robin` returned "Cannot read property name of undefined".

I added a console log to the route:
```
router.get('/:name', ctx => {
  console.log(ctx.params) // returns undefined
  ctx.body = `Hello ${ctx.params.name}!`
})
```

Now, forgetting about the param, I simply re-wrote it like follows ...
```
router.get('/', ctx => {
  console.log('hit this route') // returns 'hit this route'
  ctx.body = `Hello world!`
})
```
... then sent a request: `[GET] localhost:3000/api/hello/`

The console logs as expected but my Postman app returns "Not Found".

<img width="409" alt="screen shot 2016-08-25 at 10 36 29 am" src="https://cloud.githubusercontent.com/assets/12162433/17973275/d3316f02-6aaf-11e6-81b0-633ab27da99b.png">

Am I missing some parsing middleware?

Thanks again in advance.

**Comment by Robinnnnn** [comment]
Wowwww. Fml.

In order to integrate routing with the Koa 2.0 syntax, I had to install [koa-router 7+](https://github.com/alexmingoia/koa-router/tree/master/) via `npm install koa-router@next`. I don't know if this is worth mentioning in the docs, but sorry for wasting everyone's time.
