### ISSUE TITLE
Has anyone used Fetch polyfill with this project?

### ISSUE THREAD

**Issue by JMacLulich** [davezuko/react-redux-starter-kit#986]
Hi Guys,

I'm having some issues with the built in browser `fetch` call, the problem I have is that I can't get any useful error information out of the call.

If I get a 403 or a 401 returned by the server, Chrome just returns a generic `TypeError` and I can't get anything about the error (contrary to the docs).

I want to use the `fetch` polyfill.

But I don't know how to incorporate it into the webpack configuration.

I have to do this:

```
entry: ['whatwg-fetch', ...]
```

from: https://github.com/github/fetch

but I'm not a webpack expert so I have no idea where this translates to in the myriad of webpack verbiage :)

Has anyone used the `fetch` polyfill with this starter pack?

Cheers, Jason.

**Comment by bhj** [comment]
I ran into some problems with the `whatwg-fetch` package (I can't remember exactly what right now) and switched to `isomorphic-fetch` which I'd recommend instead. Just

```
import fetch from 'isomorphic-fetch'
```

anywhere you need it.

If you do definitely want to use `whatwg-fetch` add the following to the [webpack plugins array](https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L49):

```
    new webpack.ProvidePlugin({
      'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
    })
```

and that should be it (I didn't mess with `entry`).

**Comment by bhj** [comment]
@JMacLulich No problem, if that works please close the issue 😄

**Comment by nickwaelkens** [comment]
@bhj Hm, I ended up adding the `whatwg-fetch` module to my [vendors array](https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L46) and it works fine, I can also access `fetch` from eg. the console. Is there any downside to my method, though?

**Comment by bhj** [comment]
@nickwaelkens Not sure IIRC but my issue may have involved initiating API requests from the server. Not sure if that's what you meant by console. If it works, don't fix it! :p

**Comment by nickwaelkens** [comment]
@bhj I guess I was quite tired when I wrote that comment. I meant that with "my way" (of adding it to the vendors array) the fetch method is also available on the `window` object and I can just use `fetch` throughout my project. But like you said, if it works… :ok_hand:

**Comment by sergeyjsg** [comment]
I was able to use Fetch polyfill without any problems. I just added it as a dependency to pacjage.json 
```npm install whatwg-fetch --save``` 
And then imported it in any file (I use self-written http wrapper for ajax, so I imported it there) 
```import 'whatwg-fetch';```

export function request (url, options) {
  return fetch(url, withAuth(options));
}
```

**Comment by justingreenberg** [comment]
alternatively, if you don't want to include in bundle you could use polyfill.io cdn...

```html
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch"></script>
```

**Comment by JMacLulich** [comment]
Thanks everyone for their feedback on this, very helpful.
