### ISSUE TITLE
Sharing reducers between routes with makeRootReducer and fractal project structure; contradictory?

### ISSUE THREAD

**Issue by brandonwoo** [davezuko/react-redux-starter-kit#987]
I understand that the approach described in #832 works for importing global reducers to be shared among routes/components, but doesn't that kinda go against the fractal routes structure of the project?

E.g. If i have 3 routes
/routes/Users
/routes/Organizations
/routes/Teams

Lets say Organizations depend on Users, and Teams depend on Organizations.

If I understand correctly, the injectReducer style of injecting the reducer when importing routes would only work for the outermost routes which are not depended on by any other route at all (Teams in this case).
User reducer would have to be imported in [makeRootReducer](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/store/reducers.js#L6) because Organizations depends on it, and Organization reducer has to be imported there too because Teams depend on it.

This approach seems to interfere with the fractal structure of this project. Or am I missing something here?

**Comment by renanvalentin** [comment]
We are facing the same doubts here and still not clear how to solve this problem, we've came up with this:

We've added a "common" directory between each route root, which is organized by it's own domain...

**Comment by przeor** [comment]
hello @renanvalentin, could you elaborate? 

That means that effectively, the redusers Users and Organizations are going to:
```
export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    // Add sync reducers here
    router,
    ...asyncReducers
  })
}
```

... and only teams are loaded async because they are not depended on by any other route at all?

**Comment by justingreenberg** [comment]
some perspective...
- reducers are just pure functions, usually fast, lightweight, and memoizable
- `injectReducer` just maps a reducer to key on the store. it is 
- "fractability" is just a concept, so don't worry about breaking any rules, cuz there aren't any

i don't think there is any problem here :) this project just provides a canvas for building apps using fractal patterns with _code splitting and bundling_ in mind, but you should use whatever works best for you. for example—even if *all* your actions/reducers/sagas/selectors were in the "main" app bundle (project root) or even split by domain, it does not diminish any wins provided by fractal dependency graph to split heavy component trees into async chunks. if you have heavy ui logic in a reducer that you want to load in an async bundle, then maybe consider using setState, create a new redux store, or use another library like redux elm, redux-loop or redux-local

**Comment by davezuko** [comment]
Closing per @justingreenberg 's comment.
