### ISSUE TITLE
redbox

### ISSUE THREAD

**Issue by ioRekz** [davezuko/react-redux-starter-kit#99]
I can't manage to see the redbox on error.
The console display an error and the page is refreshed.

I don't have any useful log and I don't know where to look to fix this, any idea ?

**Comment by ioRekz** [comment]
I had error on Object.assign so I updated my chrome version and it works.
Is this normal ?

**Comment by davezuko** [comment]
Interesting, where was the Object.assign error being thrown? Might have to include the Babel polyfill.

**Comment by davezuko** [comment]
Closing this for now since a lot has been updated since this was reported and I haven't heard anything new. Please let me know if you're still having issues.
