### ISSUE TITLE
API Network call is not happening in iOS and Safari for a website build on React

### ISSUE THREAD

**Issue by Abhimanyuv92** [davezuko/react-redux-starter-kit#994]
I could not provide the web link as its in local :(

**Comment by jjwon0** [comment]
any more details or example code?

**Comment by davezuko** [comment]
If yu could provide more details I can help diagnose, but until then there's not much we can do. Closing until then, thank you!

**Comment by techhysahil** [comment]
I also got stuck in similar kind of issue. If anyone still have "fetch api not working on Safari". Below is the solution.
Add Webpack addon 
   new webpack.ProvidePlugin({
    'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
  })
And add npm modules 
npm i imports-loader exports-loader -D

**Comment by ssageghi** [comment]
@techhysahil Hi 
can u specify which file should I add webpack plugin?

**Comment by techhysahil** [comment]
@ssageghi , you have to add above in webpack.config.js.
